kiali/kiali-ui

- src/components/Nav/Navigation.tsx
- src/components/Nav/RenderPage.tsx
- src/components/Nav/SecondaryMasthead.tsx
- src/styles/_layout.scss
Patternfly sets the height of the "Page" to 95vh, so we can our calc wrong in the GraphPage.
Additionally, sets the header height to the remaining 5vh, if not, when the screen is big (height about 1800px) a black bar appears on bottom.
> KIALI-2970 Removes fixed height of 95vh for page

- src/store/Selectors/GraphData.ts
Before to match edge certain edge rates you needed to treat the zero-case with a NaN match.  For example:
"%httperror < 5 or %httptraffic = NaN"
Now it works as expected:
"%httperror < 5"
> KIALI-3000 Improve find/hide for edge traffic expressions

- package.json
- yarn.lock
Fix a CVE with handlebars version < 4.0.14
WS-2019-0064 More information
high severity
Vulnerable versions: < 4.0.14
Patched version: 4.0.14
Versions of handlebars prior to 4.0.14 are vulnerable to Prototype Pollution. Templates may alter an Objects' prototype, thus allowing an attacker to execute arbitrary code on the server.
https://issues.jboss.org/browse/KIALI-3002
Yes
No
See https://github.com/wycats/handlebars.js/compare/v4.1.1...v4.1.2
> KIALI-3002 Fix Handlebars subpackages CVE with version < 4.0.14.

- src/components/GraphFilter/GraphFind.tsx
- src/pages/Graph/GraphHelpFind.tsx
Here is an example of the change. I have bookinfo and istio-system and I hide the GRPC traffic edges:
Before:
After:
> KIALI-3005 Hide nodes with only hidden edges

- package.json
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- yarn.lock
Make graph labels selectable.
Had to update cytoscape lib, latest version has bug fixes that blocked this feature when using labels on a different position than the default.
~~Warning: I still need to test edge labels.~~
> KIALI-3001 Makes graph labels selectable

- src/actions/GraphActions.ts
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/FocusAnimation.ts
- src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
- src/components/GraphFilter/GraphFind.tsx
- src/components/Metrics/IstioMetrics.tsx
- src/components/MetricsOptions/MetricsSettings.tsx
- src/components/NamespaceDropdown.tsx
- src/components/Nav/Masthead/UserDropdown.tsx
- src/pages/Graph/GraphPage.tsx
- src/pages/ServiceDetails/ServiceInfo/types/DestinationRuleValidator.ts
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
- src/reducers/__tests__/NamespacesReducer.test.ts
- src/store/Store.ts
Parameters that come from the URL and from redux can be null or
undefined without causing compilation errors. This does not compile
anymore with `react-scripts`, so it needs to be fixed before the
upgrade.
> KIALI-2529 Fix values that can be undefined or null

- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
This allows to use `Link` in the context menu.
KIALI-3008 Links from graph's context menu yield 404 when open in new window/tab
No UI changes
> KIALI-3008 Adds Router to cytoscape context menu

- package.json
- src/services/Api.ts
- tsconfig.json
- yarn.lock
Updates to latest version of typescript:
- https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/
This update makes the compiler a little more strict, so some of the
things that we had before will not work. This update has the same
motivation as #1154, and having a more up to date typescript helps us
with it (some errors happen because of the lacking `unknown` type, which
is defined as `null | undefined | T extends {}`).
Some other changes:
* `@types/react-redux` has been updated because it generates a
compilation error. This is build-only, so no impact. Also, we're already
running the latest redux, so we're just keeping them in sync.
* `hoist-non-react-statics` had improper typescript typings and had to
be forcefully updated. I did some investigations on the changes for
the …
> Update to Typescript 3.5

- src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/pages/AppList/FiltersAndSorts.ts
- src/pages/ServiceList/FiltersAndSorts.ts
- src/pages/ServiceList/__tests__/ServiceListComponent.test.ts
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/types/Health.ts
Typescript has no way to know if the item has the health attribute or
not. Before, it just defaulted to any, but when we start using babel, it
becomes a compilation error.
This is one of those cases where the current implementation is incorrect
and only worked because it downcasted it to `any`.
> KIALI-2529 Add type hints to composite types

- src/pages/AppList/FiltersAndSorts.ts
- src/pages/ServiceList/FiltersAndSorts.ts
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/types/SortFilters.ts
The problem happens because some of the sort fields require health data,
while others do not. This is by design, but we need a way to make the
compiler understand what is happening.
This is a follow-up for #1240 with the fixes I've found after trying to get master again to update to `react-scripts`.
> Fix compilation problem with list filter items with health data

- src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
When a DestinationRule has a subset but no labels, the DestinationRuleDetail page fails, testing to check if subset.labels is defined fixes the problem.
https://issues.jboss.org/browse/KIALI-3028
> KIALI-3028 Allow DestinationRules without subset.labels

- package.json
Snyk does not work properly [on my machine][1] because of an issue that has [been known][2] by the developers for months, and that [fails our CI process][3] with cryptic messages that do not help, while also increasing a lot the time for the build to run (timed it at up to 1 minute per build, but could not find a way to time this correctly because it runs as a part of the install script).
It still is installed and can be run, just won't run anymore when you run `yarn install`.
[1]: https://gist.github.com/cfcosta/edb0c69b5bcd01e7dfa433c29bde8312
[2]: https://github.com/snyk/snyk/issues/445
[3]: https://travis-ci.org/kiali/kiali-ui/builds/547395925?utm_source=github_status&utm_medium=notification
> Remove snyk from the dependency install script

- src/components/IstioWizards/WeightedRouting.tsx
- src/components/JaegerIntegration/__tests__/LookBack.test.tsx
- src/components/JaegerIntegration/__tests__/RightToolbar.test.tsx
- tsconfig.json
- tslint.json
Related to #1154.
This was supposed to fix the warning that appears when you try to build:
```
no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
```
Even disabling the rule did not make the warning disappear, but enabling the checking on tsconfig showed some warnings that this PR fixes.
Those are also errors after the upgrade to `react-scripts`, but we can get the benefits now.
Those are the offending files:
```
ERROR: /home/cfcosta/Projects/go/src/github.com/kiali/kiali-ui/src/components/IstioWizards/WeightedRouting.tsx:161:11 - 'numLocks' is declared but its value is never read.
ERROR: /home/cfcosta/Projects/go/src/github.com/kiali/kiali-ui/src/components/JaegerIntegration/__tests__/LookBack.test.tsx:6:16 - 'onChangeCustom' is …
```
> Use tsc unused variable checking instead of tslint

- src/components/BoundingClientAwareComponent/BoundingClientAwareComponent.tsx
- src/components/NamespaceDropdown.tsx
It provides scrollbars to the namespace selector when needed.
This also add a class that computes the offset from the element to the screen, it allows us to avoid manual computations on that value, adjusting better if we ever make a change there.
If someone could find a better name for this component, please let me know.
Fixes https://github.com/kiali/kiali/issues/1166
> KIALI-3053 Adds a scrollbar when needed when listing too many namespaces

- src/components/Details/DetailObject.tsx
- src/components/Health/HealthDetails.tsx
- src/components/IstioWizards/MatchingRouting/MatchBuilder.tsx
- src/components/IstioWizards/MatchingRouting/Matches.tsx
- src/components/IstioWizards/MatchingRouting/RuleBuilder.tsx
- src/components/IstioWizards/VirtualServiceHosts.tsx
- src/components/JaegerIntegration/LookBack.tsx
- src/components/JaegerIntegration/TagsControl.tsx
- src/components/MetricsOptions/MetricsSettings.tsx
- src/components/NamespaceDropdown.tsx
- src/components/Nav/RenderPage.tsx
- src/components/SessionTimeout/SessionTimeout.tsx
- src/components/SummaryPanel/InOutRateChart.tsx
- src/components/SummaryPanel/RateChart.tsx
- src/components/SummaryPanel/ResponseTable.tsx
- src/components/SummaryPanel/ResponseTimeChart.tsx
- src/components/SummaryPanel/RpsChart.tsx
- src/pages/Graph/GraphHelpFind.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
- src/pages/Overview/OverviewCardContent.tsx
- src/pages/Overview/OverviewCardContentExpanded.tsx
- src/pages/Overview/OverviewCardLinks.tsx
- src/pages/Overview/OverviewStatus.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
- src/pages/ServiceDetails/ServiceTraces.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
Part of #1154.
Those are warnings after the upgrade to `react-scripts`, so we're
cleaning those up.
Only removing unused code, no breakage is expected.
> Remove all unused constructors

- package.json
- yarn.lock
Part of #1154.
Fix the warnings that happen after the `react-scripts` update that look
like this:
```
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser …
```
> Fix browserversion warnings

- src/components/Metrics/CustomMetrics.tsx
The "additionalLabels" param was missing in case version is not provided (app view)
Now back to normal:
JIRA: https://issues.jboss.org/browse/KIALI-3058
> KIALI-3058 Add version label in app-based custom metrics page

- src/components/NamespaceDropdown.tsx
- I was using "overflow: overlay" which is only supported
on webkit, changed it to auto and is working properly on
both chrome and firefox.
> KIALI-3055 Fix namespace scrollbar for non-webkit browsers

- Makefile.jenkins
- RELEASING.adoc
Now that the workflow for a major release is defined, apply this knowledge to the Jenkins pipeline.
> Prepare for major release workflow

- src/components/Health/HealthDetails.tsx
- src/components/Health/HealthIndicator.tsx
- src/components/Health/Helper.ts
- src/components/Health/__tests__/HealthIndicator.test.tsx
- src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/pages/Overview/OverviewStatus.tsx
- src/types/Health.ts
The move to PF4 icons impacts all health icons, including on overview page
Some screenshots:
**List view**
**Details**
**Details, N/A**
**Overview cards**
Maybe you will notice that the icons are not exactly the same size as before.
Previously we were setting the exact size manually, now with PF4 there are pre-defined sizes (large/medium/small) that we can (must?) use.
This is more visible on the overview cards, where the icon is bigger than before.
Please tell me what you think
cc @aljesusg @lucasponce @abonas @kiali/ux-reviewers
> KIALI-2961 Add icon for unknown health + move to PF4 icons

- src/app/AuthenticationController.tsx
- src/components/MTls/MeshMTLSStatus.tsx
- src/services/Api.ts
Decreasing Severity from MTLS Status message: from warning to informative. This prevents UI to show messages outside the MessageCenter. Less intrusive solution.
Needs: https://github.com/kiali/kiali/pull/1187
https://issues.jboss.org/browse/KIALI-3057
yes
> KIALI-3057 mTLS status messages reduced to informative when user hasn't namespaces

- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/config/Paths.ts
- src/pages/Graph/SummaryLink.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- provide a real link to the ServiceEntry detail
- show the individually requested destinations
- prevent drill down because serviceEntries are aggregates
- limit contextmenu options because serviceEntries are aggregates
- prevent sparklines in side panel because serviceEntries are aggregates
Conflicts:
src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
!! REQUIRES server pr https://github.com/kiali/kiali/pull/1193
> KIALI-3034 Improve side-panel for serviceEntry nodes (#1271)

- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- Move 3scale error message to INFO
As similar strategy with Jaeger/Grafana, if user has not rights to query istio-system ns to check if 3scale adapter is deployed, it shouldn't fail the service details page, but show an informative message instead.
> KIALI-3071 Split details and 3scale promises

- src/components/EmptyGraphLayout.tsx
Use widget-independent wording:
> KIALI-3039 Minor fix to Empty Graph text

- src/utils/Graphing.ts
- src/utils/__tests__/Graphing.test.ts
+ Add tests
This is targeting v1.0 branch directly.
Note that a slightly different fix will be needed for master, as it's involving k-charted there (no cherry-pick). I'll open a separate PR.
Series are now correctly left-aligned when they start later (here, v3 started after v1):
> [v1.0] KIALI-2985 normalize timeseries on X axis

- src/components/MessageCenter/NotificationDrawer.tsx
Prevents the message center from growing over the view port.
> KIALI-3097 Add scrollbar (when required) to MessageCenter

- src/pages/Graph/SummaryPanelNode.tsx
Fix error that appeared when using the service graph (e.g. by going to a service and clicking "Show on graph")
This was caused because the result of incomers() do not implement the [Symbol.iterator](https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html#iterables) needed for the `for-of` syntax.
Changed to use the [forEach](http://js.cytoscape.org/#eles.forEach) of cytoscapejs.
[KIALI-3109 ](https://issues.jboss.org/browse/KIALI-3109)
Before:
After:
>  KIALI-3109 Fix service graph error

- package.json
On a clean install 'yarn test' will fail because the files try to import the css of which there is none. This PR runs the build-css prior to running the tests so the tests will always have the latest css changes.
https://issues.jboss.org/browse/KIALI-3105
Yes
No
> KIALI-3105 Make sure css is generated from scss on 'yarn test'.

- src/pages/AppList/AppListComponent.tsx
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/WorkloadList/WorkloadListComponent.tsx
- src/utils/Common.ts
Reset pagination when user changes the namespace to fetch.
There are some scenarios where user can move to a page that doesn't exist.
https://issues.jboss.org/browse/KIALI-3093
> KIALI-3093 Fix reset pagination when NS changes

- src/pages/AppList/AppListComponent.tsx
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/WorkloadList/WorkloadListComponent.tsx
- src/utils/Common.ts
Backport of KIALI-3093 for v1.0.
master and v1.0 branches diverge a lot, so, now "git cherry-pick" is more difficult to use and it needs some manual backport of the issue.
> KIALI-3093 [v1.0] Fix reset pagination when NS changes

- package.json
Separate browserlist from all in one to production and development settings for use with 'yarn build' and 'yarn start' respectively. This means we will be testing the more current browsers in development while supporting more versions in production (and more kinds)
Yes
No
https://github.com/browserslist/browserslist
> Trivial: Separate browserlist from all in one to PROD and DEV sections

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/Details/DetailedTrafficList.tsx
- src/store/Selectors/GraphData.ts
- src/types/Graph.ts
Shows the TCP edges without traffic using the `triangle-cross` shape (i.e. it looks like it has traffic but with gray color)
Depends on: https://github.com/kiali/kiali/pull/1234
[KIALI-3102](https://issues.jboss.org/browse/KIALI-3102)
Before: 
After:
> KIALI-3102 Show TCP edges without traffic as "triangle-cross"

- README.adoc
Not sure why we were telling that... any idea?
We *do* use `yarn start` with the browser.
Also, mention web root when setting up proxy.
> [Readme] Fix documentation on "yarn start"

- src/components/BreadcrumbView/BreadcrumbView.tsx
Migrate the breadcrumb to PF4.
Breadcrumb is something shared between many detail pages. I think we should add it first before having two of us developing it at the same time.
> KIALI-3127 Move breadcrumb to PF4

- src/components/Nav/Masthead/UserDropdown.tsx
Assigns and id to the DropdownToggle on the UserDropdown.
https://issues.jboss.org/browse/KIALI-3138
No real visual changes in the UI, but the generated code changes less
Before:
After:
The same, but the id is always "user_logout_option"
> KIALI-3138 Assign an Id to DropdownToggle to avoid computed ID on render

- src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
- src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/pages/Graph/SummaryPanelEdge.tsx
- src/store/Selectors/GraphData.ts
- src/types/Graph.ts
- src/utils/TrafficRate.ts
Reduce direct calls to `ele.data(field)` and instead use the typesafe version of the call.
This adds more type safety, but we would need to close the loop (in a different PR) to ensure that the data we are receiving is in sync with our definitions. 
Probably something at runtime that can warns/errs about any difference found.
https://issues.jboss.org/browse/KIALI-3135
There are no visual changes.
> KIALI-3135 Add more typesafety to node/edge data

- src/components/Nav/RenderPage.tsx
- src/routes.tsx
Before code-splitting, build reports these sizes:
```
File sizes after gzip:
1.35 MB (+555.98 KB)  build/static/js/main.86522805.js
165.32 KB (+460 B)    build/static/css/main.1734869f.css
```
After code-splitting, build reports these sizes:
```
File sizes after gzip:
828.63 KB (-7 B)  build/static/js/main.158c81c6.js
239.87 KB         build/static/js/3.08cdbb49.chunk.js
177.84 KB         build/static/js/4.5d409cea.chunk.js
164.87 KB         build/static/css/main.7eaa2ccd.css
135.46 KB         build/static/js/0.fe2dc93f.chunk.js
115.75 KB         build/static/js/1.5419a62c.chunk.js
109.91 KB         build/static/js/2.40757215.chunk.js
8.83 KB           build/static/js/5.b70775d6.chunk.js
7.91 KB           build/static/js/6.2642d802.chunk.js
7.48 KB …
```
> KIALI-3035 Code-splitting for main navigation components

- src/routes.tsx
https://issues.jboss.org/browse/KIALI-3150
There is some issue with details pages. Lazy loading all them produces a blank screen bug in the containerized build (dev-mode `yarn start` works fine). It's enough if one of the detail pages is not lazy loaded to have the app working fine.
For now, leaving AppDetailsPage without lazy load to fix the issue. I'll try to find what's the root cause, but doing this to not delay the fix.
> KIALI-3150 Fix blank screen

- package.json
- src/components/MessageCenter/NotificationDrawer.tsx
- yarn.lock
JIRA https://issues.jboss.org/browse/KIALI-3172
This should not break tests
As explained inline:
For some reason not fully explained, when loaded with "import" it happens that the NotificationDrawer
does not come with the expected ".Title", ".Accordion" (etc.) fields.
Which ends up in React error "Element type is invalid" as those components are undefined.
Using the "require" way is a workaround.
Note that it is unclear what triggers the error
(may happen with or without lazy loading, generally not seen using `yarn start` but seen with build)
See also https://github.com/kiali/kiali-ui/pull/1339 and https://github.com/kiali/kiali-ui/pull/1292
Also add prop-types as this is a peer dependency of several modules; hence fixes warnings
> KIALI-3172 Use require as a workaround in NotificationDrawer

- package.json
- yarn.lock
JIRA: [KIALI-3107](https://issues.jboss.org/browse/KIALI-3107)
Typescript should be less than 3.5 
https://github.com/kiali/kiali-ui/blob/master/package.json#L134
```bash
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.5.0
YOUR TYPESCRIPT VERSION: 3.5.1
Please only submit bug reports when using the officially supported version.
=============
```
> KIALI-3107 Typescript requirement warning by  typescript-estree, typescript should be <3.5

- src/pages/Graph/SummaryPanelEdge.tsx
> KIALI-3178 rename response-time sparkline legend labels to be consistent with k-charted

- package.json
(See discussion on kiali-dev "OOM in javascript build")
> Disable source-mapping in builds to avoid out-of-mem

- src/components/MissingSidecar/MissingSidecar.tsx
- src/components/Pf/PfTitle.tsx
- src/pages/AppDetails/AppInfo/AppDescription.tsx
- src/pages/AppList/ItemDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
- src/pages/ServiceList/ItemDescription.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/pages/WorkloadList/ItemDescription.tsx
The [istio] control plane objects should not be expected to conform to the
same expectations of the data plane (mesh) objects.
For objects in the istio namespace (i.e. control plane):
- Remove missing sidecar info from App/Workload/Service lists.
- Remove missing sidecar info from App/Workload/Service details.
- Remove missing sidecar and label violation warnings from Workload detail.
Before:
After:
> KIALI-3160 Ignore sidecar and label violations for istio objects

- src/components/GraphFilter/GraphFind.tsx
- src/components/GraphFilter/GraphRefresh.tsx
- src/pages/Overview/OverviewToolbar.tsx
- src/reducers/GraphDataState.ts
- src/store/ConfigStore.ts
Saves in local storage the filterState values from redux:
edgeLabelMode, findValue, graphType, hideValue, showCircuitBreakers,
showFindHelp, showLegend, showMissingSidecars, showNodeLabels,
showSecurity, showServiceNodes, showTrafficAnimation,
showUnusedNodes, showVirtualServices
https://issues.jboss.org/browse/KIALI-2618
[ ] Is your pull-request introducing changes in behaviour? 
Is persiting filterState values to localstorage
No UI changes
> KIALI-2618 Saves graph filterState values

- src/store/ConfigStore.ts
- Adds: duration, refreshInterval and graph.layout
I added the messageCenter there, but someone else thinks that it could hold obsolete information (or maybe sensitive information?) so that data is restored on login.
https://github.com/kiali/kiali-ui/blob/d6a7fb41efaf523ec1e87f08b53c4c36a56fa354/src/reducers/MessageCenter.ts#L173-L176
Anyone thinks we should save the messagecenter or is OK to just clean it?
https://issues.jboss.org/browse/KIALI-1400
No
No visual changes
> KIALI-1400 Save state between sessions

- src/actions/GraphDataThunkActions.ts
- src/actions/LoginThunkActions.ts
- src/actions/MessageCenterActions.ts
- src/actions/__tests__/MessageCenterAction.test.ts
- src/app/AuthenticationController.tsx
- src/app/StartupInitializer.tsx
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/IstioWizards/IstioWizard.tsx
- src/components/IstioWizards/IstioWizardDropdown.tsx
- src/components/IstioWizards/ThreeScaleIntegration.tsx
- src/components/ListPage/ListComponent.tsx
- src/components/MTls/MeshMTLSStatus.tsx
- src/components/MessageCenter/NotificationDrawer.tsx
- src/components/Metrics/CustomMetrics.tsx
- src/components/Metrics/IstioMetrics.tsx
- src/helpers/TrafficDetailsHelper.ts
- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/Overview/OverviewPage.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/reducers/MessageCenter.ts
- src/reducers/__tests__/MessageCenterReducer.test.ts
- src/services/Api.ts
- src/services/__tests__/ApiMethods.test.tsx.ts
- src/types/MessageCenter.ts
- src/utils/MessageCenter.ts
- hide additional detail inside an expandable for a cleaner toast and list
- consistently use MessageCenter utils to format and dispatch notifications
- use new addError() consistenly when reporting AxiosError
- feature the message, when supplied, hiding error and additional detail
- feature error when message not supplied, hiding any additional detail
- remove unnecessary API.getMessage, getErrorMessage, getInfoMessage
- severity is already shown via icon
- replace with API.getErrorString, getErrorDetail
*** SERVER PR: https://github.com/kiali/kiali/pull/1319
> KIALI-2938 MessageCenter improvements and detail handling

- src/pages/Overview/OverviewCardBars.tsx
- src/pages/Overview/OverviewCardContentExpanded.tsx
- src/pages/Overview/OverviewCardSparkline.tsx
- src/utils/Graphing.ts
JIRA: https://issues.jboss.org/browse/KIALI-3198
There's:
- sparkline chart
- bars chart
Splitting in dedicated components by the way.
!Note!: there's a regression with PF3 charts: we don't have tooltips here on the sparkline. So it now only represents a trend but we cannot really read values for it. This is because I couldn't find a good way to display tooltips on victory charts especially when the chart is small, because it requires huge padding around the chart to not be cut on borders.
I think we should investigate alternatives, such as a fixed-position tooltip, or debugging/forking victory's voronoi to "clamp" tooltip on borders, or maybe no tooltip but show y-axis values...
> KIALI-3198 Migrate charts in overview cards to pf4

- src/store/ConfigStore.ts
https://issues.jboss.org/browse/KIALI-3204
Recently, the Message Center was included in the list of things to persist from the Redux store.
The problem is that the messageCenter part of the redux store is including fields/attributes with Date typings, which is a complex data type with attributes, methods, etc.
Apparently, redux-persis package is using string representation to persist data (at least, this is what the browser console shows). Thus, Date typed fields are being loaded as strings rather than the expected Date objects and Kiali crashes with a "toLocaleDateString is not a function" error.
This commit is excluding the message center from persistence to quickly fix the blank page issue and release patch version v1.3.1. A more elaborated solution should be implemented to properly …
> KIALI-3204 Fix blank screen issue (message center persistence problem)

- src/components/VirtualList/Config.ts
- src/components/VirtualList/Renderers.tsx
- src/components/VirtualList/VirtualItem.tsx
- src/components/VirtualList/VirtualList.tsx
- Formalized type Renderer
- Strong link between ResourceType and Renderer
- Type guard on TResource w/ health ("hasHealth"), health not "any" anymore
- Generic on ResourceType, Renderer, VirtualList to avoid use of "any"
JIRA: https://issues.jboss.org/browse/KIALI-3213
> KIALI-3213 More type-safety on Virtual Lists

- src/components/Metrics/CustomMetrics.tsx
- src/components/Metrics/IstioMetrics.tsx
- Toolbars migration, both Istio and Custom metrics pages, +1 icon
- Also remove now useless "isVisiblePage" that was a workaround for PF3 charts (chart migration merged previously)
JIRA https://issues.jboss.org/browse/KIALI-2630
> KIALI-2630 Migrate to PF4 on metrics page

- src/components/GraphFilter/GraphFind.tsx
The first tab in the video is the "before".  I switch tabs to the "after":
> KIALI-3240 Improve layout/zoom handling when clearing the hide box

- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
https://issues.jboss.org/browse/KIALI-3261
Added keys to tabs to remvoe console warning
```bash
ndex.js:1437 Warning: Each child in an array or iterator should have a unique "key" prop.
Check the render method of `WorkloadDetails`. See https://fb.me/react-warning-keys for more information.
in ForwardRef (at WorkloadDetailsPage.tsx:221)
in WorkloadDetails (created by Connect(WorkloadDetails))
in Connect(WorkloadDetails) (created by Context.Consumer)
in Route (at RenderPage.tsx:13)
in Switch (at SwitchErrorBoundary.tsx:42)
in SwitchErrorBoundary (at RenderPage.tsx:28)
in div (at RenderPage.tsx:27)
in div (at RenderPage.tsx:39)
in RenderPage (at Navigation.tsx:116)
in section (created by PageSection)
in PageSection (at Navigation.tsx:115)
in main (created by Page)
in div (created by Page) …
```
> KIALI-3261 Fix warnings in details view app and workloads

- src/components/Refresh/RefreshButton.tsx
Fix https://github.com/kiali/kiali/issues/1598
Require https://github.com/kiali/kiali-ui/pull/1383
> KIALI-3256 [PF4] Migrate Refresh Button

- package.json
- yarn.lock
There is the need to use CharBullet component from PF4. This component is available in 4.7.9 of Patternfly Charts dependency.
This PR adds that Component up.
Need in https://github.com/kiali/kiali/issues/1593
> Update patternfly charts to 4.7.9 in order to have ChartBullet 

- src/services/Login.ts
Instead of taking the user directly to the OpenShift login page, we take them to the Kiali Login page that has a button to go to the OpenShift login page.
https://issues.jboss.org/browse/KIALI-3046
What the login page looks like (note: this login page already exists, but its bypassed currently)
Note: awaiting feedback from UX
> KIALI-3046 Present a link to login into OpenShift

- package.json
- src/index.tsx
- src/polyfills.ts
- yarn.lock
- This is currently required for Firefox ESR
Fixes kiali/kiali#1631
Adds polyfills for missing function customElements
> Kiali#1631 Polyfills window.customElements

- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/GraphFilter/GraphFind.tsx
- src/components/SummaryPanel/RateChart.tsx
- src/pages/Graph/GraphPage.tsx
- src/pages/Graph/SummaryPanelCommon.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/types/Graph.ts
- This new default summary provides a quick summary of client requests.
- add tabbed view to toggle between "Incoming" and "Total" traffic.
- also, fix a long-standing precision rendering issue in the chart
Fixes https://github.com/kiali/kiali/issues/1422
> Add incoming traffic summary to graph side panel

- src/components/IstioActions/IstioActionsButtons.tsx
- src/components/IstioActions/IstioActionsDropdown.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.scss
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Includes https://github.com/kiali/kiali-ui/pull/1397, otherwise cancel button doesn't work. Merge https://github.com/kiali/kiali-ui/pull/1397 first.
Closes https://github.com/kiali/kiali/issues/1593
> [PF4] MIgrate Actions and ACEeditor buttons from Istio Page

- src/pages/AppDetails/AppDetailsPage.tsx
Code is similar to what is done in WorkloadDetails page
Closes https://github.com/kiali/kiali/issues/1654
> Do not mount metrics pages when they're not visible

- src/pages/Graph/SummaryPanelCommon.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- The node info does not reflect the actual set of OS badges on the k8s object
and so OS badge styling was confusing.  Simple Badge styling is still
visually striking while not being misleading.
Fixes https://github.com/kiali/kiali/issues/1392
@serenamarie125 Because we are not actually displaying OS labels I've used a different styling, this is using PF4 Badge, what do you think:
Productpage Service Node:
Productpage Versioned App Node:
The connecting Edge:
> Replace use of OS label styling in side panel with PF4 badge styling

- src/components/CytoscapeGraph/CytoscapeToolbar.tsx
- src/pages/Graph/GraphPage.tsx
Migration of the cytoscape toolbar to PF4 and use the new design for the toolbar.
Replaces PF3 with PF4.
fixes: https://github.com/kiali/kiali/issues/1606
https://github.com/kiali/kiali/issues/1606
Yes
No
**Previous**:
**After**:
> Migrate the cytoscape toolbar to PF4

- src/components/IstioWizards/SuspendTraffic.tsx
Refactor of SuspendTraffic Wizard to use only PF4 components.
https://github.com/kiali/kiali/issues/1595
This is the easy one, as all components used have a 1to1 mapping with PF4:
> PF3->PF4 Migrate Suspend Wizard

- src/components/Metrics/IstioMetrics.tsx
- src/types/GrafanaInfo.ts
- Any number of dashboards can be defined
- Now we can also have links on "app" in addition to "workload" and "service"
- No change to the nominal case: default Istio dashboards for Workload and Service are still accessible same way as before
Backend PR: https://github.com/kiali/kiali/pull/1678
Closes https://github.com/kiali/kiali/issues/1268
Picture when multiple dashboards are defined:
> Allow customized links to Grafana (front)

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/Nav/Masthead/HelpDropdown.tsx
- src/pages/Graph/GraphPage.tsx
In Redux 6.0 `getWrappedInstance()` got removed, so it is always false,
and always sets the ref as null, so broken buttons.
Reference:
https://medium.com/@mehran.khan/using-refs-with-react-redux-6-how-to-use-refs-on-connected-components-4b80d4ea7300
Fixes https://github.com/kiali/kiali/issues/1661
> Fix zoom buttons on the graph

- package.json
- src/components/GraphFilter/__tests__/GraphFind.test.tsx
- src/components/IstioWizards/__tests__/UtilRegexp.test.ts
- src/components/MessageCenter/__tests__/MessageCenter.test.tsx
- src/components/Metrics/__tests__/IstioMetrics.test.tsx
- src/components/Metrics/__tests__/TrafficDetails.test.tsx
- src/pages/Overview/__tests__/OverviewPage.test.tsx
The react-script build that we use won't compile our test files anymore so they can be broken (although they're not failing because runtime JS is still OK)
I'm fixing these errors but we should find a solution to make them being compiled again.
For the time being I'm just adding "tsc" as a script in package.json to run manual compilation.
> Fix compiler issues in tests

- src/components/About/AboutUIModal.tsx
If the url is not set, display N/A instead of "undefined"
Fixes kiali/kiali#1652
Show the links in the about box as a link and not plain text.
Before:
After:
> Makes links clickable in the about page

- src/pages/IstioConfigList/FiltersAndSorts.ts
Backport of https://github.com/kiali/kiali/issues/1585 in v1.0 branch.
Master has changed and we need to check if the issue is still happening there.
> IstioConfigList can't filter by 2 or more names

- src/components/Details/DetailObject.tsx
- src/components/Details/__tests__/DetailObject.test.tsx
- src/components/Details/__tests__/__snapshots__/DetailObject.test.tsx.snap
- src/components/Validations/GlobalValidation.tsx
- src/components/Validations/TooltipValidation.tsx
- src/components/Validations/Validation.scss
- src/components/Validations/Validation.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/types/DestinationRuleValidator.ts
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/services/__mockData__/getServiceDetail.ts
- src/types/IstioObjects.ts
- src/types/ServiceInfo.ts
Migrating all Validation icons, tooltips and so on.
https://github.com/kiali/kiali/issues/1635
yes
Shows the list of all the validations for a group of checkers.
Only shows the status of the whole object.
> [PF4] KIALI-1635 Migrate validations to PF4 from Istio Page

- package.json
- src/components/Metrics/CustomMetrics.tsx
- src/components/Metrics/GrafanaLinks.tsx
- src/components/Metrics/IstioMetrics.tsx
- src/components/Metrics/__tests__/CustomMetrics.test.tsx
- src/components/Metrics/__tests__/IstioMetrics.test.tsx
- src/types/GrafanaInfo.ts
- yarn.lock
New GrafanaLinks component used in both IstioMetrics and CustomMetrics pages
WIP: needs https://github.com/kiali/k-charted/pull/50 + k-charted bump
Backend PR: https://github.com/kiali/kiali/pull/1691
Part of kiali/kiali#1676
> Use Grafana Links in custom dashboards

- src/components/ConfigValidation/ConfigIndicator.tsx
- src/components/Health/Helper.ts
- src/components/Validations/Validation.tsx
- src/components/Validations/ValidationList.tsx
- src/components/Validations/ValidationSummary.tsx
- src/components/VirtualList/Renderers.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
Migrating Summary validation popovers to PF4 (in Tooltip maner).
https://github.com/kiali/kiali/issues/1635
yes
Shows a summary of validations (warnings and errors) for one object.
This was previously implemented with a Popover. However, its behavior was changed to behaves as a Tooltip. In PF4, this behavior changes is not possible to be done, so it has been migrated to a tooltip as it follows.
Found in:
Workloads details page:
Service List:
Service Details (ports field):
Istio Config list:
> [PF4] KIALI-1635 Summary Validation popover moved to PF4

- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo.tsx
- src/types/ServiceInfo.ts
Both ServiceDetails and WorkloadDetails page has tabs with validation icons.
This PR changes those icons to new validation components.
https://github.com/kiali/kiali/issues/1635
yes.
Closes https://github.com/kiali/kiali/issues/1635
> [PF4] Moving tab validations to PF4

- src/components/About/AboutUIModal.tsx
Fixes warning about not using `key` in  a child list for AboutUIModal
Fixes kiali/kiali#1714
> Add `key` prop to component list

- src/components/SummaryPanel/ResponseTimeChart.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
Istio 1.3.0 experimental introduces mixer-less telemetry. In this new approach latency is reported via
a new metric: request_duration_milliseconds, as opposed to what has has been done with request_duration (in seconds).
I'm not aware of a way to drive off config to know which will be in service for a time period, so until the legacy metric is removed we need to support both. This makes for some sort-of-hacky code.
I'm not really asking reviewers to run the code with mixer-less, rather to ensure no regression using the existing telemetry.  On the UI side this means the graph edge summary sparklines should work normally.
https://github.com/kiali/kiali/issues/1694
Server PR: https://github.com/kiali/kiali/pull/1711
> Support request_duration_milliseconds for latency reporting in mixer-less telemetry

- package.json
- src/pages/Overview/OverviewCardBars.tsx
- src/pages/Overview/OverviewCardSparkline.tsx
- yarn.lock
- This is possible by upgrading victory/react-charts and using new prop constrainToVisibleArea
- Also fix an issue with axis on bars charts not being hidden as expected (not sure if this issue was introduced with the lib version upgrade)
- The k-charted upgrade allows the same improvement with tooltips in metrics pages (see https://github.com/kiali/k-charted/pull/54)
Closes https://github.com/kiali/kiali/issues/1702
> Re-enable tooltips in overview sparklines, upgrade k-charted

- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
Latest patternfly-charts update broke the VirtualService detail page:
This PR fixes that:
> FIX a Patternfly charts upgrade that broke VirtualService chart.

- src/pages/Graph/SummaryPanelGroup.tsx
Don't use OS label styling in the summary panel because we're not displaying a set of labels, just descriptive information.  Instead use PF4 Badges:
Note that other node types, and edges, have previously been updated.  The App Box was an oversight.  It should now be consistent with the other summary panels.
Fixes https://github.com/kiali/kiali/issues/1709
> Fix styling for app box summary

- src/components/Validations/Validation.tsx
fix https://github.com/kiali/kiali/issues/1719
In the Mockup https://marvelapp.com/i9h9g7j/screen/59315434
there is a CheckCicle with greenlight color https://patternfly-react.surge.sh/patternfly-4/icons/Icons/ we need to change the OkIcon in validation to this one
> [PF4] Move icon of validation to CheckCircle like MockUP

- src/components/GraphFilter/GraphLegend.tsx
- src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap
This is a very small alignment fix to the graph legend close box as it looked a bit off. Now it is in better alignment with the Legend Title.
yes
no
**Before**:
**After**:
> Trivial: Better align the Graph Legend Close box.

- src/components/MTls/MTLSIcon.tsx
- src/components/MTls/MTLSStatus.tsx
- src/components/MTls/MeshMTLSStatus.tsx
- src/components/MTls/NamespaceMTLSStatus.tsx
- src/components/MTls/__tests__/MTLSIcon.test.tsx
- src/components/MTls/__tests__/__snapshots__/MTLSIcon.test.tsx.snap
Migration of mTLS tooltips from masthead and overview page.
Closes https://github.com/kiali/kiali/issues/1735
yes
> Migrate mTLS icons and tooltips to PF4

- src/components/BreadcrumbView/BreadcrumbView.tsx
Fixes kiali/kiali#1729
Before:
After:
> When building the breadcrumbs, consider "." in the item name

- src/components/IstioWizards/ThreeScaleIntegration.tsx
Migration of 3scale Wizard to PF4 componets. 
Minor refactor to adjust same features with PF4.
Added extra notes.
Closes https://github.com/kiali/kiali/issues/1595
> PF3->PF4 Migrate 3scale Wizard

- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/components/Pf/PfColors.tsx
Changing colors to first palette of colors: 100 instead of 200.
Following this color guide: https://www.patternfly.org/v4/design-guidelines/styles/colors
Previous:
Now:
> Health and validations icon colors now are down to 100

- src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
- src/components/SummaryPanel/ResponseFlagsTable.tsx
- src/components/SummaryPanel/ResponseHostsTable.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/types/Graph.ts
Adds an additional Tab in the edge summary to show requested host information, by response status code. 
This video shows external requests being routed to a serviceEntry, PassthroughCluster, and Unknown (i.e. BlackholeCluster).  With the **Hosts Tab** the user can now see exactly which requested host resulted in these endpoints.  Although not shown here, this information is available on all edges, revealing if nothing else, the full host name for the resulting service (e.g. reviews:9080):
Server PR: https://github.com/kiali/kiali/pull/1687
Website PR: https://github.com/kiali/kiali.io/pull/167
Closes https://github.com/kiali/kiali/issues/1405
> UI-side support for request.host information

- src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts
- can't use elems.jsons() to store element info because it loses styles, and
we use style 'hidden' for graph hide.
Fixes https://github.com/kiali/kiali/issues/1745
Note that this issue only occurred when "compress hidden' option was disabled.
> Fix issue when hide expression hides app box elements

- src/components/Details/DetailedTrafficList.tsx
- src/components/Details/__tests__/DetailedTrafficList.test.tsx
- src/components/Metrics/TrafficDetails.tsx
- src/components/Metrics/__tests__/TrafficDetails.test.tsx
- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Adds the ability to show ServiceEntries items in the traffic tab. Links to metric pages will pre-select the destination hostnames listed in the received graph data.
Fixes kiali/kiali#1613.
Only traffic tab of workload and apps are showing the service entries. The Services don't, because services only reach workloads.
This is how it looks:
> Display Service Entries in traffic tab

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts
After some investigation we (@josejulio , @jshaughn) found that two PR's created independently sort of clashed when run together, so it didn't emerge until after the merge.
First, in our GroupCompoundlayout,  use elems.remove() as opposed to elems.move().  It's not clear why this is better, but it is.  And do the remove/restore in one shot, for all parents.
The changes in the layout surfaced an issue in the new UX graph styling code, so that is part two of the fix.
The issues showed up in Chrome, but adversely affected FF even more, and Cola layout was the worst.  Local testing on both browsers and all layouts now seem happy,
Fixes https://github.com/kiali/kiali/issues/1764
> Tweak to the group compound layout algorithm

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts
* Tweak to the group compound layout algorithm
- Remove nodes from the parents instead of moving them outside
* Makes bounds-expansion more stable by ommiting small diffs
*** BACKPORT To 1.6 ***
> Tweak to the group compound layout algorithm (#1464)

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx
Fixing the following bug:
1. Go to a Virtual Service that has a link to a Gateway.
2. Click that gateway link.
3. Kiali shows an error.
yes
Solution:
> Fix Istio page title when clicking gateway link from VS

- src/styles/_overrides.scss
Because of the PF4 migration, styles changed a lot and, most likely, PF3 Kiosk mode styles lost effect. The new PF4 styles for Kiosk mode were omitted. This is adding the required styles for Kiosk mode to properly work.
Fixes kiali/kiali#1758.
> Fix Kiosk mode not working

- src/components/GraphFilter/GraphSettings.tsx
MIgrate the GraphSettings Display Popover to PF4 using Dropdown.
Patternfly Issue: https://github.com/patternfly/patternfly-react/issues/3043
fixes: https://github.com/kiali/kiali/issues/1746
**Previous(PF3):**
**New(PF4):**
> PF4 the GraphSettings display menu.

- src/components/Health/HealthIndicator.tsx
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/pages/AppDetails/AppInfo/AppDescription.tsx
- src/pages/Graph/SummaryPanelGroup.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
- src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
Relates to https://github.com/kiali/kiali/issues/1720 (but without mockup implementation)
Please note, there's a small regression, it seems in PF4 popovers cannot be triggered on mouseenter anymore. Also, it creates some divergence with the istio config indicator which uses Tooltip instead of Popover. I also tried Tooltip but it's supposed to be used for small texts - not the case here. Also, text in tooltips are centered, which is not desirable for health. Probably this needs to be harmonised.
> Move health indicator popover to PF4

- src/pages/AppList/AppListPage.tsx
- src/pages/IstioConfigList/IstioConfigListPage.tsx
- src/pages/ServiceList/ServiceListPage.tsx
- src/pages/WorkloadList/WorkloadListPage.tsx
Related with old tracker JIRA [PF4] Migrate Breadcrumb
> migrate breadcrumb to PF4 in lists

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/utils/MathUtils.ts
It tries to move the loop edges when it finds overlaps with other edges
Fixes kiali/kiali#1610
Before:
After:
Before:
After:
> For loop edges, try to avoid overlap with other edges

- src/config/KialiIcon.tsx
- src/pages/Graph/SummaryPanelNode.tsx
Create a typesafe way to reuse Pf4Icons across Kiali-ui.  Also, makes changing the icons globally, very easy.
To use:
```
<div>
<KialiIcon.Info /> Sparkline charts not supported for unknown node. Use edge for details.
<hr />
</div>
```
closes https://github.com/kiali/kiali/issues/1813
> Create Pf4Icon function to consolidate all of the icons into a single place

- src/components/SummaryPanel/RpsChart.tsx
Backport kiali/kiali#1800 on 1.7
> [v1.7] RpsChart: Fix array out of bound

- package.json
This is re-synching version number with the one found in https://github.com/kiali/kiali/blob/master/Makefile#L6.
Because version 1.8 is the next one to be released at end of sprint.
> Trivial: Re-sync package.json version with back-end version

- src/components/Tab/Tabs.tsx
- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Removing workaround to render DOM only if tabs are visible.
Workaround was due a missing feature in older versions of PF4.
Closes kiali/kiali#1716.
> Use mountOnEnter and unmountOnExit for PF Tabs

- src/components/About/AboutUIModal.tsx
- src/components/GraphFilter/GraphFind.tsx
- src/components/NamespaceDropdown.tsx
- src/components/Tour/Tour.tsx
- src/config/KialiIcon.tsx
- src/pages/Graph/GraphHelpFind.tsx
- src/pages/Graph/GraphPage.tsx
- src/pages/Graph/SummaryLink.tsx
- src/pages/Graph/SummaryPanel.tsx
- src/pages/Graph/SummaryPanelCommon.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/Graph/SummaryPanelGroup.tsx
- src/pages/Graph/SummaryPanelNode.tsx
Replacing all of the PF3 icons with PF4 icons via KialiIcon.tsx .
closes https://github.com/kiali/kiali/issues/1825
> [PF4] Replace PF3 icons with PF4 icons via KialiIcon.tsx.

- src/components/VirtualList/Renderers.tsx
- src/components/VirtualList/VirtualList.tsx
When sorting, there is a duplicated query of the backend.
When health is not yet calculated, we render an empty cell, to avoid that table content is moved when promises are resolved, that improves the effect of "no waiting".
Closes kiali/kiali#1845
> Fix performance issues in VirtualTables

- src/components/GraphFilter/GraphSettings.tsx
Replaces the Dropdown control with the Select control.
The aim is to stop using a free-form dropdown to a proper PF pattern.
Closes kiali/kiali#1849.
> Use Select control in graph's Display dropdown

- src/components/MissingSidecar/MissingSidecar.tsx
- src/pages/AppDetails/AppInfo/AppDescription.tsx
Fix https://github.com/kiali/kiali/issues/1852
> Application Details, the missing Istio Sidecar is so close to workload name

- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/components/Pf/PfColors.tsx
Change the success green to a darker green instead of the lime green. The Patternfly folks have provided us with a new color.
Although patternfly has not published a new css variable for green yet (meaing --pf-global--success-color--100 is not correct for now).
closes https://github.com/kiali/kiali/issues/1862
> Change the PfColors to reflect new darker green color for success/chart.

- src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
Require: https://github.com/kiali/kiali-ui/pull/1512
> Set Missing Istio Sidecar Icon in the same line in service details

- package.json
- src/components/GraphFilter/GraphFind.tsx
- src/components/Tab/SimpleTabs.tsx
- src/pages/Graph/GraphHelpFind.tsx
- yarn.lock
UPDATE: 11/5/2019
- expanding PR/Issue to include all of graph find/hide
Converts the GraphFind and GraphHelpFind components to PF4, removing PF3.
- Add PF4 design to text inputs
- Convert help from Draggable Modal to Popover
- removes react-draggable because PF4's Tabs were unable to function inside of Draggable (I don't know why).
- Popover gives us a more consistent look (like graph tour and tooltips) but at the expense of draggability (I'm not sure draggability is veryt PF4 anyway).  On the down-side, using PF4's Popover, Tabs and Table costs us elephant space.  I'm not css savvy enough to make the tables very compact, so vertical scrolling is going to be in play.
- I Introduced SimpleTabs util just to hide the active tab state changes from parent components.
I think this is a …
> PF4 Graph Find/Hide, including Help

- src/components/MessageCenter/AlertToast.tsx
- src/components/MessageCenter/NotificationList.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
On a second inspection the PF3 code ended up being unreachable.  This PR now just removes it.  The only validation needed is to make sure the service detail page renders normally, no error generation is required.
The first revision of the PR added an enhancement to our PF4 notification handling utility, that code remains in the PR because it is useful, despite no longer being used here.
Fixes https://github.com/kiali/kiali/issues/1882
> Remove PF3 notifications from ServiceInfo

- src/components/MetricsOptions/MetricsSettingsDropdown.tsx
This fixes the gray hover over the 
background that occurs with the Metrics Settings dropdown when selected.
fixes: https://github.com/kiali/kiali/issues/1895
Before:
After:
> Change the background from gray to white on the Metrics Settings dropdown

- src/components/IstioWizards/IstioWizard.tsx
- src/components/IstioWizards/IstioWizardActions.ts
- src/components/IstioWizards/TrafficPolicy.tsx
- src/types/IstioObjects.ts
Fixes kiali/kiali#1847
It adds support for MUTUAL TLS setup in DestinationRules from Wizards.
When selecting MUTUAL, Wizard adds extra form to describe the custom certificates.
> Support MUTUAL Tls method in Wizard with extended form

- src/components/Time/LocalTime.tsx
Sample output: _Oct 9, 2:42 PM_
Closes https://github.com/kiali/kiali/issues/1878
> Use native js function to format date, fixing 12am/pm issue

- src/components/NamespaceDropdown.tsx
I tested this locally using a kiali-operator not installed with **, by editing the Kiali CR to add/drop a namespace (default for example) while sitting on a page using the NamespaceDropdown (like graph).  Before it would not update, now it does.
Fixes https://github.com/kiali/kiali/issues/1901
> Fix regression, ensure NamespaceDropdown refreshes accessible namespaces

- src/components/EmptyGraphLayout.tsx
Migrate EmptyGraphLayout control to PF4.
Sample screenshots
BEFORE:
AFTER:
Related to kiali/kiali#1588
> Patternfly-fourize EmptyGraph control

- deps-and-resolutions-notes.txt
- package.json
- yarn.lock
The BrowsersList warning was removed by:
* bumping version of react-scripts from 3.1.1 to 3.2.0,
* removing caniuse-lite, @typescript-eslint/parser and @typescript-eslint/eslint-plugin from the package.json resolutions,
* adding table-resolver@3.3.0 as a dependency,
* and, finally, by invoking `yarn upgrade react-scripts` to upgrade versions of react-scripts sub-dependencies
This PR is also:
* Bumping rapidoc version to latest 5.3.1 from 5.0.5, which allows to remove `marked` from the resolutions.
* Remove handlebars from resolutions in package.json, because it's no longer needed given the react-scripts upgrade.
* Remove js-yaml from resolutions in package.json, because it's redundant (it's already a dependency).
Closes kiali/kiali#1836
> Fix BrowsersList warning and other package.json updates

- src/components/ErrorBoundary/ErrorBoundaryWithMessage.tsx
- src/pages/WorkloadDetails/WorkloadInfo.tsx
Fixes https://github.com/kiali/kiali/issues/1899
One thing to keep in mind when testing this is that the errors still appear during development (that's intencional, see https://stackoverflow.com/questions/52096804/react-still-showing-errors-after-catching-with-errorboundary).
This is what happens if you have an error:
> Error boundaries on workload list

- src/pages/Graph/GraphPage.tsx
Finish PF4 migration of the graph page by removing import of patternfly-react and migrating the breadcrumb to PF4.
BEFORE:
AFTER:
Related to kiali/kiali#1588
> Patternfly-fourize graph page

- src/components/Link/IstioObjectLink.tsx
- src/components/VirtualList/Config.ts
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/types/IstioObjects.ts
Kiali has now istio object referenced in some validations. For example, multi match gateways validation. This PR adds visual list of references in the editor page, as a sidebar.
Closes https://github.com/kiali/kiali/issues/1419
Backend changes: https://github.com/kiali/kiali/pull/1912
P.S.: Adding the sidebar makes space for other referenced items (not exclusively from validations). It just popped in my mind this old jira: https://issues.jboss.org/browse/KIALI-1883
#1419
yes
Editor page with referenced objects:
Editor page without referenced objects:
Editor page without validations:
> Add referenced istio objects to validations

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Fixes https://github.com/kiali/kiali/issues/1897
After the change:
> Add better error blank slate for istio object details

- src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/Health/__tests__/HealthIndicator.test.tsx
- src/components/Pf/PfColors.tsx
- src/components/SessionTimeout/SessionTimeout.tsx
- src/components/SummaryPanel/RateChart.tsx
- src/components/SummaryPanel/RpsChart.tsx
- src/components/Validations/Validation.tsx
- src/config/KialiIcon.tsx
- src/types/Health.ts
An issue is that not every API accepts the variables and instead is wanting the hex value.  To handle this the PR provides a function to get the variable values.  The first call will determine the values (the document must exist), subsequent calls are faster.
- also, a little bit of renaming for clarity
Fixes https://github.com/kiali/kiali/issues/1839
This screenshot is just showing that the expected colors are rendered in the graph and side panel chart:
> Use PF4 css color variables more consistently

- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Adjust better the behaviour of the tabs.
Instead to wait to first "enter" it will "unmount" non visible tabs.
This will fix the "back button" problem in some pages and will maintain the desired behavior to not load non-visible tabs that are heavy.
Fixes kiali/kiali#1863
> Unmount non visibible children instead to mountonenter only

- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Fix https://github.com/kiali/kiali/issues/1898
> Fix Logs page, message error not centered

- src/pages/Overview/OverviewPage.tsx
- src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
Fix https://github.com/kiali/kiali/issues/1896
> Fix Overview Page, message not centered

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
This blocks migration and https://github.com/kiali/kiali/issues/1857
> Move IstioConfigDetails emptyState to PF4

- package.json
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
- yarn.lock
- The issue in runtimes list occurs when we display alone a custom dashboard with empty runtime name, such as the Envoy one => the "Runtime" title was being written with nothing below.
- Also bump k-charted 0.3.1-rc1 to integrate https://github.com/kiali/k-charted/pull/57 (release will come later / waiting for tracing work)
> [minor] Fix small issue rendering runtimes list & bump k-charted

- src/components/Validations/ValidationSummary.tsx
- src/config/KialiIcon.tsx
- src/pages/Graph/SummaryLink.tsx
- src/pages/Graph/SummaryPanelCommon.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/Graph/SummaryPanelGroup.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/pages/Overview/Sorts.ts
- apply UX design as part of this work as it helps with the overall display of the new information.
- apply UX design to other graph side panel headers for consistency
- replace text with PF kiali badges
- replace text links with icon links and add icon link for config
- consistent placement of health/inaccessible/validation(todo) icons
- consistent spacing
- improved handling of version labels
- apply latest pattern for state handling in graph summary (this was missed when node/edge/group summaries were updated)
- downgrade a console log to debug
- tweak validation tooltips to be more descriptive/easier to understand outside of overview page
Fixes https://github.com/kiali/kiali/issues/1941
@xeviknal This PR changes the validation status tooltip format a little by adding a title …
> Add namespace validation status in graph side panel header

- src/components/Nav/Page/RenderComponentScroll.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.scss
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Fixes kiali/kiali#1955
Adjust CSS for Logs container and ACE Editor to adjust unnecessary scroll after PF4 migration.
> Adjust CSS styles to fix wrong scroll on logs and yaml editor

- src/pages/Overview/OverviewToolbar.tsx
Fix OverviewToolbar.tsx so that TimeRangeContainer has a 'key' that React requires for array rendering.
Small but needed change for React not to complain.
fixes: https://github.com/kiali/kiali/issues/1976
> Fix OverviewToolbar.tsx so that TimeRangeContainer has a 'key' 

- .travis.yml
- package.json
- src/pages/Overview/__tests__/OverviewPage.test.tsx
- yarn.lock
Now that Node.js 12.x is LTS we need to support that as well as the existing LTS which is 10.x
fixes: kiali/kiali#1946
Looks like it is backward compatible with 10.x
No
> Add support for Node.js 12 LTS 

- src/components/IstioWizards/MatchingRouting.tsx
- src/components/IstioWizards/MatchingRouting/MatchBuilder.tsx
Fixes kiali/kiali#1368
This PR introduces a "sugar syntax" in the Mathing Routing, declaring a "pseudo-operator" called "is present" that is translated to a generic regex were creating rules:
Note that we don't propagate the "is present" operator in all layers, because Wizard creates VirtualServices and DestinationRules that user can edit manually, so at the end user needs to know that "is present" === "/^.*$/" but I guess it's a compromise to help them to edit. Also, this only applies to headers.
Not yet finished, it's just a prototype tested locally.
> Introduce 'is present' syntax sugar for Matching Routing

- src/pages/Login/LoginPage.tsx
- src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
- src/services/Api.ts
- src/services/Login.ts
- src/services/__tests__/ApiMethods.test.tsx.ts
- src/types/Auth.ts
This is providing a new login screen with only one "Token" field. The user is expected to paste a service account token to login into Kiali.
The UI will pass the provided token to the back-end. In turn, the back-end will provide a cookie as usual (if the Token is valid). The back-end should use the provided token during the session of the user to make calls to the Kubernetes/OpenShift API, so that the cluster's RBAC takes effect.
Fixes kiali/kiali#1139
> Implement token authentication

- src/components/CytoscapeGraph/CytoscapeToolbar.tsx
The graph toolbar is difficult to read and very difficult to tell what layout is currently selected.
fixes https://github.com/kiali/kiali/issues/2001
Before:
After:
> Make the cytoscape bottom toolbar more readable

- src/components/IstioWizards/IstioWizard.tsx
- src/components/IstioWizards/IstioWizardActions.ts
- src/config/ServerConfig.ts
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
- src/types/ServerConfig.ts
Fixes kiali/kiali#1879
This PR allows Wizards to use FQDN like "reviews.bookinfo.svc.cluster.local" instead of short names "reviews" for the VirtualServices and DestinationRules generated by Kiali Actions.
> Update Wizards to use FQDN

- src/components/Charts/SparklineChart.tsx
Closes: https://github.com/kiali/kiali/issues/1928
Fixes the following error on the overview graphs:
This does not fix the other error that appears, even with this fix (another issue is going to be created for it):
> Fix a console error on SparklineChart

- src/pages/Overview/OverviewCardLinks.tsx
- src/pages/Overview/__tests__/OverviewCardLinks.test.tsx
Implements hiding a redundant link in the links area of the cards of the Overview page. Hidden item is redundant because the middle of the card has a text based on the view type which is a link to the relevant list page.
Fixes kiali/kiali#1474
> Remove link redundancy in cards of Overview page

- src/pages/Graph/GraphToolbar/GraphSettings.tsx
The **visiibility** section of the Graph Settings **Display** dropdown doesn't have a label like the **Badges** section.
Make GraphSettings display settings more consistent 
by adding a 'Visibility' group heading label to match the 'Badges' group heading label.
It looked a little off without the balance of the visibility section; then they look similar.
Yes
No
Before:
After:
> Make Graph Settings display settings more consistent 

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Fix link to services on DR and VS when two parts shortname is shown:
https://github.com/kiali/kiali/pull/2036#issuecomment-567852163
> Host link in DR/VS details page: Support svc.ns format

- src/pages/Overview/Sorts.ts
Fixes https://github.com/kiali/kiali/issues/2047
> Fix overview sort field name from 'Status' to 'Health'

- package.json
- src/components/IstioWizards/Slider/Boundaries.tsx
- src/components/IstioWizards/Slider/Slider.tsx
- src/components/MissingSidecar/MissingSidecar.tsx
Removes prop-types and it's dependency, as it is not used on Typescript.
Closes https://github.com/kiali/kiali/issues/1579
> Remove prop-types

- src/components/Charts/SparklineChart.tsx
This is for sparkline charts (not k-charted)
Fixes https://github.com/kiali/kiali/issues/2069
*Before*:
*After*:
> Hack - one-pixel domain padding to prevent clipping

- src/config/ServerConfig.ts
The initial durations list was not a constant and was overwritten for a default retention (6h). When server config is fetched, the first-pass filtering did already cause the loss of higher duration values.
Fixes https://github.com/kiali/kiali/issues/2072
Here's what I have after this fix:
cc @suraj77foru
> Fix durations not filtered for retention

- src/components/Filters/StatefulFilters.tsx
- src/pages/AppList/FiltersAndSorts.ts
- src/pages/IstioConfigList/FiltersAndSorts.ts
- src/pages/Overview/Filters.ts
- src/pages/ServiceList/FiltersAndSorts.ts
- src/pages/ServiceList/__tests__/ServiceListComponent.test.ts
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/types/Filters.ts
The list of Istio Objects has increased substantially since we started the project.
https://github.com/kiali/kiali-ui/pull/1582#issuecomment-567601410 suggested to sort types alphabetically. This is step further to ease the task of filtering objects by type.
This PRs add the ability to pick istio types by typing its name. It uses the [PF4 typeahead selector](https://www.patternfly.org/v4/documentation/core/components/select#single-with-typeahead).
https://github.com/kiali/kiali-ui/pull/1582#issuecomment-567601410
** screenshot **
> IstioConfigList - Istio type selector now is typeahead variant

- src/components/Charts/Charts.scss
- src/components/Charts/CustomFlyout.tsx
- src/components/Charts/SparklineChart.tsx
Also fix an issue with the tooltip arrow not pointing exactly to the hovered datapoint
Fixes https://github.com/kiali/kiali/issues/2068
> Make sparkline tooltips overflowing (svg scope)

- src/pages/AppList/FiltersAndSorts.ts
- src/pages/IstioConfigList/FiltersAndSorts.ts
- src/pages/Overview/Filters.ts
- src/pages/ServiceList/FiltersAndSorts.ts
- src/pages/ServiceList/__tests__/ServiceListComponent.test.ts
- src/pages/WorkloadList/FiltersAndSorts.ts
When there are two filters with same names, the filter keeps applied between pages. That is the case of Name filter for Services/Apps/Workloads.
The bug was introduced here: https://github.com/kiali/kiali-ui/pull/1590
> Undo filter renaming on List Pages

- src/components/Health/Health.scss
- src/components/Health/HealthDetails.tsx
- src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/pages/AppDetails/AppInfo/AppDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
- src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
- src/types/Health.ts
* change "Health" to "Overall Health"
* change "Pods Status" to "Pod Status"
* remove the colon after "Pods Status" & "Error Rate over last 5m"
* remove the icons from "Pods Status" & "Error Rate over last 5m"
In screenshot left is BEFORE, right is AFTER the changes. I had to change the workloads and services cards to have children and keep the health icon in those cases. I hope that's OK; if not, I may need to do a 2nd iteration in the UXD call to check how to deal with those cases.
Fixes kiali/kiali#1720
> UX suggestions for Health card in detail pages

- src/components/Details/DetailObject.tsx
- src/components/Details/__tests__/DetailObject.test.tsx
- src/components/Details/__tests__/__snapshots__/DetailObject.test.tsx.snap
Remove the `text-capitalize` class from the DetailObject component. Because the match rule's keys are case-sensitive, users cannot distinguish if their original case when using `text-capitalize` class.
Before change:
After change:
> Remove capitalize class from DetailObject component

- src/components/Charts/CustomFlyout.tsx
- src/components/Charts/CustomLabel.tsx
- src/components/Charts/SparklineChart.tsx
See inline comment for hack description.
Note that I'll suggest a patch in victory to get a better solution
Fixes https://github.com/kiali/kiali/issues/2097
> Sparklines: show several colors on tooltip (hacky)

- package.json
we have the lint:precommit task and the lint task in build:dev (executed by travis) we don't need execute again lint in the build:prod.
All the code in the project has passed eslint so it has no sense pass it again in the prod build.
> Remove lint in build:prod

- src/components/CytoscapeGraph/CytoscapeToolbar.tsx
- src/components/Pf/PfColors.tsx
- src/components/Time/Replay.tsx
- src/components/Time/_Time.scss
- src/pages/Graph/GraphPage.tsx
I lost my final commit when squashing the PR for Graph Replay.  This adds it back.
Addendum to kiali#1421 (PR #1585)
- thicken replay border
- set replay color to --pf-global--active-color--300
- border
- slider selection background (I added it here for consistency)
- badged time range background
- set active speed to --pf-global--primary-color--200
- set active custom start icon to --pf-global--active-color--400
- also, for consistency, set same for active layout icon in cytoscape toolbar
> Add back Graph Replay lost commit for final UX tweaks

- src/components/PfSpinner.tsx
Backport for 1.12
Fix https://github.com/kiali/kiali/issues/1978
> Add id to the loading spinner

- src/app/AuthenticationController.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
backport to v1.12
jaeger error didn't appear in MessageCenter.
Now we can see the message related with the integration.
Fix: kiali/kiali#2155
> Service Details load Error when Jaeger is configured wrongly

- src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
- src/components/IstioActions/IstioActionsDropdown.tsx
- src/components/IstioActions/IstioActionsNamespaceDropdown.tsx
- src/components/IstioWizards/IstioWizardActions.ts
- src/config/Config.ts
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/IstioConfigNew/GatewayForm.tsx
- src/pages/IstioConfigNew/IstioConfigNewPage.tsx
- src/pages/IstioConfigNew/SidecarForm.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/routes.tsx
- src/services/Api.ts
- src/types/IstioConfigDetails.ts
- src/types/IstioObjects.ts
- src/utils/IstioConfigUtils.ts
- src/utils/__tests__/IstioConfigUtils.test.ts
Today, Kiali creates IstioConfig at Service details level only using "context" wizards, where Services/Workloads are combined in a high level abstraction to allow user to define Istio configuration in a set of driven scenarios.
This new PR allows to create objects that are out of the context of a Service, for example, on this work we have introduced Gateways and Sidecars.
This new option is enabled at Istio Config list level:
It moves to a new Form page where user can select the type of resource to create:
On this first step, only Gateways and Sidecars can be generated. 
Another goal of this work is to structure these subforms in a way that is easy to add more.
Also, the forms don't cover all the potential scenarios (some objects as Sidecars may have huge combination of possibilities) but …
> Add structure to create new Istio config resources at namespace level

- src/components/Metrics/CustomMetrics.tsx
- src/components/Metrics/IstioMetrics.tsx
- src/components/Metrics/SpanOverlay.ts
- Move spans-fetching related code from istio metrics component to a separate class
- Re-use in custom metrics
Fixes https://github.com/kiali/kiali/issues/2160
> Enable traces correlation with runtime metrics

- src/components/Pf/PfColors.tsx
- src/components/SummaryPanel/RateChart.tsx
It is currently very difficult to tell the difference between 5xx and 4xx colors in the sidepanel rate chart.
This was done on purpose because the 4xx is being treated as Errors in the context of this rate chart. However, the colors are too close together to differentiate.
This PR is what UxD approved for colors to more easily differentiate between 4xx and 5xx in the rate chart. 
The PR adds a new `WarningDanger` color for the warnings being interpreted as danger in the rate chart.
closes https://github.com/kiali/kiali/issues/2075
https://github.com/kiali/kiali-design/issues/165
**Before**:
**After**:
> Make sidepanel rate chart graph colors more easily distinguished.

- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/components/SummaryPanel/InOutRateTable.tsx
- src/components/SummaryPanel/RateChart.tsx
- src/components/SummaryPanel/RateTable.tsx
- src/components/Tab/SimpleTabs.tsx
- src/pages/Graph/SummaryLink.tsx
- src/pages/Graph/SummaryPanel.tsx
- src/pages/Graph/SummaryPanelCommon.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/Graph/SummaryPanelGroup.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/pages/Graph/_Graph.scss
- src/styles/index.scss
Apply design feedback for graph side panels:
- prefer badged resources
- remove "node badges" (confusing as not equivalent to labels)
- make health a distinct badge
- introduce kebab action menu equiv to context menu options
- consistent font
- thin charts and reduce whitespace
- thin chart bars
- use white background for table headers
- remove links in graph summary as they duplicate the main accordian menu options
- extend tabs to 100%
- add fixed scroll bar to avoid "resize flashing" on refresh
Design issue
closes https://github.com/kiali/kiali-design/issues/149
Kiali issue
closes https://github.com/kiali/kiali/issues/1417
@mattmahoneyrh, @pbajjuri20  For testing I suggest setting up a before/after approach and compare old side panel with new side panel.  Also, verify kebab options …
> Graph side-panel UX review

- src/components/Validations/ValidationSummary.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/Overview/OverviewPage.tsx
- src/types/IstioObjects.ts
Needs backend PR: https://github.com/kiali/kiali/pull/2193
Kiali doesn't compute the validity of a namespace, Kiali analyzes Istio objects living in a namespace. Because of that, the behavior in the Overview page and Graph regarding Istio Objects is changed in this PR.
The new behavior is:
- Kiali shows 'N/A' with a tooltip saying: "No Istio Objects found in this namespace" **when** there aren't istio Objects for that namespace.
- Kiali shows an Icon (Validation higher severity) with a tooltip saying: "N objects analyzed - Error - 4 warnings, 2 errors found", **when** there is one or more Istio Objects.
In the picture below we have:
1. default ns - bookinfo example running on the mesh and we have istio objects (in warning).
2. desert ns - no applications running, no istio objects. It …
> Show Istio Config status only when objects present. Show # objects counted

- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/pages/Graph/SummaryPanelGroup.tsx
- src/pages/Graph/SummaryPanelNode.tsx
It happens when jaeger is not configured in cluster: external link is used in this case. It must be dealt with something like window.open
Fixes https://github.com/kiali/kiali/issues/2202
@jshaughn I've put the click handler in a common function for wherever it's used. I could have opted for a dedicated component as well... but did the quickest way, if it's ok with you.
> Summary panel actions: allow open in new window

- src/pages/Graph/SummaryPanelGraph.tsx
For regular k8s apps, meaning non-istio (without sidecars) apps, correct the namespace spacing and validations to look proper.
fixes #https://github.com/kiali/kiali/issues/2217
Before:
After:
> For non-istio apps make correct the namespace/validation spacing

- src/components/IstioWizards/ThreeScaleIntegration.tsx
- src/components/Nav/Menu.tsx
- src/components/Nav/RenderPage.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/extensions/threescale/ThreeScaleHandlerDetails/ThreeScaleHandlerDetailsPage.tsx
- src/pages/extensions/threescale/ThreeScaleHandlerList/ThreeScaleHandlerListPage.tsx
- src/routes.tsx
- src/types/ServerConfig.ts
UI changes to refactor 3scale feature to move it like a structured add-on/extension.
In the previous 3scale extension implementation, the 3scale handler management was included inside the 3scale wizard.
This PR moves the handlers to a separate 3scale section enabled/disabled from the backend config as an extension:
It implements a pretty basic list/details model with a basic form to create/edit a 3scale handler (an entity with 4 fields):
Note that 3scale handlers have no notion of namespace, user manages 3scale entities that Kiali maps internally on Istio Rules/Adapter/Handlers typically co-located into the control plane.
But from 3scale extension perspective, it doesn't belong to any namespace as it is not a formal entity.
In practice, the implementation of these handlers are regular …
> Read server config for 3scale rendering

- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
This improves the styling of the logs-textarea on a workloads detail page.
* the textarea is now filling the entire available height
* resizing is disabled, as that doesn't provide any benefit anymore with the above improvement
* there is some padding around the text so the logs are not hugging the border of the textarea anymore
fixes: https://github.com/kiali/kiali/issues/2189
[ ] Is your pull-request introducing changes in behaviour? No
Before:
After:
> Expand log area

- package.json
- src/app/__tests__/App.test.tsx
- src/components/Metrics/CustomMetrics.tsx
- src/components/Metrics/IstioMetrics.tsx
- src/components/Time/TimeRangeComponent.tsx
- src/setupTests.ts
- yarn.lock
It allows to zoom-in charts by selecting a region (works for Istio metrics & Custom metrics)
Fixes https://github.com/kiali/kiali/issues/1860
It needs k-charted update /  https://github.com/kiali/k-charted/pull/78
> In-chart time navigation with brush container

- src/app/History.ts
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/pages/Graph/GraphPage.tsx
- src/pages/Graph/GraphToolbar/GraphToolbar.tsx
- src/utils/SearchParamUtils.ts
ensure that the focusSelector is processed only one time
- clean the URL param and prop after initial render
bonus fix: another dirty state issue, ensure graph replay is stopped when navigating away from the graph.
Fixes https://github.com/kiali/kiali/issues/2228
Test1:
1) Nav to workloads
2) Select a workload
3) Click "Show on Graph"
- note the animation
4) Click Replay
5) Click Start
pre-fix: note focus animation repeats
post-fix: no second animation and url is clean of the focusSelector param
Test2:
1) Nav to graph
2) Click Replay
3) Nav to workloads (left menu)
4) Nav back to graph (left menu)
pre-fix: replay is still open
post-fix: replay is not open, standard graph for current time
> Focus animation changes

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
This enables line wrapping on the YAML editor of Istio resources.
https://issues.redhat.com/browse/KIALI-2215
https://github.com/kiali/kiali/issues/1406
[] Is your pull-request introducing changes in behaviour?
Not really changes in behaviour - this is solely a visual change.
> KIALI-2215: Enable wrapping on the ACE editor

- src/components/IstioWizards/IstioWizardActions.ts
- src/components/IstioWizards/WeightedRouting.tsx
Fixes kiali/kiali#2205
This PR address the use cases we have discussed.
I'm going to review 2205 in the context of the other wizards and see here what is missing.
But probably the Weigthed Routing Wizard can be tested. @hhovsepy
> Support Weigthed Routing Wizard when workloads are added/removed

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/EmptyGraphLayout.tsx
- src/pages/Graph/GraphPage.tsx
This is pulling up redux properties and disconnecting CytoscapeGraph and EmptyGraphLayout components from Redux. The behavior of the components look unchanged and it makes sense, because the same properties are still being provided to the changed components. Properties are just coming from GraphPage rather than directly from Redux.
Fixes kiali/kiali#2151
> Decouple settings of CytoscapeGraph component from redux

- package.json
- yarn.lock
Make version strategy consistent with other package versioning with 'pinned' static versions.
Using the pinned versions will prevent building something that may not have been tested. So if QE tests a particular version built a couple of weeks ago and then a newer version of that library comes out -- it gets pulled in unknowingly.
> Trivial: Make version strategy consistent with other package versioning 

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
Today in the graph, a single click selects a node and a double-click drills down into the node focus graph (aka node graph, node detail graph). On the node focus graph a double-click on the focus node has no effect because we are already drilled down. A natural progression would be to have that double-click navigate to the relevant detail page.
fixes https://github.com/kiali/kiali/issues/2046
> Double-click focus node to navigate to detail

- src/pages/Graph/SummaryLink.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
Use "auto" tooltip positioning for the graph side panel badges to reduce tooltip covering.
Fixes https://github.com/kiali/kiali/issues/2196
@abonas A couple of comments.  First, as seen in the screenshot the tooltip pointer does not have a black background when positioned to the left.  That seems to be a feature of Tooltip, perhaps a minor bug.  I am going to show UX and create a PF bug if necessary.   Second, I have very occasionally seen the second part of this issue, the "transparent" tooltip.   I can't reproduce it reliably, or sometime at all.  This looks like a PF issue for sure.  The Tooltip looks like it's stuck in a "fade" animation.  We could try to workaround this by explicitly setting animation="none" but I think it 's probably better to generate a PF issue.  Again, I'll pass …
> Use "auto" tooltip positioning for graph side panel

- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
Adding warnings to route table into VR details page.
To reproduce:
```
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
name: reviews
namespace: default
spec:
hosts:
- reviews
http:
- route:
- destination:
host: reviews
subset: v1
weight: 80
- destination:
host: reviews
subset: v1
weight: 20
```
Fixes https://github.com/kiali/kiali/issues/2446
> Add new validation path to VS route table

- src/components/VirtualList/Config.ts
Typo that makes sidecar yaml editor page blow up.
https://github.com/kiali/kiali/pull/2468
> Typo: Sidercars. IstioConfig details error

- src/components/Nav/Menu.tsx
Fixes https://github.com/kiali/kiali/issues/2479
@aljesusg I think i introduced this regression in a previous change. In Menu props, now `jaegerUrl` is `string?` instead of `string`.
> Fix distributed tracing link displayed with no url

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/types/IstioConfigDetails.ts
Fixes kiali/kiali#1383
This PR introduces a poll mechanism to refresh the current editable resource with the aim to identify changes on the resourceVersion or errors (delete situation).
On this cases send a warning to the user, in the case when a resource is deleted, it disables "delete/save" actions only allowing to reload/cancel the page to move back to the list page.
Note that this PR uses a fixed timeout, as a first try, this also brings the scenario to enable "refresh" in list/details pages for similar use case: automatically updates.
But this last scenario will be discussed/implemented in a separate issue/PR.
> IstioConfigDetails: notify user when resource changes outside Kiali

- src/pages/AppList/FiltersAndSorts.ts
- src/pages/ServiceList/FiltersAndSorts.ts
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/types/Health.ts
- src/types/SortFilters.ts
Closes https://github.com/kiali/kiali/issues/1935.
This, combined with https://github.com/kiali/kiali-ui/pull/1561 fixes all the problems with the health tooltips and sorting.
The main problem this tackles is that, when doing the sort, the health for the services/apps/workloads might not be available yet, so it fails. It is ittermitent but it does not happen anymore after the change.
> Fix race condition when sorting by Health

- src/components/Validations/ValidationSummary.tsx
- src/pages/Overview/OverviewPage.tsx
Moving the istio config status next to namespace name in the overview page.
The extra line on the bottom is removed. It covers the proposal made in https://github.com/kiali/kiali/issues/2321#issuecomment-565288808
> Overview - Move Istio Objects status to namespace name level

- .travis.yml
- package.json
- src/pages/WorkloadDetails/WorkloadInfo/__tests__/WorkloadDescription.test.tsx
- src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
- yarn.lock
cf https://github.com/kiali/kiali-ui/pull/1673/commits/11d5bd57a6089f30490f022c57e9d21b8348b818
The problem was that we use pretty-quick in our dev tools / pre-commit hook, and travis was using something different (prettier), and wasn't failing upon files rewrite (which in turn generated JSX minor changes, and snapshot failures).
> Put WorkloadDescription snapshot back (and use pretty-quick)

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/MiniGraphCard.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/Pf/PfTitle.tsx
- src/pages/AppDetails/AppInfo/AppDescription.tsx
- src/pages/Graph/GraphToolbar/GraphFind.tsx
- src/pages/Graph/GraphToolbar/GraphToolbar.tsx
- src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
- src/pages/Overview/OverviewCardLinks.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
- src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
Follow up of the mini-graph feature. This is addressing the following points (commented in https://github.com/kiali/kiali-ui/pull/1670#issuecomment-590141647):
* the graph shouldn't have any actions, other than pan enabled
* add a View graph link on the card title
* The "Show on graph" link of the title of the page was moved under a kebab menu on the mini-graph card.
* mini-graph shouldn't manipulate the URL
**BEFORE:**
**AFTER:**
---
This is creating a MiniGraphCard component to reduce code duplication.
Additionally, because of UX feedback, this is also:
* Turning off traffic animation for mini-graph
* Shorten to "Back to full graph" on the back button of the drilled-down graph
* Use "Show" instead of "Go to" in the tooltips of the cards on the overview page
---
Fixes kiali/kiali#1960.
> Move "Show on graph" link down to the mini-graph card

- src/components/SummaryPanel/ResponseHostsTable.tsx
Improve edge side-panel Hosts tab by presenting host value as ellipsed with tooltip, when necessary.
Fixes https://github.com/kiali/kiali/issues/2499
After:
> Improve edge side-panel Hosts tab

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/ServiceLink.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/__tests__/ServiceLink.test.tsx
Service link from both DestinationRule and VirtualService details page is fixed.
Supported links:
- reviews
- reviews.default (not cross-namespace, may clash with service entries)
- reviews.default.svc.cluster.local (cross-namespace supported)
Not linked:
- service entries
- *.local
- *.bookinfo.svc.cluster.local
https://github.com/kiali/kiali/issues/2533
Fixes https://github.com/kiali/kiali/issues/2533
> Fix service link into Istio Object details page

- src/components/CytoscapeGraph/TrafficAnimation/AnimationTimerConfig.ts
- src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
- src/components/CytoscapeGraph/TrafficAnimation/__tests__/AnimationTimerConfig.test.ts
- Needs to calibrate amplitude as first step
- Use linear relation between rate and dots generator
- Use consistent code between http & tcp rates
Fixes https://github.com/kiali/kiali/issues/2469
> Make traffic animation proportional to volumetry

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
There are some times when changing the graph edge label to **response time** causes a crash. This PR fixes that issue.
fixes https://github.com/kiali/kiali/issues/2549
> Fix graph error when enabling response time edges in some cases.

- src/pages/Overview/OverviewPage.tsx
- Adding some styles to truncate the namespace name if it is too large to fit the card in one line
- Add a tooltip to be able to read the full name of the namespace
Fixes kiali/kiali#2330.
**BEFORE**
**AFTER CHANGES**
**Expanded view** (notice tooltip)
**Compact view** (tooltip available, but not shown)
> Ellipsis on cards of overview page when namespace name is too large

- src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/components/Pf/PfColors.tsx
- src/pages/Graph/GraphHelpTour.ts
- src/pages/Graph/GraphToolbar/GraphSettings.tsx
- src/pages/Graph/GraphToolbar/GraphToolbar.tsx
- src/pages/Graph/_Graph.scss
The graph toolbar wraps even on relatively wide browser windows.  Merging it into the Display dropdown conserves quite a bit of space and helps limit wrapping.  It also consolidates display options since edge labeling is an option.
@lwrigh, @israel-hdez  The good news is that I was able to get the mixture of radio buttons and checkboxes into a single dropdown.  The bad news is that I had to toss out the use of the PF4 Select component.  The dropdown is now signifigantly long and the Select component did not handle scrolling well, and so for shorter windows the bottom options were clipped.  Note that this was true in the past as well, but the lesser number of options made it unlikely to happen.  As an alternative I reworked things in the model of what we do in the namespaces dropdown. …
> Graph: Merge edge options into display dropdown to limit toolbar wrap

- src/pages/Overview/OverviewCardContentExpanded.tsx
- src/pages/Overview/OverviewCardSparkline.tsx
* Change the size of "N/A" indicator to match "No traffic" size (expanded/list views)
* Position "N/A" and "No traffic" in the middle of the card (expanded/list views)
Fixes kiali/kiali#2331
**Expanded view / BEFORE**
**Expanded view / AFTER**
**List view / BEFORE**
**List view / AFTER**
> Better font sizing and positioning in Overview page

- package.json
- yarn.lock
This is from Github security alerts. Note: this is a dev-dependency only so, low risk. Only for builds.
closes #https://github.com/kiali/kiali/issues/2604
> Upgrade the 'kind-of' library for vulnerability. (Medium)

- src/pages/WorkloadList/FiltersAndSorts.ts
Fix https://github.com/kiali/kiali/issues/2631
Now If there is not additional details the workload list will sort by missing labels.
both missing labels > 1 missing labels
In case same missing labels so by name.
> Sort by details in workload list with missing labels

- src/components/Nav/SecondaryMasthead.tsx
- src/pages/Graph/GraphHelpFind.tsx
- src/pages/Graph/GraphToolbar/GraphFind.tsx
- src/pages/Graph/GraphToolbar/GraphSecondaryMasthead.tsx
- src/pages/Graph/GraphToolbar/GraphToolbar.tsx
- src/routes.tsx
A custom secondary masthead allows us to move some things around for a more balanced use of space and less overall width required.
Also includes:
- change to info icon for graph find help
- a couple of small tweaks to the find help popover to remove scrollbar in preface and arrow on tabs
Fixes https://github.com/kiali/kiali/issues/2620
> Graph toolbar use custom secondary masthead

- package.json
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
- yarn.lock
Split the workload tab into pod logs and container logs sections. This eliminated the container selection dropdown as well.
Before:
After:
closes https://github.com/kiali/kiali/issues/2203
> Split the workload logging tab  into pod logs and container logs

- src/components/IstioWizards/IstioWizardActions.ts
- src/pages/IstioConfigNew/AuthorizationPolicyForm.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/From/SourceBuilder.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/From/SourceList.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleBuilder.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleList.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/To/OperationBuilder.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/To/OperationList.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionBuilder.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionList.tsx
- src/pages/IstioConfigNew/IstioConfigNewPage.tsx
- src/types/IstioObjects.ts
This PRs provides a new form to create AuthorizationPolicy objects.
Note:
- IstioConfig new form only support the creation of the object, updates are done via yaml editor.
- AuthorizationPolicy is a complex object with multiple edges and corner cases, hard to focus just on some, so, the form supports all cases (in other objects as Gateways/Sidecars forms only support a subset of most direct scenarios).
- User requires to catch up with the terminology used by AuthorizationPolicy entity.
How to test:
- Best strategy would be to follow the Istio tasks tutorial https://istio.io/docs/tasks/security/authorization/ and check that all scenarios can be done via the form, checking that resulting yaml is valid and well formed.
Fixes https://github.com/kiali/kiali/issues/2041
It requires backend PR …
> Add AuthorizationPolicy form

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
- src/pages/Graph/GraphToolbar/GraphFind.tsx
This fixes an issue with zoom/fit/pan and graph hide.  We only want to re-establish the zoom/pan settings if we believe the graph is unchanged (basically the same removed elements are in play as when we previously executed the hide logic).  The determination is not perfect but should work fairly well.
- also made a couple of minor tweaks to "safeFit()" on the off-chance it could help in general.
Fix related to https://github.com/kiali/kiali/issues/2514
In the _before_ video note that after applying the hide expression and toggling `Show Services` that we need to also click `Fit` in the cytoscape toolbar.  In the _after_ video we can see that the clicking `Fit `has no effect, the graph is already layed out correctly.
Before:
After:
After 2: this second _after_ video shows that we maintain …
> Fix issue zoom/pan/fit and graph-hide

- src/components/Metrics/GrafanaLinks.tsx
- src/components/Metrics/__tests__/GrafanaLinks.test.ts
Example: Configured Grafana URL 'http://grafana:3000?orgId=1' to not screw up link generation
Fixes https://github.com/kiali/kiali/issues/2623
Backend PR: https://github.com/kiali/kiali/pull/2687
> Allow pre-set query params in Grafana URL

- src/pages/Overview/OverviewPage.tsx
Fix https://github.com/kiali/kiali/issues/2693
Now the tooltip is at bottom of the "labels trigger" and I set the distance to 5 (iis the distance of the tooltip to its target, defaults to 15)
> Labels tooltip on overview displayed shifted for top right projects

- src/components/Health/__tests__/HealthIndicator.test.tsx
- src/pages/Overview/NamespaceInfo.ts
- src/pages/Overview/OverviewCardBars.tsx
- src/pages/Overview/OverviewCardContentExpanded.tsx
- src/pages/Overview/OverviewPage.tsx
- src/types/Health.ts
- src/types/__tests__/Health.test.ts
Fix https://github.com/kiali/kiali/issues/2049
The idea is show resources undesired replica
> Namespaces overview should differentiate idle from failure apps

- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
This PR adds:
fixes: https://github.com/kiali/kiali/issues/2667
**Before**
**After**
> Log tailing capability (and horizontal scrolling)

- src/components/Health/Health.scss
- src/components/Health/HealthIndicator.tsx
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
Fixes https://github.com/kiali/kiali/issues/2706
Now health is consistent with other tooltips used in Kiali:
This out-of-sync is more visible in the same row that other tooltips are used:
Note, that this is consistent with other complex tooltips with similar structure (list of status with icons):
> Sync Health tooltip style with rest of Kiali

- src/components/IstioWizards/IstioWizard.tsx
When Kiali Wizard is updated, Gateway is populated from properties but without initializing state.
This creates a bug when updating a Wizard when Gateway are wrongly deleted.
Related to https://github.com/kiali/kiali/issues/2726
How to reproduce error:
1.- Go to service reviews
2.- Create configuration using wizard, i.e. Weighted Routing.
3.- Add/Select a Gateway.
4.- Save configuration.
5.- Confirm Gateway is in generated VirtualService.
6.- Open the Wizard for Updates.
7.- Modify some weights but don't touch the Gateway.
8.- Save configuration.
9.- Gateway is removed. This is a bug.
How to test:
- Validate repeating previous steps, on step 9, an existing Gateway prevails in the update.
It requires a PR in master branch.
> [v1.12] Fix missing Gateway initialization on Wizard state

- src/components/IstioWizards/IstioWizard.tsx
When Kiali Wizard is updated, Gateway is populated from properties but without initializing state.
This creates a bug when updating a Wizard when Gateway are wrongly deleted.
Fixes kiali/kiali#2726
How to reproduce error:
1.- Go to service reviews
2.- Create configuration using wizard, i.e. Weighted Routing.
3.- Add/Select a Gateway.
4.- Save configuration.
5.- Confirm Gateway is in generated VirtualService.
6.- Open the Wizard for Updates.
7.- Modify some weights but don't touch the Gateway.
8.- Save configuration.
9.- Gateway is removed. This is a bug.
How to test:
Validate repeating previous steps, on step 9, an existing Gateway prevails in the update.
> Fix missing Gateway initialization on Wizard state

- package.json
- yarn.lock
- jquery fixed @3.5.0
- maistra-1418
- was @3.4.0 implicitly
- lodash @4.17.15
- maistra-1327
- was @4.17.11 explicitly
- required 4.17.12 but bumped to latest due to other known CVEs
- forced us to fix table-resolver @3.2.0
- minimist @1.1.2
- maistra-1303
- was @0.0.10 implicitly
also: remove snyk from this branch and manage deps manually
> package updates to satisfy CVEs

- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Adds the ability to change the orientation of the logging layout from horizontal/vertical.
fixes:  https://github.com/kiali/kiali/issues/2700
**Vertical:**
**Side by Side**:
> Add log orientation layout

- package.json
- yarn.lock
Our deps (PF4) are already on the latest so this only removes the older version.
> Update lodash to the latest because there are known CVEs against earlier versions

- src/components/IstioActions/IstioActionsButtons.tsx
- src/components/Metrics/IstioMetrics.tsx
- src/components/Metrics/TrafficDetails.tsx
- src/pages/AppDetails/AppInfo.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceTraces.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
- src/styles/_layout.scss
This is a minor CSS adjustment, but necessary to align all header components with tabs and body cards in the details pages:
Fixes https://github.com/kiali/kiali/issues/2744
Note the bottom padding is a little bit more complex as it requires more checking to adjust correctly the scrolling in "all" components.
> Adjust alignment of tabs and body with header in all pages

- src/components/Nav/Masthead/Masthead.tsx
- src/components/PfSpinner.tsx
This is using the new spinner. Note that it's said to be experimental.
Fixes https://github.com/kiali/kiali/issues/2679
(See also https://www.patternfly.org/v4/documentation/core/components/spinner )
A couple of notes:
- Previously the spinner was positioned to the left via absolute position. For some reason, this style wasn't applied on the new spinner, so I just removed it. Our spinner is in the "masterhead" icons/controls, so it makes more sense IMO to display it to the right ... if it's not what we want, then we should reorganize the whole masthead I think. Let me know if it's not ok to have it to the right.
- The PF component is said to be experimental. While testing I've seen that sometimes it displays very short arcs (almost dots) instead of the long ones, I'm not sure if it's …
> Use new patternfly spinner

- src/pages/IstioConfigNew/IstioConfigNewPage.tsx
Changed the order of namespaces field:
Added "canCreate" validation on "isFormValid" to not enabled the create button if user has not rights.
Fixes https://github.com/kiali/kiali/issues/2762
> Re-org namespaces in Create Istio New Config

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
Fixes https://github.com/kiali/kiali/issues/2787
I've seen that when there has never been mtls traffic, isMTLS has a -1. It made the not getting in the if condition and therefore, not printing any badge.
My question is, should I protect the usage of `mtlsPercentage` or the system guarantees that there will be always a number?
Steps to test this PR in bookinfo: https://github.com/xeviknal/istio-lab/tree/master/meshwide-mtls/details-disabled
> Show broken locks into edges without mtls in mesh-wide mtls scanarios

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
> v1.18 cherry-pick of #1787 - Show broken locks into edges without mtls

- package.json
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
- yarn.lock
Add the ability to select a container in the pod.
fixes: https://github.com/kiali/kiali/issues/2765
> Add Container selection back into Workload logs.

- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Add a hide log lines feature for eliminating noise when displaying workload logs. 
Many times there is so much noise in the logs that one must filter via `grep` or whatever in the CLI.  in the UI, we need the similar capability to filter the logs.
fixes: https://github.com/kiali/kiali/issues/2778
> Add a hide log lines feature(noise) when displaying workload logs

- src/components/JaegerIntegration/JaegerResults/SpanTable.tsx
Fix https://github.com/kiali/kiali/issues/2712
The proposal is /^([a-z0-9-\.]+)-[a-z0-9]+-[a-z0-9]+\.[a-z0-9-]+$/
We had ${srv}-v[0-9]*
I can't test if works because I have problems with me maistra cluster
Sample node to parse => sidecar~172.17.0.22~ai-visitors-779956ddf8-s78gr.default~default.svc.cluster.local
We need ai-visitors-779956ddf8-s78gr.default
In normal cases reviews-v2(.bookinfo)
> Link from traces to workload logs can be wrong

- src/components/IstioWizards/IstioWizardActions.ts
- src/components/MessageCenter/AlertDrawerMessage.tsx
- src/helpers/ValidationHelpers.ts
- src/pages/IstioConfigNew/AuthorizationPolicyForm.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/From/SourceBuilder.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleList.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/To/OperationBuilder.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionBuilder.tsx
- src/pages/IstioConfigNew/GatewayForm.tsx
- src/pages/IstioConfigNew/IstioConfigNewPage.tsx
- src/pages/IstioConfigNew/PeerAuthenticationForm.tsx
- src/pages/IstioConfigNew/RequestAuthenticationForm.tsx
- src/pages/IstioConfigNew/RequestAuthorizationForm/JwtRuleBuilder.tsx
- src/pages/IstioConfigNew/RequestAuthorizationForm/JwtRuleList.tsx
- src/pages/IstioConfigNew/SidecarForm.tsx
- src/pages/extensions/threescale/ThreeScaleHandlerDetails/ThreeScaleHandlerDetailsPage.tsx
- src/types/IstioObjects.ts
- src/utils/IstioConfigUtils.ts
- src/utils/__tests__/IstioConfigUtils.test.ts
This PR adds support to PeerAuthentication and RequestAuthentication objects in Create New IstioConfig.
Now together with AuthorizationPolicy, Kiali should be able to create all type of Security scenarios.
Requires https://github.com/kiali/kiali/issues/2797
How to test:
- Try to create objects described in https://preliminary.istio.io/docs/tasks/security/authentication/authn-policy/ 
- Or try to add objects described in https://preliminary.istio.io/docs/reference/config/security/peer_authentication/ and https://preliminary.istio.io/docs/reference/config/security/request_authentication/
Fixes https://github.com/kiali/kiali/issues/2797
Fixes https://github.com/kiali/kiali/issues/2685
Fixes https://github.com/kiali/kiali/issues/2694
> Add {Peer,Request}Authentication objects to Create Istio Config

- src/components/BreadcrumbView/BreadcrumbView.tsx
- src/components/FilterList/FilterHelper.ts
- src/components/FilterList/__tests__/ListPagesHelper.test.ts
- src/components/Filters/CommonFilters.ts
- src/components/Filters/LabelFilter.tsx
- src/components/Filters/StatefulFilters.tsx
- src/components/VirtualList/Renderers.tsx
- src/helpers/LabelFilterHelper.ts
- src/helpers/__tests__/LabelFilterHelper.test.ts
- src/pages/AppList/AppListComponent.tsx
- src/pages/AppList/FiltersAndSorts.ts
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/Overview/Filters.ts
- src/pages/Overview/OverviewPage.tsx
- src/pages/Overview/OverviewStatus.tsx
- src/pages/Overview/__tests__/OverviewPage.test.tsx
- src/pages/ServiceList/FiltersAndSorts.ts
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/pages/WorkloadList/WorkloadListComponent.tsx
- src/pages/extensions/iter8/Iter8ExperimentList/FiltersAndSorts.ts
- src/types/Filters.ts
Fix https://github.com/kiali/kiali/issues/2734
- I had to add this like a new Filter to be able to move this param to other lists
- LabelOperation Dropdown is displayed when user go to Label filter selection or we have a Label filter applied
- LabelOperation not add a "chip" in filters because by default we'll apply "OR" operation and it make not sense to add it for me.
- Applied in Workload, Services and Apps.
- It make sense to have this in overview too when we are filtering by labels related with the namespace and not by the objects of the namespace?
The line https://github.com/aljesusg/kiali-ui/blob/fix_2734/src/helpers/LabelFilterHelper.ts#L14 throw TS error
```bash
TypeScript error in /home/aljesusg/Projects/kiali/kiali-ui/src/helpers/LabelFilterHelper.ts(14,59):
No overload matches …
```
> Labels filtering: "all of" / "any of" switch

- src/config/ServerConfig.ts
- src/types/ServerConfig.ts
Counterpart of https://github.com/kiali/kiali/pull/2846 to have access to the canonicalMetrics flag to check if telemetry is based on v1/v2 metrics.
> Expose Istio Telemetry Version to Public Config

- src/actions/LoginThunkActions.ts
- src/app/AuthenticationController.tsx
- src/components/Nav/Masthead/UserDropdown.tsx
- src/config/AuthenticationConfig.ts
- src/pages/Login/LoginPage.tsx
- src/services/Login.ts
- src/types/Auth.ts
* Add support for OpenId strategy for authentication.
* It was just a matter of adding openid to some conditionals.
* Renamed OpenshiftLogin class as OAuthLogin for code clarity
* (see commits cdd8ffac07ca1a8de459e0768c4e434f40cb8fc3 and c6415eafa8c741c304f9b5869036566fd1aab048)
* Move the checkCredentials to AuthenticationController.tsx
* This was mainly for a more centralized authentication flow.
* Also, to prevent showing the login form for OpenShift/OpenID while the login cycle is finalizing.
* (see commit 3defea26de510bb7ae34c39126d4f5861e8a55c1)
Part of kiali/kiali#2056
> Add support for OpenId strategy for authentication

- src/pages/Login/LoginPage.tsx
- src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
Results on the following when LDAP is configured:
Results on the following when "login" is configured:
Part of kiali/kiali#2863, kiali/kiali#2862.
> Show message if Kiali is configured with LDAP or login strategy for authentication

- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Fix bug in Hide logs when `backspace` or `delete` is used to reset the hide filter. 
Note: using the 'x' already does the proper resetting of the hide filter.
fixes: https://github.com/kiali/kiali/issues/2878
> Fix bug in Hide logs when backspace or delete is used to reset 

- src/components/Link/IstioObjectLink.tsx
- src/components/VirtualList/Config.ts
- src/components/VirtualList/Renderers.tsx
- src/config/Config.ts
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigList/FiltersAndSorts.ts
- src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
- src/services/Api.ts
- src/types/IstioConfigDetails.ts
- src/types/IstioConfigList.ts
- src/types/IstioObjects.ts
- src/utils/IstioConfigUtils.ts
This PR removes the old "subtypes" used for adapter/templates.
In short, in Istio 1.0 there were some legacy mixer adapters that populated a lot of new interfaces.
We managed that in Kiali as logical "subtypes" of adapters/templates to simplify this view to the user.
Now, Istio manages those objects as standard handlers/instances, so we put them as regular object and clean some of the technical debt introduced in the first Kiali versions.
This PR requires the backend:
https://github.com/kiali/kiali/pull/2881
How to test this:
- Check regressions in all related Istio config existing features.
- Check that Handlers and Instances are showed up as normal Istio Config objects (3scale extension can be used for that easily).
> Remove subtypes. Add Instances/Handlers

- src/components/BreadcrumbView/BreadcrumbView.tsx
- src/components/FilterList/FilterHelper.ts
- src/components/FilterList/__tests__/ListPagesHelper.test.ts
- src/components/Filters/CommonFilters.ts
- src/components/Filters/LabelFilter.tsx
- src/components/Filters/StatefulFilters.tsx
- src/components/VirtualList/Renderers.tsx
- src/helpers/LabelFilterHelper.ts
- src/pages/AppList/FiltersAndSorts.ts
- src/pages/Overview/Filters.ts
- src/pages/Overview/OverviewPage.tsx
- src/pages/Overview/OverviewStatus.tsx
- src/pages/Overview/__tests__/OverviewPage.test.tsx
- src/pages/ServiceList/FiltersAndSorts.ts
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/types/Filters.ts
- src/utils/Common.ts
- src/utils/__tests__/Common.test.ts
This triggered some refactoring:
- New ActiveFilter "title" field
- Some simplification in StatefulFilters
- More typing: "groupBy" function, LabelFilters explicit call to avoid 'any'
- Move labelFilter type to CommonFilters.ts
Fixes https://github.com/kiali/kiali/issues/2785
> [Maintenance] Make filters "title" only used for display

- src/config/Config.ts
- src/pages/extensions/iter8/Iter8ExperimentDetails/CriteriaInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCreatePage.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCriteriaForm.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentDetailsPage.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/Iter8Dropdown.tsx
- src/services/Api.ts
- src/types/Iter8.ts
* Add Auto Refresh for Iter8 Detail page
* Auto detect Telemetry v1 vs v2 ( Input field fixed at unit=second, and conversion based on v1 or v2
* Action Design - Pause/Resume, Roll-forward, Roll-Back
* Criteria Tab using compact expandable
* Adding experiment estimate duration in Experiment creation page
* Iter8 Experiment Create page improvement
1.  Change Show Advance Options -> More / Less
2.  Default to show More
3.  Add one paragraph saying "Your experiment will run for x hours ...."
4.  Allow user to enter non-existing candidate right at the pull down list.
reference original Kiali-UI PR request [Kiali-UI PR  # 1805](https://github.com/kiali/kiali-ui/pull/1805)
** Dependency **
This PR depends on  [Kiali PR# 2815](https://github.com/kiali/kiali/pull/2815)
** …
> Iter8 v0.1.1 Integration for Kiali

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/MiniGraphCard.tsx
- src/pages/Graph/GraphPage.tsx
- src/types/Graph.ts
Double clicks on mini-graph card is enabled. When double-clicking, the mini-graph will redirect the user to the detail page of the selected node. No redirection is done if the detail page of chosen node is the one already being displayed. Also, nodes with no detail page (like service entries and inaccessible nodes) are ignored.
A small refactor had to be done to the CytoscapeGraph component. The double-tap event handlers were pulled up to the GraphPage component in order to be able to perform a different action depending on the page hosting the CytoscapeGraph component.
Fixes kiali/kiali#2790.
> Navigation to other detail pages using mini-graph

- src/services/Login.ts
OAuthLogin class is being used for both openshift and openid login strategies. OpenShift passes always the `access_token` parameter. OpenId providers *may* pass the access_token parameter, but id_token is warranted to be present (because of the asked response_type).
This is fixing a blocked login if the OpenId provider is not passing the access_token.
Fixes kiali/kiali#2925
> Fix test to determine OpenId/OAuth preparation

- package.json
- src/components/JaegerIntegration/JaegerScatter.tsx
- src/components/Metrics/CustomMetrics.tsx
- src/components/Metrics/IstioMetrics.tsx
- src/components/Metrics/SpanOverlay.ts
- src/components/Metrics/__tests__/IstioMetrics.test.tsx
- src/components/SummaryPanel/RateChart.tsx
- src/components/SummaryPanel/RpsChart.tsx
- src/utils/Graphing.ts
- yarn.lock
Bumping k-charted to enable:
- Overlay bucketed display (https://github.com/kiali/kiali/issues/2198)
- Collapsible blocks (https://github.com/kiali/kiali/issues/2614)
For overlay buckets, they are active when number of spans reaches 1000.
Clicking on a bucket will "zoom" in the related time frame.
> Bump k-charted, handle zooming on buckets

- package.json
- yarn.lock
Bump k-charted 0.6.0-rc5 => 0.6.0 (no change, just use released final version)
> Bump k-charted 0.6.0 final (no change)

- src/app/History.ts
- src/components/JaegerIntegration/JaegerResults/FormattedTraceInfo.ts
- src/components/JaegerIntegration/JaegerResults/JaegerItem.tsx
- src/components/JaegerIntegration/JaegerResults/JaegerTraceTitle.tsx
- src/components/JaegerIntegration/TraceListItem.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/pages/Graph/SummaryPanelNodeTraces.tsx
- src/pages/Graph/SummaryPanelNodeTraffic.tsx
- src/utils/SearchParamUtils.ts
- Split file SummaryPanelNode => (SummaryPanelNode + SummaryPanelNodeMetrics)
- When traces are enabled & service is selected, show a tabbed view Traces/Metrics below contextual node info
Fixes https://github.com/kiali/kiali/issues/2840
> Traces list in side-panel

- src/components/CytoscapeGraph/EmptyGraphLayout.tsx
- src/pages/Graph/GraphToolbar/GraphFind.tsx
- src/pages/Graph/GraphToolbar/GraphSettings.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
Was due to improper array equality check in EmptyGraphLayout
Fixing at the same time some warning in dev console:
- Some missing key props in lists
- React complaining that GraphFind should not be PureComponent as it has 'shouldComponentUpdate'
Fixes https://github.com/kiali/kiali/issues/2957
> Fix graph losing focused node context after first refresh

- src/components/IstioWizards/ServiceWizard.tsx
- src/components/IstioWizards/ServiceWizardDropdown.tsx
- src/components/IstioWizards/TrafficPolicy.tsx
- src/components/IstioWizards/WizardActions.ts
- src/pages/ServiceDetails/ServiceInfo.tsx
This PR's handles the fact of creating/editing/removing a PeerAuthentication while user is performing any traffic management wizard from the service details page.
When the user switch on the 'Add PeerAuthentication', the wizard will create a PeerAuthentication object with the selected dropdown. In case, the user switch off the selector, the wizard will remove that PeerAuthentication object.
The PeerAuthentication object it always apply to the workload in the same namespace and applying to the same 'app' label.
There is not option to indicate the tls mode at port-level. IMO, this scenario is a bit advanced.
Fixes https://github.com/kiali/kiali/issues/1381
> Traffic wizards - handle PeerAuthentications

- package.json
- src/components/Metrics/CustomMetrics.tsx
- src/components/Metrics/Helper.ts
- src/components/Metrics/IstioMetrics.tsx
- yarn.lock
Includes several changes for iter8
Removed p95 as visible by default
Backend PR required: https://github.com/kiali/kiali/pull/3046
> Bump k-charted 0.6.1-rc2 + default grouping on remote app

- src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
- src/components/NamespaceDropdown.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/CriteriaInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCreatePage.scss
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCreatePage.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCriteriaForm.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentDetailsPage.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentHostForm.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListContainer.tsx
- src/types/Iter8.ts
1. Iter8 v0.2 supports deployment/service-based experiment
2. add Host/Gateway support
3. Warning message if not running Iter8 v0.2
4. disable default namespace dropdown for experiment create page
Note: Replace the original [PR#1841] (https://github.com/kiali/kiali-ui/pull/1841)
[#1007](https://github.com/kiali/kiali/issues/2007)
This PR depends on [PR#3033](https://github.com/kiali/kiali/pull/3033)
1. Iter8 v0.2 supports deployment/service-based experiment
A. Deployment-Based
B. Service-Based
C. Experiment Listing page show the two different …
> Support Iter8 v0.2

- src/actions/MessageCenterActions.ts
- src/actions/__tests__/MessageCenterAction.test.ts
- src/components/MessageCenter/NotificationList.tsx
- src/components/MessageCenter/__tests__/MessageCenter.test.tsx
- src/reducers/MessageCenter.ts
- src/types/MessageCenter.ts
- src/utils/AlertUtils.ts
- src/utils/IstioValidationUtils.ts
Relax the popup warning for Istio Config validations.
Other notifications (AlertToasts) should remain as default behaviour.
Fixes https://github.com/kiali/kiali/issues/3074
> Relax Warning AlertToasts on Istio Config validations

- src/components/Validations/ValidationSummary.tsx
- src/components/Validations/__tests__/__snapshots__/ValidationSummary.test.tsx.snap
- src/pages/Overview/OverviewCardContentCompact.tsx
- src/pages/Overview/OverviewCardContentExpanded.tsx
Fixes https://github.com/kiali/kiali/issues/3082
When a CSS is built for production, there are some conflicts in the order of style for components compared with the developer one.
> Tooltip issues

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/pages/Graph/GraphToolbar/GraphFind.tsx
Fixes https://github.com/kiali/kiali/issues/3072
- For consistency between graph find/hide and logs show/hide, improve graph find handling to report independent errors for find and hide expressions.
- apply a UX-approved tweak to slightly reduce/lighten the find overlay to maintain better visibility of labels and nodes.
- immediately submit a find/hide value selected from the autocomplete dropdown   (or pasted).  Note that there is no native support for this, so we just assume any single input change > 1 character should be applied.  It seems to work well as a rule of thumb.
@mtho11 If you like the immediate submit on autocomplete select, we can add that to log show/hide as well.
> Find/Hide improvements:

- src/actions/JaegerThunkActions.ts
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/CytoscapeGraphSelector.ts
- src/components/CytoscapeGraph/CytoscapeTrace.ts
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/JaegerIntegration/JaegerHelper.ts
- src/pages/Graph/GraphPage.tsx
- src/pages/Graph/SummaryPanelCommon.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/pages/Graph/SummaryPanelNodeTraces.tsx
- src/pages/Graph/SummaryPanelTraceDetails.tsx
- src/utils/SearchParamUtils.ts
- Add trace ID to URL
- Split side-panel with a bottom section to show trace info when a trace is selected
- Allow selecting other nodes from that trace, keeping that panel opened
- Show some trace information
- Show spans information for each span within the trace for the selected node
- Link to Trace Details
- Focus animation triggered to localize span other-end client/server
Fixes https://github.com/kiali/kiali/issues/3010
> In-graph tracing: show trace details

- src/components/IstioWizards/WizardActions.ts
- src/config/Config.ts
- src/config/ServerConfig.ts
- src/pages/Overview/OverviewPage.tsx
- src/services/Api.ts
- src/types/ServerConfig.ts
Fixes https://github.com/kiali/kiali/issues/2896
Needs https://github.com/kiali/kiali/pull/3085
In compact view:
In table views where all labels are explicit:
When this feature is disabled, via operator or direct config, the new action shouldn't be added in the menu:
> Add/Remove Auto Injection

- src/components/IstioWizards/MatchingRouting.tsx
- src/components/IstioWizards/MatchingRouting/MatchBuilder.tsx
- src/components/IstioWizards/MatchingRouting/Matches.tsx
- src/components/IstioWizards/MatchingRouting/RuleBuilder.tsx
- src/components/IstioWizards/MatchingRouting/Rules.tsx
- src/components/IstioWizards/ServiceWizard.tsx
- src/components/IstioWizards/WeightedRouting.tsx
- src/components/IstioWizards/WizardActions.ts
Fixes https://github.com/kiali/kiali/issues/1374
Re-arrange the wizard to separate "Select Matching" / "Select Routes":
Introduce workload weights as opposed as simple workload names:
Allow to combine multiple routes with matching and different weights:
> Allow specify Weights in Matching Routing Wizard

- src/pages/Graph/SummaryPanelCommon.tsx
- src/pages/Graph/SummaryPanelTraceDetails.tsx
- Non-envoy traces now look consistent with envoy ones
- Fixed panel overflow
- Removed to full ID display as it's not a very important information; add a smaller ID slice instead
- Replaced some 'br' with 'p', and try to fit everything in height without scroll bars as much as possible
Fixes https://github.com/kiali/kiali/issues/3100
Screenshots:
- With envoy spans and short urls:
- With envoy spans and longer urls:
- With user-defined spans:
> Fix style issues with in-graph tracing

- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadInfo/FullScreenLogModal.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Moves the refresh controls from inside the logging tab to outside the logging tab to match other tabs for consistency.
fixes #https://github.com/kiali/kiali/issues/3011
Yes
Before:
After:
> Refactor refresh log tab

- src/components/JaegerIntegration/TraceListItem.tsx
- src/components/PfSpinner.tsx
- src/components/RightActionBar/RightActionBar.tsx
- src/components/TextOrLink.tsx
- src/pages/AppList/AppListPage.tsx
- src/pages/IstioConfigList/IstioConfigListPage.tsx
- src/pages/ServiceList/ServiceListPage.tsx
- src/pages/WorkloadList/WorkloadListPage.tsx
- src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListPage.tsx
Remove the deprecated `React.SFC` and replace with `React.FunctionComponent` as docs specify.
No behavioral changes just syntax change.
> Trivial: Remove the deprecated React.SFC and replace with FunctionComponent

- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadInfo.tsx
Fixes https://github.com/kiali/kiali/issues/3133
WorkloadInfo was refreshing workload when the proper way was delegating this into the parent component.
This causes side effect like run a Workload action and not having a fresh workload in other tabs (specially logs tab).
> Proper refresh Workload from WorkloadDetails

- src/pages/Graph/SummaryPanelNodeTraces.tsx
- src/pages/Graph/SummaryPanelTraceDetails.tsx
Two trivial changes about wording used in graph traces.
"Go to Tracing" -> "View App Traces"
"See trace in Jaeger" -> "View Trace in Tracing"
- Tracing is used in "Traces" Tab to refer to the external tracing tool, better to refer to "App Traces" on this case.
- The same external link is used in "traces" tab, so better to unify the same wording instead o introduce new one.
Place the external link at the bottom, when the app/service is too long, it's hardly differentiated from the trace title one.
I think with this little change it's more clear and it seems clean.
> Adjust wording between traces in graph and details

- package.json
- yarn.lock
Address a vulnerability detected by github in the 3rd party libraries.
I've addressed this in k-charted as well https://github.com/kiali/k-charted/pull/110.
I'd require more testing, smoke tests seem ok, but these changes may be good if are tested by anyone else as they can easily introduce side effects.
> Bump dot-prop and lodash

- src/reducers/LoginState.ts
Show in login screen the error that the back-end is outputting to better inform to the user what went wrong.
Now, we should see:
Fixes kiali/kiali#3150
> Show login error message returned from back-end

- src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
- src/components/CytoscapeGraph/CytoscapeToolbar.tsx
- src/pages/Graph/GraphPage.tsx
Introduce a new control on the cytoscape toolbar to toggle the ability to drag nodes (default=no drag).  This allows users to move nodes around to improve the layout manually for for visual inspection, screenshots, etc.
The manual repositioning is lost (and the toggle disabled) whenever there is a:
- change of graph type
- navigation away and back to the graph page (including node detail graphs)
- browser refresh
The manual repositioning is maintained on graph refresh unless a layout is required.  A layout change will not disable the toggle if it is currently enabled.   A layout is required when:
- the graph refreshes and nodes are lost or gained for the new time period.
- nodes are hidden via graph hide (and the Compress Hidden Display option is enabled)
- manual layout change via the …
> Add ability to drag nodes

- src/components/IstioConfigSubList/IstioConfigSubList.tsx
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadServices.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCreatePage.tsx
- src/pages/extensions/threescale/ThreeScaleNew/ThreeScaleNewPage.tsx
- src/services/Api.ts
- src/types/IstioConfigList.ts
- src/types/ServiceInfo.ts
Related to https://github.com/kiali/kiali/issues/3015
Requires https://github.com/kiali/kiali/pull/3157
It adds IstioConfig linked with a workload (resources with some workloadSelector that matches the workload labels).
For testers, I've used this (somehow artificial) example (you can modify it inside Kiali to check that validations are working):
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
name: details-pa
namespace: default
spec:
selector:
matchLabels:
app: details
mtls:
mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
name: details-ra
namespace: default
spec:
selector:
matchLabels:
app: details
jwtRules:
- issuer: "issuer-foo"
jwksUri: https://example.com/.well-known/jwks.json
---
apiVersion: …
```
> Add IstioConfig under Workload Details

- src/pages/Graph/GraphHelpFind.tsx
- src/pages/Graph/GraphToolbar/GraphFind.tsx
- src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
Fixes https://github.com/kiali/kiali/issues/3165
Introduce the ability to combine AND and OR, as well as mix Node and Edge criteria.  For example, these expressions previously would generate an error, and now they work:
node=svc OR protocol=tcp
namespace=foo OR namespace=bar AND node=svc
cc @josejulio I think this is one you had wanted for a while (or maybe I am just dreaming)
> Enhance graph find/hide expression power

- src/components/Validations/Validation.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/IstioStatusMessageList.tsx
- src/types/IstioObjects.ts
Requires https://github.com/kiali/kiali/pull/3188
Fixes kiali/kiali#2236
There is a decoration: the status field is folded in order not to eat a lot of space and also avoid showing redundant information.
Demo:
> Add Status field into Istio Objects

- src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/types/Health.ts
Very trivial change in the wording:
> Trivial: remove a '.' in Traffic Status wording

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
- src/pages/Graph/GraphToolbar/GraphFind.tsx
- src/utils/AutoComplete.ts
If a user applies a custom pan/zoom of the graph then preserve that position and/or zoom as best as possible through refresh, regardless of whether the topology changes (nodes/edges come or go). Replace the unstable approach of zoom/position comparison and instead use a more coarse approach of just recording whether a custom viewport is in use.  Any custom viewport is reset when:
- the user manually applies a 'fit'
- the viewport is resized
- the graph page is reconstructed
Also:
- remove some unnecessary 'safeFit' calls and instead defer to 'layoutstop' event handling.
- simplify the logic in graph hide to leverage the new approach
- also remove some unintentional console logging
Fixes    https://github.com/kiali/kiali/issues/3158
May also improve …
> Preserve custom viewports when refreshing graph

- src/components/IstioWizards/CircuitBreaker.tsx
- src/components/IstioWizards/CircuitBreaker/ConnectionPool.tsx
- src/components/IstioWizards/CircuitBreaker/OutlierDetection.tsx
- src/components/IstioWizards/ServiceWizard.tsx
- src/components/IstioWizards/TrafficPolicy.tsx
- src/components/IstioWizards/WizardActions.ts
- src/types/IstioObjects.ts
- src/utils/IstioConfigUtils.ts
Fixes https://github.com/kiali/kiali/issues/3191
This PR refactors the "Advanced Options" in Wizards to have a separated Tab for major areas.
Advanced Options are mostly linked with DestinationRules config, so Circuit Breaker section make sense to put it there:
Note, that as is relevant it's separated from "Traffic Policy" Tab, to help user to identify this scenario.
> Advanced Options + Circuit Breaker in Wizards

- src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
- src/config/Config.ts
- src/pages/extensions/iter8/Iter8ExperimentDetails/AssessmentInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/CriteriaInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCreateFromFile.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCreatePage.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCriteriaForm.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentDetailsPage.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentHostForm.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/Iter8Dropdown.tsx
- src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListContainer.tsx
- src/pages/extensions/iter8/Iter8ExperimentList/FiltersAndSorts.ts
- src/routes.tsx
- src/services/Api.ts
- src/types/Iter8.ts
Support Iter8 v1.0.0 (Documentation - https://iter8.tools/)
Require PR [#3179] (https://github.com/kiali/kiali/pull/3179)
issue #2007
Only support  Iter8 v1.0.0
Major changes
1. Add A/B/n support ( new badge for Experiment Type: Canary and A/B/n
2. Experiment Create Page, with additional CRD requirement
3. Experiment Detail page, with new tab "Assessment"
4. Allow creation of Experiment using YAML file ( with YAML editor or file upload)
** Screen Shot ***
> Support Iter8-v1.0.0

- src/components/IstioWizards/WizardActions.ts
- src/pages/Overview/NamespaceInfo.ts
- src/pages/Overview/OverviewPage.tsx
- src/pages/Overview/__tests__/OverviewPage.test.tsx
- src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
- src/services/GraphDataSource.ts
- src/types/Graph.ts
Fixes https://github.com/kiali/kiali/issues/2924
This PR introduces a new Namespace based action triggered from the Overview page.
Given a certain traffic:
Kiali can apply Traffic Policies (Istio AuthorizationPolicies) to lock in workloads with principals described in the telemetry.
The action is added into the Namespace menu:
And the list of AuthorizationPolicies can be listed from the "Istio Config" page:
Or individually per workload (when workload selectors are used):
There is a generic DENY_ALL rule per namespace to protect the workloads, with individual ALLOW rules per workload, like described in this one:
> Traffic Policies actions on Namespace

- src/components/IstioWizards/RequestRouting.tsx
During https://github.com/kiali/kiali/issues/3174 I've introduced a regression in the Request Routing Wizard.
Wizard allow users to create *multiple* Request Matching for a Route.
The case about having a complex *single* Request Matching is not covered by the Wizard and it's delegated to Istio Config yaml editor.
> Fix regression for RequestRouting Wizard

- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadServices.tsx
Fixes https://github.com/kiali/kiali/issues/3234
Minor fix to span correctly columns on empty layout.
> Fix empty layout for pods/services

- src/components/CytoscapeGraph/CytoscapeTrace.ts
- src/components/JaegerIntegration/JaegerHelper.ts
- src/pages/Graph/SummaryPanelTraceDetails.tsx
Fixes https://github.com/kiali/kiali/issues/3226
Read some semantic conventions (https://github.com/opentracing/specification/blob/master/semantic_conventions.md) to extract span data:
- HTTP conventions
- peer / tcp conventions + messaging
Also read Envoy data which is a superset of OT http conventions
As a result, there's 4 different kind of displays depending on span kind:
- The usual Envoy:
- The non-Envoy HTTP:
- The TCP / messaging:
- The "unknown kind":
> Trace on graph: comply to opentracing standard

- src/components/Metrics/TrafficDetails.tsx
- src/pages/AppDetails/AppInfo.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/WorkloadDetails/WorkloadInfo.tsx
Fixes https://github.com/kiali/kiali/issues/3163
Now all tabs with health/traffic info that may change during time are aligned and they enable auto-refresh.
cc @jshaughn I touched a minor detail in TrafficDetails.tsx which are being modified in your PR, but I hope it's minor and you could rebase without problem.
> Add Auto-Refresh on Overview/Traffic tabs

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/types/IstioObjects.ts
This comes from this comment/fix in here: https://github.com/kiali/kiali-ui/pull/1946#pullrequestreview-498583490
It turns out that the `ValidationMessage[]` is not mandatory, therefore it might return null values.
I've changed it in the type and also reorganized two methods that are accessing this field. It makes it more consistent.
> IstioConfig: ValidationMessages are not mandatory

- src/components/IstioWizards/ServiceWizard.tsx
- src/components/IstioWizards/WizardActions.ts
This is required for https://github.com/kiali/kiali/issues/2630.
Kiali Wizards are supported in configuration generated from Kiali, they cannot load any external Istio resource, basically due the complexity of all combinations.
But we want to support some specific scenarios, like the Istio configuration generated by the Iter8 controller.
Iter8 controller would need to add some extra labels on their side, and Kiali should improve the support for additional scenarios.
This PR in particular address the Kiali Wizards when VS/DR uses different naming for subsets.
On this case, Kiali may read those pair of VS/DR in a wizard and update them normally.
cc @hhovsepy Main test here is to validate that there is no regression in normal wizard scenarios.
cc @prachiyadav for Iter8 we can perform a …
> Better read VS/DR subsets in Wizards

- src/components/Validations/ValidationList.tsx
It's probably because Validation is directly a SVG ; tooltip wouldn't be rendered; adding a span fixes it
Fixes https://github.com/kiali/kiali/issues/3288
> Fix tooltip not being rendered in Workload pods

- src/components/IstioWizards/RequestRouting/Rules.tsx
- src/components/IstioWizards/ServiceWizard.tsx
Fixes https://github.com/kiali/kiali/issues/3280
This is a convenient fix to make the user experience better when adding Gateways from the Wizards.
Wizards in the Advanced Options allow to define the VirtualService hosts; also in the "Advanced Options" is possible to create a "New Gateway".
This PR syncs GW + VH hosts in that case, when Wizard defines a new Gateway.
In https://github.com/kiali/kiali/issues/3280 was reported that if not sync-ed, user would always need to manually updated those config.
Note, only this is fixed in the scenario when a New Gateway is generated, when user selects an existing one, or updates, then Wizard won't sync the VS with the Gateway.
Basically Gateways are shared config and can't be always linked in 1-to-1 mapping with a VS so, trying to automate a sync …
> Sync VS/GW hosts on new GW

- src/components/Validations/ValidationList.tsx
(1.24 Backporting)
It's probably because Validation is directly a SVG ; tooltip wouldn't be rendered; adding a span fixes it
Fixes https://github.com/kiali/kiali/issues/3288
> [1.24] Fix tooltip not being rendered in Workload pods

- src/components/JaegerIntegration/JaegerScatter.tsx
Fixes https://github.com/kiali/kiali/issues/3247
**Before**
**After**
> Set a max size for scatter chart

- src/pages/extensions/iter8/Iter8ExperimentDetails/AssessmentInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCreatePage.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCriteriaForm.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentHostForm.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentTrafficForm.tsx
- src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListContainer.tsx
- src/types/Iter8.ts
1. Add Experiment Match Rule Supports
2. Add Tooltip for Traffic Control, and Match Rules
https://github.com/kiali/kiali/issues/2007
Dependency: Kiali PR https://github.com/kiali/kiali/pull/3277
1. Match Rule Creation
2. Traffic Control Tooltip
3. Match Rule Tooltip
> Support Match Ruls in Iter8-v1.0.0-rc3

- src/components/Nav/Page/RenderComponentScroll.tsx
- src/pages/Overview/OverviewPage.tsx
Fixes https://github.com/kiali/kiali/issues/3273
I think I introduced this bug time ago when we aligned the style between pages making all of them look similar in terms of header size, no matter if they were located in Overview, Graph or Details.
Now in long pages like lists or trace span details scroll would be adjusted to the bottom of the browser size:
I think main testing here is to check there is no side effect/regression around this.
> Fix bad padding at bottom of the pages

- src/app/History.ts
Read the base path set to WEB_ROOT, useful when using `kubectl proxy`.
Setting ``web_root` to `/api/v1/namespaces/istio-system/services/kiali:20001/` in the previous setup for `kiali` does not work as expected. Although the `env.js` setting is read in the previous logic, it doesn't seem to work properly with `subpath` in the working mode.
When I open `http://127.0.0.1:8001/api/v1/namespaces/istio-system/services/kiali:20001/` kiali will change the address to `http://127.0.0.1:8001/console/overview?pi=15000&duration=60`
I think the normal expectation is `http://127.0.0.1:8001/api/v1/namespaces/istio-system/services/kiali:20001/console/overview?pi=15000&duration=60`.
So, this code change is the solution to that problem. 
* If this is a fix for …
> Support setting history mode by parameter

- tsconfig.json
Switching to es2019 (we're on es2016) would allow for instance to use `Array.flatMap` : https://www.ecma-international.org/ecma-262/10.0/index.html#sec-array.prototype.flatmap
This doesn't change the compilation target which is still es5.
> Typescript compiler: use es2019

- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
- src/services/Api.ts
- src/types/Common.ts
- src/types/IstioObjects.ts
Convert from using the logs blob string to the new structured LogEntry return supported by the backend.  With that support we also get support for Duration, so also add custome time range support.  And finally, add a switch to be able to toggle the k8s timestamps which take up a lot of space and may not be needed depending on the log message format.
Fixes https://github.com/kiali/kiali/issues/3067
REQUIRES SERVER PR: https://github.com/kiali/kiali/pull/3352
> workload logs - use new LogEntry and Duration support

- src/pages/Graph/SummaryPanelNode.tsx
Unlike in metrics, "queryTime" here is startTime, not endTime.
Fixes #kiali/kiali#3359
> [v1.24] Fix wrong timestamp being use for traces query in graph

- src/pages/Graph/SummaryPanelNode.tsx
Unlike in metrics, "queryTime" here is startTime, not endTime.
Fixes https://github.com/kiali/kiali/issues/3359
> Fix wrong timestamp being use for traces query in graph

- src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
- src/pages/Overview/OverviewNamespaceActions.tsx
- src/pages/Overview/OverviewPage.tsx
- src/pages/Overview/__tests__/OverviewPage.test.tsx
Fixes https://github.com/kiali/kiali/issues/3333
It's not adding a feature flag, but checking permissions to enable/disable this feature.
How to test:
- Deploy Kiali in view_only_mode with a limited number of namespaces (i.e. default):
```
spec:
auth:
strategy: anonymous
deployment:
accessible_namespaces:
- default
image_name: localhost:5000/kiali/kiali
image_pull_policy: Always
image_version: dev
namespace: istio-system
service_type: ClusterIP
verbose_mode: 3
view_only_mode: true
```
- Validate that in this case actions on Overview are disabled:
> Fetch permisssions for Overview actions

- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
- src/types/IstioObjects.ts
REQUIRES SERVER PR: https://github.com/kiali/kiali/pull/3377
Fixes https://github.com/kiali/kiali/issues/1399
> Display more info about the Pod phase/status when looking at workload pods

- src/pages/extensions/iter8/Iter8ExperimentDetails/AssessmentInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListContainer.tsx
1. Add assessment bar for assessment criteria without threshold ( for example `mean_book_purchased`)
2. Fix spelling error ( indicatorr -> indicator)
> Add assessment bar for assessment criteria without threshold

- src/components/Nav/Masthead/UserDropdown.tsx
This is related to, and possibly the root cause fix for https://github.com/kiali/kiali/issues/3313.   The original PR was also needed but the problem resurfaced during testing for https://github.com/kiali/kiali/issues/2905.  So this is being included as part of the fix for that issue.
SERVER PR: https://github.com/kiali/kiali/pull/3397
Testing this issue is somewhat tedious but a series of successful login/logouts is what you are looking for, with OpenshiftAuth.  The fault was more frequent with a backend load, especially high numbers of oath sessions coming and going.
This fix was a joint effort with @israel-hdez .
> Make sure API logout completes before submitting openshift logout form

- src/components/NamespaceDropdown.tsx
Fixes https://github.com/kiali/kiali/issues/3173
This PR revises the namespace selector in a few ways:
- adds select/deselect all
- this is the primary RFE addition for 3173
- note that select/deselect all applies only to the filtered set of namespaces.  Without a name filter it is a "true" all.  This allows the user to easily modify the state of a subset of namespaces, without affecting prior selections.
- batches changes
- an important behavioral change.  prior to this PR each individual namespace select/deselect generated a state change.  this was distracting and inefficient as even changing from one namespace to another would generate 2 changes and cause pages to update while the user was still working with the dropdown.  now all changes are applied when the dropdown is closed (by …
> Revise namespace selector (add select all)

- src/components/Metrics/Helper.ts
'combineLabelsSettings' should not mutate input labels
(to be backported)
> OSSM-310 Fix lost settings on metrics page

- src/components/Metrics/Helper.ts
This is a backport of https://github.com/kiali/kiali-ui/pull/2003 (no conflict during backporting)
'combineLabelsSettings' should not mutate input labels
> [v1.24] OSSM-310 Fix lost settings on metrics page

- src/components/IstioStatus/IstioComponentStatus.tsx
- src/types/IstioStatus.ts
Needs https://github.com/kiali/kiali/pull/3423
Adding one more status for the add-ons (jaeger, grafana, prom) into the Istio Component Status.
> Add one more state for the Istio component status

- src/components/VirtualList/VirtualList.tsx
- src/pages/AppList/AppListPage.tsx
- src/pages/IstioConfigList/IstioConfigListPage.tsx
- src/pages/ServiceList/ServiceListPage.tsx
- src/pages/WorkloadList/WorkloadListPage.tsx
- src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListPage.tsx
Fixes https://github.com/kiali/kiali/issues/3437
Also fixes the sorting on table from main list pages.
Fetching all items for all namespaces is now unified using the "select-all" option in the Namespace Selector.
Note that Overview page is out of the scope of this work, that page have not namespace selection on purpose, but just filtering.
> Align select-all namespaces in List pages

- src/components/Expandable.tsx
- src/components/JaegerIntegration/JaegerResults/SpanTable.tsx
- src/components/JaegerIntegration/JaegerResults/SpanTableItem.tsx
There was a bug when there are expanded rows in the spans table, and some actions are done that trigger table refresh, such as ordering table by columns or opening the links menu. The expanded rows were back to collapsed state.
Now they are kept expanded.
> Spans table: fix expand state being lost

- src/components/Metrics/IstioMetrics.tsx
I realized there was a literal left in the Metrics tab.
> Trivial. Fix bad string.

- src/components/IstioWizards/ServiceWizard.tsx
- src/components/IstioWizards/ServiceWizardDropdown.tsx
- src/components/IstioWizards/WizardActions.ts
Fixes https://github.com/kiali/kiali/issues/3327
Add support for TCP scenarios and align Kiali Wizards with Istio Tasks.
TCP Traffic Shifting is similar as Traffic Shifting (focused on HTTP) but it doesn't have specific Advanced Features for HTTP (as Circuit Breaker).
For QE:
- You can use the travels demo https://github.com/kiali/demos/tree/master/travels
- Add mysql-v2 and mysql-v3 workloads.
- Try to operate with TCP Traffic Shifting and validate the results
> Add TCP Traffic Shifting Support

- src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
- src/pages/Mesh/MeshPage.tsx
- src/types/Mesh.ts
The back-end API is now providing the network ID of each discovered cluster (if possible to resolve). This adds a column in the UI to show the new data.
Related kiali/kiali#3448
Back-end PR: https://github.com/kiali/kiali/pull/3458
> [multi-cluter] Add network column to clusters list

- src/components/IstioWizards/RequestRouting.tsx
- src/components/IstioWizards/RequestRouting/RuleBuilder.tsx
- src/components/IstioWizards/RequestRouting/Rules.tsx
- src/components/IstioWizards/ServiceWizard.tsx
- src/components/IstioWizards/Slider/Boundaries.tsx
- src/components/IstioWizards/Slider/Slider.tsx
- src/components/IstioWizards/Slider/_Slider.scss
- src/components/IstioWizards/TrafficShifting.tsx
- src/components/IstioWizards/WizardActions.ts
- src/components/Time/Replay.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadInfo.tsx
Fixes https://github.com/kiali/kiali/issues/3476
This PR add supports for mirrored workloads in the Traffic Shifting and Request Routing wizards.
The user may select one workload that will be used as "mirror" (in the Istio VS terminology)
And the Traffic Weight for a mirror workload represents the % of traffic mirrored from the normal routing rule.
The rest of the workload distributes the regular 100% of the traffic as a normal rule but with one workload left.
For QE:
- Test the feature from Traffic Shifting / Request Routing scenarios.
- Validate no regressions and also that VS can be edited after creation and reflected in the Wizard.
There may be some comments from @lwrigh about style of the icon and color used for mirrored but feature is completed to test.
Note that mirror traffic is a …
> Support for Mirror configuration in Kiali Wizards

- src/components/JaegerIntegration/TracesComponent.tsx
- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Fixes https://github.com/kiali/kiali/issues/3503
There was a bug in the TracesComponent using a wrong duration parameter that may fall into the default (10m).
This bug was introduced in latest changes when refactoring the TimeControl component.
I think it's fixed now @israel-hdez, would you mind to test ?
I did some quick tests, but let me know if there is anything else to fix and I'll continue tomorrow my time.
> Fix from time parameters on tracing tabs

- package.json
- yarn.lock
Applying 1.12 (SM 1.1) CVE fixes to 1.24 (OSSM 2.0)
https://issues.redhat.com/browse/MAISTRA-1706
pin ajv version for CVE-2020-15366
https://issues.redhat.com/browse/MAISTRA-2012
pin y18n version for CVE-CVE-2020-7774
> [1.24] CVE updates

- src/pages/extensions/iter8/Iter8ExperimentDetails/AssessmentInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCreatePage.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentDetailsPage.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/Iter8Dropdown.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/TrafficControlInfo.tsx
- src/types/Iter8.ts
Improve on the Changes request from [PR#2015](https://github.com/kiali/kiali-ui/pull/2015) 
a)  Add Traffic Control Frame in Experiment Detail page 
> 1.  **_Using Kiali pattern for showing match rules_**
> 2. **_Fix the tab issue for TrafficControl Frame_**
b)  Add Min/Max credible interval in Experiment Assessment tab when the values are available. also add Legend for the assessment chart
c)  Using TrafficShifting Components in Terminate Experiment request
Note: has dependency on PR https://github.com/kiali/kiali/pull/3475
**Screenshot**
a) Traffic Control 
b) Min/Max Credible Internal 
c) TrafficShifting
> TrafficControl Frame, min/max RatioStatistics, use TrafficShifting

- .travis.yml
We recently moved to node.js 14 (LTS) for building/testing Kiali-ui. This PR updates the Travis CI to use the newer node version 14.
https://github.com/kiali/kiali/issues/3484
> Trivial: move travis ci to node.js 14 (LTS)

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/pages/Graph/GraphToolbar/GraphSettings.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
- src/services/GraphDataSource.ts
- src/types/Graph.ts
Add tooltip info to the "Requests Per Second" edge label option to better explain the resulting edge labeling.
Also, take care of some other improvements in the Display menu:
- rename "Requests Per Second" to "Request Rate"
- rename "Requests Percentage" to "Request Distribution"
- use consistent plurals in the edge label options
- add tooltip info for all non-obvious options
Fixes https://github.com/kiali/kiali/issues/3477
> Add tooltip info to the "Requests Per Second" edge label option

- src/components/Metrics/CustomMetrics.tsx
- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
I found a bug with custom dashboards, time selection doesn't work anymore. So here's a quick fix.
cc @lucasponce 
This is not ideal, I think it would be preferable that the child component (metrics, traces, whatever) decides which time component to use, instead of the parent deciding on behalf on its child. But not sure how to do it in a nice way, leaving that perhaps for later...
> Fix time control not working on custom dashboards

- src/components/Envoy/EnvoyModal.tsx
- src/components/IstioWizards/WorkloadWizardDropdown.tsx
fixes https://github.com/kiali/kiali/issues/3515
Fixing error message when visiting a workload page that doesn't have a sidecar.
There is no call performed under the hood before opening the modal.
> Don't fetch the config dump before opening the modal

- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Fixes https://github.com/kiali/kiali/issues/3504
I don't understand how this bug manged it's way into 1.26.  I remember fixing it in the dev phase, but somehow that fix must have been lost.  Anyway, this problem is already fixed in 1.27+ of Kiali, but because Istio 1.8 is tied to 1.26 we should backport and make a patch release, so that Istio 1.8 users that install Kiali as an addon do not hit this issue.
Verification Steps:
Without the fix the following should show the reported error:
1) Navigate to Workload Details for istio-system, grafana workload
2) Select Logs tab
With the fix you should not see a crash and the two log windows should show messages about no logs.
> [v1.26] backport of fix for empty pod logs

- src/components/IstioStatus/IstioStatus.tsx
- src/components/IstioStatus/__tests__/IstioStatus.test.tsx
Trying to approach [this](https://github.com/kiali/kiali/issues/3508#issuecomment-742617476) I have realized that the Istio component status feature in the masthead had a minor/little bug.
The component relies in the namespace list (from redux) just for reducing the severity of alerts for that component. This is specially important for multi-tenancy scenarios where users haven't given access to any namespace. Then, we don't want Kiali show an error every other refresh/page navigation.
I have found that since the `Istio Status` feature is rendered in the masthead and the `Namespace Dropdown` is fetch in the second secondary masthead, the first one won't have any namespace rendered. It will only have namespaces right after the `Namespace Dropdown` has been successfully rendered.
This should …
> Fetch Namespace if they arent present while mounting the Istio Status feat

- .github/workflows/ci.yml
This is is a build CI optimization for Github Actions to reduce the build time by > 50% by using cached libraries that refresh only when the `yarn.lock` changes.
> For Github actions CI add caching to reduce build time (a bunch)

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleOverview.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/IstioObjectDetails.scss
- src/pages/IstioConfigDetails/IstioObjectDetails/IstioStatusMessageList.tsx
- src/types/IstioObjects.ts
fixes https://github.com/kiali/kiali/issues/3505
Right now, Istio only persists the following info in the `status.validationMessages` field:
```
validationMessages:
- documentation_url: https://istio.io/v1.8/docs/reference/config/analysis/ist0130/?ref=status-controller
type:
code: IST0130
```
Therefore, this PR only will rely on this fields being present. See how the UI is shown:
When istio includes also the severity code and the message description, the UI will be like:
(this last screenshot can't be tested right now without modifying the code in order to add mock data. Needs Istio to fix a couple of issues first)
> Fix Kiali analysis messages to render them with only istio code and documentation url

- src/actions/JaegerThunkActions.ts
- src/components/CytoscapeGraph/CytoscapeTrace.ts
- src/components/JaegerIntegration/JaegerResults/FormattedTraceInfo.ts
- src/components/JaegerIntegration/JaegerResults/SpanTable.tsx
- src/components/JaegerIntegration/JaegerResults/SpanTableItem.tsx
- src/components/JaegerIntegration/JaegerResults/StatsComparison.tsx
- src/components/JaegerIntegration/JaegerResults/TraceDetails.tsx
- src/components/JaegerIntegration/JaegerResults/TraceLabels.tsx
- src/components/JaegerIntegration/JaegerScatter.tsx
- src/components/JaegerIntegration/TraceTooltip.tsx
- src/components/JaegerIntegration/TracesComponent.tsx
- src/components/JaegerIntegration/TracesFetcher.ts
- src/components/SimplerSelect.tsx
- src/pages/Graph/SummaryPanel.tsx
- src/pages/Graph/SummaryPanelNodeTraces.tsx
- src/pages/Graph/SummaryPanelTraceDetails.tsx
- src/types/JaegerInfo.ts
- src/utils/tracing/TraceStats.ts
- src/utils/tracing/TraceTransform.ts
- src/utils/tracing/TracingHelper.ts
- src/utils/tracing/__tests__/TraceStats.test.ts
- src/utils/tracing/__tests__/TracingHelper.test.ts
Redesign the trace details panel in graph to allow navigating in a given
trace, from span to span, following parent/children relationships
Fixes kiali/kiali#3361
Prior refactoring (1st commit): move tracing utility functions to 'utils/'
> Graph: navigate in trace

- src/components/IstioWizards/ServiceWizardDropdown.tsx
- src/components/IstioWizards/WizardActions.ts
Fixes https://github.com/kiali/kiali/issues/3483
Kiali Wizards expect workloads labeled with "app" and "version" labels.
It seems that "version" label tends to not be used in scenarios where there is a single workload for a service, then Fault Injection or Request Timeout scenarios can't be used.
This PR enables that use case.
For QE:
- Test potential regression in Service -> Actions scenario.
- Check that a Workload with "app" but NO "version" can be supported.
Thanks !
> Support Wizards with one workload without version label

- src/app/AuthenticationController.tsx
- src/pages/Login/LoginPage.tsx
- src/services/Api.ts
- src/services/Login.ts
- src/types/Auth.ts
Support for running Kiali behind a reverse proxy with an embedded `Authorization` header and potentially impersonation headers.  For https://github.com/kiali/kiali/issues/3207 
https://github.com/kiali/kiali/issues/3207
[x ] Is your pull-request introducing changes in behaviour?
backwards compatible.  If the authentication strategy is `header` the login screen is skipped, similar to anonymous.
Please provide an update to documentation if appropriate. For configuration options, consider sending a PR to https://github.com/kiali/kiali/blob/master/README.adoc
> Support reverse proxy authentication

- public/index.html
- src/components/Nav/Masthead/Masthead.tsx
- src/components/Nav/Navigation.tsx
- src/types/ServerConfig.ts
Cluster information is shown only if available.
Fixes kiali/kiali#3523
Related back-end PR: kiali/kiali#3580
> Display cluster_id on page title and masthead

- src/types/IstioObjects.ts
Adds workloadSelector to ServiceEntrySpec interface
https://github.com/kiali/kiali/pull/3588#issuecomment-762300182
Yes
N/A
N/A
> Add workloadSelector to ServiceEntrySpec interface

- src/components/Nav/Menu.tsx
The back-end config endpoint should be reporting cluster information only when multi-cluster is enabled in Istio. Since the "Mesh" nav entry is a page related with multi-cluster, this should show it only when needed.
Related to kiali/kiali#3592
Back-end PR: kiali/kiali#3607
> Show Mesh nav entry only when needed

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
The unknown node is being labeled as "error".
> Fix issue with unknown node label

- src/components/JaegerIntegration/JaegerResults/SpanTableItem.tsx
- src/pages/Graph/SummaryPanelTraceDetails.tsx
Fixes https://github.com/kiali/kiali/issues/3625
- In tracing page / span details
(adding two things here: the response flag in parenthesis for the compact mode, and the detailed explanation in expanded mode)
- In graph trace:
> Make envoy flags in traces more visible and detailed

- src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
- src/components/CytoscapeGraph/Layout/BoxLayout.ts
Fix BoxLayout issue with synthetic edge generation. It can no longer assume the box type of a parent node.
Also, some minor cleanup and ensure that all layout type props are applied at all times.
fixes https://github.com/kiali/kiali/issues/3623
> Fix BoxLayout issue

- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/pages/Graph/SummaryPanelAppBox.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- Now implemented for app boxes
- Removed a couple of special checks for Aggregate nodes to simplify:
now the resulting list of options is the source of truth to decide
whether or not to display links
Fixes https://github.com/kiali/kiali/issues/3624
> Fix graph contextual links

- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/pages/Graph/SummaryPanelAppBox.tsx
- src/pages/Graph/SummaryPanelNode.tsx
Backport of https://github.com/kiali/kiali-ui/pull/2069
- Now implemented for app boxes
- Removed a couple of special checks for Aggregate nodes to simplify:
now the resulting list of options is the source of truth to decide
whether or not to display links
Fixes https://github.com/kiali/kiali/issues/3624
> [v1.29] Fix graph contextual links

- src/components/Metrics/IstioMetrics.tsx
Add *_workload_namespace as an active label by default
Fixes https://github.com/kiali/kiali/issues/3650
Backend PR: https://github.com/kiali/kiali/pull/3651
> Metrics: fix peer namespace segregation

- src/pages/Graph/GraphPage.tsx
We don't need to both update the URL and update redux on a double-click. Pushing a new node graph URL will already cause a redux update when the page initializes. So, remove the redundancy and prevent two calls to the backend.
Furthermore, fix an issue on operation node double-click by properly setting the target node params.
Fixes https://github.com/kiali/kiali/issues/3649
To test:
Double-click of a node should still properly generate a node detail graph.  The user should still be able to change the target node within the detail graph by double clicking a different node.
The double-click should generate only a single backend call for graph generation, not two.
> Prevent duplicate graph fetch on double-click

- src/components/Tour/TourStop.tsx
- src/pages/Graph/GraphHelpTour.ts
- src/pages/Graph/GraphPage.tsx
- src/pages/Graph/SummaryPanel.tsx
Fix the graph tour by adding support for multiple stops at one place (i.e. wrapping the same children elements).
also
- re-acnchor the "graph" stops on the side panel
- add a stop for the side-panel
- add text to the "graph" stop mentioning the new Shift-Drag zoom feature
Fixes https://github.com/kiali/kiali/issues/3683
> Fix the graph tour by adding support for multiple stops at one place

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
Fix graph replay regression introduced when removing code that was causing duplicate layouts (in what was thought to be all cases). But we still need to ensure an initial layout is performed for any new cy graph, even if the elements are exactly the same as before, which can happen for graph replay (although, the fix is not specific to graph replay just in case there is another scenario not considered). The fix still maintains the initial goal of avoiding duplicate/unnecessary layouts.
v1.29 backport for kiali/kiali#3684
> [v1.29] Fix graph replay regression

- src/app/AuthenticationController.tsx
- src/components/NamespaceDropdown.tsx
- src/config/ServerConfig.ts
- src/types/ServerConfig.ts
Apply UI Defaults as soon as the user successfully authenticates. We immediately update the Redux store with the user-configured defaults.  Note that they can be overwritten almost immediately by anything set/bookmarked in the URL.
These defaults apply only for "vanilla" URLs.
Notes:
- We needed to now fetch the namespaces at auth time, before applying the
defaults, to ensure that any default namespaces were valid.
- Small unrelated change to NamespaceDropdown for clarity, just renaming a method.
Fixes https://github.com/kiali/kiali/issues/3371
Requires Server PR: https://github.com/kiali/kiali/pull/3688
TESTING NOTE
When testing this remember that the UI Defaults are set in the Kiali CR.  And changes won't take effect until the Kiali pod restarts.  Furthermore, the configured UI defaults …
> UI support for UI defaults

- src/components/Health/__tests__/HealthDetails.test.tsx
- src/components/Health/__tests__/HealthIndicator.test.tsx
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/components/TrafficList/TrafficDetails.tsx
- src/config/HealthConfig.ts
- src/config/__tests__/HealthConfig.test.ts
- src/pages/ServiceList/__tests__/ServiceListComponent.test.ts
- src/services/GraphDataSource.ts
- src/types/ErrorRate/ErrorRate.ts
- src/types/ErrorRate/GraphEdgeStatus.ts
- src/types/ErrorRate/TrafficHealth.ts
- src/types/ErrorRate/__testData__/ErrorRateConfig.ts
- src/types/ErrorRate/__tests__/ErrorRate.test.ts
- src/types/ErrorRate/__tests__/ErrorRateBattery.test.ts
- src/types/ErrorRate/__tests__/GraphEdgeStatus.test.ts
- src/types/ErrorRate/__tests__/TrafficHealth.test.ts
- src/types/ErrorRate/__tests__/utils.test.ts
- src/types/ErrorRate/utils.ts
- src/types/Graph.ts
- src/types/Health.ts
- src/types/HealthAnnotation.ts
- src/types/__tests__/Health.test.ts
- src/types/__tests__/HealthAnnotation.test.ts
Fix https://github.com/kiali/kiali/issues/3332
For workload and services
Require: https://github.com/kiali/kiali/pull/3362
Step 1 of https://github.com/kiali/kiali/issues/3332
> Allow custom health configuration to be deployed as annotations

- src/components/Details/DetailObject.tsx
- src/components/Validations/ValidationSummary.tsx
Replacing vanilla js undefined checks to use typescript native way.
Although the vanilla js check works fine, it is worth tho move it to typescript.
cc/ @jshaughn @israel-hdez @mtho11
> Use the typescript way to check undefined

- src/components/Charts/ChartWithLegend.tsx
- src/components/Charts/Container.tsx
- src/utils/VictoryEvents.ts
Tooltip is now hidden while hovering legend items.
Note that I also reduced the gap between the legend symbols and texts,
because the pointer isn't considered on legend while it's on that space;
reducing it makes this issue smaller.
Fixes https://github.com/kiali/kiali/issues/3035
> Fix misleading tooltip displayed on chart legends

- src/components/JaegerIntegration/TracesComponent.tsx
- src/components/JaegerIntegration/TracesDisplayOptions.tsx
- src/components/JaegerIntegration/TracesFetcher.ts
- src/types/Tracing.ts
Since the grpc jaeger client PR, minDuration now has to be passed as an
integer (in microseconds) instead of a string
> Fix broken query for trace percentiles

- src/components/CytoscapeGraph/CytoscapeTrace.ts
- src/components/TrafficList/TrafficDetails.tsx
- src/pages/Graph/SummaryLink.tsx
- src/types/Graph.ts
Replacing "isServiceEntry", which wasn't actually a bool but a string
MESH_INTERNAL or MESH_EXTERNAL, with a struct holding "location" and
"hosts"
For traces, use this new "hosts" field instead of "destServices"
Fixes https://github.com/kiali/kiali/issues/3728
Backend PR: https://github.com/kiali/kiali/pull/3729
> Add hosts to SE node

- src/components/JaegerIntegration/JaegerScatter.tsx
- src/components/JaegerIntegration/TracesComponent.tsx
- src/components/JaegerIntegration/TracesDisplayOptions.tsx
- src/components/JaegerIntegration/TracesFetcher.ts
Display toolbar is disabled, and error is written on page, when some
error occurred AND there's no trace currently displayed.
If they're some traces currently displayed, the user may still want to
interact with them.
Fixes https://github.com/kiali/kiali/issues/3698
> Tracing: disable display toolbar on errors

- src/pages/Overview/Filters.ts
Fixes https://github.com/kiali/kiali/issues/3719
@hhovsepy let me know if this PR looks good for that use case.
Yes, in highly populated namespaces, probably the delay of the async fetch is visible, but I checked that the "loading" icon is present on those cases.
> Fix overview filter for Healthy case

- src/components/Filters/CommonFilters.ts
- src/components/Health/__tests__/HealthIndicator.test.tsx
- src/pages/Overview/Filters.ts
- src/pages/Overview/NamespaceInfo.ts
- src/pages/Overview/OverviewCardContentCompact.tsx
- src/pages/Overview/OverviewCardContentExpanded.tsx
- src/pages/Overview/OverviewPage.tsx
- src/types/Health.ts
- src/types/__tests__/Health.test.ts
Fixes https://github.com/kiali/kiali/issues/3576
As discussed in https://github.com/kiali/kiali/issues/3576#issuecomment-760241754 we have a clash with same term for two different states.
This PR just renames the "Idle" status in Apps and Workloads for a better alignment with the terminology.
Idle is reserved for no traffic situations.
It's just a rename but it touches several areas so a close review and regression tests would help to confirm that nothing is missed.
> Idle -> Not Ready for Workloads scaled to 0

- src/components/Charts/ChartWithLegend.tsx
- src/components/Charts/SparklineChart.tsx
Fixes https://github.com/kiali/kiali/issues/2060
It's a one-liner PR to smooth the charts curves.
I've used monotoneX as other strategies have more visualization cornercases when reaching the limits of the chart, I think this looks better.
> Change Smooth chart properties

- src/components/Metrics/CustomMetrics.tsx
- src/components/Metrics/IstioMetrics.tsx
- src/pages/Overview/OverviewNamespaceActions.tsx
- src/pages/Overview/OverviewPage.tsx
- src/types/GrafanaInfo.ts
Fixes https://github.com/kiali/kiali/issues/2731
This PR introduces a couple of changes in the Overview page.
First, it treats the Istio control plane namespace in a different way for actions (it won't show the Sidecar Injection actions and the security option).
Second, instead if grafana links are present, it should show the links to the external dashboards that are related not to the whole cluster but they refers to the control plane instead, so I thought that would be clean to connect them from the Istio control plane.
How to test:
- From the Kiali config add the dashboards:
```
grafana:
in_cluster_url: http://localhost:13000
url: http://localhost:13000
dashboards:
- name: "Istio Service Dashboard"
variables:
namespace: "var-namespace"
service: "var-service"
- name: "Istio Workload …
```
> Links to Istio Dashboards

- src/components/FilterList/__tests__/OverviewPageHelper.test.ts
- src/components/Link/IstioConfigListLink.tsx
- src/components/Link/__tests__/__snapshots__/IstioConfigListLink.tsx.snap
- src/components/VirtualList/Renderers.tsx
- src/pages/Overview/Sorts.ts
- src/pages/Overview/__tests__/OverviewSort.test.ts
Fixes https://github.com/kiali/kiali/issues/3757
Fixes https://github.com/kiali/kiali/issues/3756
In short, as filters are stateful, they shouldn't be reset on render but on an action, otherwise it may have side effects.
This scenario was similar as this old one:
https://github.com/kiali/kiali-ui/blob/master/src/components/BreadcrumbView/BreadcrumbView.tsx#L120
I fixed and also added more tests on the filter case as I was not sure at first time if the problem was with some changes I did there.
> Fix Health broken

- src/components/Charts/KChart.tsx
Fixes https://github.com/kiali/kiali/issues/3693
How to reproduce:
- Identify a workload with traffic in only one side (Inbound or Outbound):
- Click in the tab with no traffic and check that charts are collapsed:
- Click in the tab with traffic and verify that charts are expanded (instead to see them collapsed by default):
> Fix wrong collapsed state on charts

- src/pages/Mesh/MeshPage.tsx
- src/types/Mesh.ts
This adds a column in "Mesh" page to show the Kiali instances discovered in each listed cluster.
Format of the column is "namespace / service name". If the Kiali service has the "kiali.io/external-url" annotation, the value of that annotation is used to create links and allow the user to jump to those remote Kialis.
This is the result:
Related back-end PR: https://github.com/kiali/kiali/pull/3768
Related operator PR: https://github.com/kiali/kiali-operator/pull/264
Fixes kiali/kiali#3526
> Mesh page - Add column linking remote Kialis

- src/components/BreadcrumbView/BreadcrumbView.tsx
Don't hold all parts of the breadcrumb path to valid k8s namespace value restrictions.  Let other parts conform to valid label value restrictions (see https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)
Fixes https://github.com/kiali/kiali/issues/3776
> Relax matching on breadcrumb paths

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/types/Graph.ts
fix https://github.com/kiali/kiali/issues/3707
1. When mTLS is STRICTLY enabled at mesh-level, locks are present:
1.1 All connections use mTLS:
1.2 Only details/ratings has mTLS disabled:
When mTLS is not strictly enabled at mesh-level, lock are present too:
1.1 All connections use mTLS:
1.2 Only details/ratings has mTLS:
When mTLS is not strictly enabled, but only details and ratings has mtls:
> Always show locks in graph

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
- src/components/CytoscapeGraph/FocusAnimation.ts
- src/components/CytoscapeGraph/Layout/BoxLayout.ts
- src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
- src/pages/Graph/GraphLegendData.ts
- src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
Fix the traffic animation issue, which turned out to just be a symptom of a deeper problem.  It happened only when animation was enabled and the user enabled boxing, changed to an "app" graph type, or navigated to a graph with boxing (and yes, this took a long time to realize :)). The root cause was the fact that boxLayouts finish in an async fashion, and animation was started prior to the layout completing. Theoretically it could also happen without any boxing, but just using cola or cose-bilkent
layouts, which can also run async.
The solution is to introduce some promise logic to ensure we don't complete a graph update before a layout is complete.
* unrelated but included, a small change to legend labels based on some confusion reported by a community member.
Fixes …
> Fix the traffic animation issue

- src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
- src/components/IstioActions/IstioActionsNamespaceDropdown.tsx
- src/components/IstioWizards/WizardActions.ts
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleBuilder.tsx
- src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleList.tsx
- src/pages/IstioConfigNew/GatewayForm.tsx
- src/pages/IstioConfigNew/GatewayForm/ServerBuilder.tsx
- src/pages/IstioConfigNew/GatewayForm/ServerList.tsx
- src/pages/IstioConfigNew/IstioConfigNewPage.tsx
- src/pages/IstioConfigNew/PeerAuthenticationForm.tsx
- src/pages/IstioConfigNew/RequestAuthenticationForm.tsx
- src/pages/IstioConfigNew/ServiceEntryForm.tsx
- src/pages/IstioConfigNew/SidecarForm.tsx
- src/routes.tsx
- src/types/IstioConfigDetails.ts
- src/types/IstioObjects.ts
Fixes https://github.com/kiali/kiali/issues/3761
Fixes https://github.com/kiali/kiali/issues/3763
This PR provides fixes and refactoring in several areas of the IstioConfig New Forms.
Use same "Create" group for "Actions" dropdown and allow to select the type of object in a first step:
Present the Istio Config resource on the title, and eliminate redundant fields for type and namespaces:
Namespace validation is moved to the "Create/Cancel" button similar as others used:
Review all forms (AuthorizationPolicy, Gateway, PeerAuthentication, RequestAuthentication, Sidecar) and unify criteria.
No changes in feature, just use same wording for messages, minor changes to adjust the style and use same icons/buttons for same patterns (in terms of implementations, it follows the Builder/List pattern …
> IstioConfig New Form fixes and refactoring

- src/app/History.ts
- src/components/JaegerIntegration/JaegerResults/SpanTableItem.tsx
- src/components/JaegerIntegration/TracesComponent.tsx
- src/components/Metrics/CustomMetrics.tsx
- src/components/Metrics/IstioMetrics.tsx
- src/components/Metrics/SpanOverlay.ts
- src/pages/Graph/SummaryPanelTraceDetails.tsx
- src/utils/SearchParamUtils.ts
Add to the tooltip the method of the span
When we click the span this redirect us to the traces tab with the span selected. This span will be expanded with a blue border on the right
> Metrics page: more details & links from spans

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/MiniGraphCard.tsx
- src/pages/Graph/GraphToolbar/GraphToolbar.tsx
- src/utils/AlertUtils.ts
Perform focus animation when returning back from node graph to full graph
- honors the currently selected node in the node graph (if any)
- Behavioral change: don't enable idle nodes when navigating from mini-graph
- this was originally done to help ensure focus selection worked even if
the node was idle. But this wass heavy-handed as it could litter the graph
with idle nodes and confuse users. Instead, on the off-chance that the
node does not exist and the focus fails, just provide an informational toast.
- other minor enhancement: allow some message utils to provide detail
Fixes https://github.com/kiali/kiali/issues/2281
> Perform focus animation when returning back from node graph to full graph

- package.json
- yarn.lock
@israel-hdez Snyk complained about https://snyk.io/vuln/SNYK-JS-SSRI-1085630.  It wanted to update the ssri version but I removed it from the prod deps and it seems maybe we don't even need it.  It is still pulled in by react-scripts, but that is a dev dep.  What do you think, can we just get rid of it?
> Remove prod dep on ssri, it seems unnecessary and there is a CVE

- src/components/Charts/ChartWithLegend.tsx
Fix https://github.com/kiali/kiali/issues/3844
1 - Enable spans filter in legend
2 - Wait refresh metrics or force it
3 - Now OnMouseOver in Span duration legend Item the spans disappear
Fixed
> In Metrics spans disappear in mouseOver

- src/components/CytoscapeGraph/MiniGraphCard.tsx
- src/pages/Graph/GraphPage.tsx
- src/pages/Graph/GraphToolbar/GraphSecondaryMasthead.tsx
- src/pages/Graph/GraphToolbar/GraphToolbar.tsx
A couple of other minor fixes:
- include aggregate nodes when checking for node change
- disable namespace selector in node graph view
- avoid race condition when unsetting node on return to main graph
Closes https://github.com/kiali/kiali/issues/3696
> Allow nav from detail view mini-graph to graph page node graph.

- src/components/CytoscapeGraph/CytoscapeTrace.ts
- src/components/CytoscapeGraph/graphs/GraphHighlighter.ts
- src/components/TrafficList/TrafficListComponent.tsx
- src/pages/Graph/GraphHelpFind.tsx
- src/pages/Graph/GraphToolbar/GraphSettings.tsx
- src/pages/Graph/SummaryPanelAppBox.tsx
- src/pages/Graph/SummaryPanelClusterBox.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/Graph/SummaryPanelNamespaceBox.tsx
- src/pages/Graph/SummaryPanelNodeTraffic.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/TrafficControlInfo.tsx
Consolidate terminology on inbound/outbound by converting instances of incoming/outgoing (both in the UI and the code).
Fixes https://github.com/kiali/kiali/issues/3873
@lucasponce This PR currently covers only the terminology change.  If we feel a need to change the Inbound traffic reporting we can expand the PR (see related comments in the issue). Setting to DNM until we have agreed on the scope.
> Consolidate terminology on inbound/outbound

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/MiniGraphCard.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/IstioWizards/RequestRouting/Rules.tsx
- src/components/IstioWizards/TrafficShifting.tsx
- src/components/Link/IstioObjectLink.tsx
- src/components/Pf/PfBadges.tsx
- src/components/Pf/PfColors.tsx
- src/components/TrafficList/TrafficListComponent.tsx
- src/components/VirtualList/Config.ts
- src/components/VirtualList/Renderers.tsx
- src/components/VirtualList/VirtualItem.tsx
- src/components/VirtualList/_VirtualList.scss
- src/pages/Graph/SummaryLink.tsx
- src/pages/Graph/SummaryPanelClusterBox.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/Graph/SummaryPanelNamespaceBox.tsx
- src/pages/WorkloadDetails/WorkloadPodLogs.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentInfoDescription.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentRules.tsx
- src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListPage.tsx
- src/types/Graph.ts
Fixes https://github.com/kiali/kiali/issues/3879
Improve graph badging, ensure namespace and/or cluster information is provided where needed for discrimination, and not provided when it's not.
- remove boxByCluster and boxByNamespace booleans from cy's global scratch data, no longer needed
- add homeCluster to Cy's global scratch data
- beef up side panel badge tooltips with cluster+namespace discriminators, this avoids having to display a lot more badges/values in the side panel
- This PR includes and associated refactor that touches files that apply PF badges:
- Consolidate PF Badging in a way sort of analogous to PfColors...
- Basically put all all of our used PF Badges in one place for easy reference, add some stronger typing, and provide some utilities for consistent use and styling. …
> Improve graph node labels and PF badging

- package.json
- yarn.lock
Bumps node-sass version to `5.0`. Prior versions of node sass do not compile on systems without python2 due to [this](https://github.com/sass/node-sass/issues/2877) issue.
> Bump node-sass to 5.0

- src/components/Envoy/EnvoyModal.tsx
- src/components/Envoy/tables/BaseTable.tsx
- src/components/Filters/StatefulFilters.tsx
Fixes https://github.com/kiali/kiali/issues/3635
It groups Envoy config on tabs using the main Envoy config as a driver:
Bootstrap and Full Config Dump are still using a yaml editor:
Minor alignment with badges for pod selector.
cc @xeviknal (but it's a trap, I don't expect you put ANY comment about this PR unless 6 weeks)
cc @oschaaf, Kiali is quite active trying to help in browsing the Envoy config, so any feedback would be more than welcome. This PR is pure UI refactor, but this is an area in development and more high level features will be added into Kiali as well.
> Adjust Envoy details

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/pages/Graph/SummaryLink.tsx
- src/types/Graph.ts
Some Istio versions set cluster='Kubernetes' as a default in the telemetry, but do not set it as a default on the control plane itself.
Fixes https://github.com/kiali/kiali/issues/3955
> Improve handling when adding cluster discriminators to graph node labels

- src/components/Details/DetailDescription.tsx
Fixes https://github.com/kiali/kiali/issues/3973
The list of workloads is matched with the list of workloads provided by health data, so there was a bug in the match code.
> Fix wrong render of workload list

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/MiniGraphCard.tsx
- src/pages/AppDetails/AppInfo.tsx
- src/pages/Graph/GraphPage.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/WorkloadDetails/WorkloadInfo.tsx
- src/services/GraphDataSource.ts
Fix regression in Application detail's Traffic tab.  The fix maintains the change to a versionedapp graph for application mini-graphs (the cause of the problem) but restores the traffic tab to its original behavior. 
While investigating I ended up fixing a few things that, in the end, did not contribute to the reported problem:
- fix target node selection for application nodes for node detail and application mini-graphs
- fix two double-loading issues for the graph, one related to node graphs and the other related to bookmarked graphs
Fixes https://github.com/kiali/kiali/issues/3974
>  Application Traffic - some outbound traffic is not shown

- src/app/AuthenticationController.tsx
- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
- src/pages/Graph/GraphPage.tsx
This standardizes the behavior of the graph context menu when there are no available options to show. Concretely, no options because of a node living in a remote cluster where an accessible Kiali instance couldn't be found.
When Kiali UI boots, it will check which clusters does NOT have accessible Kialis. A message will be logged in the message center telling about this fact and that no links to these clusters will be available. In the graph, context menus for relevant nodes won't be present.
Fixes kiali/kiali#3907
> Refine message for remote Kiali

- src/app/AuthenticationController.tsx
We should not generate a warning toast unless we discover at least one remote cluster without a Kiali configured with an external URL.
Fixes https://github.com/kiali/kiali/issues/3995
> Don't include the home cluster among remote clusters when checking for external URLs

- src/types/IstioConfigDetails.ts
Trivial. 
At some point a minor regression was introduced in the ACE editor and font size was not aligned with font size of rest of the details pages.
Before:
After:
In terms of code is tricky, ACE editor is a third party component with some built-in styles that are modified via CSS but it also offers a generic options in the component to change this internally, which was the method used for this fix.
> Fix ACE editor font size

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Adds the namespace to the toaster error message that appears when an Istio config object does not exist.
Before:
After:
Relates to kiali/kiali#3798
> Add namespace to istio error toaster message

- src/pages/Graph/GraphHelpFind.tsx
- src/pages/Graph/GraphToolbar/GraphFind.tsx
- src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
Note that use of these operands will auto-enable the Security Display option as it is required for populating the principal fields.
Closes https://github.com/kiali/kiali/issues/4000
> Add sourceprincipal and destprincipal operands to Graph Find/Hide.

- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/pages/Graph/SummaryLink.tsx
- src/types/Graph.ts
ServiceEntries should link to the namespace where they are defined which isn't always the node namespace.
Relates to: https://github.com/kiali/kiali/issues/3798
Requires backend changes: https://github.com/kiali/kiali/pull/3980
These ServiceEntry links were broken before when the ServiceEntry definition was outside of the graph node's namespace but should now properly direct to the Istio Config of the Service Entry.
> Fix ServiceEntry graph links

- src/app/AuthenticationController.tsx
Back-port of https://github.com/kiali/kiali-ui/pull/2151
> [v1.34] Don't include the home cluster among remote clusters when checking for external URLs

- src/pages/WorkloadDetails/WorkloadPodLogs.tsx
- src/types/IstioObjects.ts
Client-side changes utilizing the new flag to identify when the log view should treat logs as proxy-logs.
PartOf https://github.com/kiali/kiali/issues/3977
Requires Server PR: https://github.com/kiali/kiali/pull/3981
> Update to using new isProxy flag to identify proxy containers for logs view

- .env.downstream
- .env.upstream
- Makefile.jenkins
- README.adoc
- RELEASING.adoc
- package.json
No longer publish the Kiali-UI to NPM.
Back-end PR: https://github.com/kiali/kiali/pull/3986
Related issue kiali/kiali#3891
> Deprecate publishing to NPM (front-end)

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.scss
- src/types/IstioConfigDetails.ts
Fixes https://github.com/kiali/kiali-ui/pull/2154
Moved the fontSize from the ace builtint properties to the scss file.
> Better CSS fix for the ACE editor

- src/components/Nav/Masthead/UserDropdown.tsx
Strategies that don't support logout are anonymous and header.
Fixes kiali/kiali#3934
> Hide Logout option for auth strategies that don't support it

- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCreatePage.tsx
- src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentDetailsPage.tsx
- src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListPage.tsx
- src/types/Iter8.ts
Output detail error message if Iter8 v2.x was installed and using the new Iter8Info endpoint in pull request [#4028](https://github.com/kiali/kiali/pull/4028)
> Support new Iter8Info endpoint

- src/pages/Graph/GraphHelpFind.tsx
- src/pages/Graph/GraphHelpTour.ts
- src/pages/Graph/GraphToolbar/GraphFind.tsx
- src/pages/Graph/GraphToolbar/GraphFindOptions.tsx
- src/pages/Graph/GraphToolbar/GraphSettings.tsx
- src/pages/Graph/_Graph.scss
- src/types/ServerConfig.ts
Graph Find/Hide now offers preset expressions via new dropdowns on each input.  The preset expressions are supplied via the UIDefaults supplied by the server, and so can be configured by users via the CR.
Fixes https://github.com/kiali/kiali/issues/3708
SERVER PR:  https://github.com/kiali/kiali/pull/4020
Operator PR: https://github.com/kiali/kiali-operator/pull/315
> Introduce Find/Hide presets

- src/components/MissingLabel/MissingLabel.tsx
- src/components/VirtualList/Renderers.tsx
- src/config/Icons.ts
- src/pages/WorkloadDetails/WorkloadDescription.tsx
Fixes https://github.com/kiali/kiali/issues/1404
This PR aligns the "missing" validations (sidecar, app and version) used in the context of Istio.
This is a UI improvement, the original https://github.com/kiali/kiali/issues/1404 issue has a bigger scope which can be discussed later (all validations will follow same convention as other istio resources validations, and for this particular, we'll keep focusing on the Istio labels, not a generic check for presence of any label), but this will provide a consistent UI in the meantime.
So, "Missing Sidecar, "Missing App" or "Missing Version" will look in the list:
With additional tooltips as the uniform way to add details:
Note that there will be only a single message, "Missing App" or "Missing Version", being "App" more important, in the …
> Align labels validation icons

- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceOverview.tsx
This PR adds the same styles to the special "mesh" gateway as other gateways have in the VirtualService Overview and it also adds a tooltip with more details about its meaning.
**Issue**
[#1391](https://github.com/kiali/kiali/issues/1391)
**Documentation**
The following is a demo of how the change looks:
> Indicate in a different way the reserved word mesh

- src/pages/Overview/OverviewPage.tsx
- src/services/Api.ts
- src/services/GraphDataSource.ts
Ensure that Health calculations for graph nodes use the same time period as that used for the graph generation itself.
Fixes https://github.com/kiali/kiali/issues/4058
**SERVER PR** https://github.com/kiali/kiali/pull/4065
To test:
0. Start by deploying master to see the "before"  (or, you can deploy only the server PR at this point)
1. Deploy an app (bookinfo, travel, whatever) and generate "green" traffic for a few minutes.
2. Use the Kiali wizard to introduce a 100% fault injection for one of the intermediate services.
3. Wait for the traffic to go "red"
4. start graph replay before the introduction of the FI
You should see that the health of the chosen service is "red" even before the FI is introduced
5. deploy the PRs and repeat the test
You should properly see "green" for the chosen …
> Ensure that Health calculations for graph use correct time period

- package.json
- src/app/App.tsx
- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
- yarn.lock
Upgrades the `tippy.js` dependency to the latest version. There were some breaking API changes between major versions and [this migration guide](https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md) was followed to fix those. The two props the UI was previously using that I am unsure of the exact effects are [multiple](https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md#if-you-were-using-multiple-or-relying-on-its-behavior) and [size](https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md#if-you-were-using-size). I haven't noticed any regressions or changes in behavior but regression tests should be run on this PR to ensure nothing has changed with the version bump.
Fixes https://github.com/kiali/kiali/issues/4035
> Upgrade tippy dependency to latest version

- src/pages/WorkloadDetails/WorkloadInfo.tsx
- src/types/IstioObjects.ts
Potential fix of https://github.com/kiali/kiali/issues/3529
UI changes required https://github.com/kiali/kiali/pull/4075
In the case when Workload's Pod has failing non istio containers, but the Kubernetes returns that pod's state as Running, Kiali should show warning on that pod.
> Added new Warning message on workload pod in case of failing containers.

- package.json
- src/app/App.tsx
- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
- yarn.lock
This reverts commit c9789960e84c9f25bd2025207051e3e292f83cf7.
The tippy dependency bump caused css issues with the node context menu tooltips.
> Revert "Upgrade tippy dependency to latest version (#2163)"

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/CytoscapeGraph/graphs/__tests__/GraphStyles.test.ts
Displays the Circuit Breaker badge on the graph even if a Virtual Service is not present.
Fixes kiali/kiali#4076
> Show CB badge even when no VS present

- src/components/Details/DetailDescription.tsx
- src/components/IstioConfigCard/IstioConfigCard.tsx
- src/components/IstioConfigCard/__tests__/IstioConfigCard.test.tsx
- src/components/IstioConfigCard/__tests__/__snapshots__/IstioConfigCard.test.tsx.snap
- src/pages/ServiceDetails/ServiceDescription.tsx
- src/pages/WorkloadDetails/WorkloadPods.tsx
the details description component didn't apply any sorting for both apps, workloads and services (nor in backend/frontend). Therefore, some refreshing of the page made some of the list change the order all the time despite of there wasn't any information change. It was just a sorting change. It bugged me a little bit and distracted me from putting attention on other sections of the detail pages.
Same thing happens with the pod list and the istio config section.
> Sort sublists details pages

- src/components/Metrics/CustomMetrics.tsx
- src/components/Metrics/IstioMetrics.tsx
- src/components/MetricsOptions/MetricsSettingsDropdown.tsx
Fixes https://github.com/kiali/kiali/issues/4106
It's a workaround, Kiali should review how state is shared between components and URL and unify it, right now there is some technical debt from the early designs that have a mix of strategies on this.
> Fix sync state on URL on Metrics tab

- src/components/MetricsOptions/MetricsSettingsDropdown.tsx
This PR adds an option to select all the labels in the Metrics settings filter.
**Issue**
[#3596](https://github.com/kiali/kiali/issues/3596)
**Documentation**
> Adding a Select all option to metrics settings filter

- src/components/Envoy/EnvoyDetails.tsx
Fixes https://github.com/kiali/kiali/issues/4134
Now, fetch query only happens when user enters in the tab avoiding to iterate on one fetch per tab:
> Fix missing mount Envoy tabs

- src/components/Filters/CommonFilters.ts
- src/components/VirtualList/Renderers.tsx
- src/helpers/__tests__/LabelFilterHelper.test.ts
- src/pages/AppList/AppListClass.tsx
- src/pages/AppList/FiltersAndSorts.ts
- src/pages/ServiceList/FiltersAndSorts.ts
- src/pages/ServiceList/ServiceListPage.tsx
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/pages/WorkloadList/WorkloadListPage.tsx
- src/types/AppList.ts
- src/types/ServiceList.ts
- src/types/Workload.ts
Fixes https://github.com/kiali/kiali/issues/1446
This PR adds Istio config used in Services and Workloads in the list pages, allowing to browser in multi-namespace list which services have Istio config. Sorting and filtering are supported on this.
Similar for workloads:
Also, adding this info into the applications as a join view of services and workloads:
This issue was filled some time ago but it was not implemented as Kiali didn't support caching all resources.
Now all extra queries are fetched from memory, so it wouldn't add a significant impact on the request.
> Show Istio configuration linked with Services and Workloads (and Applications) on list pages

- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceNetwork.tsx
This PR enhance the Service Overview page adding a lists of hostnames that can reach the service according to the VirtualServices/Gateways configurations.
**Issue**
[#4067](https://github.com/kiali/kiali/issues/4067)
**Documentation**
If there are VirtualServices related to the Service, the hostnames will be showed as follows:
The configuration is the following:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
name: bookinfo-gateway-1
spec:
selector:
istio: ingressgateway
servers:
- port:
number: 80
name: http
protocol: HTTP
hosts:
- bookinfo.com
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
name: bookinfo-gateway-2
spec:
selector:
istio: ingressgateway
servers:
- port:
number: 80
name: http
protocol: HTTP
hosts:
- …
```
> Display hostnames in network section of service details

- src/components/IstioWizards/WizardActions.ts
- src/config/ServerConfig.ts
- src/pages/Overview/OverviewPage.tsx
- src/types/ErrorRate/__testData__/ErrorRateConfig.ts
- src/types/ServerConfig.ts
- src/types/__testData__/HealthConfig.ts
Fix for issue https://github.com/kiali/kiali/issues/3988
Requires backend: https://github.com/kiali/kiali/pull/4122
This PR contains a feature for executing Upgrade/Downgrade To Istio on Namespace action in Overview page.
When Kiali CR is configured "IstioUpgradeAction" and appropriate current and newer Istio revisions: "IstioCurrentRevision" and "IstioUpgradeRevision". Then Kiali allows user to upgrade to the newest Istio by setting the 'istio.io/rev' label to namespace.
Then all workload's pods are restared in that namespace to inject the newest Istio Envoy.
> Upgrade namespace in overview page to newer installed Istio.

- src/components/Charts/ChartWithLegend.tsx
- src/components/Charts/KChart.tsx
Minor change, it was already missed in #2200 PR, my bad, but it's needed for https://github.com/kiali/kiali-ui/pull/2181
> Adjust empty metric chart height

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/CytoscapeGraph/graphs/__tests__/GraphStyles.test.ts
Aside from root nodes, this moves the request routing icon to be the leftmost icon for consistency's sake so that the current VS icon always appears as the leftmost one.
Relates to kiali/kiali#4090 but is not required and can be merged independently of those changes.
> Make request routing icon the leftmost for consistency

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
**Bug**:
1. When one istio config has validations
2. When the validation has a referenced resource
3. The istioConfig details page doesn't show the side panel and therefore the references are not visible
4. By default, the side panel should be visible when there are references or messages.
**Fixed issue**:
By default the side panel is present when at least one reference is present.
** Steps to reproduce **:
One validation that has references is [KIA0003](https://kiali.io/documentation/latest/validations/#_kia0003_more_than_one_object_applied_to_the_same_workload)
```yaml
k apply -n bookinfo -f - <<EOF
kind: Sidecar
apiVersion: networking.istio.io/v1alpha3
metadata:
name: test-1
namespace: bookinfo
spec:
workloadSelector:
labels:
app: reviews
ingress: ~
egress:
- hosts:
- istio-system/*
- …
```
> Show editor sidepanel when there are only validation references

- src/components/Validations/GlobalValidation.tsx
- src/components/Validations/ValidationList.tsx
- src/components/Validations/ValidationStack.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceOverview.tsx
- src/types/AceValidations.ts
- src/types/IstioObjects.ts
Part of: https://github.com/kiali/kiali/issues/4197
This goes with PR https://github.com/kiali/kiali/pull/4205 - see that for more details.
I don't like this PR because there should be a common function you can call that takes a "check" object as an input parameter and returns the full message string (which is prefixed with `code` if it is not empty - e.g. `return (check.code ? check.code + ' ' : '') + check.message).` Right now that expression is everywhere that `check.message` was before. Someone enhance this PR so it does that :)
> Prefix validation message with the now explicit code

- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadPodLogs.tsx
This adds the new `spans` checkbox to the workload detail `Logs` tab view.  When enabled, the workload spans for the given time period will be included in the time-sorted unified view of the selected container logs.
This feature is will close the logs correlation epic, and is discussed there, starting with [this comment](https://github.com/kiali/kiali/issues/3499#issuecomment-836395518).
Note that the logs Show/Hide does not get applied to trace entries, if they exist.  This is by design as the trace entries don't really contain relevant log string text.
Clicking the info tooltip will navigate you directly to the span of interest.  Span entries use the same color as used for spans in the charts.
Closes https://github.com/kiali/kiali/issues/3499
@aljesusg , assigning you to review this one …
> Offer trace-spans in unified workload logs view

- STYLE_GUIDE.adoc
I had the conception that we were using the following convention for specifying redux props:
https://github.com/kiali/kiali-ui/blob/ff87e9a66894ef0f13c01a7b8f086c7a282a9aa4/src/components/IstioActions/IstioActionsButtons.tsx#L10-L24
@lucasponce proof me wrong here, which I thank for it.
https://github.com/kiali/kiali-ui/pull/2212/files#r694932209
So I thought that we could kind of agree on a way to go altogether.
I propose to use the way as linked right above.
What do you think?
> Convention for redux props usage into props components types

- src/components/Charts/ChartWithLegend.tsx
- src/components/Charts/KChart.tsx
Fixes https://github.com/kiali/kiali/issues/4325
In low height screen resolutions (600px < height < 750px) chart legend is hidden and y-axis are adjusted to improve the visualization in the current design, tooltip is used to indicate legend of the series:
(800px x 600px)
The collapse icon on height is triggered on <600px heights:
> Adjust Metrics charts on narrow height

- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceOverview.tsx
Fix for RFE: https://github.com/kiali/kiali/issues/1440
> Added the default 'mesh' and appropriate tooltip in gateway section of VirtualService overview, when no gateway is set.

- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Fix https://github.com/kiali/kiali/issues/4165
I was thinking about to add some check in this case to avoid error in envoy tab (check that there is a configDump)
But this is going to increase the consuming and maybe it's not necessary I don't think there are many cases
> Display Envoy tab for workloads running Istio Proxy without Sidecar

- src/config/Config.ts
- src/pages/WorkloadDetails/WorkloadPodLogs.tsx
- src/pages/WorkloadDetails/__tests__/WorkloadPodLogs.test.tsx
- src/services/Api.ts
Adds a way to set a workload pod's proxy log level from the kebab dropdown.
Any error that occurs when setting the log level will result in an error notification/alert.
On error:
Relates to: kiali/kiali#1525
Server side PR: kiali/kiali#4312
> Add ability to set proxy log level for workload pod

- src/pages/Graph/SummaryLink.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/pages/Graph/__tests__/SummaryLink.test.tsx
- src/pages/Graph/__tests__/SummaryPanelNode.test.tsx
- src/types/Graph.ts
In the graph node summary panel for workloads with workload entries, the link now links to the istio config page for the workload entry instead of the workloads page.
Fixes kiali/kiali#4219
Back-end changes: kiali/kiali#4372
> Generate link to istio config for workload entries

- src/pages/ServiceDetails/ServiceInfo.tsx
- src/types/IstioConfigList.ts
RFE https://github.com/kiali/kiali/issues/4326
When VirtualService have linked Gateways, then these Gateways are listed in Istio Config section of ServiceDetails page.
Gateways can be linked for instance while creating Routing via Wizard.
> ServiceDetails page, Istio Config section: added support of listing Gateways linked in VirtualServices.

- src/components/Tour/TourStop.tsx
- src/pages/Graph/GraphHelpTour.tsx
- src/pages/Graph/GraphToolbar/GraphShortcuts.tsx
- src/pages/Graph/GraphToolbar/GraphToolbar.tsx
This PR adds a new stop in the graph tour to show the shortcuts available in the graph.
This is a work in progress draft PR to get feedback:
Resolves [#4133](https://github.com/kiali/kiali/issues/4133)
> Graph shorcuts in Graph Tour

- src/components/Envoy/EnvoyDetails.tsx
Fixes https://github.com/kiali/kiali/issues/4445
Also:
- remove unnecessary span
- position copy icon closer to editor
- add tooltip to be more helpful, and consistent with logs page.
To be honest, I'm not sure it's necessary to select the text when clicking the copy icon.  But I'm fairly selecting the text is what the errant code was trying to do.
@lucasponce , do whatever you like with this if you want to move it along while I'm on PTO.
> fix text selection when copying envoy config dump to clipboard

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/pages/Graph/SummaryPanelNode.tsx
- src/types/Graph.ts
Also, the side panel should show the full list of configured hosts for the cases where the graph truncates the list.
Fixes kiali/kiali#3765
> Show list of configured hostnames for egress nodes

- src/pages/Graph/GraphToolbar/GraphSettings.tsx
- src/reducers/GraphDataState.ts
- src/reducers/__tests__/GraphDataState.test.ts
- src/services/GraphDataSource.ts
Part-of: https://github.com/kiali/kiali/issues/4547
Note that this change is in conjunction with a server-side change to omit boxing when unnecessary.
**Server PR:** https://github.com/kiali/kiali/pull/4548
> Enable cluster and namespace boxing by default, in the main graph.

- src/pages/WorkloadDetails/WorkloadDescription.tsx
Fixes https://github.com/kiali/kiali/issues/4589
There is a corner case/regression when workloads have no services attached as it returns a null value instead of an empty one.
It would require a change in the backend, but this one in the UI will protect the failing component shown in the issue.
For QE:
- You'd need an example like the [demo-errors-rate](https://github.com/kiali/demos/tree/master/error-rates) and check that getting access to a workload without services (i.e., f-client) will show an error in the details page.
It also happens when navigating from the "minigraph" to reach the "f-client".
> Fix case where workload has no services

- src/components/ToolbarDropdown/ToolbarDropdown.tsx
- src/pages/Graph/GraphToolbar/GraphSettings.tsx
- src/pages/Graph/GraphToolbar/GraphToolbar.tsx
- src/pages/Graph/GraphToolbar/GraphTraffic.tsx
The overapping graph processing can cause a problem.
- Add the same protection to the Traffic settings dropdown.
- Fix the actual button disabling as well.
Fixes https://github.com/kiali/kiali/issues/4638
I don't love the menus now get grayed out during graph refresh, but I guess it make sense to prevent fast-click and to finish one update before starting another.
cc https://github.com/Xunzhuo
> Prevent fast-click in the Graph Display settings dropdown.

- src/components/HeatMap/HeatMap.tsx
Fixes https://github.com/kiali/kiali/issues/4588
This issue title suggests a different font size, but a smaller font can become unreadable.  Clipping gives a uniform look while still allowing enough space for significant digits, and the tooltip can be used to see detail, if desired.
> Clip long numbers in heatmaps, as opposed to wrapping.

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
- src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
- src/components/CytoscapeGraph/CytoscapeToolbar.tsx
- src/components/CytoscapeGraph/Layout/BoxLayout.ts
- src/components/CytoscapeGraph/MiniGraphCard.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/pages/Graph/GraphPage.tsx
- src/pages/Graph/GraphToolbar/GraphFind.tsx
- src/pages/Graph/GraphToolbar/GraphToolbar.tsx
- src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
- src/types/Graph.ts
Fixes https://github.com/kiali/kiali/issues/4666
Graph-hide performs a layout after removing the graph elements.  Layouts
can generate intermediate zoom-level changes that should be ignored, and
so we must add that protection.
> Protect graph-hide from unwanted zoom events

- package.json
- src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
- src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
- src/components/CytoscapeGraph/CytoscapeToolbar.tsx
- src/components/CytoscapeGraph/graphs/ConcentricGraph.ts
- src/components/CytoscapeGraph/graphs/GridGraph.ts
- src/components/CytoscapeGraph/graphs/LayoutDictionary.ts
- yarn.lock
Part of https://github.com/kiali/kiali/issues/4601
~~This draft PR is used as a playground to test new layout algorithms and tweak the configuration for existing ones.~~
~~There is no intention to promote them to a formal PR, just to share some experiments and collect feedback before moving in any direction.~~
It includes a couple of minimal changes that I think will be consolidated:
- Move the BoxLayout for Namespaces to "dagre" algorithm. As it's defined per app, it's a minimal change that it has a good impact when managing large scenarios.
- In large scenarios, the "cola" algorithm has a performance penalty compared with others, so that one could be a candidate to be replaced.
- "Grid" layout works well on a high population of namespaces; results look promising.
- Still doing tests on …
> Migrate cose and cola layouts to grid and concentric algorithms

- package.json
- yarn.lock
We need this so the production builds can work.
You must make sure the builds use Node 14.  Specifically, prod builds use 14.18.2, so use the same version to ensure compatibility.
> [v1.24] due to the requirement of building with node 14, we need to bump node-sass to 5.0.0

- src/components/Envoy/EnvoyDetails.tsx
Fixes https://github.com/kiali/kiali/issues/4769
There is a bug when a workload may have an Envoy sidecar but Envoy metrics are not available (for some reason, like a misconfiguration in the dashboard).
In this case, the UI will not crash and the "Metrics" tab will be omitted.
> Don't show Envoy metrics tab if those are not present

- src/types/IstioConfigList.ts
Fix for https://github.com/kiali/kiali/issues/4766
Core changes are required: https://github.com/kiali/kiali/pull/4768
> Support 'name.namespace' key for Istio config validation result instead of 'name' only, to support multiple namespaces

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
javascript is super flexible in that it actually handles things like
numeric comparisons that may involve a string (like '10' > 0 => true). But
you can't call a numeric function on a string var.
Our 'num' variables are *supposed* to be numbers but we have an undiscovered
issue where very infrequently the number variable is a string.  Until we
fix that with confidence, we need to protect ourselves.
This extends some previous protection to be more robust.
https://issues.redhat.com/browse/OSSM-1099
> Improve protection against graph numbers that are actually string variables

- package.json
- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/components/Time/Replay.tsx
- yarn.lock
- in graph replay's custom startTime, remove minTime and maxTime properties, they did not act as desired.  Instead of being used to establish a date-time range, and enabling all times between min and max (potentially across multiple days), the date portion was ignored and the time range was applied to each day.  As the time range was tied to the prom retention period,  this created seemingly random valid time ranges, or even a single, fixed valid time.  **With the fix the time-range should allow any time to be chosen, and only the days should be restricted based on retention time.**
- update react-datepicker from 2.14 to 3.8.  This fixes a variety of component glitches and updates some dependencies.  Note that this updates popper but not to a new major version.  V4 of react-datepicker had …
> Fix time selection issue in replay custom startTime picker

- src/pages/ServiceList/ServiceListPage.tsx
- src/types/ServiceList.ts
Fix for https://github.com/kiali/kiali/issues/4793
When service list contains only ServiceEntries, which does not have validations, error it thrown in console.
Now the validation existence is checked before using.
For QE:
Create namespace.
Create only ServiceEntry in that namespace.
List Services from this namespace only in Kiali.
Error should not be shown. 
Service entry is shown.
Verify also listing all Services is not broken.
> Make Service List Item validation to be undefined to support ServiceEntries

- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceList/ServiceListPage.tsx
Fix for https://github.com/kiali/kiali/issues/4795.
Issue caused as a regression after fixing: https://github.com/kiali/kiali/issues/4766
Adding support of 'name.namespace' format of validations.
Before:
Now:
> Fixed Service List and Details pages Configuration status issue.

- src/components/FilterList/FilterComponent.tsx
- src/components/Filters/CommonFilters.ts
- src/components/TrafficList/TrafficListComponent.tsx
- src/components/VirtualList/Config.ts
- src/components/VirtualList/VirtualItem.tsx
- src/helpers/__tests__/LabelFilterHelper.test.ts
- src/pages/AppList/AppListClass.tsx
- src/pages/AppList/AppListPage.tsx
- src/pages/AppList/FiltersAndSorts.ts
- src/pages/IstioConfigList/FiltersAndSorts.ts
- src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
- src/pages/ServiceList/FiltersAndSorts.ts
- src/pages/ServiceList/ServiceListPage.tsx
- src/pages/ServiceList/__tests__/ServiceListComponent.test.ts
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/pages/WorkloadList/WorkloadListPage.tsx
- src/services/Api.ts
- src/types/AppList.ts
- src/types/HealthAnnotation.ts
- src/types/ServiceList.ts
- src/types/Workload.ts
Require https://github.com/kiali/kiali/pull/4763
Issue: https://github.com/kiali/kiali/issues/4748
This Reduce the requests, If we have N namespaces and each namespace has W workloads.
We move from **N*W requests** to **N requests**
Open network tab and check that there are only one health request instead of N request.
The behaviour must be the same that before. Try to change a health of a service/workload/app and check that in list is updated after refresh interval.
> Reduce health req lists

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/Pf/PfColors.tsx
- src/pages/Graph/GraphPage.tsx
minor changes to graph background color, box fill colors, and node edge color, to try and improve contrast and clarity, especially when zoomed out.   Not trying to make drastic changes, and the current look is UX-approved.
@lucasponce You may not even notice on a casual look, but if you do some side-by-side comparison you should see a difference.  Let me know if you see a difference, and whether you think it's better.
Related to https://github.com/kiali/kiali/issues/4610
> improve graph  contrast 

- src/pages/Graph/GraphToolbar/GraphSecondaryMasthead.tsx
Don't allow a graph type change for node graphs, they should be fixed as not every graph type makes sense for the selected node type.   I think it's reasonable to disable the entire dropdown, and not worry about potentially valid combinations.  Users can always return to the main graph and change the graph type, if necessary.
Fixes https://github.com/kiali/kiali/issues/4797
cc @Xunzhuo
> Don't allow a graph type change for node graphs

- src/config/Config.ts
- src/pages/IstioConfigNew/GatewayForm/ServerBuilder.tsx
- src/pages/IstioConfigNew/ServiceEntryForm.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/services/Api.ts
Fix for https://github.com/kiali/kiali/issues/4692
It used to list Gateways per namespace in Service Details page.
Now it sends only one query and lists all Gateways, which is used in Wizard Gateways section.
> List Gateways for All Namespaces in Service Wizzard, instead of query per namespace

- .github/workflows/ci.yml
Adds CI check to ensure that the `yarn.lock` remains the same after doing a `yarn install`.
> Add CI check for yarn lockfile diff

- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/services/GraphDataSource.ts
- src/store/Selectors/GraphData.ts
- src/types/Graph.ts
Requires back-end PR: https://github.com/kiali/kiali/pull/4772
In kiali/kiali#4772 the graph endpoint is now capable of returning the data needed to calculate health for each node. So, it is no longer needed to fire requests to health endpoints in the graph page. It is enough to to health calculation using the data that is already available in the graph JSON.
Related kiali/kiali#4611
> Calculate health status from graph data

- src/components/CytoscapeGraph/graphs/GraphHighlighter.ts
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- related to other work done for https://github.com/kiali/kiali/issues/4610
- in certain situations, unhighlighted, boxed nodes were too hard to see
- trivial - improve some naming in GraphHighlighter.ts
Related to https://github.com/kiali/kiali/issues/4610
@lucasponce @nrfox, you both commented on an "unhighlighting" issue with the latest changes around dimming and contrast.  See https://github.com/kiali/kiali-ui/pull/2326#issuecomment-1069025481.  Please try out this attempt to keep the improvements while also doing a better job of the unhighliting for boxed nodes.
> Improve unhighlighting

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
javascript is super flexible in that it actually handles things like
numeric comparisons that may involve a string (like '10' > 0 => true). But
you can't call a numeric function on a string var.
Our 'num' variables are *supposed* to be numbers but we have an undiscovered
issue where very infrequently the number variable is a string.  Until we
fix that with confidence, we need to protect ourselves.
This extends some previous protection to be more robust.
Backport of https://github.com/kiali/kiali-ui/pull/2321
https://issues.redhat.com/browse/OSSM-1099
> [backport v1.36] Improve protection against graph numbers that are actually string variables

- src/components/Time/Replay.tsx
Manual backport of https://github.com/kiali/kiali-ui/pull/2320
OSSM 2.1 only requires the DatePicker change, the TSDB retention is OK and
we will minimize changes by not changing the DatePicker component version.
> [backport v1.36] Fix time selection issue in replay custom startTime picker
