.npmignore, package-lock.json, package.json
Publish the proper assets to npm
=> SWS-91: Npm publishing

package-lock.json, package.json, src/App.css, src/index.tsx
Documentation : [Link](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#formatting-code-automatically)
This command fix all project **./node_modules/.bin/prettier --single-quote --write "src/**/*.{js,jsx,json,css}"**
When you have not issues in lint
When husky fix some issues
Thanks @mtho11 for the chat ^^
=> Add Prettier to format code

.gitignore, .prettierrc.json, package.json, src/registerServiceWorker.js, src/registerServiceWorker.ts
- 120 characters line length. This way it matches the tslint config. And the default was really small.
- Do not change semicolons. Rules between JS and TS differ
- Single quote = true
=> Configure prettier

package-lock.json, package.json
This prevents the error message at startup:
Could not find a declaration file for module: react-router-dom.
=> Add React-Router-Dom typescript types.

src/App.tsx, src/pages/Home/HomePage.tsx, src/pages/ServiceList/ServiceListPage.tsx
Following the skeletons for main pages.
Added a ServiceList page.
=> Add a ServiceListPage

package.json
This is the classic js toolbelt.
=> Add lodash since it is the goto tool for manipulating data.

package.json
I forgot to add the lodash types
=> Add lodash @types.

README.adoc, package.json
Mostly mimic the PatternFly React reference in our README.
=> SWS-96 Add a note of SASS use in the README

src/pages/ServiceDetails/ServiceMetrics.tsx, src/types/Metrics.ts, tslint.json
- Textual representation only (fancy charts are for later)
- Relaxed some tslint rules
=> SWS-106 display metrics on service details page

.travis.yml, package-lock.json, public/index.html, src/App.scss, src/App.tsx, src/components/Nav/MastHead.tsx, src/components/Nav/Navigation.tsx, src/components/Nav/Routes.tsx, src/pages/Home/HomePage.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/ServiceList/ServiceListPage.tsx
- Define a vertical navigation
- Link with routes
- Fixes some style affecting proper components layout
Note, this is just to introduce a proper navigation into the application.
It doesn't enforce to choose vertical/horizontal but in the steps we are moving, it is good to have something.
Some rationale: I started working with the PatternFly React component but it has some bug with the Routes, so I prepared a simpler component that works (most work is just to investigate what people are doing and we are mimic the best practices defined in the patternfly react demo app).
With this, it will be easier to continue working on proper components and put things together.
=> SWS-114 Add a minimal navigation

.travis.yml, src/pages/ServiceDetails/ServiceMetrics.tsx
Also applies `prettier` to `src/pages/ServiceDetails/ServiceMetrics.tsx` as it was failing our CI
=> Use nodejs 8 for CI

.travis.yml, README.adoc, package-lock.json, package.json
=> SWS-101 Add Coveralls

package.json, src/app/__tests__/App.test.tsx, src/components/Nav/__tests__/Navigation.test.tsx, src/setupTests.ts
I wanted to consume SWSUI as a NPM module and write tests in a separate repo but the NPM module is missing index.js (SWS-115)
- Add smoke tests
- Created a standalone lint command:  `npm run lint`  (currently linting is automatically run as a part of npm start/build)
=> Adding tests

src/pages/ServiceDetails/ServiceMetrics.tsx, src/services/Api.ts
Consume api endpoint /api/grafana to get grafana info and display link on metrics page
Requires PR https://github.com/swift-sunshine/swscore/pull/69 on swscore
=> SWS-119 Display Grafana link

.travis.yml
- Kicks off a swscore travis build after publishing to NPM
=> SWS 115 - Publish to NPM upon successful travis build

src/pages/ServiceDetails/ServiceInfo/ServiceInfo.tsx
- Fix proper title on cards (Pods, Source Services and Istio Route Rules)
- Add link on source services
- Minor React refactor to allow re-load services on same component
Note, there is a bug in the backend and info is duplicated and rules are wrong due this, but for the UI it doesn't block this one as it's just minor UI work.
=> SWS-185: Minor UI adjustments on Service Defails page

src/pages/ServiceList/ServiceListComponent.tsx
- When filter changes, page should be move to first one
=> SWS-197 Fix blank page when paginating + filtering

src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfo.tsx
- Update filter to only select by namespace
- Otherwise previous state prevails
=> SWS-201: Add a link to Service List from Service Details page

src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfo.tsx
This will make travis to not fail on prettier.
=> SWS-201: Missing commit prettier changes

src/pages/ServiceDetails/ServiceMetrics.tsx
Apply some patternfly to make this look nicer until we get the replacement
=> SWS-204 Add a bit of style to the metric tab.

src/pages/ServiceDetails/ServiceMetrics.tsx
Prettier was complaining about the format of this file.
=> Fix linting issues

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceGraph/SummaryPanel.tsx
This is where will be shown some data about a selected service.
This is the screenshot:
=> SWS-255: Add a blank side panel

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/CytoscapeLayout/graphs/GraphStyles.ts
=> SWS-218: when mousing over a node, dim all unrelated edges and nodes.

package-lock.json, package.json, src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/GraphFilter/GraphFilter.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx
- add bookmarkability by honoring graph url query params
- also, fix refresh bug introduced with original time filter PR
=> SWS-313 Handle graph query params

src/components/MetricsOptions/MetricsOptionsBar.tsx, src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx, src/pages/ServiceDetails/ServiceMetrics.tsx, src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx, src/types/Metrics.ts, src/types/MetricsOptions.ts
- integrate patternfly c3-based line charts
- use patternfly styles for metrics options
- separate metrics options bar as a new component
=> SWS-262 Show metrics as charts:

src/components/GraphFilter/GraphFilter.tsx
@mtho11 just adding that missing catch you noticed.
=> trivial - add catch

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/CytoscapeLayout/__tests__/CytoscapeLayout.test.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceGraph/SummaryPanelBase.tsx, src/pages/ServiceGraph/SummaryPanelEdge.tsx, src/pages/ServiceGraph/SummaryPanelGraph.tsx, src/pages/ServiceGraph/SummaryPanelGroup.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx
set up infrastructure for changing summary panels based on what is
clicked in the main graph.
=> sws-300 summary panel for graph edge

src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRoutes.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoBadge.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoCard.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDescription.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoPods.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRoutes.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRules.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoBadge.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoPods.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRoutes.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRules.test.tsx.snap, src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/types/ServiceInfo.ts
Jira [SWS-259](https://issues.jboss.org/browse/SWS-259)
@vnugent Here is the WIP of tests about ServiceDetail Info, It's working with snaphots !!! Thanks
_Changed dependencies model by Backend now the json is a Map<string,string[]>_
=> SWS-259 add tests to ServiceDetailInfo

src/components/CytoscapeLayout/graphs/GraphHighlighter.ts, src/components/SummaryPanel/ErrorRatePieChart.tsx, src/components/SummaryPanel/RateTable.tsx, src/pages/ServiceGraph/SummaryPanelGroup.tsx
partial SWS-160... shows live data except spark graph. we need to unmock that
=> sws-160: version group side panel with live data

src/pages/ServiceDetails/ServiceMetrics.tsx, src/services/Api.ts, src/types/Health.ts, src/types/Metrics.ts
Depends on https://github.com/kiali/swscore/pull/118
=> SWS-285 Update UI to fetch health from new health endpoint

.travis.yml
Attempt to fix the Travis deploy job
=> SWS-349 SWSUI deploy job fails after GitHub organization renaming

src/pages/ServiceGraph/SummaryPanelEdge.tsx
Roughly working, needs some work still.
=> SWS-302 Spark Chart

src/components/SummaryPanel/RpsChart.tsx, src/pages/ServiceGraph/SummaryPanelEdge.tsx
- also, fix rps chart from NaN and show avgs in title
@jmazzitelli this fixes that accidental impl I pushed before...
=> SWS-320 Add Edge summary spark chart

src/components/SummaryPanel/ErrorRatePieChart.tsx, src/components/SummaryPanel/InOutRateTable.tsx, src/components/SummaryPanel/RateTable.tsx, src/pages/ServiceGraph/SummaryPanelGroup.tsx
this adds customization settings for the pie chart component
=> SWS-158: provide in-out rate table 

src/components/NamespaceFilter/NamespaceFilter.tsx, src/components/Nav/Navigation.tsx, src/components/Pf/PfInfoCard.tsx, src/pages/IstioRuleDetails/IstioRuleDetailsPage.tsx, src/pages/IstioRuleDetails/IstioRuleInfo.tsx, src/pages/IstioRuleDetails/IstioRuleInfo/IstioRuleInfoAction.tsx, src/pages/IstioRuleDetails/IstioRuleInfo/IstioRuleInfoDescription.tsx, src/pages/IstioRuleDetails/IstioRuleInfo/index.tsx, src/pages/IstioRulesList/IstioRuleListComponent.tsx, src/pages/IstioRulesList/IstioRuleListPage.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDeployments.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRoutes.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRules.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoCard.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/index.tsx, src/services/Api.ts, src/services/__mockData__/getIstioRuleDetail.json, src/services/__mockData__/getIstioRules.json, src/services/__mocks__/Api.ts, src/services/__tests__/Api.test.tsx, src/types/IstioRuleInfo.ts, src/types/IstioRuleListComponent.ts, src/types/NamespaceFilter.ts, src/types/Pagination.ts, src/types/RuleId.ts, src/types/ServiceListComponent.ts
- Add API service for rule list and rule details.
- Add a rules list page.
- Add a rule details page.
- Add test coverage for API services.
- Refactor shared components between services/rules pages.
=> SWS-236 Support Istio Rules in the UI

src/components/ServiceHealth/ServiceHealth.tsx, src/components/ServiceHealth/__tests__/ServiceHealth.test.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.scss, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap, src/pages/ServiceDetails/ServiceMetrics.tsx, src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/services/__mockData__/getServiceHealth.json, src/services/__mocks__/Api.ts
- Remove from Service Metrics
- Add to Service Details
=> SWS-286 Make Service Health donut as a separate component

package.json
- Removed Hawkular reference, (added mesh)
- Removed some references to Swift Sunshine
=> KIALI-124 Remove reference to Hawkular in package.json

src/pages/ServiceGraph/SummaryPanelEdge.tsx, src/pages/ServiceGraph/SummaryPanelGroup.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx
- add loading state where needed
- show loading message when downloading the data
- don't use larger fonts - use standard font size
=> fix behavior of loading graphs

src/components/About/AboutUIModal.tsx
=> KIALI-364: Change to Kiali name in about box.

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/CytoscapeLayout/graphs/GraphHighlighter.ts
- Removed mouse hover events and only use clicks.
~~This PR considers we can click, tested using the suggested change in: https://github.com/kiali/swsui/pull/146#discussion_r175989257~~
~~I was trying to record a gif, but my box crashed while trying, i will try again later.~~
@jmazzitelli recorded a nice gif already, thanks!
=> KIALI-299 Fix GraphHighlighter using ClickEvents from CytoscapeLayout

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/CytoscapeLayout/graphs/GraphHighlighter.ts
When loading the graph, hover is enabled. The graph will highlight
all the nodes, edges and groups where the cursor is over, if we
click on a node, edge or group, said element will be "locked"
until we click the background to deselect it.
=> KIALI-299 Mix hover and click interaction with service graph

src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationPolicies.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleCorsPolicy.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleHTTPFaultInjection.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleHTTPRetry.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleHTTPTimeout.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleIstioService.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleL4FaultInjection.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleMatch.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRedirect.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRewrite.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRoute.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRouteRules.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteRules.test.tsx.snap, src/types/ServiceInfo.ts
- Split each RouteRule attribute in a single UI component
- Remove free textarea for match attribute
- Support retry/fault scenarios, as all attributes in RouteRules are covered
- Align format with DestinationPolicies component
- Update tests
=> KIALI-240 and KIALI-241 Refactor RouteRules component 

src/pages/ServiceDetails/ServiceInfo.tsx
Now route rules are shown in the order they are applied into the traffic flow.
=> KIALI-375 Show RouteRules ordered by precedence

src/pages/ServiceGraph/SummaryPanelEdge.tsx
- also, prevent link to "unknown" source service
=> KIALI-396 Fix edge summary rendering, and simplify impl.

src/pages/ServiceGraph/SummaryPanelEdge.tsx, src/pages/ServiceGraph/SummaryPanelGraph.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx
- fix/simplify some graph panel rendering
- fix issue in edge rps chart render, handle unknown better, improve titles
- fix unknown issue in node
=> KIALI-396 Graph

src/components/SummaryPanel/InOutRateTable.tsx, src/components/SummaryPanel/RateTable.tsx
- also, ensure title fits on line for inout table
=> KIALI-376 fix %error in rate tables

src/components/CytoscapeLayout/__tests__/CytoscapeLayout.test.tsx, src/components/GraphFilter/GraphFilter.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/types/Graph.ts, src/types/GraphFilter.ts
note: url param has also changed to `duration`
`http://localhost:3000/console/service-graph/istio-system?layout=breadthfirst&duration=600`
=> [KIALI-435] Renaming Interval to Duration

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceGraph/SummaryPanelGraph.tsx
also, remove some old console logging
=> KIALI-449 fix selection highlighting

src/components/Nav/Navigation.tsx
... though it didn't seem to be visible
=> [Trivial] replace a missing "swift sunshine"

README.adoc
- Reorganize some sections to put "testing" and "styling" under "Development"
- Some updates in directory structure
- Update styling section, document command to build css
- Update testing section, add some words about snapshots
- Move Production Builds after Development
=> [Doc] Update README, add testing information

package-lock.json, package.json, src/components/Nav/Navigation.tsx, src/pages/ServiceJaeger/ServiceJaegerPage.tsx
This is a PR with a Embed Jaeger while  we continue the research.
Task : [KIALI-170](https://issues.jboss.org/browse/KIALI-170)
=> [KIALI-170]Iframe with Jaeger

src/pages/ServiceGraph/SummaryPanelNode.tsx
also a problem with consecutive node clicks and duplicate badges.
=> fix handling of 'unknown' node badging.

src/components/Nav/Navigation.tsx
Fix Collapse menu navigation
[KIALI-429](https://issues.jboss.org/browse/KIALI-429)
cc @lucasponce (Owner navigation review ^^)
=> Kiali-429 Fix Collapse Menu

src/components/MetricsOptions/MetricsOptionsBar.tsx, src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap, src/pages/ServiceDetails/ServiceMetrics.tsx, src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx
[KIALI-126](https://issues.jboss.org/browse/KIALI-126)
Refresh Metrics with a Polling Interval selector.
Interval options : Pause, 5s, 10s, 30s, 1m and 5m
=> KIALI-126 Refresh Metrics

package-lock.json
=> after running "npm install" i'm getting this diff in the package-lock.json file.

.travis.yml
This is to avoid issues like the one show in #211
=> Ensure package-lock.json is in sync with package.json

src/components/CytoscapeLayout/graphs/GraphStyles.ts
Counterpart of https://github.com/kiali/kiali/pull/143
=> KIALI-498 Propagate line style on graph

src/pages/IstioRuleDetails/IstioRuleInfo.tsx, src/pages/IstioRulesList/IstioRuleListComponent.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceMetrics.tsx, src/pages/ServiceJaeger/ServiceJaegerPage.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/services/Api.ts
- Add explanation of the error when possible.
This fixes a bug reported by QE related the confusion with the messages in the error handling.
=> KIALI-196 Unify error messages on services and rules pages

src/pages/ServiceList/ServiceListComponent.tsx
=> KIALI-491: Display rate interval for the service page

src/components/SummaryPanel/RpsChart.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx
note - also includes a fix for %error calc in summary panel rps chart
=> KIALI-502 make sure summary panelresets when graph is refreshed

src/components/Nav/Navigation.tsx
Address review comment by @mtho11
=> KIALI-358 Uses PfContainerNavVertical for the fallBackComponent

src/components/Pf/PfAlerts.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx
Sample when the app/cluster is down:
Sample if only the graph fails to load:
=> KIALI-266: Display graph load errors in a notificacion

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/CytoscapeLayout/__tests__/CytoscapeLayout.test.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceGraph/SummaryPanelGraph.tsx
A little trickery needed to avoid infinite rendering loop, but I think
this does the job.
=> KIALI-500 don't require graph click before showing full graph summary

src/components/CytoscapeLayout/graphs/GraphStyles.ts
Counterpart of https://github.com/kiali/kiali/pull/153
=> KIALI-511 Add border-style on nodes

src/pages/ServiceList/RateIntervalToolbarItem.tsx, src/pages/ServiceList/ServiceErrorRate.tsx, src/pages/ServiceList/ServiceItemComparer.ts, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/ServiceList/__tests__/RateIntervalToolbarItem.test.tsx, src/pages/ServiceList/__tests__/ServiceErrorRate.test.tsx, src/pages/ServiceList/__tests__/ServiceItemComparer.test.ts, src/pages/ServiceList/__tests__/__snapshots__/RateIntervalToolbarItem.test.tsx.snap, src/types/ServiceListComponent.ts
This is:
- Extracting code into components or classes. This is to isolate code and make it testable.
- Adding tests for the extracted code.
=> KIALI-490: Add tests for service ordering by error rate

src/components/GraphFilter/DurationButtonGroup.tsx, src/components/GraphFilter/GraphFilter.tsx, src/components/GraphFilter/LayoutButtonGroup.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/types/GraphFilter.ts
- replace text button with standard refresh icon button
- move button to options bar and place to far right
- as an added bonus, protect from button clicks while graph is refreshing
=> KIALI-520 replace 'Refresh' button

src/pages/ServiceGraph/SummaryPanelGroup.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx
Also protect group sidebar in similar way.
=> KIALI-535 fix sidebar issue when node has no outgoing edges 

src/components/ServiceHealth/HealthDetails.tsx, src/components/ServiceHealth/HealthIndicator.tsx, src/components/ServiceHealth/__tests__/HealthDetails.test.tsx, src/components/ServiceHealth/__tests__/HealthIndicator.test.tsx, src/components/ServiceHealth/__tests__/__snapshots__/HealthDetails.test.tsx.snap, src/components/ServiceHealth/__tests__/__snapshots__/HealthIndicator.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap, src/pages/ServiceList/ServiceListComponent.tsx, src/services/__mocks__/Api.ts
- Add a unique 'id' in Tooltips
- Mock API.getNamespaceMetrics
- Had to rewrite a part of HealthDetails.tsx due to a prettier versus tslint conflict
=> Fix warnings and uncaught errors in tests

package-lock.json, package.json, src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/CytoscapeLayout/ReactCytoscape.tsx, src/components/CytoscapeLayout/graphs/GraphBadge.ts
This is what the circuit breaker badging will look like and how it behaves:
=> KIALI-472 use popper badges to mark nodes that have circuit breakers

package.json
This command is for @jmazzitelli It will magically fix his code! Well, some tslint errors anyway.
=> Add build script command `npm run lint-fix` to fix tslint errors

src/components/CytoscapeLayout/CytoscapeLayout.stories.tsx, src/components/CytoscapeLayout/__stories__/bookinfo.json
With recent changes, additional props were added to the component and
a new property (style) is expected in the elements format.
=> Fix CytoscapeLayout storybook

src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceGraph/SummaryPanelEdge.tsx, src/pages/ServiceGraph/SummaryPanelGraph.tsx, src/pages/ServiceGraph/SummaryPanelGroup.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx
Also avoid unmounted state hange
This may solve the problem as I haven't been able to reproduce the problem
now that we protect against overlapping fetches.
=> KIALI-519 protect the pie, avoid concurrent fetch

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/CytoscapeLayout/__tests__/CytoscapeLayout.test.tsx, src/components/GraphFilter/GraphFilter.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/types/Graph.ts, src/types/GraphFilter.ts
The button is shown on the right side of the filter bar, like this:
It can also be defined on the URL, for repeatable graph generation.
=> [KIALI-474] Add button to toggle Circuit Breakers on Graph

src/components/About/AboutUIModal.tsx, src/components/GraphFilter/GraphFilter.tsx, src/components/NamespaceFilter/NamespaceFilter.tsx, src/model/RefreshSettings.ts, src/pages/IstioRuleDetails/IstioRuleInfo.tsx, src/pages/IstioRulesList/IstioRuleListComponent.tsx, src/pages/IstioRulesList/IstioRuleListPage.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceMetrics.tsx, src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceGraph/SummaryPanelEdge.tsx, src/pages/ServiceGraph/SummaryPanelGraph.tsx, src/pages/ServiceGraph/SummaryPanelGroup.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx, src/pages/ServiceJaeger/ServiceJaegerPage.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/ServiceList/ServiceListPage.tsx, src/services/Api.ts, src/services/__mocks__/Api.ts, src/services/__tests__/Api.test.tsx, src/types/ServiceInfo.ts
Use low camel case for functions.
Also remove debugging console logs
=> [Cleaning] unify camel-case naming

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/CytoscapeLayout/graphs/GraphStyles.ts, src/pages/ServiceGraph/SummaryPanelGraph.tsx
- remove ingress
- fix regression wrt removal of composite nodes
=> KIALI-595 fix service count in graph summary

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/CytoscapeLayout/graphs/GraphHighlighter.ts
- minor refactor to prefer falsey where applicable
=> Fix kiali-595 regression in graph highlighting of group node.

package-lock.json, package.json, src/actions/NamespaceAction.ts, src/actions/index.ts, src/app/App.tsx, src/components/NamespaceDropdown.tsx, src/containers/AutoUpdateNamespaceList.tsx, src/reducers/index.ts, src/reducers/namespaces.ts, src/setupTests.ts
As discussed in https://github.com/kiali/kiali-ui/pull/243 this PR only contains Redux-related additions without any changes to existing features.
=> Introduce Redux and friends for namespace dropdown - Part 1

src/pages/ServiceJaeger/ServiceJaegerPage.tsx
=> KIALI-487 Fix inconsistent error messaging

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/GraphFilter/GraphFilter.tsx, src/components/ToolbarDropdown/ToolbarDropdown.tsx, src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx, src/types/GraphFilter.ts
[x] correctly initialized CBs when parsing url params
[x] shortened Circuit Breakers button label 
[x] check CBs flag in `CytoscapeLayout.shouldComponentUpdate()`  
[x]  misc clean up
---
CBs = OFF
CBs = ON
=> KIALI-622: incorrect default for CBs flag and make sure CytoscapeLayout aware of it

src/components/GraphFilter/GraphFilter.tsx
This data doesn't need to be recreated every render method because of its static data.
=> Move constant array creation from render() to static data.

src/components/Nav/Navigation.tsx
Sidebar kept "Graph" hightlighted when user clicked on the namespace
link in the side panel to go to the serivce list page.
=> KIALI-605: Fix sidebar focus when navigating from graph to service list

src/components/Badge/Badge.tsx, src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/MetricsOptions/MetricsOptionsBar.tsx, src/components/MetricsOptions/ValueSelectHelper.tsx, src/components/NamespaceFilter/NamespaceFilter.tsx, src/pages/IstioRulesList/IstioRuleListPage.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/ServiceList/ServiceListPage.tsx
Removed all binding methods by arrow sintax
=> Remove all binding by arrow methods

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/CytoscapeLayout/__tests__/CytoscapeLayout.test.tsx, src/components/CytoscapeLayout/graphs/GraphBadge.ts, src/components/GraphFilter/GraphFilter.tsx, src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx, src/pages/ServiceGraph/__tests__/ServiceGraphPage.test.tsx, src/types/GraphFilter.ts
This also fixes an issue with badge toggling.
=> KIALI-630 Add Route Rule Badging

src/components/GraphFilter/GraphFilter.tsx
=> KIALI-627 add namespace label to graphfilter and bring in left margin

src/components/GraphFilter/GraphFilter.tsx, src/components/MetricsOptions/MetricsOptionsBar.tsx, src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx, src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap, src/components/ToolbarDropdown/ToolbarDropdown.tsx, src/config.ts, src/pages/ServiceGraph/ServiceGraphPage.tsx
Shared duration of application [KIALI-610](https://issues.jboss.org/browse/KIALI-610).
=> [KIALI-610] Shared app duration option in toolbars

src/components/GraphFilter/GraphFilter.tsx
- use inline styles
- line up the two option toolbars
=> KIALI-627 nameaspace label (part two)

src/pages/ServiceList/ServiceListComponent.tsx
This removes a warning in the browser console.
=> Trivial: Enclose table content into <tbody>

src/components/MetricsOptions/MetricsOptionsBar.tsx, src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx, src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap, src/pages/ServiceDetails/ServiceMetrics.tsx
=> KIALI-381: new manual refresh button for metrics screen

src/components/CytoscapeLayout/CytoscapeLayout.tsx, src/components/CytoscapeLayout/graphs/GraphBadge.ts
this is going to be needed when we reuse the cy graph for graceful updates. But to avoid potential conflicts in the future, I'm committing this now so I can get small pieces in now.
=> refactor badge code

src/config.ts
JIRA: [Kiali-458](https://issues.jboss.org/browse/KIALI-458)
Changed username/password to admin/admin
Required: [kiali#184](https://github.com/kiali/kiali/pull/184)
=> [KIALI-458]Change username/password from jdoe/password to admin/admin

src/actions/index.ts, src/reducers/MessageCenter.ts, src/reducers/Namespaces.ts
It is just another place to have to replicate imports and every new/changed action would have a git conflict on one line in this file: the 'export' line.
=> Remove index.ts from actions directory.

.travis.yml
We are having issues with this check, package-lock.json is being generated
different depending the environment (os, npm, node)
=> Remove package-lock.json check

src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx, src/types/ServiceInfo.ts
=> KIALI-707 Fix missing TrafficPolicy at DestinationRule level

src/components/ToolbarDropdown/ToolbarDropdown.tsx, src/components/ToolbarDropdown/__tests__/ToolbarDropdown.test.tsx, src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
Tests for this component
JIRA: [KIALI-692](https://issues.jboss.org/browse/KIALI-692)
=> [KIALI-692] Tests for ToolbarDropdown Component

src/pages/ServiceGraph/ServiceGraphPage.tsx
Remove the extra space due to removing the filter toolbar.
Before:
After:
=> Kiali-722 Fix top margin by moving from 230px to 170px.

package-lock.json, src/components/Pf/PfSpinner.tsx, src/pages/IstioRulesList/IstioRuleListComponent.tsx, src/pages/ServiceList/ServiceListComponent.tsx
This is the first step of Reduxifying the spinner.
=> [WIP] Add PfSpinner Redux Component since it is used in multiple places.

take_test_screenshot.sh
=> kiali-733:  Improve handling of larger screenshot file

src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDeployments.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationPolicies.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRoute.css.map, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRoute.scss, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRoute.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRouteRules.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDeployments.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteRules.test.tsx.snap, src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/services/Api.ts, src/types/ServiceInfo.ts
I added the validations info on top of the route rules list within the Service Details page.
Here is the result:
=> Kiali 656 - Adding validations into route rules tab (service details page)

src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
This is the counterpart of https://github.com/kiali/kiali/pull/208 to adapt the new grouped validations into the UI.
Please, don't merge until backend is ready, but it can be reviewed and tested with the backend PR.
=> KIALI-769 Group IstioValidations per objectType and name in the UI

package.json, src/actions/ServiceGraphDataActions.ts, src/components/Badge/__tests__/Badge.test.tsx, src/components/Details/DetailObject.tsx, src/components/GraphFilter/GraphFilter.tsx, src/components/GraphFilter/GraphFilterToolbar.tsx, src/components/GraphFilter/GraphLegend.tsx, src/components/GraphFilter/__tests__/GraphFilterToolbar.test.tsx, src/components/GraphFilter/__tests__/GraphLegend.test.tsx, src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap, src/components/ServiceHealth/HealthHelper.tsx, src/components/SummaryPanel/InOutRateChart.tsx, src/components/SummaryPanel/LatencyChart.tsx, src/components/SummaryPanel/RateChart.tsx, src/components/SummaryPanel/RpsChart.tsx, src/containers/ServiceGraphPageContainer.ts, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDeployments.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRoute.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoCard.test.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceGraph/SummaryPanelEdge.tsx, src/pages/ServiceGraph/SummaryPanelGroup.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx, src/reducers/ServiceGraphDataState.ts, src/reducers/__tests__/ServiceGraphDataState.test.ts, src/services/__mockData__/getGraphElements.ts, src/store/Store.ts, src/types/GraphFilterToolbar.ts, yarn.lock
Still working, please feedback ^^ @abonas @serenamarie125 @xeviknal
=> [KIALI-153] Show Graph legend

src/actions/ServiceGraphDataActions.ts, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx, src/containers/MessageCenterContainer.tsx, src/reducers/ServiceGraphDataState.ts
Note, there's still some debug logs caused by the use of redux-logger.
=> Remove console.logs

src/components/CytoscapeGraph/graphs/TrafficRenderer.ts
Error percent 100%
Error percent 25%
Add red diamond shape for errors, the rate of diamonds to show is given by the `percentErr`, if none is found, the rate is 0 (no errors are show).
Also did a some tweaks on the params to show "TrafficPoints" more often.
=> KIALI-802 - Show error traffic in service graph traffic animation

README.adoc, STYLE_GUIDE.adoc
Working in the code style guide for the project.
[KIALI-599](https://issues.jboss.org/browse/KIALI-599)
I'll update this PR with the idea of get some feedback about this conventions while I continue working.
=> [KIALI-599] Code style guide

src/components/MetricsOptions/MetricsOptionsBar.tsx, src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap, src/pages/ServiceDetails/ServiceMetrics.tsx
- Use same spinner as in other places (pf spinner)
- Use global loading state
- <strike>Duplicate the PfSpinnerContainer component into a similar one able to show a "refresh" button when it isn't loading</strike>
=> KIALI-837 Fix metrics page spinner

src/reducers/LoginState.ts
Jira: [KIALI-846]( https://issues.jboss.org/browse/KIALI-846)
=> [KIALI-846] Show Error Connecting to Kiali when there is a 404 code

src/pages/ServiceDetails/ServiceDetailsPage.tsx
Example: after clicking on links in Source Services tab
=> KIALI-829 Fetch data again when props are updated

src/components/Nav/Navigation.tsx, src/components/Nav/UserDropdown.tsx, src/pages/Login/LoginPage.tsx, src/reducers/LoginState.ts
Move the change of the style of login from reducer to components.
=> [KIALI-534] Login Change Style, remove change in reducers

.travis.yml, src/components/GraphFilter/GraphLegend.tsx, src/components/GraphFilter/__tests__/GraphLegend.test.tsx, src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap
=> quick fix for legend, until we get a better fix

src/types/AceValidations.ts, src/types/__testData__/routeRule2.yaml, src/types/__tests__/AceValidations.test.ts
- Parse correctly offset in multiple weights/labels
- Add more tests
=> KIALI-876 Fix marker set in wrong line

package.json, yarn.lock
Added library redux-persist 
[Kiali-850](https://issues.jboss.org/browse/KIALI-850)
=> [KIALI-850] Add redux-persist library

src/components/CytoscapeGraph/CytoscapeGraph.tsx
=> KIALI-662: Fix zoom adjustment with Cose layout.

src/actions/ServiceGraphDataActions.ts, src/actions/ServiceGraphFilterActions.ts, src/actions/__tests__/GraphFilterAction.test.tsx, src/app/App.scss, src/components/GraphFilter/GraphFilter.tsx, src/components/GraphFilter/GraphFilterToolbar.tsx, src/components/GraphFilter/GraphRefresh.tsx, src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap, src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap, src/config.ts, src/containers/GraphRefreshContainer.tsx, src/containers/ServiceGraphPageContainer.ts, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx, src/reducers/ServiceGraphFilterState.ts, src/reducers/__tests__/ServiceGraphFilterStateReducer.test.ts, src/store/Store.ts, src/types/GraphFilter.ts
Adds autorefresher, the options are in the refresh button and the default refresh rate is 15s.
~~I'm using a DropdownKebab instead of a SplitButton, because the later doesn't look right inside the Toolbar.~~
Using SplitButton now, had to workaround the issue.
And added back the 5s and 10s, but the default is still 15s
=> KIALI-745 Autoupdate the service graph

package.json, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/graphs/TrafficRenderer.ts, src/components/SummaryPanel/InOutRateTable.tsx, src/components/SummaryPanel/RateTable.tsx, src/components/SummaryPanel/RpsChart.tsx, src/containers/GraphLayersContainer.tsx, src/containers/GraphRefreshContainer.tsx, src/containers/LoginPageContainer.ts, src/containers/MessageCenterContainer.tsx, src/containers/NamespaceDropdownContainer.tsx, src/containers/NavigationContainer.ts, src/containers/PfSpinnerContainer.tsx, src/containers/ServiceGraphPageContainer.ts, src/containers/UserDropdownContainer.ts, src/utils/Health.ts, yarn.lock
I coudn't bump redux thunk because of some errors -- but no big deal.
=> Kiali-853 Bump package versions for sprint 6

src/components/About/AboutUIModal.tsx
Require: https://github.com/kiali/kiali/pull/248
=> Changed name products by External Services

README.adoc
Also add 'Redux' to the Technologies list.
=> Trivial Remove 'General' section from readme it is not relevant. 

src/pages/ServiceDetails/ServiceInfo/ServiceInfoPods.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoPodsGrouping.ts, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoPods.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoPodsGrouping.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoPods.test.tsx.snap, src/types/ServiceInfo.ts
Relates to https://github.com/kiali/kiali/pull/268
=> KIALI-918 Update pods model to receive several owner references

src/pages/ServiceDetails/ServiceDetailsPage.tsx
There was a bad use of promises in ServiceDetails page.
Details and validations were not chained and that could lead in some weird error.
On this change, state is updated in a single step once both promises are resolved.
=> KIALI-875 Fix wrong promises processing in ServiceDetails page

src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx, src/types/ServiceInfo.ts
Counterpart of https://github.com/kiali/kiali/pull/274
=> KIALI-941 Updates DestinationRule Host on model

src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRoute.tsx
Add horizontal chart (Bullet Chart) into route rules view to show the weights.
Jira: [KIALI-735](https://issues.jboss.org/browse/KIALI-735)
**Require**: https://github.com/kiali/kiali-ui/pull/412
- Fix some errors with rowkeys
@serenamarie125 @abonas I am still working but I will be happy if you give me some feedback ^^
=> KIALI-735 Add Bullet Chart in Route Rules in the Service Detail

src/actions/ServiceGraphDataActions.ts, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/EmptyGraphLayout.tsx, src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceGraph/SummaryPanelGraph.tsx, src/reducers/ServiceGraphDataState.ts, src/store/Store.ts, src/utils/MessageCenter.ts
Counterpart of https://github.com/kiali/kiali/pull/282.
Thanks @jotak, I've created the PR from the web UI and for some reason it flipped the target branch !
Hope now is correct.
=> Merge master istio 0.8

src/components/ServiceHealth/HealthDetails.tsx, src/components/ServiceHealth/__tests__/HealthDetails.test.tsx, src/components/ServiceHealth/__tests__/HealthIndicator.test.tsx, src/components/ServiceHealth/__tests__/__snapshots__/HealthDetails.test.tsx.snap, src/components/ServiceHealth/__tests__/__snapshots__/HealthIndicator.test.tsx.snap, src/types/Health.ts, src/utils/Health.ts, src/utils/__tests__/Health.test.ts
Now includes inbound and outbound health
Removed some snapshots in the same time, as there was too many of them in HealthIndicator.test.tsx ; this is anyway well covered in utils/__tests__/Health.test.ts
Relates to https://github.com/kiali/kiali/pull/271 [istio 0.8]
=> KIALI-922 Update Envoy Metrics model

getLabels.py, run_itest.sh, src/__itests__/App.browser.test.tsx, take_test_screenshot.sh
itest only run if there is a label like: 
- kiali-bot-graph
- kiali-bot-services
- kiali-bot-services-review
- kiali-bot-reviews-metrics 
- kiali-bot-istio
- kiali-bot-istio-promhttp-rules 
- kiali-bot-jaeger
It's working with a regular expression so, if you add for example labels:
- kiali-bot => execute all tests
- kiali-bot-istio => kiali-bot-istio & kiali-bot-istio-promhttp-rules
=> [KIALI-902] Improve itest bot to fetch images on demand

src/pages/ServiceDetails/HistogramChart.tsx, src/pages/ServiceDetails/MetricChart.tsx, src/pages/ServiceDetails/MetricsChartBase.tsx, src/pages/ServiceDetails/ServiceMetrics.tsx
~~Styles are a little hacky. But I hope it's ok.~~
=> KIALI-757: Add expand feature in the detailed metrics page

getLabels.py, run_itest.sh, src/__itests__/App.browser.test.tsx, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/graphs/GraphStyles.ts, src/components/ServiceHealth/HealthDetails.tsx, src/components/ServiceHealth/HealthIndicator.tsx, src/components/ServiceHealth/__tests__/HealthDetails.test.tsx, src/components/ServiceHealth/__tests__/HealthIndicator.test.tsx, src/components/ServiceHealth/__tests__/__snapshots__/HealthDetails.test.tsx.snap, src/components/ServiceHealth/__tests__/__snapshots__/HealthIndicator.test.tsx.snap, src/pages/ServiceDetails/HistogramChart.tsx, src/pages/ServiceDetails/MetricChart.tsx, src/pages/ServiceDetails/MetricsChartBase.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRoute.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap, src/pages/ServiceDetails/ServiceMetrics.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceGraph/SummaryPanelGroup.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx, src/pages/ServiceList/RateIntervalToolbarItem.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/ServiceList/__tests__/RateIntervalToolbarItem.test.tsx, src/pages/ServiceList/__tests__/__snapshots__/RateIntervalToolbarItem.test.tsx.snap, src/services/Api.ts, src/types/RateIntervals.ts, take_test_screenshot.sh
This is a merge from fetching master and istio-0.8 branches to update istio-0.8 branch.
=> Update istio 0.8 version3

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts, src/types/IstioConfigDetails.ts, src/types/IstioConfigListComponent.ts
Counterpart of https://github.com/kiali/kiali/pull/297
=> KIALI-978 Add Gateway support in the UI for Istio Config

src/components/SummaryPanel/RpsChart.tsx
=> KIALI-872 User-friendly legend in summary panel when no in/out traffic

src/components/CytoscapeGraph/graphs/TrafficRenderer.ts, src/utils/MathUtils.ts, src/utils/__tests__/MathUtils.test.ts
Implements Bezier paths to allow the balls follow the curves.
There is only an issue, we are using "internal" data from cytoscape, due to https://github.com/cytoscape/cytoscape.js/issues/2139 once that is merged and released i can update the code to use public API.
=> KIALI-971 Graph animations follows the curve edges

src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/services/Api.ts, src/types/Health.ts
(side change: enforce type on api authentication param)
=> KIALI-911 optimize graph health queries having one query per namespace

src/components/GraphFilter/GraphFilter.tsx, src/components/ToolbarDropdown/ToolbarDropdown.tsx, src/components/ToolbarDropdown/__tests__/ToolbarDropdown.test.tsx, src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
ToolbarDropdown component can now work as a controlled component.
=> KIALI-859 Fix inconsistent state of service graph toolbar

src/actions/ServiceGraphDataActions.ts, src/components/CytoscapeGraph/graphs/GraphStyles.ts
This is the ui counterpart to [kiali/kiali#252](https://github.com/kiali/kiali/pull/252), so check there if you need information.
=> KIALI-817 Change node shape based on namespace.

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/types/IstioConfigDetails.ts, src/types/IstioConfigListComponent.ts
UI counterpart for https://github.com/kiali/kiali/pull/307
=> KIALI-987 Add ServiceEntry support into Istio Config in the UI

src/pages/ServiceList/ServiceListComponent.tsx
- Do not store rate interval as state (that state is actually handled in RateIntervalToolbarItem)
- make function 'fetchServices' get rate interval from field
=> KIALI-1035 and KIALI-1034 fix issues with rate interval in service list

src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/ServiceList/ServiceListComponent.tsx
Remove also binds in favor of fat arrows
And remove "loading" flag as it is not necessary anymore since the loader was moved to topbar
=> KIALI-1030 Add a refresh button for ServiceList & IstioConfig

src/types/AceValidations.ts, src/types/__testData__/destinationRule.yaml, src/types/__tests__/AceValidations.test.ts, tslint.json
A fix to mark correctly host/hosts field on VS and DR.
=> KIALI-1029 Fix marker on AceEditor when checking host

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigDetails/IstioRuleInfo.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- In Istio rule info
- In Istio config details
- In service details
=> KIALI-1036 Add missing refresh buttons

src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/pages/ServiceGraph/SummaryPanelCommon.ts, src/pages/ServiceGraph/SummaryPanelGroup.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx, src/reducers/LoginState.ts, src/types/Health.ts
Using a promise in panel's data makes sure the panel can get the latest up-to-date value for health
=> KIALI-1051 Fix health unsynchronized issue in summary panel

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
See https://github.com/securingsincity/react-ace/issues/300
=> KIALI-1056 Workaround for react-ace issue: force annotations refresh

src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/utils/Common.ts, src/utils/__tests__/Common.test.ts
Jira: [KIALI-1033](https://issues.jboss.org/browse/KIALI-1033)
=> KIALI-1033 Fix duplicates in filtering in ServiceList

src/actions/LoginActions.ts
Response is undefined when a request timeout.
=> KIALI-1079 Verify that we have a response before checking its status

src/components/Nav/UserDropdown.tsx
[KIALI-996](https://issues.jboss.org/browse/KIALI-996)
=> KIALI-996 Remove logout Icon

src/actions/GlobalActions.ts, src/app/App.tsx, src/containers/PfSpinnerContainer.tsx, src/reducers/GlobalState.ts, src/reducers/__tests__/GlobalStateReducer.test.ts, src/store/Store.ts
Also remove other spinner actions that were unused and don't really make sense anymore with a counter
=> KIALI-1080 use counter of requests for spinner

src/actions/HelpDropdownActions.ts, src/services/Api.ts, src/services/__tests__/ApiMethods.test.tsx.ts, src/store/ConfigStore.ts
Jira: [KIALI-1103](https://issues.jboss.org/browse/KIALI-1103)
- Moved about info to store-persist (Don't need to check everytime the versions)
- Removed authentication header in getStatus (Don't need it in /api and /api/status)
- Added comments to service/Api and refactor headers
=> KIALI-1103 Fix versions components in about and refactor

src/actions/LoginActions.ts, src/actions/NamespaceAction.ts, src/actions/__tests__/LoginAction.test.ts, src/config.ts, src/pages/Login/LoginPage.tsx, src/reducers/LoginState.ts, src/store/Store.ts
Everytime user refresh the website this sessiontimeout is updated, when the user refresh and the actual time pass the last time + hours in config file  user will need login again.
=> KIALI-533 Session Timeout

src/components/Details/DetailObject.tsx, src/components/Details/__tests__/DetailObject.test.tsx, src/components/Details/__tests__/__snapshots__/DetailObject.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices/VirtualServiceRoute.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap, src/types/ServiceInfo.ts
The validation will look like that:
Also, global warning has been added to each virtual service (following the style from Route Rules):
This PR requires the merge of kiali/kiali#332
=> KIALI-1068 Showing validations to spec/hosts for virtual services

src/reducers/ServiceGraphFilterState.ts, src/reducers/__tests__/ServiceGraphFilterStateReducer.test.ts
=> KIALI-1017 [Trivial] All badges turned on by default

src/actions/UserSettingsActions.ts, src/components/Nav/Navigation.tsx, src/components/Nav/__tests__/Navigation.test.tsx, src/containers/NavigationContainer.ts, src/reducers/UserSettingsState.ts, src/reducers/index.ts, src/store/ConfigStore.ts, src/store/Store.ts
Now we are storing user preferences in redux-store-persist like the collapse of the left menu.
Fix issue https://github.com/kiali/kiali/issues/325
=> KIALI-1071 Remember state of left-nav menu

README.adoc, src/actions/LoginActions.ts, src/actions/__tests__/LoginAction.test.ts, src/config.ts, src/types/Common.ts
Added documentation and change values to seconds
=> KIALI-533 Added documentation about the configuration of sessiontimeout

src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceGraph/SummaryPanelEdge.tsx, src/pages/ServiceGraph/SummaryPanelGraph.tsx, src/pages/ServiceGraph/SummaryPanelGroup.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx
=> KIALI-840 Avoid sidebar to cover the service graph when resized

package.json
Specify minimum version numbers for building the UI via:
- Node.js
- Npm
- Yarn
=> KIALI-1157: Add minimum version numbers for building the UI 

src/components/ConfigValidation/ConfigIndicator.tsx, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/types/IstioConfigListComponent.ts
Jira: [KIALI-1114](https://issues.jboss.org/browse/KIALI-1114)
=> KIALI-1114 Allow IstioConfig list show warning messages

src/components/ConfigValidation/ConfigIndicator.tsx
Fix https://github.com/kiali/kiali-ui/pull/503
=> KIALI-1114 Fix Warning Icon

src/components/GraphFilter/GraphFilter.tsx, src/components/GraphFilter/GraphRefresh.tsx, src/components/ToolbarDropdown/ToolbarDropdown.tsx, src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
Part of the UxD toolbar refactor. This PR makes the changes to the Refresh button and dropdown.
New Toolbar:
Old Toolbar:
=> KIALI-933 UxD Refresh Button changes

src/pages/ServiceDetails/ServiceInfo.tsx, src/types/ServiceInfo.ts
JIRA: [KIALI-1162](https://issues.jboss.org/browse/KIALI-1162)
@lucasponce I changed the note **Not all checks passed** too, I think that this should show if there is an error or warning too.
=> KIALI-1162 Missing warning icon on tab under ServiceDetails

src/pages/ServiceDetails/IstioObjectDetails.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
Fix the link in the Destination Rule.
=> KIALI-1220 Fix link to yaml in DestinationRule

src/actions/ServiceGraphDataActions.ts, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx, src/components/GraphFilter/GraphFilterToolbar.tsx, src/components/GraphFilter/__tests__/GraphFilterToolbar.test.tsx, src/components/Nav/NavUtils.tsx, src/containers/GraphSettingsContainer.tsx, src/containers/ServiceGraphPageContainer.ts, src/pages/ServiceGraph/ServiceGraphPage.tsx, src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx, src/types/Graph.ts, src/utils/Enum.ts, src/utils/__tests__/Enum.test.ts
=> KIALI-1227 Add graphType and versioned query params to fetch the graph data

src/components/CytoscapeGraph/graphs/GraphStyles.ts, src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx, src/types/Graph.ts
change app to be the same semantics as what appPreferred was
=> KIALI-1255 - remove appPreferred

src/components/Details/DetailObject.tsx, src/components/Details/__tests__/__snapshots__/DetailObject.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
Required : #530 [KIALI-1220](https://issues.jboss.org/browse/KIALI-1220)
JIRA: [KIALI-1201](https://issues.jboss.org/browse/KIALI-1201)
=> KIALI-1201 ServiceDetails: Move DestinationRules into a Table

src/pages/ServiceDetails/ServiceMetrics.tsx, src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx, src/types/GrafanaInfo.ts
Note that there isn't in and out dashboards anymore. Just one dashboard for a given service.
=> KIALI-1180 Update grafana link for istio-1 dashboards

src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/EmptyGraphLayout.tsx
- Makes it more consistent the layout (for non random layouts, i'm looking at you cose)
- Correctly displays when switching from a non-empty namespace to a empty namespace (and vice versa)
Issues:
Cose still flashs, I suspect is due to its non discrete nature.
=> KIALI-1291 Fix graph issues with relayout

src/containers/ServiceMetricsContainer.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceMetrics.tsx
This is a workaround, the root issue is related to C3Chart
=> KIALI-1295 Fix KIALI locking up in the service details metric page

src/components/MetricsOptions/MetricsOptionsBar.tsx, src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
Use prom app labels instead of service (source service doesn't exist anymore)
=> KIALI-1175, istio-1 fix, update grouping options in metrics

src/components/GraphFilter/GraphFilter.tsx, src/components/ToolbarDropdown/EdgeLabelRadioGroup.tsx
Some items in the toolbar weren't in sync with the value in the URL.
Fixing those controls passing the right properties to the components.
=> KIALI-1312 Fix inconsistency between URL and graph toolbar

src/pages/ServiceDetails/ServiceMetrics.tsx, src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx, src/services/Api.ts
Relative to backend PR: https://github.com/kiali/kiali/pull/428
JIRA: https://issues.jboss.org/browse/KIALI-1324
=> KIALI-1324 Dissociate apps metrics versus service metrics

README.adoc
Remove breadthfirst and klay and change cose to 'cose-bilkent'
=> Trivial - Upgrade graphLayouts in README

src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceMetrics.tsx, src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceMetrics.test.tsx.snap
Simplifies code for state & charts definitions
JIRA: https://issues.jboss.org/browse/KIALI-1343
Screenshot:
=> KIALI-1343 Service details metrics: show only inbound

package.json
Prepare for the next release (0.7.0).
=> KIALI-1359: Update to the next version

README.adoc
Spotted a few typos in README that were easy to fix.
N/A
No
N/A
=> Fix typos in README.md

src/pages/AppList/AppListClass.tsx, src/pages/AppList/AppListComponent.tsx, src/pages/AppList/AppListPage.tsx, src/pages/AppList/FiltersAndSorts.ts, src/routes.tsx, src/services/Api.ts, src/types/AppList.ts
It requires https://github.com/kiali/kiali/pull/444.
It introduces a new application list page with basic features:
Note that application details, and health and metrics will be added in following PRs.
=> KIALI-1240 Add a new App list page

src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
=> KIALI-1377 Fix tab Name Outbound Metrics

src/components/GraphFilter/GraphFilter.tsx, src/components/GraphFilter/GraphFilterToolbar.tsx, src/components/GraphFilter/GraphRefresh.tsx, src/components/ToolbarDropdown/ToolbarDropdown.tsx, src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
=> KIALI-1229 Add toolbar control to be able to change graph type

src/components/Metrics/Metrics.tsx, src/components/Metrics/__tests__/Metrics.test.tsx, src/pages/ServiceGraph/SummaryPanelCommon.tsx, src/pages/ServiceGraph/SummaryPanelEdge.tsx, src/pages/ServiceGraph/SummaryPanelGraph.tsx, src/pages/ServiceGraph/SummaryPanelGroup.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx, src/types/Metrics.ts, src/types/MetricsOptions.ts, src/utils/Graphing.ts
- Fix edge sparkline data
- Fix separate issue with edge sparklines from unknown
- Add support for edges to service nodes
- Add support for service node sparklines
- update to handle new split telemetry from the server metrics api
REQUIRES Server PR https://github.com/kiali/kiali/pull/445 to run.
=> KIALI-1389 Fix edge sparklines

src/components/ToolbarDropdown/ToolbarDropdown.tsx, src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
Metrics - Duration select and Poll Interval - Too close
[KIALI-1409](https://issues.jboss.org/browse/KIALI-1409)
cc @hhovsepy
=> KIALI-1409 Metrics - Duration select and Poll Interval - Too close

.travis.yml
=> KIALI-1370 Fix travis.yml syntax and allow deployment on master and tags

src/pages/AppList/AppErrorRate.tsx, src/pages/AppList/AppListClass.tsx, src/pages/AppList/AppListComponent.tsx, src/pages/AppList/AppListPage.tsx, src/pages/AppList/FiltersAndSorts.ts, src/pages/AppList/ItemDescription.tsx, src/types/AppList.ts
Fetch health and error rate information per application item on application list page.
https://issues.jboss.org/browse/KIALI-1392
=> KIALI-1392 Update AppList with Health and Error Rate

src/components/Nav/Navigation.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx
Open Jaeger tracing in a new tab
Needed [KIALI PR #460](https://github.com/kiali/kiali/pull/460)
[KIALI-1423](
https://issues.jboss.org/browse/KIALI-1423)
=> KIALI-1423 Move Jaeger iFrame to external links

run_itest.sh
=> Fix Kill PID in run_itest

src/pages/ServiceDetails/ServiceInfo/ServiceInfoRoutes.tsx
https://issues.jboss.org/browse/KIALI-1458
=> KIALI-1458 Fix unknown link on Service Details page

src/pages/AppList/AppListComponent.tsx, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/WorkloadList/WorkloadListComponent.tsx
Wrong pagination counts on list pages after using filtering.
https://issues.jboss.org/browse/KIALI-1436
yes.
** Is your pull-request introducing changes in behaviour? **
Yes, it resets the page when changing filters.
This behavior is applied also in App list, workload list and istio config list.
=> KIALI-1436 List pages: Reset page number when filters change

src/pages/ServiceGraph/SummaryPanelGroup.tsx, src/pages/ServiceGraph/SummaryPanelNode.tsx, src/pages/ServiceGraph/WorkloadLink.tsx
Avoid to render links when workload = unknown
=> KIALI-1465 Do not display workload links to workload=unknown

PULL_REQUEST_TEMPLATE.md
Instead of: 'Backwards in compatible' (which should be 'incompatible') and is the negative of compatible. Change to: 'Backwards compatible?'.
It is similar to asking someone: "Are you not hungry?" Which requires additional comprehension.
=> Trivial: Change to PR template wording: Backwards 'in compatible' 

src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoRoutes.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRoutes.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRoutes.test.tsx.snap, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/types/ServiceInfo.ts
... instead of source services (old way)
https://issues.jboss.org/browse/KIALI-1480
Related backend PR: https://github.com/kiali/kiali/pull/480
=> KIALI-1480 Fix Service dependencies using source workload

.travis.yml
Get travis notification in IRC when status of a branch change.
https://issues.jboss.org/browse/KIALI-113
=> KIALI-113 Add irc notification on travis

src/pages/ServiceDetails/ServiceDetailsPage.tsx
Propagate virtualservice/destinationrule parameter when tab is selected.
https://issues.jboss.org/browse/KIALI-1511
=> KIALI-1511 Propagate istio object on tabSelectHandler

src/components/ListPage/ListPage.ts, src/pages/AppList/AppListComponent.tsx, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/WorkloadList/WorkloadListComponent.tsx, src/types/Pagination.ts
Put back perPageOptions to Patternfly's "Paginator" props
JIRA: https://issues.jboss.org/browse/KIALI-1530
=> KIALI-1530 fix broken pagination

src/assets/img/graph-legend.svg, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/TrafficAnimation/TrafficPointRenderer.ts, src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
Implement the UXD suggestions for the traffic animation
https://github.com/kiali/kiali-design/blob/0c55e9373fc5b67926b8481b407ce97ccd07a9d7/service-graph/design.md#traffic-animation-options
~~This code is not ready, but was used to create the following screenshots~~
As per feedback, we are going for Option 1 and 4, here is the updated gif with the legend
Option 1 and 4
Option 2
Option 3 and 5
=> KIALI-1427 UXD changes to traffic animation

src/pages/ServiceDetails/ServiceDetailsPage.tsx
Backport of https://issues.jboss.org/browse/KIALI-1511 into the v0.7 branch
=> KIALI-1511 Propagate istio object on tabSelectHandler (#658)

src/components/Filters/NamespaceFilter.ts, src/components/Filters/StatefulFilters.tsx, src/components/ListPage/ListPage.ts, src/components/ListPage/__tests__/ListPage.test.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/AppList/AppListComponent.tsx, src/pages/AppList/AppListPage.tsx, src/pages/AppList/FiltersAndSorts.ts, src/pages/Graph/SummaryPanelGraph.tsx, src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/ServiceList/ServiceListPage.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadList/FiltersAndSorts.ts, src/pages/WorkloadList/WorkloadListComponent.tsx, src/pages/WorkloadList/WorkloadListPage.tsx, src/types/Filters.ts
- Not dedicated to namespace anymore
- This is basically a patternfly filter that manages state
- Move some common functions related to filtering from specific list pages to common ListPage class
No visible change expected.
=> KIALI-1543 Refactor NamespaceFilter => StatefulFilters prior to kiali- 1477 and kiali- 1528

src/actions/GraphFilterActions.ts, src/actions/__tests__/GraphFilterAction.test.tsx, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx, src/components/GraphFilter/GraphFilterToolbar.tsx, src/components/Nav/NavUtils.tsx, src/containers/GraphPageContainer.ts, src/containers/GraphRefreshContainer.tsx, src/containers/GraphSettingsContainer.tsx, src/pages/Graph/GraphPage.tsx, src/pages/Graph/GraphRouteHandler.tsx, src/reducers/GraphDataState.ts, src/reducers/GraphFilterState.ts, src/reducers/__tests__/GraphFilterStateReducer.test.ts, src/store/Store.ts
There is some trickery here that I hope I did in a reasonable way.  It's mainly because the graph settings are in redux but the url props are not.  So it's important to keep it in sync.
=> KIALI-1483 Add Show Service Nodes option

src/components/GraphFilter/GraphFilter.tsx, src/components/GraphFilter/GraphRefresh.tsx, src/pages/Graph/GraphPage.tsx
- fix logic to only fetch new graph type, was fetching old and then new
- prevent a fetch when changing refresh interval
- ensure an update of graphType forces a fetch
=> KIALI-1569 Fix GraphType Change

src/actions/LoginActions.ts, src/components/Nav/UserDropdown.tsx, src/services/Api.ts, src/services/__tests__/ApiMethods.test.tsx.ts
… with actual backend timeout
Also add a better error message in such situation.
https://issues.jboss.org/browse/KIALI-1457
=> KIALI-1457 Fix frontend session timeout out of sync 

src/actions/GraphFilterActions.ts, src/components/GraphFilter/GraphRefresh.tsx, src/components/ListPage/ListPageLink.tsx, src/components/Refresh/Refresh.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/Graph/GraphPage.tsx, src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/Overview/FiltersAndSorts.ts, src/pages/Overview/NamespaceInfo.ts, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/OverviewStatus.tsx, src/pages/Overview/OverviewToolbar.tsx, src/pages/Overview/__tests__/OverviewPage.test.tsx, src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/routes.tsx, src/store/Store.ts, src/types/Common.ts, src/types/GraphFilter.ts
- Navigation / menu entry
- Namespace cards
- Fetching backend app health
- Links to other sections with pre-selected namespace
JIRA: https://issues.jboss.org/browse/KIALI-1528
Still to do:
=> KIALI-1528 Introduce new Overview page

src/components/CytoscapeGraph/CytoscapeGraph.tsx
Add support for double-click drill down into an app box.
=> KIALI-1581 Detail graph for App Box

src/pages/Graph/SummaryPanelGraph.tsx
- This looks like it was just left behind and it generates a lot of console errors
=> trivial - remove extraneous cancelablePromise

src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/Nav/NavUtils.tsx, src/pages/Graph/GraphRouteHandler.tsx, src/routes.tsx, src/services/Api.ts, src/types/Graph.ts
This is the ui-side support.  It depends on merge of server-side PR https://github.com/kiali/kiali/pull/517.  Setting DNM until that is merged.
=> KIALI-1598 Support service detail graphs

src/components/SummaryPanel/RpsChart.tsx, src/pages/Graph/SummaryPanelEdge.tsx, src/pages/Graph/SummaryPanelGroup.tsx, src/pages/Graph/SummaryPanelNode.tsx
- Add more protection when deciding whether there is traffic.
- Unrelated but also add some more protection when canceling promises.
=> KIALI-1599 triple-click issue

src/utils/Authentication.ts
Removes usage of `// @ts-ignore` in the code.
Yes
=> Trivial - Removes ts-ignore from code

src/components/GraphFilter/GraphRefresh.tsx, src/components/ListPage/ListPage.ts, tslint.json
Also ban parseInt in the tslint so future use is discouraged
=> KIALI-1571 Replace use of parseInt with Number()

package.json
=> KIALI-1653 Prepare for 0.9.0

package.json, src/components/Metrics/HistogramChart.tsx, src/components/Metrics/MetricChart.tsx, src/components/Metrics/Metrics.tsx, src/components/Metrics/MetricsChartBase.tsx, yarn.lock
Use d3-format with SI notation
JIRA: https://issues.jboss.org/browse/KIALI-1371
Screenshot:
=> KIALI-1371 Metrics: add units on Y-axis

src/actions/GraphDataActions.ts, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/pages/Graph/SummaryPanelGraph.tsx
- also:
- fix up some dated and incomplete node and edge initialization
- quiet some console logging
=> KIALI-1715 Make node to node navigation use a new cy

src/components/Health/__tests__/HealthIndicator.test.tsx, src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap, src/pages/AppDetails/AppInfo/AppDescription.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoPods.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoPodsGrouping.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoPods.test.tsx.snap, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx, src/pages/WorkloadList/FiltersAndSorts.ts, src/pages/WorkloadList/ItemDescription.tsx, src/services/Api.ts, src/types/Health.ts, src/types/IstioObjects.ts, src/types/Workload.ts, src/types/__tests__/Health.test.ts
UI side of https://github.com/kiali/kiali/pull/500
=> KIALI-1284 Update Health to use Workloads instead Deployments

package.json, src/components/MessageCenter/MessageCenterTrigger.tsx, src/components/Nav/Navigation.tsx, src/components/Nav/UserDropdown.tsx, src/pages/Login/LoginPage.tsx, src/pages/ServiceDetails/IstioObjectDetails.tsx, src/utils/Authentication.ts, yarn.lock
- Upgraded typescript to v3 and patternfly-react to v2.20.3.  I had to upgrade both in one PR due to older d3-*** libs (required by patternfly) are incompatible with typescript v3.
- Fixed various typescript compilation errors.  Some of the errors:
```
src/pages/ServiceDetails/IstioObjectDetails.tsx
(131,5): Not all code paths return a value.
src/utils/Authentication.ts
(5,19): Property 'authentication' does not exist on type '{}'.
src/components/Nav/UserDropdown.tsx
(69,5): Object is possibly 'null'.
src/pages/Login/LoginPage.tsx
(38,5): Object is possibly 'null'.
```
Kiali-1554 
Kiali-1590 
no
=> kiali-1554 kiali-1590 upgraded typescript and patternfly

src/components/Health/__tests__/HealthDetails.test.tsx, src/components/Health/__tests__/HealthIndicator.test.tsx, src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap, src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/pages/ServiceList/__tests__/ItemDescription.test.tsx, src/pages/ServiceList/__tests__/ServiceErrorRate.test.tsx, src/pages/ServiceList/__tests__/ServiceListComponent.test.ts, src/services/__mockData__/getServiceDetail.json, src/types/Health.ts, src/types/__tests__/Health.test.ts
Error ratio is now directly provided by the backend: see PR https://github.com/kiali/kiali/pull/552
=> KIALI-1619 update health model for backend changes

src/pages/AppDetails/AppDetailsPage.tsx, src/pages/AppDetails/AppInfo/AppDescription.tsx, src/types/App.ts
Counterpart of https://github.com/kiali/kiali/pull/564 to support in the UI applications with no workloads.
(Corner case when a workload is a simple pod).
=> KIALI-1738 Support app without workload

package.json
Preparing KIALI console for next release, v0.10.0.
https://issues.jboss.org/browse/KIALI-1651
=> KIALI-1751 Prepare for 0.10.0

src/actions/GraphDataActions.ts, src/services/Api.ts, src/types/Common.ts, src/utils/Authentication.ts
This refactors the Api to be more type-safe and more immutable. 
Yes
No changes in behaviour
=> Refactor: Add more type safety around Api and Auth

src/assets/img/graph-legend.svg
=> KIALI-1784 add mTLS edge badge to legend

src/components/IstioActions/IstioActionsDropdown.tsx, src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts, src/pages/ServiceDetails/IstioObjectDetails.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/services/__mockData__/getServiceDetail.json, src/services/__tests__/Api.test.tsx, src/types/IstioConfigList.ts, src/types/Permissions.ts, src/types/ServiceInfo.ts
Model updated after backend changes
Create new "IstioActionsDropdown" component
Backend PR: https://github.com/kiali/kiali/pull/612
=> KIALI-1821 Add delete action in Service > Istio details

src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/services/__mocks__/Api.ts
Move JavaScript String to TypeScript string
=> Move js String to ts string

src/actions/GraphDataActions.ts, src/actions/LoginActions.ts, src/config.ts, src/pages/Graph/SummaryPanelEdge.tsx, src/pages/Graph/SummaryPanelGroup.tsx, src/pages/Graph/SummaryPanelNode.tsx, src/services/Api.ts
- user server config to determine the istio namespace
@jmazzitelli This requires server PR https://github.com/kiali/kiali/pull/613
=> KIALI-1831 Remove hardcoded istio-system namespace

src/containers/ServiceDetailsPageContainer.ts, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/routes.tsx
Fix the popup in traces tab in the service details
JIRA [KIALI-1587](https://issues.jboss.org/browse/KIALI-1587)
cc @hhovsepy please review.
=> KIALI-1587 Jaeger link tries to open popup

src/components/Filters/CommonFilters.ts, src/components/Filters/NamespaceFilter.ts, src/components/ListPage/ListPageLink.tsx, src/pages/AppList/AppListComponent.tsx, src/pages/AppList/FiltersAndSorts.ts, src/pages/Graph/SummaryPanelGraph.tsx, src/pages/IstioConfigList/FiltersAndSorts.ts, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/ServiceList/FiltersAndSorts.ts, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/WorkloadList/FiltersAndSorts.ts, src/pages/WorkloadList/WorkloadListComponent.tsx, src/types/Filters.ts
Shared function "filterByHealth" can be called in promises chain when filtering by health
Some DRY-mutualisation on filters (common patterns in CommonFilters.ts)
Note, I based this PR on #771 , not that I had no choice but it was easier for me. So ideally, #771 should be reviewed & merged first, then  I can rebase this one.
=> KIALI-1560 Allow filtering lists by health status

src/pages/Graph/SummaryPanelEdge.tsx, src/pages/Graph/SummaryPanelGroup.tsx, src/pages/Graph/SummaryPanelNode.tsx
=> KIALI-1872 Support configured version label name in side panels

src/components/About/AboutUIModal.tsx
=> KIALI-1817 Jaeger and Graphana Versions are being wrongly present on Kiali About

src/pages/IstioConfigList/FiltersAndSorts.ts
Refactoring Istio Config sorting method.
https://issues.jboss.org/browse/KIALI-1712
=> KIALI-1712 IstioConfig sort refactored to follow same patter as others

src/pages/ServiceDetails/IstioObjectDetails.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/VirtualServiceDetail.tsx
JIRA: [KIALI-1262](https://issues.jboss.org/browse/KIALI-1262)
=> KIALI-1262 Link to the gateway

src/pages/Overview/NamespaceInfo.ts, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/OverviewStatus.tsx, src/pages/Overview/OverviewToolbar.tsx
https://issues.jboss.org/browse/KIALI-1721
=> KIALI-1721 Overview page: add services view

src/pages/ServiceDetails/IstioObjectDetails.tsx, src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/DestinationRuleDetail.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
JIRA: [KIALI-1802](https://issues.jboss.org/browse/KIALI-1802)
This change create a link for destinationRule to the overview and yaml editor like the virtualServices.
=> KIALI-1802 Make DestinationRule in service details clickable and navigate to Istio Config

src/actions/GraphDataActions.ts, src/actions/GraphDataThunkActions.ts, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/graphs/GraphStyles.ts, src/pages/Graph/SummaryLink.tsx, src/pages/Graph/SummaryPanelCommon.tsx, src/pages/Graph/SummaryPanelNode.tsx
- this replaces obsolete isEgress node metadata
This requires server PR https://github.com/kiali/kiali/pull/687
=> KIALI-2031 support new isServiceEntry node metadata

src/components/GraphFilter/GraphSettings.tsx
=> KIALI-1942 grey out showServiceNodes option when graphType=service

src/assets/img/graph-legend.svg, src/components/About/AboutUIModal.tsx, src/components/CytoscapeGraph/graphs/GraphStyles.ts, src/components/MissingSidecar/MissingSidecar.tsx, src/components/Nav/Navigation.tsx, src/components/Pf/PfInfoCard.tsx, src/config/config.ts, src/config/icons.ts, src/config/index.ts, src/config/logos.ts, src/logos.ts, src/pages/AppDetails/AppInfo/AppDescription.tsx, src/pages/AppList/AppListClass.tsx, src/pages/AppList/ItemDescription.tsx, src/pages/Graph/SummaryPanelNode.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/pages/ServiceList/ItemDescription.tsx, src/pages/ServiceList/ServiceListComponent.scss, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/ServiceList/__tests__/ItemDescription.test.tsx, src/pages/WorkloadList/ItemDescription.tsx, src/routes.tsx
Replace IstioSidecar logo by Pficon Blueprint
JIRA: [KIALI-1888](https://issues.jboss.org/browse/KIALI-1888)
=> KIALI-1888 UXD: Update Missing Sidecars icons

src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/graphs/GraphStyles.ts, src/pages/Graph/SummaryLink.tsx, src/pages/Graph/SummaryPanelCommon.tsx, src/pages/Graph/SummaryPanelEdge.tsx, src/pages/Graph/SummaryPanelNode.tsx, src/types/Graph.ts
- fix service entry node labels
- fix service entry side panel
- fix namespace display for multi-namespace graphs
- fix unknown handling in graph and side panel
- change "Destination/Source" -> "To/From" in edge side panel to save space and better handle unknown
=> KIALI-2026 Improve display of namespaces in node labels

src/reducers/GrafanaState.ts, src/store/Store.ts
(and not show the grafana links in case of errors)
JIRA: https://issues.jboss.org/browse/KIALI-2048
=> KIALI-2048 Make GrafanaInfo initial state null to better handle errors

Makefile.jenkins, RELEASING.adoc
https://issues.jboss.org/browse/KIALI-2040
=> KIALI-2040 Support for snapshot releases through Jenkins Pipeline

src/components/ListPage/ListPageLink.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/Graph/SummaryPanelGraph.tsx, src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/OverviewStatus.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- updated links to supports multiple namespace filters
=> KIALI-2134 Fix links in graph summary page

src/app/App.scss, src/components/Nav/NavUtils.tsx, src/components/Nav/Navigation.tsx, src/pages/Graph/GraphPage.tsx, src/utils/SearchParamUtils.ts
Add kiosk mode like grafana so that other system can embed page
* [#651](https://github.com/kiali/kiali/issues/651)
[ X ] Is your pull-request introducing changes in behaviour?
=> Add kiosk mode like grafana so that other system can embed page

src/app/App.tsx
This is just a js console reporting feature so no functionality changes.
Due to this: https://github.com/reduxjs/react-redux/issues/897
Originally from:: 
https://github.com/kiali/kiali-ui/pull/869
=> Trivial: Remove React.StrictMode due to some Redux issues. 

src/pages/Graph/SummaryPanelGraph.tsx
=> Kiali 2168 Change links in graph summary panel

package.json, yarn.lock
Updates to latest Husky, and removes the deprecation error for the new version.
https://issues.jboss.org/browse/KIALI-2158
Yes!
=> KIALI-2158 Update husky and remove deprecation error

Makefile.jenkins, RELEASING.adoc
https://issues.jboss.org/browse/KIALI-2039
=> KIALI-2039 Support for patch releases through Jenkins Pipeline

src/actions/GraphDataActions.ts, src/actions/GraphDataThunkActions.ts, src/containers/GraphPageContainer.ts, src/pages/Graph/GraphPage.tsx, src/reducers/GraphDataState.ts, src/reducers/__tests__/GraphDataState.test.ts, src/store/Store.ts
Note the time range in the top right corner:
This UI PR requires Server PR: https://github.com/kiali/kiali/pull/750
=> KIALI-565 Show the graph time range on screen

src/routes.tsx
=> KIALI-2175 Hide namespace selection when rendering node detail graph

README.adoc
Update _README_ to reflect new directories and mark deprecated directories: `containers`
=> Trivial: Update directory structure documentation on README.

src/assets/img/graph-legend.svg, src/components/CytoscapeGraph/graphs/GraphStyles.ts, src/config/icons.ts, src/pages/Graph/SummaryLink.tsx, src/pages/Graph/SummaryPanelCommon.tsx, src/pages/Graph/SummaryPanelNode.tsx
- update node summary with new title
- update legend
- remove poc badging
=> KIALI-1811 New Service Entry Node Shape

package.json, yarn.lock
Upgrades patternfly version to fix the issue found in https://github.com/kiali/kiali-ui/pull/907
The difference is that this PR upgrades the yarn.lock
=> KIALI-2204 - Upgrades patternfly version

src/components/About/AboutUIModal.tsx, src/components/MetricsOptions/MetricsOptionsBar.tsx, src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/DestinationRuleDetail.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/reducers/LoginState.ts, src/services/Api.ts
See https://lgtm.com/projects/g/kiali/kiali-ui/alerts
- Secure external links with rel="noopener noreferrer"
- Remove unecessary condition checks
- Remove unecessary assignments
- Un-hide "LoginState" imported type
=> [code fixes] Fix some issues found by LGTM

src/pages/Overview/OverviewPage.tsx, src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
https://issues.jboss.org/browse/KIALI-1928
BEFORE:
AFTER:
=> KIALI-1928 Fix content width of the Overview page

src/components/CytoscapeGraph/graphs/GraphStyles.ts
=> KIALI-2203 Remove background image from service entry nodes

src/pages/Graph/SummaryPanelNode.tsx
Same issue as was fixed in TrafficRenderer.  This time resolving a regression in the node side panel.
=> KIALI-2227 Similar fix in different location

src/pages/Overview/OverviewPage.tsx
JIRA: https://issues.jboss.org/browse/KIALI-1998
=> KIALI-1998 Remove link on cards title

src/components/NamespaceDropdown.tsx, src/components/Nav/SecondaryMasthead.tsx
Updates the namespace selector with uxd suggestions, see https://github.com/kiali/kiali-design/issues/67
=> KIALI-2176 Update namespace selector with UXD suggestions

.snyk
Update the snyk remediation file for January since it only gives you 30-day exemptions.
=> Snyk update for January

src/components/Metrics/Dashboard.tsx, src/components/Metrics/Helper.ts, src/components/Metrics/__tests__/IstioMetrics.test.tsx, src/types/Metrics.ts
... as it can stand for both raw (gauges/counters) or rate data
JIRA: https://issues.jboss.org/browse/KIALI-2237
Backend PR: https://github.com/kiali/kiali/pull/781
=> KIALI-2237 Rename chart model counterRate -> metric

src/reducers/LoginState.ts, src/reducers/index.ts
For consistency with the rest of the state reducers -- replacing 'LoginStateInterface' with 'LoginState'.
=> Trivial: Remove 'LoginStateInterface' and replace with 'LoginState'

src/pages/AppDetails/AppDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/types/App.ts, src/types/Workload.ts
JIRA https://issues.jboss.org/browse/KIALI-2269
Backend PR: https://github.com/kiali/kiali/pull/796
=> KIALI-2269 Update runtimes model to dissociate with dashboards

README.adoc
Update the `README.adoc` for latest tools added to `package.json`
- Snyk Vulnerability Testing
- Source map visualization (package size %)
=> Update README.adoc with Snyk testing and source map analysis.

src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
JIRA: https://issues.jboss.org/browse/KIALI-1977
=> KIALI-1977 show runtime names in workload details

package.json, src/store/ConfigStore.ts, yarn.lock
Saves the selected namespaces in the localStorage.
=> KIALI-2069 Persist selected namespace

src/assets/img/graph-legend.svg
- change from 'traffic source' to 'unknown source'
Before:
After:
=> KIALI-2268 Update legend text for diamond node shape

src/actions/GraphFilterActions.ts, src/components/GraphFilter/GraphFind.tsx, src/components/GraphFilter/GraphSettings.tsx, src/components/GraphFilter/__tests__/GraphFind.test.tsx, src/reducers/GraphDataState.ts, src/reducers/__tests__/GraphDataState.test.ts, src/store/Selectors.ts, src/store/Store.ts
- maintain find/hide when navigating away and then back to the graph
- note: this intentionally is not in the URL and does not survive an F5
=> KIALI-2247 Reduxify graph-find and graph-hide values

src/routes.tsx
Fix a typo in the RegExp constructor as adding extra char broke the pattern.
I guess with this is fixed.
Please @hhovsepy let me know if this is fixed.
=> KIALI-2319 Fix Menu item deselected

src/components/CytoscapeGraph/graphs/GraphStyles.ts, src/pages/Graph/SummaryPanelNode.tsx
Also:
- fix an issue in app graph node labeling for app nodes in app boxes
=> KIALI-2198 Add isDead/noPods info to the node side panel

src/pages/Graph/SummaryLink.tsx
=> KIALI-2353 Fix multiple service links in node side panel

src/components/CytoscapeGraph/CytoscapeGraph.tsx
- prevent unnecessary check and console log error
=> KIALI-2350 Avoid health check for node with unknown namespace

src/components/IstioWizards/IstioWizard.tsx, src/types/IstioObjects.ts
Loadbalancing support on wizard
Usability fix: dont adjust slider when there are more than 2 workloads
=> KIALI-2364 mTLS support on Traffic Routing wizard

src/actions/GraphDataActions.ts, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx, src/reducers/__tests__/GraphDataState.test.ts, src/services/Api.ts, src/services/__mockData__/getGraphElements.ts, src/store/Selectors/GraphData.ts, src/store/Store.ts, src/types/Graph.ts
Defined the interface contract. The schema is pretty much the Cytoscape elements schema for nodes/edges.
This PR address  https://issues.jboss.org/browse/KIALI-585
=> KIALI-585 Add Type Interface for Service Graph json

package.json, src/app/History.ts, src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
* Fix failing tests in IstioConfigListComponent.test.ts
* Fix error console.error messages
https://issues.jboss.org/browse/KIALI-2328
`yarn test` should now run beautifully without any warning nor error messages.
=> KIALI-2328 Fix test failing but ignored and cleanup console errors

STYLE_GUIDE.adoc
This is following some previous discussions and trying to have clearer guidelines (although not entirely clear yet). See previous discussions here: https://github.com/kiali/kiali-ui/pull/923
In that discussion, @israel-hdez provided a link to Basarat's guide that I'm taking here as a reference. @mtho11 pointed to microsoft's guide (https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines ), which is actually quite similar, but I'm not taking it as a reference because of the disclaimers it shows.
So, changes are:
- Mainly following Basarat's guide https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md
- Some exceptions listed
- Removed the section about Proptypes as we don't use it
ping @jshaughn  @josejulio @israel-hdez @mtho11 @aljesusg @lucasponce …
=> Update Style Guide

src/actions/NamespaceAction.ts, src/actions/__tests__/NamespaceAction.test.ts, src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx, src/components/NamespaceDropdown.tsx, src/reducers/NamespaceState.ts, src/reducers/__tests__/NamespacesReducer.test.ts, src/store/Selectors.ts, src/store/Store.ts
The filter value is in redux.
I didn't fully use the proposed design because i have some questions regarding its overal designl and will open a new issue in the design repo.
=> KIALI-2091 Adds namespace selector filter

src/components/GraphFilter/GraphRefresh.tsx, src/components/MetricsOptions/MetricsDuration.tsx, src/components/ToolbarDropdown/ToolbarDropdown.tsx, src/config/serverConfig.ts, src/pages/Overview/OverviewToolbar.tsx
- Callers must handle the fact that ToolbarDropdown returns a string when a selection is made
- add some stronger typing to make this clear
=> KIALI-2428 Fix issue with updating durations

src/components/Details/DetailedTrafficList.tsx
https://issues.jboss.org/browse/KIALI-2410
* Remove the green/red bars that appear at the end of each row in the detailed traffic tab.
* Add a "status" column showing colored icons, depending on the thresholds.
This is per UXD recommendation: https://github.com/kiali/kiali-design/issues/70#issuecomment-462904571
=> KIALI-2410 Replace bars with status column (traffic tab)

src/components/Metrics/TrafficDetails.tsx, src/helpers/TrafficDetailsHelper.ts
https://issues.jboss.org/browse/KIALI-2435
Fixes blank traffic page when there is no inbound nor outbound traffic. This will be shown in this case:
=> KIALI-2435 Fix blank traffic page when there is no traffic

src/components/CytoscapeGraph/graphs/GraphStyles.ts, src/config/icons.ts, src/pages/Graph/SummaryPanelEdge.tsx, src/types/Graph.ts
mTLS is indicated in side panel on selection, regardless of whether 
Full time period:
Percentage of the time period:
REQUIRES SERVER PR https://github.com/kiali/kiali/pull/827
=> KIALI-2332 Add MTLS percentage to edge side panel

src/pages/Graph/SummaryLink.tsx
*** REQUIRES SERVER PR: https://github.com/kiali/kiali/pull/871 ***
=> KIALI-2448 Handle updated JSON for node.destServices

src/components/Tour/StatefulTour.tsx, src/pages/Graph/GraphHelpTour.ts
- Adds additional property to StatefulStep to provide an isVisible function
=> KIALI-2385 Do not show tour step for the graph when is empty

src/components/SummaryPanel/InOutRateChart.tsx, src/components/SummaryPanel/RateChart.tsx, src/components/SummaryPanel/ResponseTimeChart.tsx, src/components/SummaryPanel/RpsChart.tsx, src/components/Tour/Tour.tsx, src/pages/Graph/GraphHelpTour.ts, src/pages/Graph/SummaryPanel.tsx, src/pages/Graph/SummaryPanelEdge.tsx, src/pages/Graph/SummaryPanelGraph.tsx, src/pages/Graph/SummaryPanelGroup.tsx, src/pages/Graph/SummaryPanelNode.tsx, src/types/Graph.ts
https://issues.jboss.org/browse/KIALI-2361
=> KIALI-2361 Make graph side panel collapsible

src/components/Metrics/Helper.ts, src/components/Metrics/TrafficDetails.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
https://issues.jboss.org/browse/KIALI-2379
This is adding a dropdown to the traffic pages:
=> KIALI-2379 Add duration control in traffic pages

src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/IstioMetrics.tsx, src/components/MetricsOptions/MetricsSettings.tsx
- If the dashboard has no histogram, hide histogram options
- If the dashboard has no label, hide labels options
- If the dashboard has none of the above, hide options
JIRA: https://issues.jboss.org/browse/KIALI-2483
Screenshot (histogram hidden) :
=> KIALI-2483 Custom metrics: hide inappropriate options

src/components/Filters/FilterStyles.tsx, src/components/Filters/StatefulFilters.tsx, src/components/GraphFilter/GraphFilter.tsx, src/components/GraphFilter/GraphFind.tsx, src/components/GraphFilter/GraphRefresh.tsx, src/components/GraphFilter/GraphSettings.tsx, src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap, src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap, src/components/JaegerToolbar/__tests__/__snapshots__/LookBack.test.tsx.snap, src/components/MetricsOptions/MetricsDuration.tsx, src/components/Refresh/Refresh.tsx, src/components/ToolbarDropdown/ToolbarDropdown.tsx, src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap, src/config/config.ts, src/pages/AppList/AppListComponent.tsx, src/pages/Graph/GraphHelpTour.ts, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/Overview/OverviewToolbar.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/WorkloadList/WorkloadListComponent.tsx
@jmazzitelli , for now just let me know if this layout prevents your graph toolbar from wrapping in your Jira environment.  Make sure to test with longest menu values.
=> KIALI-2321 Better support smaller screen widths

src/components/IstioWizards/IstioWizard.tsx, src/components/IstioWizards/Slider/Slider.tsx, src/components/IstioWizards/WeightedRouting.tsx
Hide pins when there are only two workloads
Align text into center
Minor changes on style buttons
https://issues.jboss.org/browse/KIALI-2496
=> KIALI-2496 Disabled Slider should not show +/- buttons

src/components/GraphFilter/GraphFind.tsx, src/pages/Graph/GraphPage.tsx
- use overlays as opposed to Icon titles
=> KIALI-2474 Fix tooltips on firefox for graph tour and find/hide

src/components/IstioWizards/IstioWizard.tsx, src/components/IstioWizards/MatchingRouting.tsx, src/components/IstioWizards/TrafficPolicy.tsx
https://issues.jboss.org/browse/KIALI-2535
=> KIALI-2535 Move TLS/LoadBalancer under Show Advanced Options

src/components/DebugInformation/DebugInformation.tsx, src/config/serverConfig.ts
https://issues.jboss.org/browse/KIALI-2540
New configs shown are:
* Authentication config
* Status config (prometheus)
=> KIALI-2540 Show server configs in Debug dialog

STYLE_GUIDE.adoc
Add a description and links to our usage of Redux which uses the typesafe-actions library for Actions/Reducers. Gives developers a more formal definition of how to write code for our project using Redux (since it is a typesafe variant of the norm).
Here is the link included in the PR: https://github.com/piotrwitek/typesafe-actions
=> Add Documentation to the style guide for type-safe Redux 

src/components/Nav/UserDropdown.tsx
https://issues.jboss.org/browse/KIALI-2517
Fixing logout option. It's now disabled when anonymous login is enabled:
=> KIALI-2517 Disable logout for anonymous login strategy

src/components/CytoscapeGraph/CytoscapeGraphUtils.ts, src/components/CytoscapeGraph/graphs/GraphStyles.ts, src/store/Selectors/GraphData.ts, src/types/Graph.ts
It is not required for running but this PR goes with server PR https://github.com/kiali/kiali/pull/919
=> KIALI-2544 Edges can no longer be markes as 'isUnused'

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigList/FiltersAndSorts.ts, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts, src/types/IstioConfigDetails.ts, src/types/IstioConfigList.ts, src/types/IstioObjects.ts
Adding RbacConfigs to IstioConfig section. 
https://issues.jboss.org/browse/KIALI-2563
=> KIALI-2563 Add RbacConfigs to IstioConfig section

src/actions/LoginThunkActions.ts
https://issues.jboss.org/browse/KIALI-2561
=> KIALI-2561 Fix login page appearing when anonymous mode enabled

src/pages/Overview/OverviewPage.tsx
Add a small icon to each namespace health box which links to the Istio Config list
KIALI-2398
=> KIALI-2398 Add link to Istio Config per namespace in the overview page

src/components/CytoscapeGraph/CytoscapeGraphUtils.ts, src/components/SummaryPanel/ResponseTable.tsx, src/pages/Graph/SummaryPanelEdge.tsx, src/store/Selectors/GraphData.ts, src/types/Graph.ts
*** REQUIRES Servr PR https://github.com/kiali/kiali/pull/913
=> KIALI-470 Add Response Code summary to Edge side panel

src/components/IstioWizards/IstioWizardDropdown.tsx
https://issues.jboss.org/browse/KIALI-2336
=> KIALI-2336 Explain Istio Wizard disabled menu items

src/components/IstioWizards/Slider/BootstrapSlider.tsx, src/components/IstioWizards/Slider/Slider.tsx, src/components/IstioWizards/WeightedRouting.tsx
Align evenly button to the right
https://issues.jboss.org/browse/KIALI-2537
=> KIALI-2537 Add columns to Weighted Routing Wizard

src/types/IstioConfigList.ts
Instead of manually enabling a type each time (like #1042) this patch makes the backend decide which items are validated. Thus it allows future types (such as those coming from KIALI-2392 backend parts) to display validation results without changes to the UI.
Also, removes code duplication.
Part of KIALI-2392 which requires new types.
Yes.
No UI impact.
=> KIALI-2392 Enable validations for any backend returned type

src/pages/Graph/SummaryPanelGroup.tsx
- support service links (not sure if multiple is possible bit it doesn't hurt)
- support VS and CB badging
=> KIALI-1997 App Box summary panel should provide service link and appropriate badging

src/components/MTls/NamespaceMTLSStatus.tsx, src/pages/Overview/Filters.ts, src/pages/Overview/FiltersAndSorts.ts, src/pages/Overview/OverviewHelper.ts, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/OverviewToolbar.tsx, src/pages/Overview/Sorts.ts, src/pages/Overview/__tests__/OverviewPage.test.tsx, src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap, src/routes.tsx, src/types/Filters.ts
Adding sorting and filtering by mTLS status to overview page.
https://issues.jboss.org/browse/KIALI-2580
=> KIALI-2580 Add filtering and sorting by mTLS in overview

package.json
To prepare for the next release.
=> Bump version to 0.19.0

src/components/Details/__tests__/DetailedTrafficList.test.tsx, src/components/Metrics/TrafficDetails.tsx, src/components/Metrics/__tests__/TrafficDetails.test.tsx
https://issues.jboss.org/browse/KIALI-2355
Adding unit tests for Traffic tab work.
=> KIALI-2355 Tests for DetailedTrafficList

src/components/NamespaceDropdown.tsx, src/components/Nav/SecondaryMasthead.tsx, src/styles/_overrides.scss
Move Namespace selecto to PF4 and aligned with Openshift
JIRA: [KIALI-2626](https://issues.jboss.org/browse/KIALI-2626)
=> KIALI-2626 [PF4] Namespace Selector

src/pages/Login/LoginPage.tsx
[KIALI-2715](https://issues.jboss.org/browse/KIALI-2715)
=> KIALI-2715 have login page immediately indicate that a secret is missing

src/pages/ServiceList/ItemDescription.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/ServiceList/__tests__/ItemDescription.test.tsx, src/types/ServiceList.ts
Adds validation status for service validations in the service list. Waits for further information from kiali-design #118
KIALI-2454
In the kiali-design ticket.
=> KIALI-2454 Add service validations information to the UI

src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
JIRA: https://issues.jboss.org/browse/KIALI-2750
=> KIALI-2750 Use monospace font for logs

src/components/Nav/Navigation.tsx
=> Fix Menu Collapsed when mobile screen

package.json, src/styles/index.scss, yarn.lock
Upgrade to the stable release 3.2.6 for production
=> KIALI-2732 [PF4] Upgrade patternfly/react-core to 3.2.6

src/pages/ServiceList/ServiceListComponent.tsx, src/pages/WorkloadList/ItemDescription.tsx, src/pages/WorkloadList/WorkloadListComponent.tsx
- also, tweak some typing to be a little stronger
=> KIALI-2792 Fix console warning for workload list page

src/components/Metrics/Dashboard.tsx, src/components/Metrics/HistogramChart.tsx, src/components/Metrics/MetricChart.tsx, src/components/Metrics/MetricsChartBase.tsx
JIRA: https://issues.jboss.org/browse/KIALI-2789
=> KIALI-2789 Fix x-axis ticks on small screens

src/components/CytoscapeGraph/CytoscapeGraph.tsx
Checks if we the element is from the same cy instance before trying to operate it.
=> KIALI-2810 Test if the current element is valid before operating it

src/components/GraphFilter/GraphLegend.tsx, src/pages/Graph/GraphHelpFind.tsx, src/pages/Graph/GraphPage.tsx
@mtho11, by adding bounds on the Draggables for me it seems reasonable if not great.  It does generate vertical scrollbars as needed and I never get into a situation where I lose the handle or can't get rid of the modal.  It does not introduce or generate horizontal scrollbars.  I would sort of expected that to happen but it doesn't and I don't know how to make it happen or if it's even possible.
Give it a try and see whether it's enough to get by or if we need a guru to get this in better shape.
=> KIALI-2786 Set bounds on graph legend and find help modals

src/components/JaegerIntegration/JaegerToolbar.tsx, src/components/JaegerIntegration/LookBack.tsx, src/components/JaegerIntegration/RightToolbar.tsx, src/components/JaegerIntegration/ServiceDropdown.tsx, src/components/JaegerIntegration/TagsControl.tsx, src/components/JaegerIntegration/__tests__/LookBack.test.tsx, src/components/JaegerIntegration/__tests__/RightToolbar.test.tsx, src/components/JaegerIntegration/__tests__/ServiceDropdown.test.tsx, src/components/JaegerIntegration/__tests__/TagsControl.test.tsx, src/components/JaegerIntegration/__tests__/__snapshots__/RightToolbar.test.tsx.snap, src/components/JaegerIntegration/__tests__/__snapshots__/ServiceDropdown.test.tsx.snap, src/components/JaegerIntegration/__tests__/__snapshots__/TagsControl.test.tsx.snap, src/components/Nav/Navigation.tsx
Improve the toolbar and the user experience
JIRA: [KIALI-2627](https://issues.jboss.org/browse/KIALI-2627)
Improved selector to be more clear with groups by namespace
=> KIALI-2627 [PF4] Jaeger Integration with Kiali

src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/graphs/GraphHighlighter.ts, src/components/CytoscapeGraph/graphs/GraphStyles.ts
To get this to work the label had to be centered, the offset calculation
seemed confused when the app-box and/or font size would change.  Perhaps
it needed more refreshing somewhere.
=> KIALI-2826 App Box label should increase in size when highlighted

src/pages/IstioConfigDetails/IstioConfigDetailsPage.scss, src/types/AceValidations.ts
Adds UI support for cases where we can't validate the end result. 
KIALI-2818
=> KIALI-2818 Add info message line in case of unknown validation result

src/components/ListPage/ListPagesHelper.ts
Some Api changed from returning an array to a string
=> KIALI-2794 Fix Sort Order - Resets Sort Type

src/components/IstioActions/IstioActionsDropdown.tsx, src/components/IstioWizards/IstioWizardDropdown.tsx
Increase font on Delete Dialogs.
=> KIALI-2863 Increase font of Delete Dialogs

src/components/IstioWizards/IstioWizardDropdown.tsx, src/components/Nav/Menu.tsx
Prevent react warnings by using keys in arrays/loops
No changes in the UI.
=> KIALI-2860 Prevent react warnings by using keys in arrays/loops

src/components/Nav/Masthead/UserDropdown.tsx
JIRA: [KIALI-2729](https://issues.jboss.org/browse/KIALI-2729)
=> KIALI-2729 PF4 update allows 'logout' when using anonymous login

src/pages/ServiceDetails/ServiceDetailsPage.tsx
Jira: [KIALI-2851](https://issues.jboss.org/browse/KIALI-2851)
=> KIALI-2851 Tracing tab when tracing is disabled

src/components/BreadcrumbView/BreadcrumbView.tsx, src/components/Pf/PfTitle.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/AppDetails/AppInfo.tsx, src/pages/AppDetails/AppInfo/AppDescription.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoCard.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx, src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap, src/styles/_overrides.scss
JIRA: [KIALI-2840](https://issues.jboss.org/browse/KIALI-2840)
Design: https://github.com/kiali/kiali-design/issues/116
cc @serenamarie125 @abonas
=> KIALI-2840 Redesign Service Details

src/components/Metrics/MetricsChartBase.tsx
https://issues.jboss.org/browse/KIALI-1527
This applies the "No data" design available at https://www.patternfly.org/pattern-library/cards/base-card/#design
=> KIALI-1527 Show "No data available" on empty metrics

package.json, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts, yarn.lock
Updates cytoscape libs
workarounds a possible bug.
see: https://github.com/cytoscape/cytoscape.js/issues/2402
No UI changes
=> KIALI-2650 Updates cytoscape libs

src/components/CytoscapeGraph/CytoscapeGraph.tsx
- also, change invalid  drill-down from ERROR to WARNING message
=> KIALI-2890 Don't allow detail graph of unused node

src/components/DurationDropdown/DurationDropdown.tsx, src/components/GraphFilter/GraphRefresh.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/AppDetails/AppInfo.tsx, src/pages/Overview/OverviewToolbar.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo.tsx, src/services/Api.ts
Adds a way to configure the time of the health in the details page
@abonas Is this what you meant? If so i can continue to add it to the workload and app page.
=> KIALI-2636 Adds DurationDropdown to detail pages

src/components/DurationDropdown/DurationDropdown.tsx, src/components/Metrics/TrafficDetails.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/AppDetails/AppInfo.tsx, src/pages/AppList/AppListComponent.tsx, src/pages/AppList/AppListPage.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/ServiceList/ServiceListPage.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo.tsx, src/pages/WorkloadList/WorkloadListComponent.tsx, src/pages/WorkloadList/WorkloadListPage.tsx
Allows to configure the rate interval on the list pages.
=> KIALI-2884 Add DurationDropdown to list pages

src/pages/Graph/GraphHelpFind.tsx
=> KIALI-2896 Used fixed height for graph find modal

src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
https://issues.jboss.org/browse/KIALI-2909
Probably not an optimal fix, but doing anyway until we find a way to use JSX inside the tooltip.
=> KIALI-2909 Use react router in the graph context menu

src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
- Instead of applying the event listener to specific nodes apply it at graph
level, and use a selector to keep it up to date with the current node set.
- Generate the context-menu when needed
=> KIALI-2908 make context-menu insensitive to graph element changes

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Vertical aligns the action button in istio config details
Before:
After:
=> KIALI-2923 Align action button in istioConfig detail

src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
Aligns the subset fields in Service detail -> Overview -> Destination Rules
=> KIALI-2922 Vertically aligns subsets

src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
JIRA: [KIALI-2906](https://issues.jboss.org/browse/KIALI-2906)
cc @abonas
=> KIALI-2906 change tooltip direction in validation messages

src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx, src/components/CytoscapeGraph/CytoscapeContextMenu.tsx, src/components/CytoscapeGraph/CytoscapeGraph.scss, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx, src/components/JaegerIntegration/RouteHelper.ts, src/styles/index.scss
JIRA: [KILA-2911](https://issues.jboss.org/browse/KIALI-2911)
=> KIALI-2911 Add options to menu in graph

src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx, src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
Add ```<div id="basic-tabs">``` into Workload's Details as it is in ServiceDetails.
https://issues.jboss.org/browse/KIALI-2917
=> KIALI-2917 Add "<div id="basic-tabs">" into Workload's Details

src/components/MTls/MeshMTLSStatus.tsx
@jmazzitelli Please try this if you get the chance, would be good to get a fix in for this.
=> KIALI-2972 Avoid infinite querying by protecting against 0 refresh interval

src/pages/IstioConfigList/FiltersAndSorts.ts, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts, src/types/IstioConfigDetails.ts, src/types/IstioConfigList.ts, src/types/IstioObjects.ts, src/utils/IstioConfigUtils.ts
Adds Sidecar istio resource
Core PR https://github.com/kiali/kiali/pull/1108
=> KIALI-2748 Support Sidecar Istio resource in Istio Config

src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
@jotak Thanks for spotting this one.
=> KIALI-2988 Refresh logs on pod selection

src/components/Nav/Navigation.tsx, src/pages/Login/LoginPage.tsx, src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap, src/styles/_overrides.scss
https://issues.jboss.org/browse/KIALI-2993
Sample background images are at:
* Login page
* About dialog box
* Masthead
* Initializing screen
Also, fixing a Firefox issue about white background in the login page.
Screenshots:
=> KIALI-2993 Remove PatternFly sample background images

src/pages/Overview/OverviewPage.tsx, src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
=> KIALI-2990 Show empty page messaging when overview has no namespaces

src/components/IstioWizards/GatewaySelector.tsx, src/components/IstioWizards/IstioWizard.tsx, src/components/IstioWizards/IstioWizardActions.ts, src/components/IstioWizards/TrafficPolicy.tsx
Fix some issues on Advanced Settings wizard when some updates are performed.
https://issues.jboss.org/browse/KIALI-3015
=> KIALI-3015 Fix several issues with reset AdvancedSettings

src/types/IstioObjects.ts
Support for https://github.com/kiali/kiali/pull/1167
=> KIALI-3031 Add missing fields in VS/SE

package.json
We are going to have two active branches.
Master will host the 1.1.0 and following versions, so better to update the versions.
There will be a similar one for backend.
=> Mark master as 1.1.0

src/components/BreadcrumbView/BreadcrumbView.tsx, src/components/CytoscapeGraph/CytoscapeContextMenu.tsx, src/components/IstioActions/IstioActionsDropdown.tsx, src/components/IstioWizards/IstioWizard.tsx, src/components/IstioWizards/IstioWizardDropdown.tsx, src/components/IstioWizards/MatchingRouting/RuleBuilder.tsx, src/components/IstioWizards/MatchingRouting/Rules.tsx, src/components/IstioWizards/SuspendTraffic.tsx, src/components/IstioWizards/ThreeScaleIntegration.tsx, src/components/IstioWizards/TrafficPolicy.tsx, src/components/IstioWizards/WeightedRouting.tsx, src/components/ListPage/ListPagesHelper.ts, src/components/Metrics/TrafficDetails.tsx, src/components/MetricsOptions/MetricsSettings.tsx, src/components/Pf/PfTitle.tsx, src/components/SummaryPanel/ResponseTable.tsx, src/pages/Login/LoginPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/WorkloadDetails/WorkloadInfo.tsx, src/store/Selectors/GraphData.ts, src/types/Health.ts, src/types/IstioConfigList.ts
Part of #1154.
This fixes many of the warnings after the upgrade to `react-scripts`. Not all, but most of the errors, the ones missing might be more complicated to fix.
Here's the list of all warnings before the change:
```
./src/store/Selectors/GraphData.ts
Line 103:  Expected to return a value in arrow function                                                               array-callback-return
Line 108:  Prefer 'as DecoratedGraphNodeData' instead of '<DecoratedGraphNodeData>' when doing type assertions        @typescript-eslint/no-angle-bracket-type-assertion
Line 110:  Prefer 'as DecoratedGraphNodeWrapper' instead of '<DecoratedGraphNodeWrapper>' when doing type assertions  @typescript-eslint/no-angle-bracket-type-assertion
Line 128:  Prefer 'as DecoratedGraphEdgeData' instead of …
```
=> Fix more warnings

src/index.js
=> Remove index.js as it's not used but breaks build

src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/config/Paths.ts, src/pages/Graph/SummaryLink.tsx, src/pages/Graph/SummaryPanelEdge.tsx, src/pages/Graph/SummaryPanelNode.tsx
- provide a real link to the ServiceEntry detail
- show the individually requested destinations
*** Requires SERVER PR: https://github.com/kiali/kiali/pull/1172
=> KIALI-3034 Improve side-panel for serviceEntry nodes

src/app/AuthenticationController.tsx
JIRA: https://issues.jboss.org/browse/KIALI-3065
=> KIALI-3065 reset state of jaeger/grafana info on error

src/components/Health/Health.scss, src/components/Health/HealthDetails.tsx, src/components/Health/HealthIndicator.tsx, src/components/Health/Helper.ts, src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap, src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap, src/pages/Overview/OverviewStatus.tsx, src/types/Health.ts
Also fixing CSS (overflow:visible) for health icon and adding some space after the icon on overview status cards
https://issues.jboss.org/browse/KIALI-3073
=> KIALI-3073 Add attribute info to health icon

src/components/CytoscapeGraph/CytoscapeToolbar.tsx
- Also, add tooltips for zoom options
This is for one of the bullets in https://github.com/kiali/kiali/issues/1211.
=> KIALI-GH-1211 Improve layout popups

package.json, src/components/About/AboutUIModal.tsx, src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap, src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap, src/components/JaegerIntegration/__tests__/__snapshots__/RightToolbar.test.tsx.snap, src/components/JaegerIntegration/__tests__/__snapshots__/ServiceDropdown.test.tsx.snap, src/components/JaegerIntegration/__tests__/__snapshots__/TagsControl.test.tsx.snap, src/components/Nav/Masthead/HelpDropdown.tsx, src/components/Nav/Masthead/UserDropdown.tsx, src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap, yarn.lock
Stable version 3.58.1 https://www.npmjs.com/package/@patternfly/react-core
=>  KIALI-2809 Upgrade PF4 to release 3.58.1 

package.json, src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/Helper.ts, src/components/Metrics/IstioMetrics.tsx, src/components/Metrics/__tests__/CustomMetrics.test.tsx, src/components/Metrics/__tests__/IstioMetrics.test.tsx, src/components/MetricsOptions/MetricsRawAggregation.tsx, src/components/MetricsOptions/MetricsSettings.tsx, src/services/Api.ts, src/types/Metrics.ts, src/types/MetricsOptions.ts, yarn.lock
K-Charted now lies in `@kiali/k-charted-pf3`. Some components were renamed.
Backend PR: https://github.com/kiali/kiali/pull/1220
=> Deps update: upgraded k-charted to get bug fix (KIALI-2985)

src/components/IstioWizards/IstioWizardDropdown.tsx
- Workloads without sidecar
- Workloads without app/version labeling
- Add tooltip explaining why actions are disabled
=> KIALI-3113 Disable actions when service has not valid Workloads

tsconfig.json
I don't know if there is a better way, but it seems the current tsconfig.json doesn't help IDE to resolve dependencies.
Adding this one helps but not sure if it may have some non desired side effect.
Please, review.
=> Add typeRoot for resolving types from IDE

src/components/Pf/PfTitle.tsx
Fix bug on PfTitle as state is not properly refreshed when props change.
=> KIALI-3114 Refresh PfTitle when props change

src/pages/Overview/OverviewPage.tsx, src/pages/Overview/__tests__/OverviewPage.test.tsx, src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
JIRA: https://issues.jboss.org/browse/KIALI-3116
See also https://github.com/kiali/kiali-ui/pull/1321
=> KIALI-3116 [v1.0] Workaround to avoid graphical glitch on nav collapse

src/pages/Overview/OverviewPage.tsx
JIRA: https://issues.jboss.org/browse/KIALI-3116
Backport PR: https://github.com/kiali/kiali-ui/pull/1322
=> KIALI-3116 Workaround to avoid graphical glitch on nav collapse

src/components/IstioWizards/IstioWizardDropdown.tsx
Add a tooltip message when user has not permissions to perform actions.
=> KIALI-3123 Disable Actions on Service for User without permissions

package.json, yarn.lock
Medium CVE fix from Snyk through Patternfly module for (JS-Query depdency)
https://snyk.io/vuln/SNYK-JS-JQUERY-174006
yes
no
=> Snyk cve fix for https://snyk.io/vuln/SNYK-JS-JQUERY-174006

src/components/Nav/RenderPage.tsx, src/routes.tsx
Reverting code-splitting, because it's causing undesirable issues.
=> Revert code split KIALI-3035

.github/kiali.yml
Same as https://github.com/kiali/kiali/pull/1283, but for UI side.
This is inheriting same configs as in the back-end repo.
=> KIALI-3082 Enable check to enforce QE approvals

src/components/Details/DetailedTrafficList.tsx
=> KIALI-3098 Fix icon spacing issue

fetch-k-charted.sh, package.json, src/components/Metrics/Helper.ts, src/components/Metrics/IstioMetrics.tsx, src/components/MetricsOptions/MetricsSettingsDropdown.tsx, src/components/SummaryPanel/ResponseTable.tsx, src/utils/ResponseFlags.ts, yarn.lock
https://issues.jboss.org/browse/KIALI-3168
Needs k-charted update: https://github.com/kiali/k-charted/pull/47
(and needs k-charted version bump after the above is merged)
=> KIALI-3168 Metrics page, improve display of response_flags

fetch-k-charted-pf4.sh, package.json, src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/Helper.ts, src/components/Metrics/IstioMetrics.tsx, src/components/Metrics/__tests__/CustomMetrics.test.tsx, src/components/Metrics/__tests__/IstioMetrics.test.tsx, src/components/MetricsOptions/MetricsRawAggregation.tsx, src/components/MetricsOptions/MetricsSettings.ts, src/components/MetricsOptions/MetricsSettingsDropdown.tsx, src/services/Api.ts, src/types/Metrics.ts, src/types/MetricsOptions.ts, yarn.lock
JIRA: https://issues.jboss.org/browse/KIALI-3067
Ongoing work in k-charted repo: https://github.com/kiali/k-charted/issues?q=is%3Aissue+label%3APF4+
=> KIALI-3067 PF4 migration: charts / k-charted

src/components/MissingSidecar/MissingSidecar.tsx
restores code presumably lost in rebase.
=> KIALI-3217 Fix regression in MissingSidecar

src/store/ConfigStore.ts
Same as #1363.
This is the back-port to v1.3 branch to make the v1.3.1 release.
=> KIALI-3204 Fix blank screen issue (message center persistence problem)

Makefile.jenkins
Adds the possibility to use a custom package registry.
=> Use custom registry, if specified

src/actions/GraphDataThunkActions.ts, src/components/CytoscapeGraph/CytoscapeGraphUtils.ts, src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts, src/components/CytoscapeGraph/graphs/GraphStyles.ts, src/components/MissingSidecar/MissingSidecar.tsx, src/components/VirtualList/Config.ts, src/config/ServerConfig.ts, src/pages/Graph/GraphPage.tsx, src/pages/Graph/SummaryLink.tsx, src/pages/Graph/SummaryPanelCommon.tsx, src/pages/Graph/SummaryPanelEdge.tsx, src/pages/Graph/SummaryPanelGroup.tsx, src/pages/Graph/SummaryPanelNode.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/store/Selectors/GraphData.ts, src/types/Graph.ts, src/types/ServerConfig.ts
*** SERVER PR: https://github.com/kiali/kiali/pull/1321
=> KIALI-3195 UI-side changes for multi-namespace Istio deployment

package.json, src/components/JaegerIntegration/__tests__/__snapshots__/TagsControl.test.tsx.snap, src/components/Tab/Tabs.tsx, yarn.lock
JIRA: [KIALI-3242](https://issues.jboss.org/browse/KIALI-3242)
We need upgrade to continue working in Overview Page.
=> KIALI-3242 upgrade patternfly/react-core to 3.87.3 stable

src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts, src/components/GraphFilter/GraphFind.tsx
- https://github.com/kiali/kiali/issues/1342 (related)
=> KIALI-3240 Allow graph compression on Graph Hide

src/components/GraphFilter/GraphRefresh.tsx
Jira: [KIALI-3245](https://issues.jboss.org/browse/KIALI-3245)
Use the same component for refresh button in graphPage.
This will avoid having to change several parts
=> [KIALI-3245] Use the same component for refresh button in graph page

src/pages/AppDetails/AppInfo.scss, src/pages/AppDetails/AppInfo/AppDescription.tsx
Migrate App details page to PF4
https://issues.jboss.org/browse/KIALI-2631
yes
=> KIALI-2631 Migrate AppDetails page to PF4

package.json, src/components/Filters/StatefulFilters.tsx, src/components/JaegerIntegration/__tests__/__snapshots__/ServiceDropdown.test.tsx.snap, src/pages/AppList/FiltersAndSorts.ts, src/pages/IstioConfigList/FiltersAndSorts.ts, src/pages/Overview/Filters.ts, src/pages/Overview/OverviewToolbar.tsx, src/pages/ServiceList/FiltersAndSorts.ts, src/pages/WorkloadList/FiltersAndSorts.ts, src/types/Filters.ts, yarn.lock
Move filters to PF4 
JIRA: [KIALI-3249](https://issues.jboss.org/browse/KIALI-3249)
=> [KIALI-3249] [PF4] Move filters to PF4

src/pages/Overview/OverviewCardLinks.tsx, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
JIRA: [Kiali-3255](https://issues.jboss.org/browse/KIALI-3255)
=> [KIALI-3255][PF4] Move Overview Cards and Links

src/components/Filters/StatefulFilters.tsx, src/pages/AppList/AppListComponent.tsx, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/OverviewToolbar.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/WorkloadList/WorkloadListComponent.tsx
First PR to move Overview Toolbar,
Next [KIALI-3260 [PF4] Migrate ToolbarDropdown](https://issues.jboss.org/browse/KIALI-3260) https://github.com/kiali/kiali-ui/pull/1383
Fix: https://github.com/kiali/kiali/issues/1599
=> [KIALI-3257][PF4] Move Overview Toolbar

src/components/Filters/StatefulFilters.tsx, src/components/GraphFilter/GraphFilter.tsx, src/components/Metrics/IstioMetrics.tsx, src/components/ToolbarDropdown/ToolbarDropdown.tsx, src/components/ToolbarDropdown/__tests__/ToolbarDropdown.test.tsx, src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap, src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Need PR https://github.com/kiali/kiali-ui/pull/1381
Continue https://github.com/kiali/kiali/issues/1598
Fix https://github.com/kiali/kiali/issues/1601
=>  KIALI-3260 [PF4] Migrate ToolbarDropdown

src/pages/Overview/OverviewCardLinks.tsx, src/pages/Overview/OverviewPage.tsx
Fixes https://github.com/kiali/kiali/issues/1589
=> KIALI#1589 Overview type should determine graph type when linking to graph

src/components/Validations/Validation.tsx, src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx, src/types/ServiceInfo.ts
Migrates PF3 components to PF4 in the DestinationRule and VirtualService page.
Still needs to migrate:
- Labels: https://github.com/kiali/kiali/issues/1634
- Validations: https://github.com/kiali/kiali/issues/1635
Once both above PR will be closed, this page will be totaly migrated.
Splitting in those two issues not to have a big PR.
Epic:
https://github.com/kiali/kiali/issues/1588
=> KIALI-2633 Migrate VS and DR from Istio Details page to PF4

src/components/Tab/Tabs.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo.tsx
Navigating through the browser history don't update tabs. Fixed it.
yes
=> Go back in browser history not reloading tabs

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Fixes kiali/kiali#1586
https://github.com/kiali/kiali/issues/1586
=> Revert back YAML changes when canceling

README.adoc
Closes https://github.com/kiali/kiali/issues/1538
=> Document issue with file watchers

src/components/Filters/StatefulFilters.tsx
Fix https://github.com/kiali/kiali/issues/1640
=> Overview page toolbar breaks with small browser window

src/components/IstioWizards/GatewaySelector.tsx, src/components/IstioWizards/IstioWizard.tsx, src/components/IstioWizards/IstioWizardActions.ts, src/components/IstioWizards/TrafficPolicy.tsx, src/components/IstioWizards/VirtualServiceHosts.tsx
This PR included https://github.com/kiali/kiali-ui/pull/1399 and migrates the Wizard framework and the Advanced options.
Note that content of wizard is not yet migrated, that will be sent in a separate PR.
This is related to kiali/kiali#1595
=> PF3 -> PF4 Move Wizard framework and Advanced Options

src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/Helper.ts, src/components/Metrics/IstioMetrics.tsx, src/components/MetricsOptions/MetricsSettingsDropdown.tsx
So that filters are preserved upon page reload or direct linking
Closes https://github.com/kiali/kiali/issues/1558
=> Store metrics filters in URL

src/pages/Graph/SummaryPanelGraph.tsx
Each version was being counted as an app, which was inconsistent with the overview page and the Apps list.
This fixes the app counter and, as suggested, a version counter is also added.
Fixes kiali/kiali#1490
=> Fix app counter in the side panel and add versions counter

src/components/JaegerIntegration/JaegerToolbar.tsx, src/components/JaegerIntegration/TagsControl.tsx, src/components/JaegerIntegration/__tests__/__snapshots__/TagsControl.test.tsx.snap
Require: https://github.com/kiali/kiali-ui/pull/1412
=> Fix error showing advanced options in Jaeger

src/pages/IstioConfigList/FiltersAndSorts.ts
Closes https://github.com/kiali/kiali/issues/1585
=> IstioConfigList can't filter by 2 or more names

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Backport of kiali/kiali#1586 for v1.0 branch.
@hhovsepy could you test if it is ok for v1.0 branch (potentially to be added into Kiali 1.0.6).
=> Backport - Revert back YAML changes when canceling

src/components/Metrics/CustomMetrics.tsx
(css display flex)
Closes https://github.com/kiali/kiali/issues/1701
=> Styling: don't break line on pods aggregation combo

src/components/GraphFilter/GraphLegend.tsx, src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap, src/pages/Graph/GraphPage.tsx
Use the new design for Graph Legend (moving it to the left instead of floating to the right). This will resolve some other bug/issues with regards to small screens etc.
- [x ] Move Graph Legend to Left side of Graph (and make non-modal)
- [x ] Resolve issues with hide/show Sidebar and hide/show Legend together
- [x ] Migrate the code to PF4
fixes: https://github.com/kiali/kiali/issues/1620
**Before**:
**After**:
**Expand/Collapse of Both Nav and Legend:**
=> Make Graph Legend Scrolling more Obvious (and move to PF4)

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/utils/IstioValidationUtils.ts, src/utils/MessageCenter.ts
=> Show notification about warning/error validations for IstioConfig

Makefile.jenkins
Backports the jenkins file with some needed changes to push to the public npm registry.
=> Backport jenkins file to use npm registry

src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/utils/IstioValidationUtils.ts
Instead of showing every error, shows a summary of which Configs have errors/warnings
Fixes #1500
=> Shows a reduced message in IstioConfig list

src/components/BreadcrumbView/BreadcrumbView.tsx
- "Istio object type"
- "Istio object"
- "Service" and "Workload" in the service and workload view
Fixes kiali/kiali#1531
=> Removed some information from the breadcrumbs

src/components/Label/Label.scss, src/components/Label/Label.tsx, src/components/Label/Labels.tsx, src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap, src/components/Label/__tests__/__snapshots__/Labels.test.tsx.snap, src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
Migration of Labels to PF4.
Closes https://github.com/kiali/kiali/issues/1634
Workload details:
ServiceDetails:
VirtualService details:
=> [PF4] Migrate Labels to PF4

package.json, yarn.lock
Switch from release candidate to release (same code)
=> Update k-charted 0.3.0

src/components/GraphFilter/GraphFind.tsx, src/components/GraphFilter/__tests__/GraphFind.test.tsx, src/pages/Graph/GraphHelpFind.tsx
Fixes https://github.com/kiali/kiali/issues/1755
=> Fix Find/Hide not working for =, != numeric expressions

src/assets/img/legend/app.svg, src/assets/img/legend/service-entry.svg, src/assets/img/legend/service.svg, src/assets/img/legend/unknown.svg
Fixes kiali/kiali#1759
Before:
After:
=> Updates node shapes in the legend

src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts
Instead record the parent positions to avoid any future bug if this changes.
This is a small refactor that demystifies the reason the batch was required for a portion of the code.
I recall we had a bug when upgrading the `cytoscape` lib, and had to add that startBatch there
see https://github.com/kiali/kiali-ui/pull/1185 and https://github.com/cytoscape/cytoscape.js/issues/2402#issuecomment-495308640 for more details.
When adding back the children to the parent nodes (moving the off the graph or changing their parent) the parent loses its positions and instead adopts the position that covers all their children.
The reason it was working with the `batch` is because it locks (or prevents recompute) the positions (among other things), but we shouldn't rely on this …
=> Do not rely on "startBatch" for locking positions

src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts, src/components/GraphFilter/GraphFind.tsx
- Position is reset to 0,0
- Cleaning the code
Fixes kiali/kiali#1767
before:
after:
=> Reset to node's positions and small tweaks

src/components/JaegerIntegration/JaegerToolbar.tsx, src/components/JaegerIntegration/__tests__/JaegerToolbar.test.tsx, src/components/JaegerIntegration/_jaegerIntegration.scss
Fix: https://github.com/kiali/kiali/issues/1665
=> [PF4] Jaeger Toolbar expand advanced options component

src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRouteVirtualServices.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoWorkloads.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceMock.ts, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/styles/_overrides.scss
Fix: https://github.com/kiali/kiali/issues/1591
=> [PF4] Move Service Details to PF4

src/components/MetricsOptions/MetricsSettingsDropdown.tsx
Based on @mtho11 's work here: https://github.com/kiali/kiali-ui/pull/1458
There's the same odd artifact of having a gray background when mouse comes over.
=> Move metrics settings to PF4

src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
Closes https://github.com/kiali/kiali/issues/1786
Still not sure why I'm the only one to see this issue, but anyway, here's a patch
Also remove unused function
=> Fix handling missing validation objecti

src/pages/Overview/OverviewCardContentCompact.tsx, src/pages/Overview/OverviewCardContentExpanded.tsx, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/OverviewStatus.tsx
Looks like some stuff were missed in cards migration https://github.com/kiali/kiali-ui/pull/1378
So here's the missing parts :-)
=> Move missing stuff from Overview Cards to PF4

src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadServices.tsx, src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
Fix https://github.com/kiali/kiali/issues/1592
=> Move workload page/details to PF4

src/components/SummaryPanel/RpsChart.tsx
Closes https://github.com/kiali/kiali/issues/1800
=> RpsChart: Fix array out of bound

src/pages/AppDetails/AppDetailsPage.tsx, src/pages/AppDetails/AppInfo.tsx
Related with [PF4] App Page task old tracker JIRA
=> Move AppInfo To PF4

src/components/MissingSidecar/MissingSidecar.tsx, src/config/Icons.ts
Fix https://github.com/kiali/kiali/issues/1799
=> [PF4] Move MissingIstioSidecar component

src/components/PfSpinner.tsx
Fix https://github.com/kiali/kiali/issues/1802
=> move Spinner to PF4

src/components/SessionTimeout/SessionTimeout.tsx
=> Move SessionTimeout component to PF4

package.json, src/components/MissingSidecar/MissingSidecar.tsx, src/components/VirtualList/Renderers.tsx, src/components/VirtualList/VirtualTable.tsx, src/pages/AppDetails/AppInfo/AppDescription.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx, yarn.lock
This is a tricky issue (at least for me).  The problem occurs because of the width taken by the scroll bar when the virtual list requires scrolling.  Initially I thought it was due to problems with the cell rendering itself, but eventually I discovered the root cause.  A fix is difficult, or possibly just difficult for me given a lack of experience with visual orientation issues.  But because the Virtual table body is rendered independently of the table header, when the body width is reduced the cells compress slightly, but the header positions do not change.
On Chrome (webkit) the problem is solvable with a proprietary setting (overflowY: 'overlay'), but this does not exist on FF or Edge.  This PR contains the Chrome solution but this would still be a known issue for non-chrome browsers. …
=> List views alignment issue

package.json, src/components/Details/DetailedTrafficList.tsx, src/components/Details/__tests__/DetailedTrafficList.test.tsx, src/components/Metrics/TrafficDetails.tsx, src/components/Metrics/__tests__/TrafficDetails.test.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/styles/index.scss, yarn.lock
Fix https://github.com/kiali/kiali/issues/1808
=> Move Traffic tab to PF4

src/config/KialiIcon.tsx
Small change to add additional icons to `KialiIcon` and make the width 10px.
=> Trivial: Add additional icons to KialiIcon.tsx and make width of icons 10px.

src/pages/ServiceDetails/ServiceDetailsPage.tsx
=> Fix refresh problem of traces tab

src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx
Fixes [1663](https://github.com/kiali/kiali/issues/1663)
=> Move IstioObjectDetails Page Overview Items into Stack and StackItem.

src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
Closes kiali/kiali#1590
@aljesusg I think ServiceDetailsPage is in Pf4, I've found a couple of problems that are fixed with this PR.
=> ServiceDetailsPage: minor fixes

src/pages/AppDetails/AppInfo/AppDescription.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx, src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
Moved strong tag to h3
Fixes [1841](https://github.com/kiali/kiali/issues/1841)
=> Appliations Health to the same style as Service and Workload.

package.json, src/components/CytoscapeGraph/CytoscapeContextMenu.tsx, src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/CytoscapeGraphUtils.ts, src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx, src/components/CytoscapeGraph/CytoscapeToolbar.tsx, src/components/CytoscapeGraph/graphs/GraphStyles.ts, yarn.lock
Adds typesafety to cytoscape methods
Fixes kiali/kiali#1835
Depends on DefinitelyTyped/DefinitelyTyped#39245
=> Adds @types/cytoscape

src/components/GraphFilter/GraphRefresh.tsx, src/components/Refresh/Refresh.tsx, src/pages/AppList/AppListComponent.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Fixes #1865, helping the QE folks to automate their UI tests.
Tested pages, all working:
- Overview
- Graph
- Applications
- Workloads
- Services
- Istio Config
=> Use the same ID for all refresh buttons

src/components/Health/Health.scss, src/components/Health/HealthIndicator.tsx, src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
Fix https://github.com/kiali/kiali/issues/1834
cc @hhovsepy can you check if this fix the problem ?
=> Fix Masthead disappears after scrolling on lists

src/assets/img/legend/edge-danger.svg, src/assets/img/legend/edge-idle.svg, src/assets/img/legend/edge-success.svg, src/assets/img/legend/edge-warn.svg, src/components/CytoscapeGraph/TrafficAnimation/TrafficPointRenderer.ts, src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts, src/components/CytoscapeGraph/graphs/GraphStyles.ts
Fixes https://github.com/kiali/kiali/issues/1843
before:
after:
=> graph UX - solid edges, updated legend, larger animation particles

src/components/NamespaceDropdown.tsx
As the title says, this is migrating the namespace selector to PF4.
=> Pf4 the namespace selector

src/components/NamespaceDropdown.tsx
=> Fix id in namespace selector

src/components/NamespaceDropdown.tsx
1.9 Backport for https://github.com/kiali/kiali/issues/1901
=> Fix regression, ensure NamespaceDropdown refreshes accessible namespaces

src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx, src/components/JaegerIntegration/JaegerIntegration.tsx, src/components/Metrics/IstioMetrics.tsx, src/components/Metrics/TrafficDetails.tsx, src/components/Metrics/__tests__/IstioMetrics.test.tsx, src/components/Nav/Page/RenderContent.tsx, src/components/Nav/Page/RenderHeader.tsx, src/components/Nav/Page/index.ts, src/components/Nav/RenderPage.tsx, src/components/Nav/SecondaryMasthead.tsx, src/components/VirtualList/VirtualList.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/AppList/AppListPage.tsx, src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigList/IstioConfigListPage.tsx, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceTraces.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/pages/ServiceList/ServiceListPage.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx, src/pages/WorkloadList/WorkloadListPage.tsx, src/styles/_layout.scss
UX Design: https://marvelapp.com/i9h9g7j/screen/59315420
Fix : https://github.com/kiali/kiali/issues/1600
Next steps: Continue migration PF4 views
=> KIALI-1600 [PF4] Create background in grey color as suggested by UX for all views

src/components/Refresh/RefreshButton.tsx
Fix https://github.com/kiali/kiali/issues/1724
UX design: https://marvelapp.com/i9h9g7j/screen/59315432
=> Move refresher button to UX design

src/components/GraphFilter/GraphFilter.tsx
This PR finishes off the last of the Graph Filter changes for the migration to PF4. Much of it has already been done in other PRs but this closes https://github.com/kiali/kiali/issues/1607
**After**:
=> Pf4 the GraphFilter.tsx

src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/IstioMetrics.tsx, src/components/Metrics/TrafficDetails.tsx, src/components/Nav/Navigation.tsx, src/components/Nav/Page/RenderComponentScroll.tsx, src/components/Nav/Page/RenderContent.tsx, src/components/Nav/Page/index.ts, src/components/Nav/RenderPage.tsx, src/components/VirtualList/VirtualTable.tsx, src/pages/AppDetails/AppInfo.tsx, src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceTraces.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/pages/WorkloadDetails/WorkloadInfo.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx, src/styles/_layout.scss
Fix https://github.com/kiali/kiali/issues/1902
Fix https://github.com/kiali/kiali/issues/1922
=> Fix double scroll and fix last row in lists

src/app/AuthenticationController.tsx, src/app/History.ts, src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx, src/components/JaegerIntegration/JaegerIntegration.tsx, src/components/JaegerIntegration/JaegerToolbar.tsx, src/components/JaegerIntegration/RouteHelper.ts, src/components/JaegerIntegration/ServiceDropdown.tsx, src/components/JaegerIntegration/__tests__/JaegerToolbar.test.tsx, src/reducers/JaegerState.ts, src/reducers/__tests__/JaegerStateReducer.test.ts, src/store/Store.ts, src/types/JaegerInfo.ts
Fix: https://github.com/kiali/kiali/issues/1785
Require: https://github.com/kiali/kiali/pull/1801
=> Add Jaeger configuration for namespaceSelector

src/pages/Graph/SummaryPanelEdge.tsx, src/pages/Graph/SummaryPanelGroup.tsx, src/pages/Graph/SummaryPanelNode.tsx
When transitioning from one selected graph element to another of the same type (e.g. edge1 to edge2), we rendered one time using stale metric data.  This was invalid in a normal case, and in the worst case could cause a crash.  This PR ensures that on a prop change for the target element we immediately move to loading state, and initialize the metric state.  It also ensures a more complete init of metric state when applicable.  It applies the same logic to edge, node and group (i.e. app box) summary panels.
Fixes https://github.com/kiali/kiali/issues/1933
=> Improve handling when graph summary target element changes

src/components/SummaryPanel/ResponseFlagsTable.tsx, src/components/SummaryPanel/ResponseHostsTable.tsx, src/components/Tab/SimpleTabs.tsx, src/pages/Graph/SummaryPanelCommon.tsx, src/pages/Graph/SummaryPanelEdge.tsx, src/pages/Graph/SummaryPanelGraph.tsx, src/pages/Graph/SummaryPanelGroup.tsx, src/pages/Graph/SummaryPanelNode.tsx
Migrate the Tabs, Nav elements and Icons for the Graph Side panel to PF4.
fixes: https://github.com/kiali/kiali/issues/1608
=> [Pf4] MIgrate the Graph Side Panel

src/components/IstioWizards/IstioWizard.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
=> 3scale fixes

src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
=> Adjust size of subsets column in DR table

package.json, src/styles/index.scss, yarn.lock
Fix https://github.com/kiali/kiali/issues/1857
=> Remove Patternfly-react

src/components/Validations/Validation.tsx, src/components/Validations/ValidationObjectSummary.tsx, src/components/Validations/ValidationSummary.tsx, src/components/VirtualList/Renderers.tsx, src/config/Config.ts, src/pages/Overview/NamespaceInfo.ts, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/Sorts.ts, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap, src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx, src/services/Api.ts, src/types/IstioObjects.ts
Adding validation status to overview page.
Needs backend PR: https://github.com/kiali/kiali/pull/1932
https://github.com/kiali/kiali/issues/1556
=> Adding validation status to Overview page

src/pages/Graph/SummaryPanelEdge.tsx, src/pages/Graph/SummaryPanelGroup.tsx, src/pages/Graph/SummaryPanelNode.tsx
- no need for the null markers after the fixes for #1933.  And those metric fields should never be null.
Fixes : https://github.com/kiali/kiali/issues/1956
=> remove null markers

src/components/Refresh/Refresh.tsx
Fixes https://github.com/kiali/kiali/issues/1974
=> Fix regression: properly set lastRefreshAt

package.json, src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/IstioMetrics.tsx, yarn.lock
Fixing several vulns:
- https://app.snyk.io/vuln/SNYK-JS-HANDLEBARS-534478
- https://app.snyk.io/vuln/SNYK-JS-HANDLEBARS-480388
- https://app.snyk.io/vuln/SNYK-JS-HANDLEBARS-469063
- https://app.snyk.io/vuln/SNYK-JS-HANDLEBARS-534988
- https://app.snyk.io/vuln/SNYK-JS-MIXINDEEP-450212
- https://app.snyk.io/vuln/SNYK-JS-SETVALUE-450213
- https://app.snyk.io/vuln/SNYK-JS-ESLINTUTILS-460220
=> Update dependencies (rm yarn.lock)

src/components/IstioWizards/IstioWizard.tsx
=> Reset state when Wizard is closed

src/components/Nav/Page/RenderComponentScroll.tsx, src/components/Validations/ValidationList.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadServices.tsx
Fixes kiali/kiali#1989
Fixes kiali/kiali#1977
=> Fix missing icon and wrap phase status

package.json, src/components/Metrics/IstioMetrics.tsx, src/config/Config.ts, src/services/Api.ts, src/types/Tracing.ts, yarn.lock
- Fetch service spans
- Use new k-charted overlay feature
- Rolling-window for refreshes
Part of https://github.com/kiali/kiali/issues/1854
Pic:
Needs k-charted: https://github.com/kiali/k-charted/pull/59
Needs backend: https://github.com/kiali/kiali/pull/1994
=> Traces (spans) in metrics

package.json, yarn.lock
Update the latest `react-scripts` to fix synk vulernability
fixes https://github.com/kiali/kiali/issues/2024
yes
No
=> Update react-scripts from 3.2.0 to 3.3.0 to fix Snyk vulnerability

src/components/VirtualList/Config.ts, src/pages/IstioConfigList/FiltersAndSorts.ts, src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts, src/types/IstioConfigDetails.ts, src/types/IstioConfigList.ts, src/types/IstioObjects.ts, src/utils/IstioConfigUtils.ts
Adding AuthorizationPolcies CRD to IstioConfig section
Needs https://github.com/kiali/kiali/pull/2028
https://github.com/kiali/kiali/issues/1344
=> Add Support to AuthorizationPolicies CRD

src/components/VirtualList/Renderers.tsx, src/pages/Overview/OverviewPage.tsx
Fixes https://github.com/kiali/kiali/issues/2014
=> Link from overview page, service page and istio config to validation page

src/components/About/AboutUIModal.tsx, src/types/StatusState.ts
fixes https://github.com/kiali/kiali/issues/2054
report the kiali container version
related server PR: https://github.com/kiali/kiali/pull/2055
=> show the new container version in the about box

src/pages/IstioConfigList/FiltersAndSorts.ts
Sorting all the istio types in the IstioConfig filter dropdown
https://github.com/kiali/kiali-ui/pull/1582#issuecomment-567601410
** Screencapture **
=> Sort Istio Type Selector alphabetically

src/pages/Graph/GraphHelpTour.ts, src/pages/Graph/GraphPage.tsx
Closes: https://github.com/kiali/kiali/issues/1750
=> Adds a tour step for the contextual menu on the graph

yarn.lock
Fix yarn.lock file for prop-types removal via: https://github.com/kiali/kiali-ui/pull/1592
=> Fix yarn.lock for prop-types.

package.json, src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/Helper.ts, src/components/Metrics/IstioMetrics.tsx, yarn.lock
Fixes https://github.com/kiali/k-charted/issues/15
Requires https://github.com/kiali/k-charted/pull/72
Screenshot:
=> Display charts on the whole requested time window

src/components/Nav/Page/RenderComponentScroll.tsx, src/pages/Overview/OverviewPage.tsx
Fixes kiali/kiali#2094
This only fixes the Overview pages, list pages will be fixed in a following PR.
=> Fix scroll in Overview page

src/components/Filters/CommonFilters.ts, src/components/Filters/StatefulFilters.tsx, src/pages/IstioConfigList/FiltersAndSorts.ts, src/pages/Overview/Filters.ts, src/pages/WorkloadList/FiltersAndSorts.ts, src/types/Filters.ts
Move Workload type filter selector to typeahead.
=> Move Workload type filter to typeahead selector

src/app/AuthenticationController.tsx
Require : https://github.com/kiali/kiali/pull/2118
Fix: https://github.com/kiali/kiali/issues/2117
=> Traces tab should be visible just with InClusterURL configured

src/pages/ServiceDetails/ServiceDetailsPage.tsx
Fix https://github.com/kiali/kiali/issues/2120
=> Update traces when refresh

src/pages/ServiceDetails/ServiceDetailsPage.tsx
Fix https://github.com/kiali/kiali/issues/2120
=> [Traces] Screen not refreshed as expected

src/pages/AppList/FiltersAndSorts.ts, src/pages/IstioConfigList/FiltersAndSorts.ts, src/pages/Overview/Filters.ts, src/pages/ServiceList/FiltersAndSorts.ts, src/pages/ServiceList/__tests__/ServiceListComponent.test.ts, src/pages/WorkloadList/FiltersAndSorts.ts
=> Backporting: Undo filter renaming (#1603)

src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
Fixing the regression found: https://github.com/kiali/kiali/pull/2124#pullrequestreview-345826470
=> Showing weight validation on VSs in IstioDetails page

package.json
see https://github.com/kiali/kiali/issues/2141
=> remove postinstall from package.json

package.json
see https://github.com/kiali/kiali/issues/2141
=> [backport] remove postinstall from package.json

src/components/PfSpinner.tsx
Fix https://github.com/kiali/kiali/issues/1978
Id added "loading_kiali_spinner"
=> Add id to the loading spinner

src/app/AuthenticationController.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx
jaeger error didn't appear in MessageCenter.
Now we can see the message related with the integration.
Fix: https://github.com/kiali/kiali/issues/2155
=> Service Details load Error when Jaeger is configured wrongly

package.json, yarn.lock
to include bug fix https://github.com/kiali/kiali/issues/2083
I think should be backported to 1.12
=> Bump k-charted 0.4.3

package.json, yarn.lock
to include bug fix https://github.com/kiali/kiali/issues/2083
Backport of https://github.com/kiali/kiali-ui/pull/1639
=> [v1.12] Bump k-charted 0.4.3

src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/IstioMetrics.tsx, src/components/Metrics/SpanOverlay.ts
- Check integration flag to know if Jaeger should be fetched
- Do not repeat consecutive errors
Fixes https://github.com/kiali/kiali/issues/2187 (part-of)
=> Improved error handling in Spans overlay

package.json, src/app/History.ts, src/components/Metrics/IstioMetrics.tsx, src/components/Metrics/SpanOverlay.ts, src/pages/ServiceDetails/ServiceTraces.tsx, yarn.lock
Fix https://github.com/kiali/kiali/issues/2107
Require K-charted dump
=> [Metrics] Clicking on a span should lead to Traces view

src/actions/__tests__/JaegerActions.test.ts, src/components/JaegerIntegration/JaegerResults/SpanTable.tsx, src/reducers/JaegerState.ts, src/reducers/__tests__/JaegerStateReducer.test.ts, src/types/JaegerInfo.ts
Require https://github.com/kiali/kiali/pull/2225
Fix https://github.com/kiali/kiali/issues/2230
=> Add a whitelist for services in istio-system

src/components/VirtualList/VirtualList.tsx, src/pages/AppList/AppListComponent.tsx, src/pages/IstioConfigList/IstioConfigListComponent.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/WorkloadList/WorkloadListComponent.tsx
Fix https://github.com/kiali/kiali/issues/1674
=> Improve empty table in list views

src/components/VirtualList/VirtualList.tsx
Fix https://github.com/kiali/kiali/issues/2259
=> Fix Empty table in lists - Filters are gone

README.adoc
Adds a link to a video detailing the step by step installation of the kiali-ui dev environment. Should be good for on-boarding and attracting community.
=> Add a link the kiali-ui development setup video.

src/pages/ServiceDetails/ServiceTraces.tsx
Fix https://github.com/kiali/kiali/issues/2245
=> Smaller screen Traces tab layout issues

src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/EmptyGraphLayout.tsx, src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/AppDetails/AppInfo.tsx, src/pages/AppDetails/AppInfo/AppDescription.tsx, src/pages/Graph/GraphPage.tsx, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDescription.test.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap, src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx, src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx, src/pages/WorkloadDetails/WorkloadInfo/__tests__/WorkloadDescription.test.tsx, src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
Initial implementation of mini-graph on detail pages.
Related to kiali/kiali#1960
=> Implement mini-graph on detail pages

src/components/IstioWizards/Slider/Slider.tsx
Fix https://github.com/kiali/kiali/issues/2475
=> Percent in Slider in IstioWizard so small

src/pages/Graph/SummaryPanelCommon.tsx, src/pages/Graph/SummaryPanelNode.tsx
Fixes https://github.com/kiali/kiali/issues/2498
Metrics are now visible in summary panel:
Note: for testing you can use this setup: https://github.com/ia3andy/game-of-stacks/blob/master/ISTIO-QUICK-START.md
=> Allow root nodes to show metrics to other namespaces

src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx, src/components/VirtualList/VirtualList.tsx
Fixes https://github.com/kiali/kiali/issues/2471
After:
=> Don't rely on path value for "Istio Config" title.

src/components/Filters/LabelFilter.tsx, src/components/Filters/StatefulFilters.tsx, src/components/VirtualList/Renderers.tsx, src/pages/AppList/AppListClass.tsx, src/pages/AppList/FiltersAndSorts.ts, src/pages/Overview/Filters.ts, src/pages/Overview/NamespaceInfo.ts, src/pages/Overview/OverviewPage.tsx, src/pages/ServiceList/FiltersAndSorts.ts, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/WorkloadList/FiltersAndSorts.ts, src/pages/WorkloadList/WorkloadListComponent.tsx, src/types/AppList.ts, src/types/Filters.ts, src/types/Namespace.ts, src/types/ServiceList.ts, src/types/Workload.ts
Related with https://github.com/kiali/kiali/issues/2233
Fix https://github.com/kiali/kiali/issues/1511 & https://github.com/kiali/kiali/issues/1522
Require https://github.com/kiali/kiali/pull/2496
Added Tooltip in app and version label validation with the value
Added filter by label
=> Add new filter in list by label

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/ServiceLink.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/__tests__/ServiceLink.test.tsx
Backport of https://github.com/kiali/kiali-ui/pull/1706
=> Fix service link into Istio Object details page

package.json, src/components/Time/Replay.tsx, yarn.lock
Update version of react-datepicker to pick up bug fixes and dep updates.   Includes a minor UX tweak to replay dropdown.
Epic: kiali/kiali#2279
=> update react-datepicker (snyk recommended)

package.json, src/components/SummaryPanel/RateChart.tsx, yarn.lock
This upgrade brings fixes for https://github.com/kiali/kiali/issues/2527 and https://github.com/kiali/kiali/issues/2525
=> Update to k-charted 0.5.0

src/pages/Graph/SummaryPanelGraph.tsx
Fix for https://issues.redhat.com/browse/OSSM-175
=> Graph side panel fix

src/components/Filters/LabelFilter.tsx, src/helpers/LabelFilterHelper.ts, src/pages/AppList/FiltersAndSorts.ts, src/pages/Overview/Filters.ts, src/pages/ServiceList/FiltersAndSorts.ts, src/pages/WorkloadList/FiltersAndSorts.ts
Fix https://github.com/kiali/kiali/issues/2550
Go to workload list and try to filter by label with "app=reviews version=v2,v3"
=> Fix duplicate results when filter by labels

src/pages/Graph/SummaryPanelEdge.tsx
Fixes https://github.com/kiali/kiali/issues/2497
=> Allow sparkline metrics on edge to service entries

src/components/Filters/StatefulFilters.tsx, src/components/Label/Labels.tsx, src/components/ToolbarDropdown/ToolbarDropdown.tsx, src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap, src/components/VirtualList/Config.ts, src/components/VirtualList/Renderers.tsx, src/components/VirtualList/VirtualItem.tsx, src/components/VirtualList/VirtualList.tsx, src/helpers/TracesHelper.ts, src/pages/AppList/FiltersAndSorts.ts, src/pages/Overview/Filters.ts, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/OverviewToolbar.tsx, src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap, src/pages/ServiceList/FiltersAndSorts.ts, src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx, src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap, src/pages/WorkloadList/FiltersAndSorts.ts, src/types/Filters.ts
Fix https://github.com/kiali/kiali/issues/2547
Now in workloads we remove the label validation and we add the warning in details
=> Show labels ui

src/components/CytoscapeGraph/graphs/GraphStyles.ts
Backport ui crash fix to v1.15.
=> [v1.15] Fix graph error when enabling response time edges in some cases. (#1715)

src/components/VirtualList/Renderers.tsx, src/pages/ServiceList/ServiceListComponent.tsx
After replace of '"' by ':' I forgot change it in the light feature
=> Fix lighted when label is equal a value

src/pages/AppList/AppListComponent.tsx, src/pages/ServiceList/ServiceListComponent.tsx, src/pages/WorkloadList/WorkloadListComponent.tsx, src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListContainer.tsx
@lucasponce I think this is what you're looking for across the list pages.
Fixes https://github.com/kiali/kiali/issues/2628
=> Add timer refresh to list pages

src/pages/ServiceDetails/ServiceDetailsPage.tsx
Fix https://github.com/kiali/kiali/issues/2221
Incremental Refresh like spans for traces
=> Traces page: incremental refresh

src/components/JaegerIntegration/RouteHelper.ts, src/pages/ServiceDetails/ServiceDetailsPage.tsx
Fix https://github.com/kiali/kiali/issues/2221
=> Incremental refresh in jaeger traces fix

src/pages/Graph/SummaryPanelNode.tsx
Fixes https://github.com/kiali/kiali/issues/2673
=> Don't offer kebab navigation in summary panel for inaccessible nodes.

src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx, src/components/Nav/Page/RenderHeader.tsx, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/AppDetails/AppInfo/AppDescription.tsx, src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx, src/pages/Overview/Filters.ts, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/__tests__/OverviewPage.test.tsx, src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap, src/pages/ServiceDetails/ServiceDetailsPage.tsx, src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx, src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap, src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentDetailsPage.tsx, src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListContainer.tsx, src/pages/extensions/threescale/ThreeScaleHandlerDetails/ThreeScaleHandlerDetailsPage.tsx, src/pages/extensions/threescale/ThreeScaleHandlerList/ThreeScaleHandlerListPage.tsx
Fixes https://github.com/kiali/kiali/issues/2616
Fixes https://github.com/kiali/kiali/issues/2635
Fixes https://github.com/kiali/kiali/issues/2521
Fixes https://github.com/kiali/kiali/issues/2648
All steps and rationale for these CSS changes are described and documented under https://github.com/kiali/kiali/issues/2616
In short, early optimization in UI layer may create easily CSS problems. As soon as someone wants to put in a single component something that is used in several locations and at the end that shared component may have different styles, it can create easily problems that are hard to fix.
This PR has no intention to refactor the UI, don't propose "hey, this can be put together in a single component", all these problems started with a comment like that :-).
A little bit of …
=> Fix several CSS issues

src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/IstioMetrics.tsx, src/components/Metrics/SpanOverlay.ts
Fixes https://github.com/kiali/kiali/issues/2705
=> Custom time selection not ignored anymore while fetching spans

package.json, src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/Helper.ts, src/components/Metrics/__tests__/IstioMetrics.test.tsx, src/services/__tests__/ApiMethods.test.tsx.ts, yarn.lock
Depends on https://github.com/kiali/k-charted/pull/87 (merged) and https://github.com/kiali/kiali/pull/2643 (the backend PR)
Fixes https://github.com/kiali/kiali/issues/1778
=> Allow multiple metrics per chart

package.json, yarn.lock
Remove unnecessary deps:
- react-floater
- react-iframe
Part of: https://github.com/kiali/kiali/issues/2600
=> Remove unnecessary deps

src/pages/Graph/GraphPage.tsx, src/types/Graph.ts
Just ugh.
https://github.com/kiali/kiali/issues/2721
=> Fix summary panel sparkline regression

src/pages/Graph/GraphToolbar/GraphFind.tsx
Further attempts to eliminate graph drift on refresh when using graph hide. Perform a fit unless there is a significant zoom/pan change. Also, run the layout twice, it seems to help.
Possible fix for https://github.com/kiali/kiali/issues/2514
=> Further attempts to eliminate graph drift on refresh when using graph hide

src/components/VirtualList/Config.ts, src/pages/IstioConfigList/FiltersAndSorts.ts, src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts, src/types/IstioConfigDetails.ts, src/types/IstioConfigList.ts, src/types/IstioObjects.ts, src/utils/IstioConfigUtils.ts
Adding PeerAuthentication to IstioConfig section.
Needs https://github.com/kiali/kiali/pull/2738 / Part of #2520 
Backend https://github.com/kiali/kiali/pull/2739
=> Adding support to PeerAuthentication to IstioConfig section

src/components/VirtualList/Config.ts, src/pages/IstioConfigList/FiltersAndSorts.ts, src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts, src/types/IstioConfigDetails.ts, src/types/IstioConfigList.ts, src/types/IstioObjects.ts, src/utils/IstioConfigUtils.ts
UI counterpart of
https://github.com/kiali/kiali/pull/2746
Fixes https://github.com/kiali/kiali/issues/2737
=> Add support for WorkloadEntry and RequestAuthentication

src/pages/Overview/Filters.ts, src/types/Filters.ts
Fix https://github.com/kiali/kiali/issues/2559
=> Filters for different kind of labels are mixed up

src/components/Validations/ValidationSummary.tsx, src/components/Validations/__tests__/ValidationSummary.test.tsx, src/components/Validations/__tests__/__snapshots__/ValidationSummary.test.tsx.snap
Fixes https://github.com/kiali/kiali/issues/2773
=> Show validation icon even with 1 object

src/pages/extensions/iter8/Iter8ExperimentDetails/CriteriaInfoDescription.tsx, src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentInfoDescription.tsx
A minor CSS change to adjust the margins:
=> Adjust CSS in Iter8 details

src/pages/Overview/OverviewPage.tsx
=> Adjust CSS align on overview list view

src/pages/Overview/OverviewPage.tsx
Minor CSS adjust in overview page:
=> [v1.18]Adjust CSS align on overview list view

src/components/IstioWizards/IstioWizardActions.ts, src/components/MessageCenter/AlertDrawerMessage.tsx, src/helpers/ValidationHelpers.ts, src/pages/IstioConfigNew/AuthorizationPolicyForm.tsx, src/pages/IstioConfigNew/AuthorizationPolicyForm/From/SourceBuilder.tsx, src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleList.tsx, src/pages/IstioConfigNew/AuthorizationPolicyForm/To/OperationBuilder.tsx, src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionBuilder.tsx, src/pages/IstioConfigNew/GatewayForm.tsx, src/pages/IstioConfigNew/IstioConfigNewPage.tsx, src/pages/IstioConfigNew/PeerAuthenticationForm.tsx, src/pages/IstioConfigNew/RequestAuthenticationForm.tsx, src/pages/IstioConfigNew/RequestAuthorizationForm/JwtRuleBuilder.tsx, src/pages/IstioConfigNew/RequestAuthorizationForm/JwtRuleList.tsx, src/pages/IstioConfigNew/SidecarForm.tsx, src/pages/extensions/threescale/ThreeScaleHandlerDetails/ThreeScaleHandlerDetailsPage.tsx, src/types/IstioObjects.ts, src/utils/IstioConfigUtils.ts, src/utils/__tests__/IstioConfigUtils.test.ts
Backport of #1804 to v1.18 branch.
@hhovsepy please, let me know if everything looks good, I needed to resolve some conflict cherry-picking and not 100% sure if it's all clean.
=> [v1.18] Add {Peer,Request}Authentication objects to Create Istio Config

src/components/Filters/CommonFilters.ts, src/components/Filters/FilterStyles.tsx, src/components/Filters/LabelFilter.tsx, src/components/Filters/StatefulFilters.tsx, src/components/VirtualList/Config.ts, src/components/VirtualList/Renderers.tsx, src/components/VirtualList/VirtualItem.tsx, src/components/VirtualList/VirtualList.tsx
Fixes https://github.com/kiali/kiali/issues/2735
I need to do it for OverviewPage too but I want to sent the PR for start reviewing it.
What do you think @jotak ? I didn't see another way to do it than use refs.
=> Labels filtering: click on labels to filter

src/components/VirtualList/Config.ts, src/pages/IstioConfigList/FiltersAndSorts.ts, src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts, src/types/IstioConfigDetails.ts, src/types/IstioConfigList.ts, src/types/IstioObjects.ts, src/utils/IstioConfigUtils.ts
Backport of https://github.com/kiali/kiali-ui/pull/1813
=> [v1.18]Add EnvoyFilter,AttributeManifest,HttpApiSpec{Binding} (#1813)

package.json, yarn.lock
@mattmahoneyrh Not sure if you want to smoke this before or after the prod build.  Approve when ready.
=> Maistra-1403 CVE

src/pages/Overview/OverviewCardContentCompact.tsx
Fix https://github.com/kiali/kiali/issues/2867
=> Idle status objects missing on Overview's Compact View

src/components/Filters/StatefulFilters.tsx, src/components/VirtualList/Renderers.tsx, src/components/VirtualList/VirtualItem.tsx, src/components/VirtualList/VirtualList.tsx, src/pages/Overview/OverviewPage.tsx, src/pages/Overview/OverviewToolbar.tsx, src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
Fix https://github.com/kiali/kiali/issues/2904
And some warnings with keys
=> Click on namespace labels crashes

src/components/FilterList/FilterHelper.ts
Fix https://github.com/kiali/kiali/issues/2920
=> Label operation - Refresh resets the value

src/components/Nav/Navigation.tsx, src/components/Nav/__tests__/Navigation.test.tsx, src/components/Nav/__tests__/RenderPage.test.tsx, src/styles/_overrides.scss
Fix https://github.com/kiali/kiali/issues/2946
=> In kiosk mode，the main header should not be shown

src/components/JaegerIntegration/ServiceTraces.tsx, src/config/Config.ts, src/services/Api.ts
Fixes https://github.com/kiali/kiali/issues/2970
Backend PR: https://github.com/kiali/kiali/pull/2971
=> Remove namespace/service path params for single trace

package.json, src/components/MetricsOptions/MetricsSettingsDropdown.tsx, yarn.lock
epic: kiali/kiali#2600
snyk security report update
=> Update lodash due to Snyk security report

src/assets/img/legend/aggregate.svg, src/components/CytoscapeGraph/graphs/GraphStyles.ts
closes https://github.com/kiali/kiali/issues/2856
Now:
=> change op nodes from star to round-pentagon, and update legend

src/pages/AppDetails/AppDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Fixes https://github.com/kiali/kiali/issues/2996
=> Do not show tabs list until async data is fetched

src/pages/Graph/GraphToolbar/GraphFind.tsx
Fixes https://github.com/kiali/kiali/issues/2979
=> Fix issue with suppressed error message

package.json, src/components/MetricsOptions/MetricsSettingsDropdown.tsx, yarn.lock
CVE-2020-8302
https://issues.redhat.com/browse/MAISTRA-1664
=> Update lodash due to Snyk security report (#1847)

src/components/CytoscapeGraph/graphs/GraphStyles.ts
Related to https://github.com/kiali/kiali/issues/2999
See https://github.com/kiali/kiali/pull/3004#pullrequestreview-453581881
=> Show namespace in ServiceEntry label, when appropriate

src/components/CytoscapeGraph/graphs/GraphStyles.ts
Server PR: https://github.com/kiali/kiali/pull/3038
https://github.com/kiali/kiali/issues/2999
=> [v1.18 backport] Show namespace in ServiceEntry label, when appropriate (#1857)

src/pages/Graph/SummaryPanelNodeTraces.tsx
=> Graph traces list: add a separate refresh button

src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
use PF4 guideline and make it like graph find/hide.
Fixes https://github.com/kiali/kiali/issues/2973
=> Don't use message center alerts for regex errors

src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCreatePage.tsx
@jadeyliu939, I've proposed some changes in the Iter8 form to adjust with the patterns used in the Istio Config forms.
Changes:
- Titles for tables.
- Conditional rendering used with switches.
- Align nested forms.
- Refine some wording to use same style in other forms.
Screenshots:
Expanded Traffic Control:
Expended Optional Host/Gateway:
Some examples of same style used in Istio Config:
It shouldn't change the feature, let me know what do you think.
=> Adjust Iter8 form to Istio Config forms

package.json, src/components/Metrics/Helper.ts, src/components/MetricsOptions/MetricsSettings.ts, src/components/MetricsOptions/MetricsSettingsDropdown.tsx, yarn.lock
Fixes https://github.com/kiali/kiali/issues/3047
Requires k-charted PR https://github.com/kiali/k-charted/pull/108
Backend: https://github.com/kiali/kiali/pull/3078
=> Bump k-charted, implement single-selection on labels in dashboards

src/pages/AppDetails/AppDetailsPage.tsx
Fixes https://github.com/kiali/kiali/issues/3080
=> Fix broken tabs selection in Application details

src/components/BreadcrumbView/BreadcrumbView.tsx
Fixes https://github.com/kiali/kiali/issues/2960
=> Fix regression on Adapter/Template breadcrumb

src/pages/Login/LoginPage.tsx, src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
Fixes https://github.com/kiali/kiali/issues/3101
=> Align login text with website.

package.json, yarn.lock
Update to the latest lodash version for CVE patch.
=> Bump Lodash version.

src/app/StartupInitializer.tsx, src/components/SessionTimeout/SessionTimeout.tsx, src/config/AuthenticationConfig.ts, src/pages/Login/LoginPage.tsx, src/pages/Login/__tests__/LoginPage.test.tsx, src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap, src/reducers/LoginState.ts, src/services/Login.ts, src/types/Auth.ts
https://github.com/kiali/kiali/issues/3017
=> remove login and ldap auth strategy

src/components/IstioWizards/WizardActions.ts, src/components/IstioWizards/WorkloadWizardDropdown.tsx, src/config/ServerConfig.ts, src/pages/Overview/OverviewNamespaceActions.tsx, src/pages/Overview/OverviewPage.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx, src/types/ServerConfig.ts, src/types/Workload.ts
Fixes https://github.com/kiali/kiali/issues/3125
Fixes https://github.com/kiali/kiali/issues/3124
Requires https://github.com/kiali/kiali/pull/3130
@hhovsepy I've introduced a explicit "Disabled" vs "Removed" as this opens the possibility to annotate workloads individually.
Lucas
=> Enable/Disable/Remove Istio Auto Injection on Namespace/Workload

src/pages/Graph/GraphToolbar/GraphSettings.tsx
Related: https://github.com/kiali/kiali/issues/3152
=> Add info tooltip to Graph Security Display option.

src/components/Filters/StatefulFilters.tsx
Fixes https://github.com/kiali/kiali/issues/3156
=> Empty textinput when adding a filter

src/pages/Graph/GraphToolbar/GraphFind.tsx, src/utils/AutoComplete.ts
Done analogous to CLIs, Tab key will loop through choices that start with the current input.
Fixes https://github.com/kiali/kiali/issues/1411
=> Add simple AutoComplete for graph find/hide

src/pages/Graph/GraphHelpFind.tsx, src/pages/Graph/GraphToolbar/GraphFind.tsx, src/utils/AutoComplete.ts
- fix issue when there are no completions
- support completion with ! operator
- support completion of more than just the first operand
- update help
Related to https://github.com/kiali/kiali/issues/1411
=> Improve graph find/hide autocomplete

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Fixes https://github.com/kiali/kiali/issues/2250
=> Add Galley error messages when updating an istio object

src/components/JaegerIntegration/TracesComponent.tsx, src/components/JaegerIntegration/TracesFetcher.ts, src/pages/AppDetails/AppDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/types/JaegerInfo.ts
Fixes https://github.com/kiali/kiali/issues/2710
Backend PR: https://github.com/kiali/kiali/pull/3177
=> Add traces tab to workload details

src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/IstioMetrics.tsx, src/components/Metrics/SpanOverlay.ts, src/config/Config.ts, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/services/Api.ts
Adding span correlation to workload metrics
Fixes https://github.com/kiali/kiali/issues/3175
Backend PR: https://github.com/kiali/kiali/pull/3200
=> Use workload/service endpoints while fetching spans

src/components/IstioConfigSubList/IstioConfigSubList.tsx, src/components/IstioStatus/IstioStatusList.tsx, src/components/IstioStatus/__tests__/__snapshots__/IstioStatusList.test.tsx.snap
- Typo "config found found"
- Some linter warnings on missing 'key'
=> [Minor] Typo and lint fixes

src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/JaegerIntegration/JaegerResults/JaegerTraceTitle.tsx, src/components/JaegerIntegration/JaegerResults/TraceDetails.tsx, src/components/JaegerIntegration/TracesComponent.tsx
Fixes https://github.com/kiali/kiali/issues/2842 (and part of https://github.com/kiali/kiali/issues/3095)
Note: as part of https://github.com/kiali/kiali/issues/3095 it is possible that the design / placement of this link will soon change.
Comments are welcome for readjustments of the whole table.
=> Link graph from trace details, with trace overlay

src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx, src/components/IstioWizards/ServiceWizard.tsx, src/components/IstioWizards/ServiceWizardDropdown.tsx, src/components/IstioWizards/WizardActions.ts, src/pages/Graph/SummaryPanelGroup.tsx, src/pages/Graph/SummaryPanelNode.tsx, src/pages/Overview/OverviewNamespaceActions.tsx, src/pages/Overview/OverviewPage.tsx, src/styles/_menu.scss, src/styles/index.scss
Fixes https://github.com/kiali/kiali/issues/3217
Overview page:
Graph:
cc @lwrigh
=> Group Show Actions

package.json, yarn.lock
See changes: https://github.com/kiali/k-charted/releases/tag/v0.6.2
=> Bump k-charted 0.6.2

src/components/JaegerIntegration/JaegerScatter.tsx, src/components/JaegerIntegration/TracesComponent.tsx
Make it a little darker
Part of https://github.com/kiali/kiali/issues/3095
=> Visualize selected trace in scatter chart

package.json, src/components/IstioActions/IstioActionsButtons.tsx, src/components/MessageCenter/MessageCenter.tsx, src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleOverview.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceOverview.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx, src/pages/IstioConfigDetails/ValidationReferences.tsx, src/types/AceValidations.ts, src/types/IstioConfigDetails.ts, src/types/__tests__/AceValidations.test.ts, src/utils/AlertUtils.ts, src/utils/IstioValidationUtils.ts, yarn.lock
Fixes https://github.com/kiali/kiali/issues/3196
Please @xeviknal @hhovsepy try to make extra tests on validations, I've bumped the ace editor dependency (it was pretty old) and I did some smoke tests but I'd like to confirm that nothing is broken with the features around the editor.
This is not a bug, but also thinking loud if we may want to cherrypick this to 1.24 branch to avoid future problems due the old editor dependency.
=> Refactor Istio Details: Bump Editor + Overview Drawer

package.json, src/components/IstioActions/IstioActionsButtons.tsx, src/components/MessageCenter/MessageCenter.tsx, src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleOverview.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceOverview.tsx, src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx, src/pages/IstioConfigDetails/ValidationReferences.tsx, src/types/AceValidations.ts, src/types/IstioConfigDetails.ts, src/types/__tests__/AceValidations.test.ts, src/utils/AlertUtils.ts, src/utils/IstioValidationUtils.ts, yarn.lock
Backport of #1932 into v1.24 branch.
=> [1.24] Refactor Istio Details: Bump Editor + Overview Drawer (#1932)

src/components/BreadcrumbView/BreadcrumbView.tsx, src/components/Filters/StatefulFilters.tsx
Fixes https://github.com/kiali/kiali/issues/3230
=> Fix reset filters on breadcrumb

src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx, src/pages/WorkloadDetails/WorkloadInfo/WorkloadServices.tsx
=> [v1.24] Fix empty layout for pods/services

src/components/BreadcrumbView/BreadcrumbView.tsx, src/components/Filters/StatefulFilters.tsx
=> [v1.24] Fix reset filters on breadcrumb

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Fixes https://github.com/kiali/kiali/issues/3240
=> Fix z-index on Istio actions

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
=> [v1.24] Fix z-index on Istio actions (#1940)

src/components/IstioWizards/WizardActions.ts, src/pages/IstioConfigNew/AuthorizationPolicyForm.tsx
Fixes https://github.com/kiali/kiali/issues/2695
It requires backend https://github.com/kiali/kiali/pull/3243
=> Fix AuthorizationPolicy DENYALL and ALLOWALL

src/components/IstioWizards/WizardActions.ts, src/pages/IstioConfigNew/AuthorizationPolicyForm.tsx
=> [v1.24] Fix AuthorizationPolicy DENYALL and ALLOWALL

src/app/InitializingScreen.tsx, src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx, src/components/Filters/StatefulFilters.tsx, src/components/Label/Labels.tsx, src/components/Label/__tests__/__snapshots__/Labels.test.tsx.snap
Fixes https://github.com/kiali/kiali/issues/3267
```
Note that the development build is not optimized.
To create a production build, use yarn build.
Compiling...
Files successfully emitted, waiting for typecheck results...
Compiled successfully!
You can now view @kiali/kiali-ui in the browser.
Local:            http://localhost:3000
On Your Network:  http://192.168.1.145:3000
Note that the development build is not optimized.
To create a production build, use yarn build.
```
=> Fix yarn start warnings

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx, src/types/IstioObjects.ts
cherry-pick of https://github.com/kiali/kiali-ui/pull/1949
=> [v1.24] IstioConfig: ValidationMessages are not mandator

src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/IstioMetrics.tsx, src/components/Metrics/SpanOverlay.ts
Fixes https://github.com/kiali/kiali/issues/3284
=> Handle dashboards updated (tabs switched)

src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/IstioMetrics.tsx, src/components/Metrics/SpanOverlay.ts
Fixes https://github.com/kiali/kiali/issues/3284
(backporting https://github.com/kiali/kiali-ui/pull/1956 )
=> [1.24] Handle dashboards updated (tabs switched)

src/components/IstioWizards/RequestRouting/Rules.tsx, src/components/IstioWizards/ServiceWizard.tsx
=> [v1.24] Sync VS/GW hosts on new GW (#1960)

src/actions/JaegerThunkActions.ts, src/components/JaegerIntegration/TracesComponent.tsx
Fixes https://github.com/kiali/kiali/issues/3299
Also: when the trace ID doesn't exist, remove it from URL
=> Fix empty trace tabs with no trace

src/components/FilterList/FilterHelper.ts, src/components/Filters/StatefulFilters.tsx, src/components/JaegerIntegration/JaegerResults/Filters.ts, src/components/JaegerIntegration/JaegerResults/SpanDetails.tsx, src/components/JaegerIntegration/JaegerResults/SpanTable.tsx, src/components/JaegerIntegration/JaegerResults/SpanTableItem.ts, src/components/JaegerIntegration/JaegerResults/TraceDetails.tsx, src/components/JaegerIntegration/JaegerResults/TraceLabels.tsx, src/pages/Overview/Filters.ts, src/pages/Overview/OverviewPage.tsx, src/types/Filters.ts
Fixes https://github.com/kiali/kiali/issues/3278
Add sorting & filtering capabilities on the spans table.
reusing the StatefulFilters component
=> Trace details page, spans table: add filtering toolbar

src/components/CytoscapeGraph/CytoscapeGraphUtils.ts, src/pages/Graph/GraphToolbar/GraphSettings.tsx, src/pages/Graph/SummaryPanelEdge.tsx, src/store/Selectors/GraphData.ts, src/types/Graph.ts
Fixes https://github.com/kiali/kiali/issues/2939
=> Show Principals in edge side panel, when available.

src/components/JaegerIntegration/JaegerHelper.ts, src/components/JaegerIntegration/__tests__/JaegerHelper.test.ts
(but this still has flaws, see code comments)
(Kind of) fixes https://github.com/kiali/kiali/issues/3306
=> Try to disambiguate deployment-like and replicaset-like workload in spans

src/components/Filters/StatefulFilters.tsx
Fixes https://github.com/kiali/kiali/issues/3334
=> Fix filters padding on overview page

src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListContainer.tsx
Distinguish traffic to baseline or candidate.
Currently, when iter8 experiment completes, the phase is always green check-mark regardless it it to baseline or candidate. This PR is to distinguish if the winner is baseline, then the phase is red check-mark. If winner is candidate, the phase is green check-mark
=> Iter8 - Update completion Icon based on traffic direction ( baseline or candidate)

package.json, yarn.lock
This fixes https://github.com/kiali/kiali/issues/3307
=> Bump k-charted to 0.6.3

src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts, src/components/CytoscapeGraph/graphs/GraphHighlighter.ts, src/components/CytoscapeGraph/graphs/GraphStyles.ts
See issue for video of this change.
Fixes https://github.com/kiali/kiali/issues/3349
=> Stop animation on hovered edge so a user can easily read the label

src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Also
- Fix issue when pod had no app container
- Fix issue when app container had no version label
- and use configured version label name
https://github.com/kiali/kiali/issues/3388
=> Fix pod logs issue when pod had no proxy

src/components/Filters/StatefulFilters.tsx, src/components/Filters/__tests__/StatefulFilters.test.tsx, src/components/VirtualList/Renderers.tsx
Fixes https://github.com/kiali/kiali/issues/3389
Backport: https://github.com/kiali/kiali-ui/pull/1996
=> Remove label filter by clicking on the label is not working

src/components/Filters/StatefulFilters.tsx, src/components/Filters/__tests__/StatefulFilters.test.tsx, src/components/VirtualList/Renderers.tsx
Fix https://github.com/kiali/kiali/issues/3389
=> [1.24] Remove label filter by clicking on the label is not working

src/components/Nav/Masthead/UserDropdown.tsx
Backport for https://github.com/kiali/kiali/issues/3313
related to https://github.com/kiali/kiali/issues/2905
=> [1.24] Make sure API logout completes before submitting openshift logout form

src/components/Nav/Masthead/UserDropdown.tsx
Backport for kiali/kiali#3313
related to kiali/kiali#2905
=> [1.12] Make sure API logout completes before submitting openshift logout form

src/components/HeatMap/HeatMap.tsx, src/components/JaegerIntegration/JaegerHelper.ts, src/components/JaegerIntegration/JaegerResults/SpanTable.tsx, src/components/JaegerIntegration/JaegerResults/SpanTableItem.ts, src/components/JaegerIntegration/JaegerResults/StatsComparison.tsx, src/components/JaegerIntegration/JaegerResults/TraceDetails.tsx, src/components/JaegerIntegration/TracesComponent.tsx, src/components/JaegerIntegration/TracesFetcher.ts, src/config/Config.ts, src/pages/Graph/SummaryPanelTraceDetails.tsx, src/services/Api.ts, src/types/Common.ts, src/types/Metrics.ts, src/types/MetricsOptions.ts
It uses new endpoint `api/stats/metrics`
Fixes https://github.com/kiali/kiali/issues/3293
Required backend PR: https://github.com/kiali/kiali/pull/3347
=> Compare metrics-based stats for every envoy spans, using a heatmap

src/components/HeatMap/HeatMap.tsx, src/components/JaegerIntegration/JaegerResults/TraceDetails.tsx
Fixes https://github.com/kiali/kiali/issues/3450
=> Reset old selected trace from local storage

src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
Fixes https://github.com/kiali/kiali/issues/3465
=> Fix guard null values in ContextMenu

src/pages/Graph/SummaryPanelNode.tsx
Fixes https://github.com/kiali/kiali/issues/3461
=> Do not try to fetch traces for a service entry

package.json, yarn.lock
https://issues.redhat.com/browse/MAISTRA-1706
- pin ajv version for CVE-2020-15366
https://issues.redhat.com/browse/MAISTRA-2012
- pin y18n version for CVE-CVE-2020-7774
=> [v1.12] CVE updates

package.json, yarn.lock
https://issues.redhat.com/browse/MAISTRA-1706
pin ajv version for CVE-2020-15366
https://issues.redhat.com/browse/MAISTRA-2012
pin y18n version for CVE-CVE-2020-7774
=> Applying 1.12 (SM 1.1) CVE fixes to master

src/components/Charts/ChartWithLegend.tsx, src/components/Charts/Container.tsx, src/components/Charts/CustomTooltip.tsx, src/components/HeatMap/HeatMap.tsx, src/components/JaegerIntegration/JaegerResults/FormattedTraceInfo.ts, src/components/JaegerIntegration/JaegerResults/TraceDetails.tsx, src/components/JaegerIntegration/JaegerScatter.tsx, src/components/JaegerIntegration/TraceTooltip.tsx
- New custom tooltip for traces
- Shows heatmap (compact mode) + summarized stats
- Show incomplete stats notification in trace details
Fixes https://github.com/kiali/kiali/issues/3487
=> Enhanced trace tooltip

.github/workflows/ci.yml
A github action to run CI: install/build/test. Similar to what Travis CI is doing today.
https://github.com/kiali/kiali/issues/3502
=> Add Github action to run install and run CI tests for PRs.

src/components/CytoscapeGraph/CytoscapeTrace.ts
Fixes https://github.com/kiali/kiali/issues/3572
**Before**
**After**
=> Fix service-type graph not showing service-to-service trace edges

package.json, yarn.lock
Fixes the ini version but adding it on the "resolution" package.json section.
This takes precended over https://github.com/kiali/kiali-ui/pull/2036
For QE:
- Just a simple regression test
=> Fix ini resolution dep

src/components/Envoy/EnvoyModal.tsx, src/components/Envoy/tables/BaseTable.tsx, src/components/Envoy/tables/ClusterTable.ts, src/components/Envoy/tables/ListenerTable.ts, src/components/Envoy/tables/RouteTable.ts, src/components/Filters/StatefulFilters.tsx
belongs to https://github.com/kiali/kiali/issues/3346
Adding filters to help explore the envoy dump tables for each pod.
=> Adding filters into envoy dump tables

src/app/History.ts, src/pages/Overview/OverviewPage.tsx
Fix https://github.com/kiali/kiali/issues/3272
=> Overview view should be "bookmarkable"

src/pages/Graph/GraphToolbar/GraphSettings.tsx
related to: https://github.com/kiali/kiali/issues/3611
=> Improve info tooltip for "Idle Nodes" graph display option.

src/components/CytoscapeGraph/graphs/GraphStyles.ts
Backport fix for Unknown node label in graph.
=> [v1.29] Fix issue with unknown node label

src/components/CytoscapeGraph/CytoscapeGraphUtils.ts, src/components/CytoscapeGraph/Layout/BoxLayout.ts
Backport for https://github.com/kiali/kiali/issues/3623
=> [v1.29] Fix BoxLayout issue 

src/types/__mocks__/Charts.mock.ts, src/utils/TimeSeriesUtils.ts, src/utils/__tests__/TimeSeriesUtils.test.ts
Add tests on TimeSeriesUtil
Fixes https://github.com/kiali/kiali/issues/3659
=> Metrics page: don't show labels with a single value in legend

src/components/CytoscapeGraph/CytoscapeGraph.tsx
Allow user to zoom by dragging a box overlay around an area of the graph.  Because we already allow panning via mouse-drag,
the user must drag while also pressing the shift or control button.
Fixes https://github.com/kiali/kiali/issues/3681
Before (wheel-zoom and pan):
After (drag-zoom):
=> Allow user to zoom by dragging a box overlay around an area of the graph

src/utils/ResponseFlags.ts
Update envoy response flags that we know about for the Flags tab in graph side-panel.
Closes https://github.com/kiali/kiali/issues/3685
=> Update envoy response flags that we know about

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Fixes https://github.com/kiali/kiali/issues/3600
=> Fold status+managedFields fields in yaml editor

src/components/Link/IstioConfigListLink.tsx, src/components/Link/ValidationSummaryLink.tsx, src/components/Link/__tests__/IstioConfigListLink.tsx, src/components/Link/__tests__/ValidationSummaryLink.tsx, src/components/Link/__tests__/__snapshots__/IstioConfigListLink.tsx.snap, src/components/Link/__tests__/__snapshots__/ValidationSummaryLink.tsx.snap, src/components/Validations/ValidationObjectSummary.tsx, src/components/VirtualList/Renderers.tsx, src/pages/Graph/SummaryPanelGraph.tsx, src/pages/Graph/SummaryPanelNamespaceBox.tsx, src/pages/Overview/OverviewPage.tsx
fixes https://github.com/kiali/kiali/issues/2218
=> Add links from Graph side panel validation status to istio config list

src/components/IstioStatus/IstioComponentStatus.tsx, src/components/IstioStatus/IstioStatus.tsx, src/components/IstioStatus/__tests__/IstioComponentStatus.test.tsx, src/components/IstioStatus/__tests__/IstioStatus.test.tsx, src/components/IstioStatus/__tests__/__snapshots__/IstioComponentStatus.test.tsx.snap, src/components/IstioStatus/__tests__/__snapshots__/IstioStatus.test.tsx.snap, src/types/IstioStatus.ts
needs backend end: https://github.com/kiali/kiali/pull/3766
=> Adding new istio component status: NotReady - replicas set to 0

src/components/JaegerIntegration/JaegerResults/SpanTable.tsx, src/components/JaegerIntegration/JaegerResults/SpanTableItem.tsx
Fix https://github.com/kiali/kiali/issues/3814
=> Span detail can't be open when navigating from Graph

src/components/MissingSidecar/MissingSidecar.tsx, src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
Fixes https://github.com/kiali/kiali/issues/3535
=> Add MissingSidecar tooltip

src/pages/Graph/GraphToolbar/GraphSettings.tsx, src/styles/DropdownStyles.ts
Fixes https://github.com/kiali/kiali/issues/3861
=> Fix annoying "blocked" pointer when hovering on graph settings dropdown.

src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleOverview.tsx
fixes https://github.com/kiali/kiali/issues/3818
=> Only show DR link to host when no checkers presents

src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx, src/components/Link/KialiPageLink.tsx, src/components/Nav/Masthead/Masthead.tsx, src/components/Nav/Navigation.tsx, src/config/ServerConfig.ts
Ensure serverConfig has proper defaults in case the server does not provide certain information.
Fixes https://github.com/kiali/kiali/issues/3913
=> Ensure serverConfig has proper defaults

src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx, src/components/Link/KialiPageLink.tsx, src/components/Nav/Masthead/Masthead.tsx, src/components/Nav/Navigation.tsx, src/config/ServerConfig.ts
BACKPORT to upstream 1.33 branch for https://github.com/kiali/kiali/issues/3913
=> [backport v1.33] Ensure serverConfig has proper defaults (#2129)

src/pages/Login/LoginPage.tsx
The UI wasn't showing the error messages passed in the URL by the OpenID provider. This make sure error messages from the IdP are displayed in the login page.
Also, when Kiali is using the authorization code flow, any error was being returned as a bare JSON in the browser. But back-end is having a behavioral change and will be doing a redirection with the error in an "openid-error" parameter. These changes will also show the error returned by kiali back-end in the login form.
Related back-end PR (soft-required): https://github.com/kiali/kiali/pull/3937
Related kiali/kiali#3574
=> Friendly error messages for OpenID

src/components/Details/DetailDescription.tsx, src/components/VirtualList/Config.ts, src/components/VirtualList/Renderers.tsx
Fixes https://github.com/kiali/kiali/issues/3958
Includes:
- Better handle of list on narrowed screens.
- "health" is aligned into the left column.
- Better treatment of "labels" and "details" columns, adding no wrapping on special cases, for better support of corner cases where a lot of population of labels are used.
- Remove redundant titles on details card [1]
[1] https://github.com/kiali/kiali-ui/pull/2122#issuecomment-827358907
It doesn't include https://github.com/kiali/kiali/issues/1404 that require special rebase and re-adjust as probably we may want to consolidate validations.
=> Adjust list/details layout and title

src/pages/IstioConfigNew/ServiceEntryForm.tsx
Fixes https://github.com/kiali/kiali/issues/3960
It's a trivial change but I cc QE team in case it touches any CI integration test.
=> Fix SE column title

src/pages/Graph/GraphToolbar/GraphToolbar.tsx
Fixes https://github.com/kiali/kiali/issues/3982
@mattmahoneyrh IMO, no QE required for this non-reproducible fix. Just assigning as an FYI.
=> Protect against code-drop-through

src/components/IstioWizards/WizardActions.ts, src/components/Pf/PfBadges.tsx, src/components/VirtualList/Config.ts, src/pages/IstioConfigList/FiltersAndSorts.ts, src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts, src/types/IstioConfigDetails.ts, src/types/IstioConfigList.ts, src/types/IstioObjects.ts, src/utils/IstioConfigUtils.ts
Backend needed https://github.com/kiali/kiali/pull/4024
=> Support WorkloadGroup Istio resources

src/config/ServerConfig.ts, src/types/ErrorRate/__testData__/ErrorRateConfig.ts, src/types/ServerConfig.ts, src/types/__testData__/HealthConfig.ts
fixes: https://github.com/kiali/kiali/issues/4109
=> remove istio_component_namespaces config

src/components/IstioWizards/CircuitBreaker/ConnectionPool.tsx, src/components/IstioWizards/CircuitBreaker/OutlierDetection.tsx, src/components/IstioWizards/FaultInjection.tsx, src/components/IstioWizards/FaultInjection/AbortFault.tsx, src/components/IstioWizards/FaultInjection/DelayFault.tsx, src/components/IstioWizards/GatewaySelector.tsx, src/components/IstioWizards/RequestRouting/Matches.tsx, src/components/IstioWizards/RequestRouting/RuleBuilder.tsx, src/components/IstioWizards/RequestRouting/Rules.tsx, src/components/IstioWizards/RequestTimeouts.tsx, src/components/IstioWizards/RequestTimeouts/RouteRetry.tsx, src/components/IstioWizards/RequestTimeouts/RouteTimeout.tsx, src/components/IstioWizards/ServiceWizard.tsx, src/components/IstioWizards/TrafficPolicy.tsx, src/components/IstioWizards/TrafficShifting.tsx, src/components/IstioWizards/WizardHelp.tsx, src/components/IstioWizards/WorkloadWizard.tsx
Fixes https://github.com/kiali/kiali/issues/1369
It enhances the current Service Wizards with additional tooltip:
Wording is synced with Istio reference.
=> Wizard Help Icons

src/pages/WorkloadDetails/WorkloadPodLogs.tsx
Fix reference-assignment issue.  Also, improve clarity with some variable renaming and remove a redundant check in componentDidUpdate.
Fixes https://github.com/kiali/kiali/issues/4130
To Recreate issue for Testing:
1) Go to a workload detail that has both a proxy and app container.
2) Go to Logs tab
- container options should be correct at the top of the logs window
3) Change (or reselect) the pod
- the app container name should be duplicated
After the fix the duplication should go away and everything else should work the same as always for the logs tab.
=> Fix duplicate container options in workload pod logs

src/pages/WorkloadDetails/WorkloadPodLogs.tsx
V1.36 BACKPORT for https://github.com/kiali/kiali/issues/4130
=> [v1.36] Fix duplicate container options in workload pod logs

src/components/Details/DetailDescription.tsx, src/components/IstioConfigCard/IstioConfigCard.tsx, src/components/IstioConfigCard/__tests__/IstioConfigCard.test.tsx, src/components/IstioConfigCard/__tests__/__snapshots__/IstioConfigCard.test.tsx.snap, src/pages/ServiceDetails/ServiceDescription.tsx, src/pages/WorkloadDetails/WorkloadPods.tsx
Cherry-picking https://github.com/kiali/kiali-ui/pull/2183
=> [v1.36] Sort sublists details pages (#2183)

src/components/Envoy/EnvoyDetails.tsx
Backport of https://github.com/kiali/kiali-ui/pull/2190
=> [v1.36] Fix missing mount Envoy tabs

src/components/MetricsOptions/MetricsSettingsDropdown.tsx
I think this one wouldn't require QE test.
=> Trivial: remove debug console.log

src/components/Metrics/CustomMetrics.tsx, src/components/Metrics/IstioMetrics.tsx, src/components/MetricsOptions/MetricsSettingsDropdown.tsx
=> [v1.36] Fix sync state on URL on Metrics tab (#2186)

src/pages/AppList/FiltersAndSorts.ts, src/pages/ServiceList/FiltersAndSorts.ts, src/pages/WorkloadList/FiltersAndSorts.ts
During https://github.com/kiali/kiali-ui/pull/2192 review I introduced this issue when filtering.
Adding a fix.
=> Fix wrong type used in filtering

src/components/Metrics/CustomMetrics.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/types/MetricsOptions.ts
Required for https://github.com/kiali/kiali/pull/4146
=> Use workload parameters for custom dashboards

src/components/Metrics/CustomMetrics.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/types/MetricsOptions.ts
Backport of https://github.com/kiali/kiali-ui/pull/2197
=> [v1.36] Use workload parameters for custom dashboards (#2197)

src/components/Charts/Dashboard.tsx, src/components/Charts/KChart.tsx, src/components/Metrics/__tests__/IstioMetrics.test.tsx, src/stories/__dataStories__/dashboardService.ts, src/stories/__dataStories__/dashboardWithLegends.ts, src/stories/__dataStories__/envoyMetrics.ts, src/types/Dashboards.ts, src/types/__mocks__/Dashboards.mock.ts
Fixes https://github.com/kiali/kiali/issues/4156
It requires https://github.com/kiali/kiali/pull/4171
=> Support multiple rows in metrics dashboards

src/components/Charts/Dashboard.tsx, src/components/Charts/KChart.tsx, src/components/Metrics/__tests__/IstioMetrics.test.tsx, src/stories/__dataStories__/dashboardService.ts, src/stories/__dataStories__/dashboardWithLegends.ts, src/stories/__dataStories__/envoyMetrics.ts, src/types/Dashboards.ts, src/types/__mocks__/Dashboards.mock.ts
=> [v1.36] Support multiple rows in metrics dashboards

src/components/Charts/ChartWithLegend.tsx, src/components/Charts/KChart.tsx
=> [v1.36] Adjust empty metric chart height (#2203)

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
backporting https://github.com/kiali/kiali-ui/pull/2207/commits
=> [1.36] Show editor sidepanel when there are only validation references

src/components/MetricsOptions/MetricsReporter.tsx
Fix for RFE https://github.com/kiali/kiali/issues/1433
=> Added help icon and tooltip on Metrics tab Reported from dropdown.

src/components/Validations/ServiceValidationSummary.tsx, src/components/Validations/ValidationServiceSummary.tsx, src/components/Validations/__tests__/ServiceValidationSummary.test.tsx, src/components/Validations/__tests__/__snapshots__/ServiceValidationSummary.test.tsx.snap, src/components/VirtualList/Config.ts, src/components/VirtualList/Renderers.tsx
Original RFE: https://github.com/kiali/kiali/issues/3872
Service configuration tooltip was re-using the IstioConfig tooltip, thus the message was not related to Service itself..
Added separate code for ServiceValidation to show Service related info in tooltip.
=> Modified Configuration tooltip on ServiceList page to be Service related

src/pages/ServiceDetails/ServiceNetwork.tsx, src/types/ServiceInfo.ts
UI part of https://github.com/kiali/kiali/pull/4499
=> Showing appProtocol information in tooltip for Service details Network section.

src/components/BreadcrumbView/BreadcrumbView.tsx, src/components/Pf/PfBadges.tsx, src/components/VirtualList/Renderers.tsx, src/helpers/__tests__/LabelFilterHelper.test.ts, src/pages/ServiceDetails/ServiceDescription.tsx, src/pages/ServiceDetails/ServiceInfo.tsx, src/pages/ServiceDetails/ServiceNetwork.tsx, src/pages/ServiceList/FiltersAndSorts.ts, src/pages/ServiceList/ServiceListPage.tsx, src/services/__mockData__/getServiceDetail.ts, src/types/IstioConfigList.ts, src/types/ServiceInfo.ts, src/types/ServiceList.ts
Required for https://github.com/kiali/kiali/pull/4479
=> Istio Registry changes

src/components/Charts/ChartWithLegend.tsx
Fixes https://github.com/kiali/kiali/issues/4668
=> Protect trendlines from undefined values

src/components/CytoscapeGraph/CytoscapeGraph.tsx, src/components/CytoscapeGraph/CytoscapeGraphUtils.ts, src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx, src/components/CytoscapeGraph/CytoscapeToolbar.tsx, src/components/CytoscapeGraph/Layout/BoxLayout.ts, src/components/CytoscapeGraph/MiniGraphCard.tsx, src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx, src/components/CytoscapeGraph/graphs/GraphStyles.ts, src/pages/Graph/GraphPage.tsx, src/pages/Graph/GraphToolbar/GraphFind.tsx, src/pages/Graph/GraphToolbar/GraphToolbar.tsx, src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx, src/types/Graph.ts
Backport for kiali/kiali#4666
Backport of https://github.com/kiali/kiali-ui/pull/2290
=> [v1.45] Protect graph-hide from unwanted zoom events

package.json, src/components/MissingAuthPolicy/MissingAuthPolicy.tsx, src/components/VirtualList/Renderers.tsx, src/config/Icons.ts, src/helpers/__tests__/LabelFilterHelper.test.ts, src/pages/WorkloadDetails/WorkloadDescription.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadList/WorkloadListPage.tsx, src/services/Api.ts, src/types/Workload.ts, src/utils/IstioConfigUtils.ts
Needed by: [4409](https://github.com/kiali/kiali/pull/4409)
Workloads list
Workloads details
=> Indicate if workloads are not covered by any AuthorizationPolicy

src/components/IstioActions/IstioActionsDropdown.tsx, src/components/IstioActions/IstioActionsNamespaceDropdown.tsx, src/components/IstioWizards/ServiceWizardDropdown.tsx, src/components/IstioWizards/WorkloadWizardDropdown.tsx, src/pages/IstioConfigNew/IstioConfigNewPage.tsx
Signed-off-by: Xunzhuo <mixdeers@gmail.com>
fix grammar in error message "user has not permissions" 
* If this is a fix for a GH-issue, please link it here
Fixes https://github.com/kiali/kiali/issues/4704
Yes
=> fix: grammar in error message

package.json, yarn.lock
@nrfox This should likely wait for the pending server-side changes.
=> [v1.24] bump axios

package.json, yarn.lock
@nrfox This should likely wait for the pending server-side changes.
=> [v1.36] bump axios

src/components/IstioActions/IstioActionsNamespaceDropdown.tsx, src/components/IstioConfigPreview/EditResources.tsx, src/components/IstioConfigPreview/IstioConfigPreview.tsx, src/components/IstioWizards/WizardActions.ts, src/pages/IstioConfigNew/IstioConfigNewPage.tsx
Fix https://github.com/kiali/kiali/issues/4733
Grouped by namespace
=> Istio preview under istio config view

src/pages/AppDetails/AppDetailsPage.tsx, src/pages/AppDetails/AppInfo.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo.tsx, src/services/Api.ts, src/types/App.ts, src/types/Health.ts, src/types/Workload.ts
Require: https://github.com/kiali/kiali/pull/4799
Related with: https://github.com/kiali/kiali/issues/4611
=> Migrate health in details

src/pages/AppDetails/AppDetailsPage.tsx, src/pages/AppDetails/AppInfo.tsx, src/pages/WorkloadDetails/WorkloadDetailsPage.tsx, src/pages/WorkloadDetails/WorkloadInfo.tsx, src/types/Health.ts
Fix comments in health https://github.com/kiali/kiali-ui/pull/2329
=> Fix naming and order in health

src/services/Api.ts, src/services/__tests__/ApiMethods.test.tsx.ts
Follow-up task to clean unused health endpoints from the UI.
I'm preparing a task in the backend as I've noticed a hidden bug in the Workload logic (it was before that the health refactoring effort, but thanks to this work, that issue is more evident).
Please, I did a smoke test and everything worked as expected, let me know if this PR is good.
=> Remove unused Application/Service/Workload health endpoints

src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigOverview.tsx
Fixes [#4807](https://github.com/kiali/kiali/issues/4807).
=> Showing validation references on warnings

src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Fix for https://github.com/kiali/kiali/issues/4753
=> Remove 'null' array values in Istio Config update JSON
