kiali/kiali-ui

- LICENSE
- package.json
Adds an apache-2 license file and appropriate license settings for publishing to npm (in `package.json`)
Fixes: #2
> Add Apache 2 License

- package.json
Not all file types will be *.tsx some will be *.ts -- if there is no JSX in it.
> Add *.ts as a file type to format with prettier.

- tsconfig.json
Set noImplicitAny flag in tsconfig.json to false so we can use 3rd pa…rty libaries without @type libs.
I could not use the cytoscape.js library without this because it has no type libraries (*.d.ts)
> Set noImplicitAny flag in tsconfig.json to false 

- .travis.yml
Following React docs [1]
[1] https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#travis-ci
> SWS-104 Adds travis testing

- src/.editorconfig
So folks can just get the right settings for the editor and have the IDE 'know' the right settings for indent spacing etc...
Most IDEs and editors support this.
http://editorconfig.org/
> Add editorconfig, the universal editor config settings

- README.adoc
This PR has the configuration required to point to swscore inside openshift without having to do any tricky stuff (build swscore docker again, rsync, etc) while developing the UI.
We only have to add the `proxy` configuration [1] to our `package.json` and point it to our swscore endpoint.
Notes: 
- We can't access the API by writing its URL on the browser, is because the proxy will only serve requests without the `text/html` accept header [2].
- This only works when running `npm start` so a production build is not affected.
- This can be further configured [3] if we need to access many endpoints from different URLs.
[1] https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development
[2] …
> Adds information on how to configure proxy to swscore server

- tsconfig.json
These messages currently show up:
```
Failed to load tsconfig.json: Missing baseUrl in compilerOptions
Creating an optimized production build...
Found no baseUrl in tsconfig.json, not applying tsconfig-paths-webpack-plugin
Found no baseUrl in tsconfig.json, not applying tsconfig-paths-webpack-plugin
```
https://issues.jboss.org/browse/SWS-128
> SWS-128 Fix tsconfig compiler error messages

- .npmignore
- package-lock.json
- package.json
Don't publish the 300mb of `node_modules` to npm.
From the archive tarball it gets us down to about 7mb.
https://issues.jboss.org/browse/SWS-129
Required by: https://issues.jboss.org/browse/SWS-127
> Don't publish node modules to npm

- package.json
This is to enable client-side routing. Else HTML contains links such as "/services/static/js/main.f06a050d.js" instead of "/static/js/main.f06a050d.js" when hitting url "http://sws.../services"
> SWS-131 change homepage (= base url) to /

- src/components/Nav/Navigation.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceList/ServiceFilter.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/ServiceList/ServiceListPage.tsx
- src/pages/ServiceList/ServicePagination.tsx
- Changed proper icons on navigation and service
- Introduce basic features proposed for service list: filtering and paging
- This is pure mock with demo data, no connectivity with backend
I wanted to split SWS-63 in two parts, this is just a mock data showing the visual elements we are going to add, following PR will complete the connectivity with real backend calls, but to not send a big PR, I guess it's better to propose this way (note. I will ruse same JIRA code for next commit).
So, this page shows the list of services and will provide basic filtering by namespace or service name and also a basic pagination (as we don't know how many services we will have).
Also, in the list we can anticipate some info from the details, i.e. summary of pods, versions, istio rules, or even some mini …
> SWS-63: Preliminar mock for ServiceList page

- src/app/App.tsx
Needs https://github.com/swift-sunshine/swscore/pull/64 on server side
PS: for motivations, see discussion on server-side PR
> SWS-131: prefix all client routes with /console

- package-lock.json
- package.json
- src/pages/ServiceGraph/CytoscapeConfig.ts
- src/pages/ServiceGraph/FakeData.ts
- src/pages/ServiceGraph/ServiceGraphPage.tsx
Preliminary Service Graph with Cytoscape
https://issues.jboss.org/browse/SWS-73
Next steps to hook up to Jay's live data (we have already agreed on a cytoscape data format to send).
Still need to tweak look-n-feel more, add namespace selection and linking to other screens.
> Add Cytoscape layout for the Service Graph page

- src/services/Api.ts
- tslint.json
ES6 best practice is to not use `var` but instead use `const` or `let` which are more explicit and have lexical scope boundaries that are more concrete (no hoisting errors). With `var` we also don't know the intention: is it mutable or immutable?
> No var keyword tslint

- src/pages/ServiceGraph/CytoscapeConfig.ts
With these small changes, the graph will now show arrows:
> SWS-149: Visualize the direction of the flow/traffic

- src/index.css
- src/pages/ServiceGraph/ServiceGraphPage.tsx
This defines the logic for scaling the service graph canvas on the page,
and recomputing it on resize.
Fixes: https://issues.jboss.org/browse/SWS-150
> [SWS-150] Have the service graph fill all the whitespace

- .travis.yml
- package-lock.json
- package.json
NPM doesn't accept to upload the same version, we need to bump it.
Manually bumping the version would be hard, and automatically doing so
would require committing that package.json.
npm-snapshot sets the version to ${VERSION}-snapshot.${input} and we
are using $TRAVIS_BUILD_NUMBER as input.
> SWS 115 - Uses npm-snapshot to have a snapshot version

- package-lock.json
- package.json
- src/components/CytoscapeLayout/CytoscapeLayout.tsx
This is just adding back in a feature that got removed because the file structures had changed so much it wasn't possible to merge.
This is @cfcosta work from commit: b89fde7ea014d00d09b8edbf76e5336db234149e
Video: https://www.dropbox.com/s/6l3km3buwfzxtgn/cytoscrape-resize.mov?dl=0
> SWS-150 Fill the whitespace in the service graph page.

- .travis.yml
Travis is doing a cleanup before publishing and that is interfering with npm-snapshot
```
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
```
> SWS 115 - Skips cleanup and fixes request message ($TRAVIS_COMMIT)

- src/components/CytoscapeLayout/CytoscapeLayout.tsx
Before this change. the details node would sometimes be placed into the 'reviews' box.
The change tells the layout engine to make adjustments after the first round. 
Also the spacing factor has been reduced so that nodes are closer together.
Now with this change:
https://issues.jboss.org/browse/SWS-182
See also #65 for some changes to coloring.
> SWS-182 Improve layouting

- src/components/Nav/Navigation.tsx
- Select Graph as default one
As Home page is removed, Overview entry in navigation should be removed as well, it was creating some errors.
Now default page is Graph.
> SWS-187: Fix unused navigation entry

- src/pages/ServiceDetails/ServiceInfo/ServiceInfo.tsx
- src/types/ServiceInfo.ts
- Minor tweaks on style
Basically this is a ephemeral UI changes for demo:
- Matching is now show in the rules, as it might have a complex type inside, I decided to put it as a parsed json source, using list indented wasn't looking good. We can revisit this on Sprint 2.
- Also trying to reduce space, Endpoints was showing redundant ports, so we could unify it.
- Adding some labels to define what is what.
Goal is to show the info, UI is open to change quite soon, but at least BookInfo scenarios should be covered.
> SWS-192 Show matching details in ServiceDetails page

- src/components/CytoscapeLayout/CytoscapeLayout.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/types/NamespaceId.ts
Namespace selector is a Patternfly dropdown. It is placed in the header,
replacing the namespace text.
> SWS-165: Add namespace selector to service graph

- src/pages/ServiceDetails/ServiceInfo/ServiceInfo.tsx
- Route uses same labels as pods, so it should have same visual identity
> SWS-199: Unify labels style in service details page

- src/pages/ServiceDetails/ServiceInfo/ServiceInfo.tsx
- Port is shown as a list instead
> SWS-200: Fix Ports overflow on ServiceDetails page

- package-lock.json
- package.json
Prettier runs on the precommit. It will fail the commit if any file is updated by it, a message is show to warn the developer.
Moved husky and prettier to devDependencies and removed lint-staged as is no longer used.
@jotak I think you removed the precommit because it staged the files automatically, this does something similar to swscore, please review.
Note: There is one file that is failing the linter, fixed in PR #88
> SWS-243 Adds back the precommit hook

- .prettierrc.json
- package.json
This allows to parse json files
Removes options on package.json, they were already defined in .prettierrc.json
Before:
After:
> SWS-161 Let prettier infer the format by the path

- src/pages/ServiceDetails/ServiceMetrics.tsx
Note also that the http call /api/grafana may return 204 if the link should not be displayed
> SWS-171 More configurable grafana link

- src/services/__mockData__/getGrafanaInfo.json
- src/services/__mockData__/getGraphElements.json
- src/services/__mockData__/getNamespaces.json
- src/services/__mockData__/getServiceDetail.json
- src/services/__mockData__/getServices.json
- src/services/__mocks__/Api.ts
- src/services/__tests__/Api.test.tsx
Jira: [SWS-260](https://issues.jboss.org/browse/SWS-260)
Add tests and mocks for Service API. 
With this we can mock the API calls in the tests.
Example test of ServiceDescription, thanks for @vnugent, great masterclass 
```js
import * as React from 'react';
import { shallow } from 'enzyme';
import { ServiceInfoDescription, ServiceInfoCard } from '../index';
jest.mock('../../../../services/Api');
const API = require('../../../../services/Api');
describe('#ServiceInfoDescription render correctly with data', () => {
it('should load service detail data', () => {
return API.GetServiceDetail('istio-system', 'reviews').then(data => {
const wrapper = shallow(
<ServiceInfoDescription
name={data.name}
labels={data.labels}
type={data.type}
ip={data.ip}
endpoints={data.endpoints}
/>
); …
```
> SWS-260 Add tests and mock for service API

- package-lock.json
- src/components/CytoscapeLayout/CytoscapeLayout.tsx
- src/components/CytoscapeLayout/graphs/BreadthFirstGraph.ts
- src/components/CytoscapeLayout/graphs/ColaGraph.ts
- src/components/CytoscapeLayout/graphs/DagreGraph.ts
- src/components/CytoscapeLayout/graphs/GraphStyles.ts
- src/components/CytoscapeLayout/graphs/GraphType.ts
- src/components/Pf/PfContainerNavVertical.tsx
- src/components/Pf/PfHeader.tsx
- src/pages/ServiceGraph/CytoscapeToolbar.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
Instead of just the one layout, add multiple layout options(3) for the graphs selectable on a toolbar.
There are still two other layouts that need to be added: cosa and klay (their configurations and libraries are more complicated). But nothing stopping this from being merged.
[SWS-94](https://issues.jboss.org/browse/SWS-194)
> SWS-94: Add multiple layouts for graphs.

- package-lock.json
- package.json
- src/app/__tests__/App.test.tsx
Related to SWS-256
Cytoscape smoke test was failing because of two reasons:
1) Cytoscape uses `canvas`, but jsdom doesn't implement it.
2) Cytoscape relies on the values `paddingXXX` provided by `window.getComputedStyle`,  but `jsdom` implementation is not complete, not all values are returned with sane defaults.
Fixed 1) by adding `jest-canvas-mock`.
Fixed 2) by mocking getComputedStyle and adding default for `paddingXXX`.
@vnugent please take a look
> Restore cytoscape smoke test

- src/app/__tests__/App.test.tsx
- src/pages/ServiceGraph/SummaryPanel.tsx
It looks like this:
The panel is always there (even if the graph is blank).
> SWS-215: Side panel mock-up with fake data

- README.adoc
Couple readme updates:
Remove unused folder descriptions such as `containers` and `hoc`
Add Testing section with instructions for OS/X testing dependencies -- needs `watchman`
> Readme updates: 

- src/components/CytoscapeLayout/CytoscapeLayout.tsx
- src/components/CytoscapeLayout/graphs/GraphHighlighter.ts
- Highlight related nodes when clicking a service.
- Mouseover will only highlight related nodes of the service (if one
is selected).
- Moved all the highlight code out of the CytoscapeLayout component.
Issues: When the graph is refreshed, we lose the current selected service.
> SWS 299 - Highlight connection and nodes for services

- src/components/CytoscapeLayout/graphs/GraphStyles.ts
Make service graph labels text more readable via:
- give more space between edge/node and label text
- make edge label text a bit smaller font
- make edge label text gray instead of black
https://issues.jboss.org/browse/SWS-322
> SWS-322 Make service graph text more readable

- src/components/CytoscapeLayout/CytoscapeLayout.tsx
Adds in a loading page for when we are fetching data from the backend and we don't have a response yet.
An easy way to test is to shutdown your p8s instance as it will take a while for the backend to respond
[there are other issues created to handle the error page and empty page]
> SWS-265: add in loading page for the service graph

- src/components/CytoscapeLayout/graphs/GraphHighlighter.ts
- src/components/ServiceFilter/ServiceFilter.tsx
- src/config.ts
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx
- src/registerServiceWorker.ts
- tslint.json
> There really should be no need for 'function'. Especially when Traditional functions don’t bind lexical scope (and Typescript does), which can lead to unexpected behavior when accessing ‘this’.
>
> https://palantir.github.io/tslint/rules/only-arrow-functions/
Replaces #35
> Add tslint rule for only ES6 arrow functions (no function syntax)

- src/pages/ServiceGraph/ServiceGraphPage.tsx
It appears someone accidentally deleted the `PfHeader` and `PfContainerNavVertical`. This gives us consistency and when we change the style we do it in one place.
Also, got rid of an unnecessary div.
> Trivial: Add back in PfHeader and PfContainerNavVertical to service graph page

- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/components/MetricsOptions/ValueSelectHelper.tsx
- src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
- src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
- src/pages/ServiceDetails/ServiceMetrics.tsx
- src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx
- src/types/Metrics.ts
- src/types/MetricsOptions.ts
- allow grouping by label
- add unit to charts
- some refactoring in MetricService to compute as few as possible during rendering
- replace option "step" with "ticks", to prevent having too many datapoints freezing the browser when we have low step + high duration. Step = duration / ticks
Screenshot: https://screenshots.firefox.com/vO3BZbotsIKtJA5I/localhost
> SWS-277 allow grouping metrics by label

- src/components/CytoscapeLayout/graphs/GraphStyles.ts
I'm in the process of trying to figure out why the graph highlighter doesn't work.
I noticed our styles are messed up. Some aren't used, some need to be renamed, some are using ad hoc colors. It needs to be cleaned up.
This PR simply cleans up the graph styles ensuring only those styles used are defined as well as makes sure the colors used match those from the official patternfly color palette here: https://www.patternfly.org/styles/color-palette/
> clean up the styles - get colors to match official patternfly palette

- src/components/CytoscapeLayout/CytoscapeLayout.tsx
- src/components/CytoscapeLayout/__tests__/CytoscapeLayout.test.tsx
- removed auto-refresh logic. 
- added a manual refresh button
- adjusted test
Do not merge until I can confirm Refresh button location in relation to the graph
> [SWS-342] Remove auto-refresh logic. Add a manual refresh button

- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceGraph/SummaryPanel.tsx
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- src/types/Graph.ts
Add rateInterval to graph summary panels such that they reflect the same interval setting selected for the graph rendering.
> SWS-302 Add rateInterval to graph summary

- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationPolicies.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRouteRules.test.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteRules.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/index.tsx
- src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/types/ServiceInfo.ts
This requires https://github.com/kiali/swsui/pull/140 be merged first as it has dependencies introduced there.
This is a preliminar way to present DestinationPolicies objects (load balancers, circuit breakers) attached/grouped per service, in the Service Details page.
It is just a list, not open the discussion about better UX, as further discussion about how to re-org hasn't started yet, but it makes sense to bring it into the details page as a preliminar step.
> Add Destination Policies to the Service Details page

- src/components/SummaryPanel/RpsChart.tsx
- src/pages/ServiceDetails/ServiceMetrics.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- src/utils/graphing.ts
Using the group panel as a template. The RpsChart can now show the
timestamps of the data points if data is received with the rigth format.
Pulling out "toC3Columns" function to an utils object to reuse the code.
> SWS-217: Display data in side panel about a selected versioned service (node) in graph

- src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules.tsx
- src/types/ServiceInfo.ts
When weight parameter is present in a RouteRule, it is shown in the associated label(s).
> KIALI-239 Add weight attribute in ServiceInfoRouteRules

- src/components/SummaryPanel/RpsChart.tsx
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- Change RpsChart to only allow data with timestamps.
- Fix styles of the side panel to avoid overflow of the content.
> Homologate all side panels to show timestamps for RpsCharts

- src/pages/ServiceList/ServiceListComponent.tsx
- src/types/ServiceListComponent.ts
Adding pod status to every service in the service list.
There are no test for this Service List, so I couldn't update them. I am planning to add a subsequent PR adding them ( I think tests are out of KIALI-362 scope).
> KIALI-362 Add pod status for each service listed

- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceGraph/SummaryPanel.tsx
- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/services/Api.ts
- src/types/Graph.ts
This aggregates info about all services reflected in the namespace graph
also:
- remove horizontal break in RateTable to conserve space/improve locality
- add updateTime to graph state (for future use)
NOTE: This depends on new backend support, setting to do not merge until core PR is merged.
> KIALI-331 graph summary for namespace

- src/components/SummaryPanel/InOutRateTable.tsx
- src/components/SummaryPanel/RateTable.tsx
- src/components/SummaryPanel/RpsChart.tsx
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- ensure the node side-panel uses the time interval selection (it was hardcoded before)
- do not consider 3xx responses as errors
- inout and rate tables now use consistent headers
- remove unused err rate variables in group side panel
- for consistency, edge side panel uses service names like the other summary panels
- use colors as per official patternfly palette
> this cleans up some things for correctness and consistency

- src/pages/ServiceGraph/SummaryPanelNode.tsx
The sparklines will now update correctly, which are the only objects not being updated correctly when selection from the graph is changed by the user.
This fix is only for versioned nodes.
> KIALI-396: Ensure charts are updated when a versioned node of the graph is selected

- src/components/GraphFilter/GraphFilter.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceGraph/SummaryPanel.tsx
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- src/types/Graph.ts
This ensures the graph will always have 30 data points, thus making the graphs look consistent but also allowing the server-side request to execute fast even when processing as large a data set as 30 days worth.
Note the current implementation uses a consistent rate interval of 1m. Not sure if it would be more efficient to increase the interval as the data size gets larger (e.g. is it better to query with 5m rate intervals over a 7d or 30d duration?). Leaving this as-is will allow us to change intervals per duration if we need to in the future.
> KIALI-400: Set step and rateInterval dependent upon duration.

- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/services/Api.ts
- src/services/__mockData__/getJaegerInfo.json
- src/services/__mocks__/Api.ts
- src/services/__tests__/Api.test.tsx
[KIALI-242](https://issues.jboss.org/browse/KIALI-242)
Should I get the jaeger url by the backend or set it in the config file of the UI?
Actually the URI is the external one, but we can set jaeger-query, but I don't know if will keep this name for this service.
The link will be like <Jaeger_Host>/search?service=<service_name> (Example : http://jaeger-query-istio-system.127.0.0.1.nip.io/search?service=jaeger-query)
cc @theute @abonas 
The link now is shoring all the traces of service, by default the query of jaeger show 20 traces of the last hour.
> http://jaeger-query-istio-system.127.0.0.1.nip.io/search?end=1521731585049000&limit=20&lookback=1h&maxDuration&minDuration&service=jaeger-query&start=1521727985049000
What kind of search we want by default when then operator go to traces?
Need …
> [KIALI-242] Add link to Traces Jaeger in ServiceDetails

- src/app/App.tsx
- src/components/Nav/Navigation.tsx
- src/components/Nav/__tests__/Navigation.test.tsx
- The sidebar is working as expected as you click on it
- If you bookmark and revisit a page later, while correct view is shown 'Graph' always gets selected.
- Partially addressed KIALI-399.  The hotlink is still incorrect.  For a smooth transition between views it's better to use React Router to update browser url.
https://github.com/kiali/swsui/blob/master/src/pages/ServiceGraph/SummaryPanelGraph.tsx#L78
```
const servicesLink = <a href={`../services?namespace=${this.props.namespace}`}>{this.props.namespace}</a>;
```
> [KIALI-399] Select sidebar according to browser url

- src/components/CytoscapeLayout/CytoscapeLayout.tsx
- src/components/CytoscapeLayout/__tests__/CytoscapeLayout.test.tsx
- src/components/CytoscapeLayout/graphs/LayoutDictionary.ts
- src/components/GraphFilter/GraphFilter.tsx
- src/components/GraphFilter/QueryOptions.ts
- src/components/NamespaceFilter/NamespaceFilter.tsx
- src/pages/IstioRulesList/IstioRuleListComponent.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/services/Api.ts
- src/types/Graph.ts
- src/types/GraphFilter.ts
- src/types/IstioRuleListComponent.ts
- src/types/Namespace.ts
- src/types/ServiceListComponent.ts
Graph data, namespace, interval and layout are now in one place, `ServiceGraphPage`.   Browser URL will set namespace, interval and layout accordingly. 
1. Make sure Namespace, Layout, Interval are used consistently.  For example, `CytoscapeLayout.namespace` prop is now of Namespace type.  You can no longer pass a string to it.
2. `CytoscapeLayout`: move graph elements state and refresh logic to its parent.
3. `GraphFilter`: propagates namespace, filter, layout changes to parent via new separate callbacks, `filterChange(newVal)`, `namespaceChange(newVal)` and `layoutChange(newVal)`.  The callback payload contains the new value. `GraphFilters` getters/setters are no longer needed. 
4. Since I introduced `Interval` type and recent changes renamed it to `Duration` in order to keep my …
> [KIALI-357] consolidate state and callbacks in ServiceGraphPage

- package-lock.json
- package.json
I locally see an error
```
events.js:137
throw er; // Unhandled 'error' event
^
``` 
on `npm test`, but I see the same with the current version
> KIALI-427 bump version of ssri.

- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/pages/ServiceDetails/ServiceMetrics.tsx
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- src/services/Api.ts
- src/types/MetricsOptions.ts
Prometheus rate function is "rate" for graph pages and "irate" for service details
Also enforce type safety on MetricsOptions
Remove unused filterLabels
> KIALI-438 Filter unnecessary metrics calls and customize rate function

- src/components/CytoscapeLayout/graphs/GraphStyles.ts
Move away from center because there is likely always an edge through the center.  Also, thin edges
for a generally cleaner look and less overlap when crossing over text.
> move group label to right side and rotate.  

- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
increase size for readability.  This also saves space as we look to add
more summary info to the side panels.
Here is an idea of what it looks like using edge as an example:
> Improve l+f by moving summary labels into panel header

- package-lock.json
- package.json
Announcement: https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8/
https://issues.jboss.org/browse/KIALI-484
> Kiali-484: Upgrade to typescript 2.8.1 from 2.7.2

- src/components/CytoscapeLayout/graphs/GraphStyles.ts
With this change, the user won't be allowed to change nodes positioning of the service graph.
> KIALI-180: Disallow the user from repositioning nodes

- src/app/App.tsx
- src/components/Nav/Navigation.tsx
Cleanup some unnecessary `div` nesting. At the very least, they bloat the DOM.
Using React 16 [Fragments](https://reactjs.org/docs/fragments.html) instead.
> Trivial: Remove superflous 'div' tags

- src/components/Nav/Navigation.tsx
- src/components/SwitchErrorBoundary/SwitchErrorBoundary.tsx
This make possible to catch unhandled render errors without breaking
the whole application, the user is still able to change pages and use
the rest of the application.
Note: The flashy error screen is show only in development mode, while the "Something wrong happened" is show always.
> KIALI-358 Wraps Switch into an ErrorBoundary object

- src/components/CytoscapeLayout/EmptyGraphLayout.tsx
Cosmetic change. Make Height 100% (actually 98%) and give some margin between side panel. Also, utilize falsey value of undefined for simpler if statement.
Before:
After:
> Trivial: Cosmetic. Make Height 100% in EmptyGraphLayout

- src/components/ServiceHealth/ServiceHealth.tsx
- src/components/ServiceHealth/__tests__/ServiceHealth.test.tsx
- src/components/ServiceHealth/__tests__/__snapshots__/ServiceHealth.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDeployments.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDeployments.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceList/ServiceListComponent.tsx
- src/services/__mockData__/getServiceHealth.json
- src/types/Health.ts
- src/types/ServiceListComponent.ts
- Replace the donut with the global indicator (colored icon) in service details
- Replace global pod status with health in services list
- Aggregate health sources into a global health
- Unit tests
Related to https://github.com/kiali/kiali/pull/145
> KIALI-480 Global health indicator

- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
- src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceMetrics.tsx
- Do not mount metrics page before its tab is actually displayed
- Clear interval timer on exit
- Do not fetch metrics when pausing / changing poll interval
> KIALI-517 Several perf enhancement on metrics page

- src/assets/img/istio-logo.svg
- src/components/NamespaceFilter/NamespaceFilter.tsx
- src/index.css
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/pages/ServiceList/ServiceListComponent.scss
- src/pages/ServiceList/ServiceListComponent.tsx
- src/types/ServiceInfo.ts
- src/types/ServiceListComponent.ts
- Add filtering and sorting by Istio services
Look and feel is temporal, pretty soon, it will change when UX teams suggest better design, but to keep things simple we have added an "Istio" icon on the service list and service details pages.
Service list page can now filter and sort by Istio based services:
> KIALI-506 Add Istio Sidecar flag on Service pages

- src/components/CytoscapeLayout/CytoscapeLayout.tsx
Eliminate some use of `null`. Use truthy/falsey checks instead.
> Trivial: Cleanup null checks. Use more readable truthy checks.

- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
In the side panel:
- Don't use badges for non-label data
- Use "services" instead of "microservices"
- In the namespace side panel, fix service count (exclude unknown node)
> KIALI-527: Consistency across the UI (badges, labels)

- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- src/utils/TrafficRate.ts
This is an answer to  @jmazzitelli concern about looping 4x more than the original code.
> KIALI-564 - Process all rates in one loop, calling cy.edges() only once.

- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/services/__mocks__/Api.ts
[KIALI-567](https://issues.jboss.org/browse/KIALI-567)
Auto scale columns.
> [KIALI-567] Hide Service Detail Information if not have a Istio enabled or no data

- src/components/Time/LocalTime.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDeployments.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationPolicies.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDescription.test.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRouteRules.test.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDeployments.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteRules.test.tsx.snap
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/types/ServiceInfo.ts
This PR needs [kiali/kiali#158](https://github.com/kiali/kiali/pull/158) to be merged.
Times shown for each resource displayed within this service page are in user's timezone.
Here you have the screenshots for each creation datetime added:
Service creation time:
Deployments creation time:
Route Rule creation time:
Destination policy creation time:
> Kiali 544 Adding creation time to all resources within service detail page

- src/components/CytoscapeLayout/CytoscapeLayout.tsx
- src/components/CytoscapeLayout/graphs/GraphStyles.ts
Remove use of json-supplied text, style and color fields to determine
node and edge presention.
A couple if notes for a couple of tabgential changes:
- updated edge fontsize from 9px to 7px
- updated edge text-margin-x from 10px to 6px
- dropped service name from grouped service nodes
- alphabetized node and edge settings for clarity (well, not diff clarity...)
> KIALI-582 remove presentation concerns from graph json

- src/pages/ServiceDetails/ServiceInfo.tsx
@aljesusg @xeviknal @lucasponce do you know if there was a good reason to have this "fetch" both from componentDidMount and componentWillReceiveProps ?
It makes 2 calls to the rest api where 1 would be enough.
I've tried and it seems to work properly, but maybe I missed some cases?
> KIALI-591 remove duplicate fetching from ServiceInfo

- src/components/GraphFilter/GraphFilter.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
Re-clicking the 'Cose' drop down option now generates the next cose variation
Also in this PR, some minor enhancements:
- Change option label 'Graph Type' to 'Layout'
- Remove PfHeader around page to remove excessive whitespace at top and
give same look as service list page.
> KIALI-590 allow cose to cycle through different cose layouts

- src/components/CytoscapeLayout/CytoscapeLayout.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceGraph/SummaryPanel.tsx
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
The graph area (the canvas and the side panel) will now adjust their size to fit the browser window. Also, the side panel will show an internal scrollbar instead of becoming large causing the browser to show scrollbars for the whole page.
> KIALI-611: Fix graph sizing problems

- src/components/CytoscapeLayout/CytoscapeLayout.stories.tsx
- src/components/MessageCenter/MessageCenter.stories.tsx
- src/components/MessageCenter/MessageCenter.tsx
- src/components/MessageCenter/NotificationDrawer.tsx
- src/components/MessageCenter/NotificationList.tsx
- src/components/MessageCenter/StatefulMessageCenter.tsx
- src/components/MessageCenter/Types.ts
- src/components/MessageCenter/__tests__/MessageCenter.test.tsx
- src/components/MessageCenter/index.ts
This PR covers the stateless component MessageCenter and would like feedback regarding the look and how it should behave. Next steps will be to couple with redux to be able to use it on any other component trough a redux action.
Patternfly [suggests](http://www.patternfly.org/pattern-library/communication/notification-drawer/) to use the NotificationDrawer along with the ToastNotification for displaying recent notifications upon login.
~~I still need to squash my commits (aka clean my mess) :)~~
> KIALI-358 Adds a MessageCenter component for showing alert notifications

- src/components/CytoscapeLayout/CytoscapeLayout.tsx
Nodes look too big if there are only a few nodes in the graph. This will prevent large zooms when the graph loads. Thereafter, the user can zoom as he desires.
> KIALI-609: Don't allow an initial large zoom for the graph

- src/components/GraphFilter/GraphFilter.tsx
- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
- src/components/ToolbarDropdown/ToolbarDropdown.tsx
There is a bug when you click the dropdown....it's loading the graph/metrics, this is because I propaged this.props to the select component so when you do the action onClick, this trigger the action.
> [KIALI-610] Fix onClick in Toolbar Component

- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/types/Graph.ts
After the graph is loaded, when the user clicks the background,
properties are pushed to the component only once. Because of this, the
side panel was not loading the required data.
Changing some code to ensure that "final" properties are always pushed
when the side panels are mounted. This allows to load chart data once
the component is mounted.
> KIALI-635: Fix namespace chart lost

- package-lock.json
- package.json
- src/config.ts
Uses the [deep-freeze](https://github.com/substack/deep-freeze) library to freeze the entire object tree for our default configuration data which should be read-only and maintained in one place.
> Kiali-650: Make the configuration data immutable down the tree. 

- package-lock.json
- package.json
- src/actions/ServiceGraphActions.ts
- src/app/App.tsx
- src/components/CytoscapeLayout/CytoscapeLayout.tsx
- src/components/CytoscapeLayout/__tests__/CytoscapeLayout.test.tsx
- src/components/CytoscapeLayout/graphs/GraphStyles.ts
- src/components/GraphFilter/GraphFilter.tsx
- src/containers/GraphLayers/GraphLayers.tsx
- src/reducers/ServiceGraphState.ts
- src/reducers/__tests__/ServiceGraphStateReducer.test.ts
- src/reducers/index.ts
- src/store/ConfigStore.ts
- src/store/Store.ts
This was originally blocked by the need of some pub/sub mechanism because the components that need to communicate are not within the same hierarchy (parent...child). With Redux we can now easily overcome this.
Component state management now using Redux. Also adds redux testing and type-safe state.
Redux libraries track with Jaeger-ui (with the addition of Redux-Thunk and typesafe-actions)
https://issues.jboss.org/browse/KIALI-345
>  Kiali-345 -Toggle node and edge labels (uses Redux)

- src/pages/IstioRuleDetails/IstioRuleInfo.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationPolicies.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRouteRules.test.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteRules.test.tsx.snap
- src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/types/ServiceInfo.ts
This PR introduces the ACE editor on Service Istio Object level.
In a preliminar iteration it follows style defined in the OpenShift Console.
From the Istio name object we can navigate to the editor like this:
> KIALI-629 Use the ACE editor on Services Istio objects

- src/components/GraphFilter/GraphFilter.tsx
- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
- src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
- src/components/ToolbarDropdown/ToolbarDropdown.tsx
Fix errors
Error index.js:2178 Warning: withRouter(Navigation): Stateless functional components do not support getDerivedStateFromProps is fixed in react-router 4.3. We must to wait until next release.
Jira: [KIALI-666](https://issues.jboss.org/browse/KIALI-666)
```
index.js:2178 Warning: Failed prop type: The prop `id` is required to make `Dropdown` accessible for users of assistive technologies such as screen readers.
in Dropdown (created by Uncontrolled(Dropdown))
in Uncontrolled(Dropdown) (created by DropdownButton)
in DropdownButton (created by DropdownButton)
in DropdownButton (created by ToolbarDropdown)
in div (created by ToolbarDropdown)
in ToolbarDropdown (created by GraphFilter)
in form (created by Toolbar)
in div (created by Col)
in Col (created by Toolbar)
in div (created by …
```
> [KIALI-666] Fix Kiali UI console log error messages

- .travis.yml
- package-lock.json
- package.json
- run_itest.sh
- src/__itests__/App.browser.test.tsx
- src/__itests__/Kiali.app.standalone.ts
- take_test_screenshot.sh
Part 1 (this PR)
Part 2 (~~future~~ this PR)
To test this feature locally:
```
```
a screenshot file `kiali-browser-test.png` will be generated in the project base dir.
new npm commands:
- `npm run kiali`: launch Kiali UI serving static files from ./build dir; API calls are proxy'ed to http://kiali-istio-system.45.56.100.74.nip.io
- `npm run itest`: run only integration tests in `__itests__` dir
Note: Since travis-ci doesn't expose encrypted env in PR build for security reason, I had to resort to a workaround, putting a github token in travis.yml.  It's a separate account with id 'kiali-bot'.  If you see  strange activities by kiali-bot, please let me know.
> KIALI-563: new real browser smoke test (part 1 & 2)

- src/components/GraphFilter/GraphFilter.tsx
- src/containers/GraphLayersContainer.tsx
- src/types/GraphFilter.ts
The current toggle button visibility filters doesn't look so great on laptop screens and there are some issues with clicking around fast.
This PR deletes the filter toolbar and just places the checkboxes in a popover to conserve screen space (and make it more appealing).
https://issues.jboss.org/browse/KIALI-589
> Kiali 589 remove toggle button filters and replace with popover checkboxes

- src/actions/ServiceGraphFilterActions.ts
- src/actions/__tests__/GraphFilterAction.test.tsx
- src/reducers/ServiceGraphFilterState.ts
Test the Redux ActionCreators to ensure the actions they create are what we think.
The testing part of https://issues.jboss.org/browse/KIALI-654
> Add ActionCreator tests to test the Actions 

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
When switching layouts and something is selected, the graph highlighter erronenously "unfreezes" - meaning the dimming and highlighting gets re-enabled when the graph should still be "frozen" (dimming and highlighting should not be affected on hover). This fixes that problem.
This also fixes multiple callbacks being triggered - turns out for each time the layout was switched, we were calling the callbacks (if we switched layouts 3 times, the callbacks were getting called 3 times). This fixes that, too. Now the callbacks are only ever called at most one time per event.
> KIALI-721 fix the graph highlighter when switching layouts.

- src/components/SummaryPanel/LatencyChart.tsx
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
This PR adds a latency sparkline chart to the edge summary.  It presents our four standard histogram metric values: average, median, 95th and 99th percentiles.  By default the median shows but the legend is clickable to allow selection of the other values.  Hover shows the actual values.
> KIALI-447 Ad latency to edge summary

- src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
It is meant to be passed as a cytoscape option.
The reason it was failing, is because GraphStyle.styles() is an array, so we were
passing each element of that array as index property to be assigned.
e.g. Object.assign({width: '100px'}, ['im', 'an array']) yields
{0: "im", 1: "an array", width: "100px"}
Firefox gets upset because it can't find the property css style "0"
> GraphStyles.styles() was never meant to be passed as a "style" attribute of a DomElement

- src/actions/ServiceGraphFilterActions.ts
- src/actions/__tests__/GraphFilterAction.test.tsx
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/CytoscapeGraph/graphs/GraphBadge.ts
- src/containers/GraphLayersContainer.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- src/reducers/ServiceGraphFilterState.ts
- src/reducers/__tests__/ServiceGraphFilterStateReducer.test.ts
- src/store/Store.ts
Depends on https://github.com/kiali/kiali/pull/188
- Show a badge if API reports missing sidecars for a service. Badge is red to denote a problematic state.
- List the badge of missing sidecars in the node summary.
- Use CSS 'em' units instead of CSS 'transform' to let the browser so vector-based rendering instead of pixel-based rendering of the badges. Now graph badges are sharper regardless of zoom:
> KIALI-661: Graph badges for missing sidecars

- src/actions/ServiceGraphFilterActions.ts
- src/actions/__tests__/GraphFilterAction.test.tsx
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/GraphFilter/GraphFilter.tsx
- src/containers/GraphLayersContainer.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx
- src/pages/ServiceGraph/__tests__/ServiceGraphPage.test.tsx
- src/reducers/ServiceGraphFilterState.ts
- src/reducers/__tests__/ServiceGraphFilterStateReducer.test.ts
- src/store/Store.ts
- src/types/Graph.ts
- src/types/GraphFilter.ts
Got a first pass on this, I had to update some redux actions to better match with this, but not yet using them I would need to connect the GraphFilter to redux and decided that other PR would better fit it.
So i setup the latency scenario like this, using this yml for openshift:
```yaml
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
name: ratings-delay-abort
namespace: bookinfo
spec:
destination:
name: ratings
match:
source:
name: reviews
route:
- labels:
version: v1
httpFault:
delay:
fixedDelay: 1.000s
percent: 100
precedence: 2
```
Delay of 1 second from reviews to rating, I suspect that [this](https://github.com/istio/istio/issues/4323) issue prevents us from seeing the delay from reviews to rating (see gif), but is definetly happening and we can see it from productpage …
> KIALI-679 Allows graph to show latency in the edges

- src/components/GraphFilter/GraphFilter.tsx
- src/components/GraphFilter/GraphFilterToolbar.tsx
- src/components/GraphFilter/__tests__/GraphFilterToolbar.test.tsx
- src/components/Nav/NavUtils.tsx
- src/components/Nav/Navigation.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx
- src/pages/ServiceGraph/index.tsx
- src/types/GraphFilterToolbar.ts
> KIALI-681: Consoliate filter events to new GraphFilterToolbar component

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/SummaryPanel/LatencyChart.tsx
- src/types/GraphFilter.ts
other:
- switch to camel case for edge label options for 'prettier' urls
- fix bug in EdgeLabelMode.fromString
- show latency < 1s as 'ms'
- change edge summary latency chart to default to 95th percentile to
match current graph setting
> KIALI-360 request percentage as new edge label option

- src/components/GraphFilter/GraphFilter.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx
Only write to and read from sessionStorage in top most component to avoid inconsistent props.  To verify the fix please remove appDuration and service-graph-params data in browser storage (Chrome -> developer tools -> Application)
@jshaughn  @mtho11 please review when you get a chance
---
> KIALI-739: filter duration erroneously set to 0

- package.json
- src/actions/MessageCenterActions.ts
- src/actions/__tests__/MessageCenterAction.test.ts
- src/app/App.scss
- src/components/MessageCenter/MessageCenter.tsx
- src/components/MessageCenter/MessageCenterTrigger.tsx
- src/components/MessageCenter/NotificationList.tsx
- src/containers/MessageCenterContainer.tsx
- src/reducers/MessageCenter.ts
- src/reducers/__tests__/MessageCenterReducer.test.ts
- src/store/Store.ts
- src/types/MessageCenter.ts
- tsconfig.json
- yarn.lock
- If the message is not manually dismissed, is still unread in the Message Center, otherwise is marked as read.
- Errors and warnings make the bell icon to show a red ball instead of blue
- Added tests for MessageCenter's action and reducers.
Had to move from es6 to [es2016](http://2ality.com/2016/01/ecmascript-2016.html#the-features-of-es2016) to use `Array.includes` method.
> KIALI-742 Show errors and warnings as a toast notification

- package.json
- src/actions/ServiceGraphFilterActions.ts
- src/actions/__tests__/GraphFilterAction.test.tsx
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/CytoscapeGraph/graphs/GraphHighlighter.ts
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/CytoscapeGraph/graphs/TrafficRenderer.ts
- src/containers/GraphLayersContainer.tsx
- src/reducers/ServiceGraphFilterState.ts
- src/reducers/__tests__/ServiceGraphFilterStateReducer.test.ts
- src/store/Store.ts
- src/utils/MathUtils.ts
- src/utils/__tests__/MathUtils.test.ts
- yarn.lock
This is Work in progress.
- ~~Currently, large edges make quicker dots than small edges~~
- This looked weird, large edges doesn't mean that the packets travel slower from source to target.
It currently uses the rate and latency to decide how fast to display the nodes, I need a more complex scenario with a "fixed" server response to make it easier to test it.
If there is any highlighting, only related edges show traffic
old gifs:
> KIALI-752 Show traffic/latency as dots passing in the edges of the service graph

- .travis.yml
- README.adoc
Travis builds are getting stuck on "yarn test --coverage"
--coverage flags makes the test [slower](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/template/README.md#coverage-reporting) there might be something wrong with our tests that sometimes makes travis unhappy
Disable for now while we check what is really affecting our tests, this should run without errors and i'll restart the test a few times to confirm no errors are there.
> KIALI-762 Fix builds failing

- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/services/__mockData__/getServiceValidations.json
- src/services/__mocks__/Api.ts
- src/services/__tests__/Api.test.tsx
PR #360 will refactor Map() object in all scenarios.
This is a continuation of #364 to use a plain js object instead of Map.
Also, added additional tests for getServiceValidations.
> Fix bad use of Map object on getServiceValidations scenario

- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoRoutes.tsx
- Non unique key for Link (two services pointing to same service triggered it)
- activeHref, activeKey set to <li>, Nav can only hold <NavItem> [1]
I also removed the `dangerouslySetInnerHTML` not sure if is needed for something else.
[1] https://github.com/react-bootstrap/react-bootstrap/issues/2199#issuecomment-245167620
> Remove some warnings that appear on serviceinfo page

- .gitignore
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoPods.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRoute.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDeployments.test.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDescription.test.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoPods.test.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRouteRules.test.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoPods.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteRules.test.tsx.snap
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/types/ServiceInfo.ts
Also now hasIstioSidecar function runs from pods rather than deployments, since not all pods may come from deployments.
Refactoring:
- Create an interface for service details model coming from API. It should be temporary (I'll create a JIRA to merge it with the model class used in ts _[edit: [KIALI-768](https://issues.jboss.org/browse/KIALI-768)]_). It's "ServiceDetailsInfoFromAPI"
- In model coming from the API, replace some "Map" fields with "raw" key-value maps ({ [key: string]: string }). Using Map is incorrect and leads to potential bugs as functions defined in the Map class are not present in runtime, leading to compile-time/runtime mismatch. There was actually a bug where "Map.size" was invoked and never returned the intended result so service labels were never displayed in service …
> KIALI-767 Show pods information + some typesafety refactoring

- src/components/NamespaceDropdown.tsx
- src/components/Nav/Navigation.tsx
- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- This will be the new default.
- The summary sparkline is omitted when 'all' is selected.
> KIALI-673 Add 'all' namespace option for graph page

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/Nav/Navigation.tsx
- src/containers/PfSpinnerContainer.tsx
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
Consolidate the spinners in each of the pages into one spinner located in the header.
Latest working spinner in the header:
This fixes the problem with the page shifting downward when the spinner was engaged.
https://issues.jboss.org/browse/KIALI-841
> Kiali-841 Standardize the isLoading Spinner to Header

- package.json
- src/store/ConfigStore.ts
- yarn.lock
Remove the redux logger since it is too verbose.
We always have Redux Dev tools which does soo much more.
https://issues.jboss.org/browse/KIALI-848
> Kiali-848 Remove Redux Logger (too verbose)

- .travis.yml
This should help in our stalled builds by forcing jest to exit.
```
--forceExit               Force Jest to exit after all tests have
completed running. This is useful when
resources set up by test code cannot be
adequately cleaned up.               [boolean]
```
> KIALI-762 - Force Jest to exit after all tests have completed running

- src/actions/ServiceGraphDataActions.ts
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/Filters/PollIntervalFilter.tsx
- src/components/GraphFilter/GraphFilter.tsx
- src/components/GraphFilter/GraphFilterToolbar.tsx
- src/components/GraphFilter/__tests__/GraphFilterToolbar.test.tsx
- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
- src/components/Nav/NavUtils.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx
- src/reducers/ServiceGraphDataState.ts
- src/types/Graph.ts
- src/types/GraphFilter.ts
The main concern of this PR is to add the polling interval to the Service Graph, however other issues happened when removing the "loading" spinner that made the graph "jump" when loading the data.
#382 Also did the same (removed the loading spinner) so this fixes some issues after that.
- Edges not being up to date after refreshes
- This was was caused because the `cy.json` only diffs the values received, it doesn't replace data and the backend doesn't return empty data (so the empty data is never replaced)
- Badges not being removed between namespace changes
- Badges were removed AFTER updating the json, if we had any badge on an element that would be removed, it would stay there (because we remove the element first and the badge later)
Issues not fixed:
- If going from a one-node layout …
>  KIALI-745 Autoupdate the service graph

- src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRoute.tsx
- src/types/ServiceInfo.ts
Allow weights to have more than one validation per line:
Before hover:
On hover:
Icon on status column correspond to the validation with the highest severity.
This PR needs [kiali/kiali#239](https://github.com/kiali/kiali/pull/239) to be merged.
> Let UI show multiple error/warnings into one DestinationWeight

- src/app/App.tsx
- src/app/History.tsx
- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/components/MetricsOptions/ValueSelectHelper.tsx
- src/pages/ServiceDetails/HistogramChart.tsx
- src/pages/ServiceDetails/MetricChart.tsx
- src/pages/ServiceDetails/MetricsChartBase.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceMetrics.tsx
- src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
This covers both KIALI-758 and KIALI-759.
* The metrics tab in the service details page is now
linkable/bookmarkable.
** As part of this, some cleanup in ServiceDetailsPage.tsx.
** Also, the "group by" options can now be specified in the URL.
* Adding simple links service graph's summary panels to the metrics tab
of the detailed page.
Also, some refactorings in ServiceMetics.tsx:
* The charts were extracted to its own components, making
ServiceMetrics.tsx smaller and some unneeded types were removed.
> KIALI-385: Link from service graph charts to detailed service page charts

- src/actions/ServiceGraphDataActions.ts
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/GraphFilter/GraphFilter.tsx
- src/pages/ServiceGraph/SummaryPanelCommon.ts
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- src/reducers/ServiceGraphDataState.ts
This should fix the following issues:
- When changing from namespace (all nodes on top of each other)
- When receiving rates/latencies, they are not updated accurately and sometimes it shows a different one nor they are removed when the rate/latency is empty.
- Edge labels are not loaded accurately, if selecting one when the metrics don't have rate or latency in place
- Refresh side panel info with the current graph
- Badges are not removed when changing from namespace
> KIALI-861 Prepare service graph for refreshing

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
This will ensure all processing is done appropriate for selecting the graph.
side note: this also changes "this.cy" to the argument "cy" - we want to reference the "cy" object given to this method directly.
> KIALI-870 send the on click message to simulate someone selecting the graph.

- src/actions/ServiceGraphFilterActions.ts
- src/actions/__tests__/GraphFilterAction.test.tsx
- src/components/GraphFilter/GraphFilter.tsx
- src/components/GraphFilter/GraphFilterToolbar.tsx
- src/components/GraphFilter/__tests__/GraphFilterToolbar.test.tsx
- src/containers/GraphLayersContainer.tsx
- src/containers/ServiceGraphPageContainer.ts
- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/reducers/ServiceGraphFilterState.ts
- src/reducers/__tests__/ServiceGraphFilterStateReducer.test.ts
- src/store/Store.ts
- src/types/GraphFilterToolbar.ts
Cleanup the toolbar. There are too many items in it now so it has started overlapping into the next line and doesn't look good. This PR moves the **Show Legend** to a Filter submenu (popover) to conserve space.
https://issues.jboss.org/browse/KIALI-852
> Kiali-852 Fix Toolbar

- src/components/ConfigValidation/ConfigIndicator.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioRuleInfo.scss
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/services/Api.ts
- src/services/__mockData__/getIstioConfigValidations.json
- src/services/__mockData__/getNamespaceValidations.json
- src/services/__mocks__/Api.ts
- src/services/__tests__/Api.test.tsx
- src/types/AceValidations.ts
- src/types/IstioConfigListComponent.ts
- src/types/ServiceInfo.ts
- src/types/__testData__/destinationPolicy.yaml
- src/types/__testData__/destinationRule.yaml
- src/types/__testData__/routeRule.yaml
- src/types/__testData__/virtualService.yaml
- src/types/__tests__/AceValidations.test.ts
- Show validations on IstioConfig list view.
- Filtering and sorting by validation state (valid, not valid, not validated).
- Add markers and annotations on editor in IstioConfig and Service Details.
- Add API for fetching validations per object.
> KIALI-753 Add config validation in IstioConfig

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
This is a bug me and Jay found while doing other things - rather than lose it, I wanted to commit it now as its own PR.
This bug will probably only manifest itself when more than one page wants a cy graph, but at any rate the code is wrong regardless so I want it fixed to prevent any problems in the future.
> cy graph component bug that is hidden and should be fixed now

- package.json
- src/app/App.tsx
- src/components/Nav/Navigation.tsx
- src/store/ConfigStore.ts
- src/utils/Authentication.ts
- src/utils/MessageCenter.ts
- src/utils/__tests__/Authentication.test.ts
- yarn.lock
With this we can persist the state of redux.
**Require**: https://github.com/kiali/kiali-ui/pull/413
- Keep the session and options after refresh app (F5)
- Let puppeter (Itest) navigate to others page for @abonas proposal 
- Fix Bug [Kiali-850](https://issues.jboss.org/browse/KIALI-850)
- Work in the session timeout [KIALI-533](https://issues.jboss.org/browse/KIALI-533) reported by @mtho11 
Documentation : [Redux-persist ](https://github.com/rt2zz/redux-persist) 5582 starts 398 forks
Things to improve.
- Select another kind of storage and encrypt this information. Currently there is no sensitive information so we can do this after.
- **localStorage** `import storage from 'redux-persist/lib/storage'`
- **sessionStorage** `import storageSession from 'redux-persist/lib/storage/session'`
- …
> [Kiali-850] Configure Redux-Persist

- src/pages/ServiceDetails/HistogramChart.tsx
- src/pages/ServiceDetails/MetricsChartBase.tsx
- src/utils/Graphing.ts
Note, this is certainly not a perfect patch. Charts still appear somewhat inconsistent because they may have different heights - which makes them not always aligned. I'm pretty sure we'll get some complains about that :)
However this is IMO still much better than the current state as described in the jira issue ( https://issues.jboss.org/browse/KIALI-741 ), having charts completely unreadable. And I do not have a better solution so far, but if anyone has ideas please let me know.
> KIALI-741 fix chart height issue due to large legend

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/ServiceHealth/HealthDetails.tsx
- src/components/ServiceHealth/HealthIndicator.tsx
- src/components/ServiceHealth/__tests__/HealthDetails.test.tsx
- src/components/ServiceHealth/__tests__/HealthIndicator.test.tsx
- src/components/ServiceHealth/__tests__/__snapshots__/HealthDetails.test.tsx.snap
- src/components/ServiceHealth/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- src/pages/ServiceList/RateIntervalToolbarItem.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/ServiceList/__tests__/RateIntervalToolbarItem.test.tsx
- src/pages/ServiceList/__tests__/__snapshots__/RateIntervalToolbarItem.test.tsx.snap
- src/services/Api.ts
- src/types/RateIntervals.ts
Since this is my first incursion in Graph code maybe I haven't done things as you would have expected, so I'm all ears about comments.
This shows colored borders on nodes for each _service_ (and not _version_).
Example:
This is a first step but maybe discussions can lead to other subtasks being created. Like improving performances, reducing number of calls or showing more information or per-version health maybe.
Currently if performs one backend api call per service, asynchronously from the main graph fetching.
I think it has advantages (graph can be displayed without having to wait for all health information being collected) and drawbacks (many http calls), so probably an optimization will be to fetch health information for all services within a namespace at once.
Then, there is also …
> KIALI-910 Show colored borders to represent health in graph

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/types/GraphFilter.ts
The aim of this PR is to display which communications are being handled using the istio mutual TLS.
[kiali/kiali#269](https://github.com/kiali/kiali/pull/269) needs to be merged at the same time.
Connected to this PR, I have created a UI JIRA for allowing edges to display icons. This would help us to make this feature fancier: https://issues.jboss.org/browse/KIALI-935
> KIALI-750 Add istio mTLS support into service graph

- src/actions/ServiceGraphDataActions.ts
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- src/types/MetricsOptions.ts
This is pending merge of the [server PR](https://github.com/kiali/kiali/pull/287).  
With both PRs in place we won't see istio infra services unless looking specifically at the istio-system namespace, which will not show all services for all namespaces, because all services interact with the istio infra services.
> KIALI-915 UI must now opt-in for istio traffic

- src/components/CytoscapeGraph/graphs/TrafficRenderer.ts
- src/utils/MathUtils.ts
Notice the long edges and loops
Before:
After:
> KIALI-986 Long edges no longer make the animation faster than short edges

- src/components/SummaryPanel/RpsChart.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
The unknown node cannot be broken down to {service name, namespace}
data. But the summary panel received the namespace in its properties.
So, if the namespace is not available in the cytoscape node, use the
namespace provided in the properties of the component.
I'm also adding a small fix to the "No traffic legend" that I saw while testing.
> KIALI-988 Query the API with the right namespace for the unknown node

- src/components/ServiceHealth/HealthIndicator.tsx
- src/pages/ServiceList/ItemDescription.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/ServiceList/__tests__/ItemDescription.test.tsx
- src/pages/ServiceList/__tests__/ServiceListComponent.test.ts
- src/services/Api.ts
- src/services/__mocks__/Api.ts
- src/types/ServiceListComponent.ts
- src/types/ServiceListOptions.ts
- Split list item descriptions into a dedicated component, which receives health as a promise
- On service update, fetch health async and update promise
- Remove ServiceListOptions, not needed anymore
> KIALI-1021 ServiceList: fetch health async

- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationPolicies.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteRules.test.tsx.snap
For route rules, destination policies, destination rules and virtual
services.
This is how it looks for route rules:
For destination policies, virtual services and destination rules, it looks like this:
> KIALI-731: Add button to show YAML of route rules, etc.

- src/components/Details/DetailObject.tsx
- src/components/Details/__tests__/DetailObject.test.tsx
- src/components/Details/__tests__/__snapshots__/DetailObject.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRoute.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices/VirtualServiceRoute.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRouteVirtualServices.test.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
- src/types/ServiceInfo.ts
The main goal of this PR is move all the visuals from RouteRules tab to Virtual Services. Here the result of this PR changes:
This PR needs kiali/kiali#319 to be merged.
> KIALI-1015 Add validations to Virtual Services

- src/app/App.tsx
Use a more typesafe action creator for dispatching actions. Also, consolidate the `isLoading` state into single function.
> Trivial: Use action creators instead of dispatching actions for spinner

- src/actions/HelpDropdownActions.ts
- src/actions/LoginActions.ts
- src/components/About/AboutUIModal.tsx
- src/components/MessageCenter/MessageCenterTrigger.tsx
- src/components/Nav/HelpDropdown.tsx
- src/components/Nav/Navigation.tsx
- src/containers/HelpDropdownContainer.ts
- src/reducers/HelpDropdownState.ts
- src/reducers/index.ts
- src/store/Store.ts
Show a warning message when the Istio version is not supported.
JIRA: [KIALI-269](https://issues.jboss.org/browse/KIALI-269)
**Require**: https://github.com/kiali/kiali/pull/248
- About Modal Refactored
- Now when the user do login an getStatus action is executed and get versions, products and warningMessages (The application no longer asks for a request each time ithe users go to aboutmodal). This trigger to MessageCenter if there is a warningMessage.
_Example with Istio installed 0.7.1 and the Istio required is >= 0.8_
@abonas I don't know if it is better to show a message in the navigation bar between the spinner and the bell icon or it's ok with this. Should we ask to @serenamarie125 ?
> KIALI-269 Warning Message when the Istio version is not supported

- src/app/App.scss
...by increasing opacity.
This will impact all legends of the whole app.
Before:
After:
> KIALI-1061 Make disabled legends more readable

- src/actions/NamespaceAction.ts
- src/actions/__tests__/NamespaceAction.test.ts
- src/containers/NamespaceDropdownContainer.tsx
- src/reducers/Namespaces.ts
- src/reducers/__tests__/NamespacesReducer.test.ts
I couldn't consistently reproduce this bug, it happened to me once, but I suspect the issue is that the namespace request fails [1] and `isFetching` remains `true`, blocking the next refresh [2]
[1] https://github.com/kiali/kiali-ui/blob/master/src/actions/NamespaceAction.ts#L34
[2] https://github.com/kiali/kiali-ui/blob/master/src/actions/NamespaceAction.ts#L42
> KIALI-1025 Set isFetching to false if an error happens

- src/types/AceValidations.ts
allow to print markers and annotations to not valid IstioObjects (not valid objects can have warnings to show).
JIRA: [KIALI-1115](https://issues.jboss.org/browse/KIALI-1115)
Do not merge this branch until we have got kiali/kiali#343 merged.
> KIALI-1115 Allow ACEditor to show warnings

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
Service name and namespace are now grouped into the box and single nodes have their version appended (if any)
Depends on https://github.com/kiali/kiali/pull/347
> KIALI-1119 Nodes from other namespaces now show their version

- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceList/ServiceListComponent.tsx
[UX] Change the term 'Undeployed' to 'Not deployed' for Istio sidecars indication
> KIALI-1147 [UX] Change the term 'Undeployed' to 'Not deployed' for Istio sidecars indication

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/graphs/BreadthFirstGraph.ts
- src/components/CytoscapeGraph/graphs/ColaGraph.ts
- src/components/CytoscapeGraph/graphs/CoseGraph.ts
- src/components/CytoscapeGraph/graphs/DagreGraph.ts
- src/components/CytoscapeGraph/graphs/KlayGraph.ts
Note: Cose still has some sort of overlap, but it seems more related to the overlapping of the group boxes
Before:
After:
Before:
After:
Before:
After:
> KIALI-1113 Avoid overlap of node labels

- src/app/History.tsx
- src/components/Nav/Navigation.tsx
- src/components/Nav/RenderPage.tsx
- src/components/Nav/__tests__/Navigation.test.tsx
- src/routes.tsx
- src/types/Routes.ts
- Refactor
- Now you manage the routes in  /src/components/routes
- Reduce the code and complexity 
- Fix Refresh
> KIALI-1159 FIX Refreshing kiali always redirects to service graph

- src/pages/IstioConfigDetails/IstioRuleInfo.scss
- src/pages/IstioConfigDetails/IstioRuleInfo.tsx
- Present MixerRules in a list/table instead of a list of links
- Separate AceEditor from list/table view for MixerRules
> KIALI-1132 IstioConfig: MixerRules UX refactoring

- RELEASING.adoc
- package.json
This is a tentative PR to gather some feedback on how we should do stuff. Right now we have a v0.5.0 branch on the UI for the latest release, but it was not updated on `package.json`. This is bad for many reasons, one being that there's no way to actually know which snapshot of 0.2.10 is the correct one for the version you're running.
So what's I'm suggesting on this (and we can merge if everyone agrees) is to bump the version on master after the sprint starts, and release the final version after it ends. This is the way most other OSS projects do it, afaik (either that or they keep the latest version number until the release is ready, but I don't like this because it creates a disconnect from what master refers to in comparison to the tag).
What do you guys think?
> KIALI-949 Document our new release process

- src/components/Nav/Navigation.tsx
- src/components/Nav/RenderPage.tsx
- src/components/Nav/__tests__/Navigation.test.tsx
- src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx
- src/routes.tsx
- src/types/Routes.ts
There were several routes in routes.tsx, and laid out in our VerticalNavigation item.
We can extract data from the routes, e.g. from the route definition `/servicegraph/:namespace` we can extract the value `namespace`.
From the url `/servicegraph/all` we have `namespace=all`, `/servicegraph/default` yields `namespace=default`.
The problem is that we had a route `/servicegraph/all` that matched the url `/servicegraph/all` but didn't had any value for namespace (unlike the route `/servicegraph/:namespace`), routes are matched in order, and `/servicegraph/all` was before `/servicegraph/:namespace`
This namespace value is used [here](https://github.com/kiali/kiali-ui/blob/master/src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx#L59).
Fixed this by adding all the routes to `pathRoutes` and …
> KIALI-1176 Fixes routes to get the right namespace

- package.json
- src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
- yarn.lock
Remove the Klay cytoscape libraries now that we are no longer using it.
> KIALI-1171: Remove the Klay cytoscape libraries

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
- src/components/CytoscapeGraph/EmptyGraphLayout.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
This won't block the controls, allowing the user to select a different layout if needed
Bonus:
Simplified the refit operation and this maybe fixed the "all nodes appearing on top of each other".
It was a mix of [KIALI-1166](https://issues.jboss.org/browse/KIALI-1166) and the graph not doing an updateLayout as the first operation (only doing the refit)
> KIALI-1058 Present an error view if the CytoscapeGraph fails

- src/components/CytoscapeGraph/EmptyGraphLayout.tsx
This fixes an unnecessary update when we are changing a property (showing badges, edge label, etc) right when we are "loading".
If we change any property right when is loading, the graph DOM will load again, this will reset pan and zoom.
This prevents this by checking if we changed from no elements to elements (or vice versa), Cytoscape should handle the rest and not the EmptyGraphLayout.
> KIALI-1166 Only update EmptyGraphLayout when needed

- src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx
- src/utils/Enum.ts
- src/utils/__tests__/Enum.test.ts
Made some changes to the Enum utility and fixed a bug when searching the graphType in the Enum. This affected the EdgeLabelMode
> KIALI-1250 Fixes test errors

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
@jshaughn this fixes some of those unknown nodes (most of them anyway). I still see one odd one that I think is this one:
```
{
"data": {
"id": "ad921d60486366258809553a3db49a4a",
"namespace": "istio-system",
"workload": "unknown",
"app": "unknown",
"version": "unknown",
"service": "unknown",
"serviceName": "istio-policy",
"hasMissingSC": true,
"isGroup": "version"
}
}
```
> fix the if-stmt when not workload graph

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/pages/ServiceGraph/SummaryPanelCommon.ts
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
UI is untouched by this PR. 
Most of this is about the sidebar.
I only replaced all the uses of `node.data('service')` by `node.data('app')` (or by `node.data('namespace')` where the actual intend was to get to parse the namespace).
I'm not yet using `workload` anywhere in the sidebar, but we could potentially add that term there 
```
app: [link to app]
workload: [link to workload?]
```
Also, still using the term "service":
> KIALI-1246 Remove all usages of cyNode.data('service')

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
This is one of the 3 ways I think we can solve this issue, by doing a `fit` if we are in the "initial" position
If we move away (pan or zoom) of that initial position, it won't do a `fit` again
Other ways to solve this would be to provide an [Empty State](https://www.patternfly.org/pattern-library/communication/empty-state/) side panel that says something like "Load a graph to show its information".
note: There is "Hello world" on the top right of this gif when the graph is "Loading", this is a quick test of the "Empty State side panel" that forgot to remove previous to recording the gif
> KIALI-1193 Re-fits the graph on every resize if we are on the "initial" pan/zoom level

- package.json
This is necessary to remove external dependencies from the build process when `node_modules` is vendored on the repository.
> Use npm instead of yarn for the build process

- src/pages/ServiceDetails/ServiceMetrics.tsx
Screenshot above shows an application workload sending queries to mongodb (TCP Sent) and receiving responses (TCP Received). The charts are in the "outgoing" column, as the application workload is making the queries.
This screenshot shows the related mongodb workload that receives the queries (TCP Received) and sending back responses (TCP Sent). The charts are in the "incoming" column, as mongo is server-side.
> KIALI-1100 Show charts for TCP metrics

- src/components/ListPage/ListPage.ts
- src/components/NamespaceFilter/NamespaceFilter.tsx
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
This PR addresses the bugs found by QE into KIALI-1173:
1. Switching from ServiceList to IstioConfig changes filter names
2. When removing first filter of a type it got not removed from url
[KIALI-1173](https://issues.jboss.org/browse/KIALI-1173?focusedCommentId=13613114&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13613114)
yes.
First bug:
Second one:
> KIALI-1173 [BUGFIX] Wrong filter renaming + wrong filter removal

- src/components/Details/DetailObject.tsx
Fix issue Service Details when you try to access to the Service Overview with Destination Tule or Virtual Services, DetailObject has an error here when the object is undefined/null in the values.
[KIALI-1288](https://issues.jboss.org/browse/KIALI-1288)
Yes
> KIALI-1288 Fix Services Overview issue with DetailObject Undefined

- src/components/CytoscapeGraph/graphs/GraphBadge.ts
- Try to put the badges in the last div of the cy container
Solves KIALI-1277 by putting the badges in the last div container (currently it was putting the badges in container[0]. That was the panzoom container).
> KIALI-1277 Do not render badges outside the graph area

- src/pages/ServiceGraph/SummaryPanelCommon.tsx
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
Now, nodes in the graph can be of several types. Nodes will be backing
services, so the old links in the headers of the side panel are no
longer valid.  Links to the backing services are now listed in the body
of the side panel (one node can be backing several services).
This commit is also: removing the link to the detailed charts for the
"edge" version of the side panel, since a link cannot be resolved
reliably; fixing titles-headings of the side panels with the right
legends (app, workload, servce).
For nodes, the panel look like this:
For versioned groups, it looks very similar to the previous screenshot. For edges, the look is the following:
> KIALI-1283 Correctly link to service details page

- package.json
- It cancels the commit and warns when trying to commit
"non-pretty" files
`npm run` needs a `--` at the end to signal that we are passing arguments.
> Trivial - Brings back the behavior of the precommit hook

- src/pages/ServiceDetails/ServiceMetrics.tsx
- src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx
- src/pages/ServiceGraph/SummaryPanelCommon.tsx
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- src/services/Api.ts
- src/services/__tests__/ApiMethods.test.tsx.ts
- src/types/Graph.ts
- src/types/Metrics.ts
Refactored the logic to handle the metrics by app(versioned or not) and workload.
Currently it shows the sparklines in the app (versioned and not versioned) when the label app is set. It doesn't (yet) handle when we need to access the workload metrics. 
I'm looking at the server code to create that service or use one if available.
TODO:
This requires: https://github.com/kiali/kiali/pull/385
> KIALI-1231 Refactors panel to handle metrics by app or workload

- src/components/NamespaceFilter/NamespaceFilter.tsx
When initialFilters is an empty [] NamespaceFilter should show the Namespacefilter only.
This is not working well because the currentFilterType.filterValues is empty, we need to set the currentFilterType after the method updateNamespaces()
[KIALI-1289](https://issues.jboss.org/browse/KIALI-1289)
This blocks to [KIALI-1209](https://issues.jboss.org/browse/KIALI-1209)
> KIALI-1289 NameSpaceFilter is not working when the initialFilters is []

- src/pages/ServiceDetails/IstioObjectDetails.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
This avoids the annoyance of re-clicking on the virtualservice/destinationrule tab if the user is browsing the list.
> KIALI-1292 Back link in VS/DR Yaml page goes to corresponding list

- src/components/CytoscapeGraph/graphs/CoseGraph.ts
- src/components/CytoscapeGraph/graphs/LayoutDictionary.ts
- src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
- src/config.ts
Change the layout for 'cose' to 'cose-bilkent'.
Whatever the 'cose' layout is, it doesn't seem to be working properly. We can't find a lot of information about it online, nothing of the configuration options listed here seem to have an affect on it: https://github.com/cytoscape/cytoscape.js/blob/master/documentation/demos/cose-layout/code.js
This fixes both
https://issues.jboss.org/browse/KIALI-1300
https://issues.jboss.org/browse/KIALI-1297
The url changes from displaying 'cose' to 'cose-bilkent'. Anyone with an old bookmark may have to update it.
> KIALI-1300: Change to cose layout to cose-bilkent

- src/pages/ServiceGraph/SummaryPanelGraph.tsx
Service Graph sidepanel has a link to Services page without passing along the selected namespace.  The fix simply appends `?namespace=<active namespace>` to the link.
KIALI-1307
No
> KIALI-1307 added namespace query string to Services link

- src/pages/ServiceGraph/SummaryPanelCommon.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
Removes the sparkline graphs for the service nodes. Service nodes don't have both incoming and outgoing metrics, so we can't display then in the same way as the other node types.
For now we should remove the sparkline graphs for service nodes. But eventually we will need to introduce in single sparkline graph for them.
https://issues.jboss.org/browse/KIALI-1325
Removes the sparkline graph for service nodes. Previously these would be stuck with 'loading graph'
> KIALI-1325: Remove the sparkline graphs for service nodes

- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/types/ServiceId.ts
Service list page is getting the initial filters from the url at constructor. There is no need to set the filters programmatically when clicking the breadcrumbs. It's enough to set parameters directly in the URL of the link.
> KIALI-1310 Fix double-refresh when using breadcrumbs links

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- this is just to make the node more visually pleasing. The unknown label
value is still visible in the side panel.  This helps make istio ingress
and some other infra-nodes look better and can better reflect an unset
version label.
> KIALI-1335 Omit 'unknown' version from app node text

- src/components/NamespaceFilter/NamespaceFilter.tsx
WARNING: this fix has to be in pre-release. It is tagged as critical/blocker bug.
Fixing the following bug:
1. Go to Services page.
2. Filter by "namespace: bookinfo".
3. You will see that it filters and shows the "bookinfo" namespace, then loads all services.
4. Go to Istio Config page. (keeping filter)
5. You will see that it loads all configs from all namespaces, even though 'bookinfo' is in filters.
** Reference **
https://issues.jboss.org/browse/KIALI-1342
yes.
> KIALI-1342 Fixing wrong fiter apply

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/config.ts
- src/types/Health.ts
- solve issues with selection hiding health
- use the same thresholds for health and graph
Here is a link to [kiali-1194]https://issues.jboss.org/browse/KIALI-1194) so that you can see the UX color chart.
This PR also solves [kiali-1280](https://issues.jboss.org/browse/KIALI-1280), which is the same issue but for edges.  Also, see this [UX design PR](https://github.com/kiali/kiali-design/pull/29) for more on the edges.
> KIALI-1194 Node and Edge styling per UX

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
Add ` componentClass={'span'}` in `breadcrumb.Item` to avoid the insertion of element `<a>` inside another element `<a>`
To Fix the warning
```java
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
--
in a (created by Link)
in Link (created by ServiceDetails)
in a (created by SafeAnchor)
in SafeAnchor (created by BreadcrumbItem)
in li (created by BreadcrumbItem)
in BreadcrumbItem (created by ServiceDetails)
in ol (created by Breadcrumb)
in Breadcrumb (created by Breadcrumb)
in Breadcrumb (created by ServiceDetails)
in ServiceDetails (created by Route)
in Route (created by RenderPage)
in Switch (created by SwitchErrorBoundary)
in SwitchErrorBoundary (created by RenderPage)
in div (created by PfContainerNavVertical)
in …
```
> KIALI-1367 Breadcrumb throw an error in console

- package.json
This just removes the convenience command from package.json that 'create-react-app' creates.
We don't ever want to encourage this because then we will have to deal directly with all the webpack stuff and manage it ourselves.
> Trivial: Remove eject script from package.json. 

- src/app/App.scss
Remove extra spacing around breadcrumb (global for all pages). See images and design issue below for exact details. This is a simple SCSS fix.
Jira: https://issues.jboss.org/browse/KIALI-1299
Design Issue: https://github.com/kiali/kiali-design/issues/26
Before: 
After:
Before:
After:
> KIALI-1299: Remove extra spacing around breadcrumb (global)

- README.adoc
- src/app/App.scss
- src/app/App.tsx
Enable selectively building with Patternfly or RCUE(RH productization) based on CLI settings.
This PR dynamically loads the RCUE css stylesheets if specified on the CLI.
By adding a React parameter to the build, we can build using different css libraries (RCUE vs Patternfly).
So to build for RCUE just pass the additional parameter to the build:
```
env REACT_APP_RCUE=true yarn build
```
Or for development:
```
env REACT_APP_RCUE=true yarn start
```
https://issues.jboss.org/browse/KIALI-1131
Yes
Before (Patternfly):
After(RCUE):
QE Instructions:
Visually, the above can be seen to tell the difference between Patternfly and RCUE.
However, if you open the JS console you will find a *debug* level …
> KIALI-1131 Use RCUE for productized Patternfly UI

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
Allows the graph to pick the styles before creating the badges.
Before we had zIndex with 0 on the first draw, and the next draws it picked the zIndex of 10 (the one that is defined in the [GraphStyles](https://github.com/josejulio/swsui/blob/1e52bceba5a5b8320607b85157156e6055213f41/src/components/CytoscapeGraph/graphs/GraphStyles.ts#L146))
Before:
After:
> KIALI-1305 end the graph update batch before creating the badges

- src/components/NamespaceFilter/NamespaceFilter.tsx
- src/pages/AppList/AppListComponent.tsx
- src/pages/AppList/FiltersAndSorts.ts
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/pages/WorkloadList/WorkloadListComponent.tsx
- src/types/NamespaceFilter.ts
Bugs fixed:
1. Filter duplication
2.  Istio filter is now: Present, Not Present (instead of Deployed/Not Deployed)
3. Let filters be updated or appended: e.g. istio filter is a boolean, so have both filters shouldn't exist. Otherwise, namespace filter can be added several times with different values. (This is done to be consistent with the workload list)
4. Before this fix, switching between workload/service/istioconfig list wasn't filtering properly with the filters brought from the previous list.
[KIALI-1323](https://issues.jboss.org/browse/KIALI-1323)
Yes.
[x] Is your pull-request introducing changes in behaviour?
> KIALI-1323 Filtering homogenization

- src/components/CytoscapeGraph/graphs/ColaGraph.ts
KIALI-1232 Set Left to Right flow for graph.
Note: "Flow" direction option is different for each graph type.
- Dadre: already displays L->R as expected
- Cola: changed flow axis from y to x
- Cose: no flow options available.  API [link](https://github.com/cytoscape/cytoscape.js-cose-bilkent#api). 
No
Dagre Before (already flowing L-R by with `rankDir: 'LR'` option)
Dagre After
Cola Before
Cola After
Cose: no flow option available
> KIALI-1232 Explicitly set L -> R flow for graph

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/types/GraphFilter.ts
A new option is added to the "Graph Settings" dropdown to be able to
show TCP traffic in the edges.
Edges with TCP traffic have a cue to be differentiated from those with
HTTP traffic. Coloring for TCP edges is PfBlue-600.
**Backwards in compatible?** It's compatible
> KIALI-1366 Add handling for edges showing TCP traffic

- src/actions/LoginActions.ts
- src/components/Nav/UserDropdown.tsx
- src/components/SessionTimeout/SessionTimeout.tsx
- src/config.ts
- src/containers/UserDropdownContainer.ts
- src/reducers/LoginState.ts
Add a Dialog Box to warn user about session Timeout
All parameters are configurable
```json
/** Configuration related with session */
session: {
/** TimeOut in Minutes default 24 hours */
sessionTimeOut: 24 * UNIT_TIME.HOUR * MILLISECONDS,
/** Extended Session in Minutes default 30 minutes */
extendedSessionTimeOut: 30 * UNIT_TIME.MINUTE * MILLISECONDS,
/** TimeOut Session remain for warning user default 1 minute */
timeOutforWarningUser: 1 * UNIT_TIME.MINUTE * MILLISECONDS
}
```
Changed time session to 24 hours like in openshift console.
See [auth opensihift file](https://github.com/openshift/console/blob/7fad08d27843c8d8e008f3d79d068c374e8dde94/auth/auth_openshift.go#L75) in the line 75 the token for console auth is `expiresIn := (time.Hour * 24).Seconds()` 24 …
> KIALI-1117 Create a Dialog Box to warn user about session Timeout

- src/components/Time/LocalTime.tsx
In Service Details page, avoid showing 'Invalid date' as it follows:
and show this:
The hyphen is shown when time is empty or has invalid format.
https://issues.jboss.org/browse/KIALI-1350
Yes.
> KIALI-1350 Avoid displaying 'Invalid Date' in Service Details page

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/components/SwitchErrorBoundary/SwitchErrorBoundary.tsx
- src/containers/EmptyGraphLayoutContainer.tsx
- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/reducers/ServiceGraphDataState.ts
- src/reducers/__tests__/ServiceGraphDataState.test.ts
- src/store/Store.ts
Adds the error icon and error message to the service graph page when an error occurs.
Jira: https://issues.jboss.org/browse/KIALI-1198
Compatible yes
Before:
After:
> KIALI-1198: Add error icon and message to service graph

- .travis.yml
Updates the release documentation to let it be know that a line has to be removed from the travis.yaml file when doing a release. Otherwise it will add 'snapshot' to the release which is not what is wanted.
Update the .travis.yml file so that it will be able to push out npm packages on tags. Otherwise it will only allow the packages to be pushed from master.
> KIALI-1370 Update release information

- src/pages/ServiceDetails/ServiceDetailsPage.tsx
When visiting virtual service detail page:
1. `Service Info` leads to Service Details page, but listing Virtual Services.
2. `Service: service name` leads to Service Details page, listing default list
Please, reviewers, have in mind that we have an ongoing discussion about breadcrumbs: https://github.com/kiali/kiali-design/issues/9
https://issues.jboss.org/browse/KIALI-1351
yes.
> KIALI-1351 Breadcrumb leads to virtual service list from virtual service

- src/pages/ServiceGraph/SummaryPanelCommon.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
* In the header of the panels, if a workload is being referred, diplay the workload name as a link to the details page.
* In the body of the panels, in the workloads list, also workload names as links to the details page.
> KIALI-1407 Add links to workloads in the graph side panels

- src/components/Metrics/Metrics.tsx
- src/components/Metrics/__tests__/__snapshots__/Metrics.test.tsx.snap
- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
- src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
Showing metrics only for one reporter leads to some gaps in the available data. In order to fill the gaps, a dropdown is added to the metrics page to let the user choose the reporting entity to view the available metrics.
Related to KIALI-1421 KIALI-1422 which are about an issue with an inconsistency in the metrics being shown. This is not really an inconsistency, but a difference in the metrics, depending on the point of view of the reporter. The reporter could be the workload generating the traffic (source) or the workload receiving the traffic (destination).
_By default, inbound metrics are reporter="destination" and outbound are reporter="source"_
> KIALI-1425 Add control to change reporter in the metrics detail pages

- src/components/Details/DetailObject.scss
- src/components/Details/DetailObject.tsx
- src/components/Details/__tests__/__snapshots__/DetailObject.test.tsx.snap
Two things:
1. Shorten indent spaces.
2. Break words in order to show in different lines.
https://issues.jboss.org/browse/KIALI-1349
Yes.
Is your pull-request introducing changes in behaviour?
No.
1. Too many space for each indent.
2. Long words were cut (hidden)
1. Less indent space
2. Long words are wrapped into next line.
> KIALI-1349 DetailObject component: smaller indent + no word cut

- src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/VirtualServiceDetail.tsx
- src/types/ServiceInfo.ts
n Istio 1.0 VirtualServices have a new type of routes called tls. This PR adds those routes to the Virtual Service details page. Including the existent validations.
This PR needs https://github.com/kiali/kiali/pull/467 to be fully working.
https://issues.jboss.org/browse/KIALI-1145
yes.
> KIALI-1145 Add VirtualService TLS routes to details page

- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
When user got into workload/app details page, the console appended 3 times the visit into browser's history.
The problem was that the metrics tab reloaded 2 extra times the metrics container.
https://issues.jboss.org/browse/KIALI-1416
yes.
[NO] Is your pull-request introducing changes in behaviour?
In the following screenshot, you will see that is possible to navigate backwards from app details page to app list with just one click. Same for workload list/details page.
> KIALI-1416 AppDetails and WorkloadDetails pages count just one item in history

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- also, formalize font for node and edge text
@cshinn , @xeviknal ,  This change fixes a regression such that the font-size of edge labels was getting ignored.  The fix involved setting a specific font-family.  The thing is, I can't find any document from UX that specifies a recommended font-family or font-size for node or label text.  So the chosen values are up for review.  See the screenshot below for the values I'm currently using, which are:
font (both node and edge):  Verdana, Arial, Helvetica, sans-serif  // see note
node font-size: 8px
edge font-size: 6px
Note that the font is a list, in order of preference, depending on what is available.  I just chose a common grouping of sans-serif fonts.
> KIALI-1433 Fix edge font-size

- src/pages/ServiceGraph/ServiceGraphPage.tsx
- src/pages/ServiceGraph/SummaryPanelCommon.tsx
- src/pages/ServiceGraph/SummaryPanelEdge.tsx
- src/pages/ServiceGraph/SummaryPanelGraph.tsx
- src/pages/ServiceGraph/SummaryPanelGroup.tsx
- src/pages/ServiceGraph/SummaryPanelNode.tsx
- src/services/Api.ts
- src/utils/Common.ts
Now, a warning is shown in the side panel if data cannot be loaded.
> KIALI-1403 Add error handling to the side panels when loading sparklines

- src/components/Metrics/Metrics.tsx
- src/components/Metrics/__tests__/Metrics.test.tsx
Grafana link was pointing always to Services dashboard, so, in App/Workload details it was showed a wrong empty dashboard.
> KIALI-1434 Fix Grafana link on App/Workload metric pages

- src/pages/ServiceDetails/ServiceDetailsPage.tsx
Fixes the breadcrumb title when switching from yaml tab to overview using the breadcrumb link in virtual service detail page.
https://issues.jboss.org/browse/KIALI-1459
Yes.
> KIALI-1459 VS Breadcrumb fix when switching from yaml to overview

- src/components/Nav/UserDropdown.tsx
[KIALI-1466](https://issues.jboss.org/browse/KIALI-1466)
> KIALI-1466 Session timeout dialog box shows negative seconds remaining for timeout

- src/components/Nav/UserDropdown.tsx
After logout, timers were in place and application couldn't calculate correctly the sessionTimeOut fields.
Debugging showed that timers are added on continuous loggin creating some weird behaviours.
I think that cleaning the timers on logout is enough for this fix.
Tested locally seems to work correctly.
Please, @aljesusg could you take a look ?
https://issues.jboss.org/browse/KIALI-1457
> KIALI-1457 Fix timers left after logout

- package.json
- src/components/About/AboutUIModal.tsx
- src/config.ts
[ ] Is your pull-request introducing changes in behaviour? **No**
--
Links are added to the 'about' dialog.
Links, icons and text are configurable in the config.ts file. The 'about' section config.ts file can be absent completely, or have only the webpage or project sections. The about box will hide and show what is available in the config file.
> KIALI-1380 Add links to the website and github organization

- src/actions/HelpDropdownActions.ts
- src/actions/LoginActions.ts
- src/actions/MessageCenterActions.ts
- src/actions/__tests__/MessageCenterAction.test.ts
- src/components/MessageCenter/MessageCenterTrigger.tsx
- src/components/MessageCenter/NotificationDrawer.tsx
- src/components/MessageCenter/__tests__/MessageCenter.test.tsx
- src/containers/HelpDropdownContainer.ts
- src/containers/MessageCenterContainer.tsx
- src/reducers/MessageCenter.ts
- src/reducers/__tests__/MessageCenterReducer.test.ts
- src/types/MessageCenter.ts
Is your pull-request introducing changes in behaviour? **Yes**
Per some discussion, the notification bell and the "open issues" message
aren't following the pattern suggested by UX. This fixes the behavior of
the messsage center, and the notifications in the main header of Kiali
page.
* Regular kiali errors and warnings (mainly, network errors) will now
show the standard bell with a badge when there are messages in the
message center. If there are errors or warnings, the badge will be red;
other types of messages will show the blue badge (we don't have any of
those kinds as of now). This is the standard PF behavior of the
notification bell and notification drawer.
* The warning "open issues" won't replace the notifications bell. For
now, the only issue that …
> KIALI-1156 Fix behavior of message center; add system errors panel

- src/actions/ServiceGraphDataActions.ts
In graph, lock icon didn't disappear when json stop sending `isMTLS` field. It turns out that there was a missing default value which made the graph to keep the mTLS previous value.
https://issues.jboss.org/browse/KIALI-1235
https://issues.jboss.org/browse/KIALI-1238
Yes.
Is your pull-request introducing changes in behaviour?
Yes.
Lock icon disappears when istio switch from using security connection to non-security one.
> KIALI-1235 Graph: lock icon disappear when json indicates that

- src/pages/WorkloadDetails/WorkloadInfo.tsx
Allow user to see services when there aren't pods in workload details page.
There was a copy&paste error.
https://issues.jboss.org/browse/KIALI-1485
yes.
> KIALI-1485 WorkloadDetails page: allow user to see services when there aren't pods

- src/components/GraphFilter/GraphFilter.tsx
This is to make service graph page more match the other screens with refresh toolbar item on the right instead of left. No changes in behaviour.
https://issues.jboss.org/browse/KIALI-1475
Yes
> KIALI-1475: right align refresh button on service graph toolbar 

- src/pages/AppList/AppListComponent.tsx
- src/pages/WorkloadList/WorkloadListComponent.tsx
bug fix: application and workload lists didnt removed the applied filters on clicking to its respective menu item.
https://issues.jboss.org/browse/KIALI-1482
yes.
> KIALI-1482 Clicking menu items erase applied filters

- src/app/History.tsx
- src/components/Metrics/Metrics.tsx
- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
On both service, app, workload metrics page, when changing options they are mapped into param in the URL. They are not creating a new item in the history because navigation it is not implemented yet.
https://issues.jboss.org/browse/KIALI-1491
yes.
> KIALI-1491 Metrics pages don't propagate the parameters into the URL

- src/components/GraphFilter/GraphFilter.tsx
Change 'Graph type' to 'Graph Type' in service graph toolbar
Yes
> Trivial: In service graph, capitalize 'type' in 'Graph type'

- package.json
- public/env.js
- public/index.html
- src/app/History.tsx
- src/components/About/AboutUIModal.tsx
- src/services/Api.ts
- Frontend changes to support custom context path such as *myapp.com/**kiali***
- By default the app is still served under / unless you specify otherwise during deployment on K8s and OpenShift. (By changing SERVER_WEB_ROOT env variable)
- Please avoid using *absolute* path to reference static assets or API endpoints.  Everything should be relative from `<SERVER_WEB_ROOT>/`  (which can also be "/" ).   
- Adding undefined guards to `AboutUIModal` component to prevent JS error when backend queries fail
- Backend PR https://github.com/kiali/kiali/pull/409
- KIALI-1059
- https://github.com/kiali/kiali/issues/321
Yes
With /kiali
404
> kiali-1059 support custom context path

- src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
Lowers the time between dots for the low request rate, so slower requests will be more continuos
Note that edge unknown -> product page has a higher rate
> KIALI-804 Lowers time between dots for the lower request rates

- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Fix IstioFlag when workload has no pods.
This could be done in backend too, but I guess it is good to have this patch in UI, as probably checkers will be reviewed as part of KIALI-1284.
https://issues.jboss.org/browse/KIALI-1558
> KIALI-1558 Fix IstioFlag in WorkloadDetails when there are not pods

- src/config.ts
This allows much safer & easier usage of config() from other places, as now it's typed (the `deepFreeze` function was removing all type info).
No expected visual change, no configuration change.
> [Trivial] Spread config() type for type-checking & better IDE integration

- src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
Adds traffic animation to TCP edges
The idea was to give the traffic of TCP somewhat different because it represents bytes per second and not requests, so an option is to put more of these "balls" in the edge, but it looks plain and hard to see if the balls are small. 
I tried to give it a little of depth by moving some balls out of the edge (see first screenshot).
I post both screenshots so people (UXD) can compare and see which one makes more sense (maybe none of them)
With traffic not completely aligned with the edge
With traffic aligned to edge
> KIALI-1515 Adds traffic animation for TCP

- src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
I reduced the size of the green dots and red triangles for HTTP traffic.
Here's what they look like - with slow rate and a little faster rate:
> KIALI-1563 smaller dots in animation

- src/components/Filters/NamespaceFilter.ts
- src/components/Filters/StatefulFilters.tsx
- src/components/ListPage/ListPage.ts
- src/components/ListPage/__tests__/ListPage.test.tsx
- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/AppList/AppListComponent.tsx
- src/pages/AppList/AppListPage.tsx
- src/pages/AppList/FiltersAndSorts.ts
- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/ServiceList/ServiceListPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/pages/WorkloadList/WorkloadListComponent.tsx
- src/pages/WorkloadList/WorkloadListPage.tsx
- src/types/Filters.ts
This PR has 2 commits:
- ab2f864 takes back the rollbacked PR #667
- 1527eed fixes found issues afterward (KIALI-1562)
The first one was already reviewed, the addition bring by the second are:
- Move more logic into StatefulFilters
- Now shared-memory filters is the "source of truth" (before i was more ambiguous between URL and shared mem)
- As a consequence, when linking with filter, 'onclick' must be set to update shared mem (it was sometimes done before, but not always)
- Some other bits simplified, hopefully not too much
- Also, from Summary Graph panel, replace the "Services list" link to Apps list, as it seems to be a forgotten step from earlier devs.
> KIALI-1543 - continuing list filters refactoring

- src/components/SummaryPanel/RpsChart.tsx
- src/pages/Graph/SummaryPanelCommon.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/Graph/SummaryPanelGroup.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/utils/Graphing.ts
TCP sparklines will be shown only if the selected node, group or edge
has any TCP traffic.
The HTTP charts will also show this behavior: they will be hidden if
there is no HTTP traffic.
So, if a node is "unused" no charts will appear.
** Backwards compatible? ** It should be compatible
Node only with TCP traffic:
Node with both TCP and HTTP traffic - very similar for versioned group box (this is zoomed in the browser, panel will usually show scrollbars):
Edge:
Note: Per https://issues.jboss.org/browse/KIALI-1401, the edges shouldn't have both TCP and HTTP. So, I only tested individual cases.
Graph (namespace; no selected item in graph):
_This panel won't hide any graph_
> KIALI-1099 Add TCP charts to side panel

- src/pages/Graph/SummaryPanelCommon.tsx
Egress nodes don't have a details page. Omitting the links.
> KIALI-1526 Don't display links in side panel for egress nodes

- src/pages/Overview/OverviewPage.tsx
They were accidentally removed
(cf KIALI-1528 for overall task)
> Overview page: add back titles in links

- src/components/About/AboutUIModal.tsx
On some cases and build environments, there is no Git available for the
About UI, showing empty parens instead of the usual commit hash. This
fixes the case on both UI and core versions.
> Fix About UI when there's no commit info

- src/components/Metrics/Metrics.tsx
- src/containers/AppMetricsContainer.tsx
- src/containers/ServiceMetricsContainer.tsx
- src/containers/WorkloadMetricsContainer.tsx
Expand link uses react-router to inject an URL parameter to show the expanded graph. Because the metrics component is redux-wrapped, redux was preventing the component to re-render because redux was unaware of the parameter change.
Re-wrapping the redux-wrapped components into react-router solves the issue.
> KIALI-1503 Fix expand link not taking effect until data refresh

- .travis.yml
Forces the dev build in travis to avoid using rcue in upstream builds
> KIALI-1564 Always run build:dev in travis

- src/app/App.tsx
- src/reducers/GlobalState.ts
- src/reducers/GraphDataState.ts
- src/reducers/HelpDropdownState.ts
- src/reducers/LoginState.ts
- src/reducers/MessageCenter.ts
- src/reducers/Namespaces.ts
- src/reducers/UserSettingsState.ts
- src/store/ConfigStore.ts
- src/utils/Authentication.ts
- src/utils/MessageCenter.ts
Properly initialize the **redux** store with defaults instead of starting with an undefined state.
Initialize the Redux store with defined defaults instead of starting with a _undefined_ store that gradually fills in based on requests eventually populating the redux store.  Even then, there might be gaps in the store being populated because certain queries or parts of the application have not been accessed.
This also has implications into Redux _known_ state. If anything is undefined, we really don't know what state it should be -- an initial known state is a much better starting point.
Some of this seems to be pushed via the new version of Redux 4.0
https://issues.jboss.org/browse/KIALI-1573
This became a blocker to: …
> KIALI-1573: Properly initialize the redux store with defaults

- src/pages/Graph/SummaryPanelGraph.tsx
It was showing a counter for "services" and another one for "edges". Given that there are several kinds of "nodes" this is fixing the "services" counter and adding the missing ones.
> KIALI-1408 Fix node counters in the namespace side panel

- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/Graph/SummaryPanelNode.tsx
Fixing the logic to choose between source side and destination side telemetry for the TCP case.
The namespace and node side panels will now correctly show TCP charts.
> KIALI-1601 Fix side panels not showing TCP charts in some cases

- src/components/ListPage/ListPage.ts
- src/pages/Overview/FiltersAndSorts.ts
- src/pages/Overview/OverviewPage.tsx
- src/pages/Overview/OverviewToolbar.tsx
Also:
- avoid refresh after changing sort field, it's not needed
- reverse sort order for status: by default, failures first
JIRA: https://issues.jboss.org/browse/KIALI-1618
> KIALI-1618 Overview: sort namespaces after refresh

- src/app/History.tsx
- src/components/Metrics/HistogramChart.tsx
- src/components/Metrics/MetricChart.tsx
- src/components/Metrics/Metrics.tsx
- src/components/Metrics/MetricsChartBase.tsx
- src/components/Metrics/__tests__/Metrics.test.tsx
- src/components/Metrics/__tests__/__snapshots__/Metrics.test.tsx.snap
- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/components/MetricsOptions/MetricsSettings.tsx
- src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
- src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/Graph/SummaryPanelCommon.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/types/Metrics.ts
- src/types/MetricsOptions.ts
- src/utils/Graphing.ts
JIRA: https://issues.jboss.org/browse/KIALI-936
Needs backend PR https://github.com/kiali/kiali/pull/514 in order to work.
- Consume new REST api for quantiles
- Add new url params for metrics options (and centralize declaration of URL parameters)
- Use enums for metrics object types and in/out direction
- Use the new Refresh component in Metrics, delegating management of polling job
- C3 Charts: need to tell explicitely which series to unload
- Add quantile 0.999 (hence rename percentile => quantile)
Screenshot:
> KIALI-936 Enhance metrics page

- src/components/SummaryPanel/ResponseTimeChart.tsx
- src/components/SummaryPanel/RpsChart.tsx
- src/pages/Graph/SummaryPanelCommon.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelGroup.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/types/Graph.ts
- Add Service to graph type selector
- For service node side panels:
- stop showing inbound/outbound graphs, only one graph with new title
- add 'hide' option to RpsChart and TcpChart and ResponseTimeChart
- For edge side panels:
- don't support any charts for service-to-service edges in the new graph type
- the graph already performs aggregation, so show the bar chart.  But to
do that aggregation in the sparklines would be difficult, so just omit it
- fix a bug that could leave "Loading graph..." message displayed
> KIALI-1534 Introduce Service Graph

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/graphs/ColaGraph.ts
- src/components/CytoscapeGraph/graphs/CoseGraph.ts
- src/components/CytoscapeGraph/graphs/DagreGraph.ts
- The fix for this is to revert part of KIALI-1291, which introduced a wipe
of the graph elements prior to a layout change.  From what I can tell we
don't need that anymore. But if we do we'll need to revisit this issue.
- also, turn off the 'fit' option on the layouts, we don't need to fit during
the batch operation, we do a fit at the end.
> KIALI-1649 maintain health and selections after layout change

- package.json
- tsconfig.json
- tslint.json
- tslint.prod.json
Instead of failing the build when using `yarn start`, it lets you work.
The normal lint will run automatically as part of the build and the precommit hook.
I'm not sure if we want to get this in, but please share your thoughts
> Remove tslint errors from the 'start' process

- src/pages/AppList/AppListClass.tsx
- src/pages/AppList/AppListComponent.tsx
- src/pages/AppList/FiltersAndSorts.ts
- src/pages/ServiceList/FiltersAndSorts.ts
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/pages/WorkloadList/ItemDescription.tsx
- src/pages/WorkloadList/WorkloadListComponent.tsx
- When rate interval changes, do not trigger an explicit reload as state change will trigger one (avoiding 2 reloads for the same action)
- When fetching backend data, filter it before calling for health (avoiding unnecessary health fetch)
- Remove incorrect health fetching from workloads 'ItemDescription' that triggered additional and incorrect queries
JIRA: https://issues.jboss.org/browse/KIALI-1695
> KIALI-1695 Performance issues on apps/svc/workload list pages

- src/actions/GraphDataActions.ts
- src/actions/GraphFilterActions.ts
- src/actions/__tests__/GraphFilterAction.test.tsx
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/GraphFilter/GraphFilterToolbar.tsx
- src/components/GraphFilter/__tests__/GraphFilterToolbar.test.tsx
- src/containers/GraphPageContainer.ts
- src/containers/GraphSettingsContainer.tsx
- src/pages/Graph/GraphPage.tsx
- src/reducers/GraphDataState.ts
- src/reducers/GraphFilterState.ts
- src/reducers/__tests__/GraphFilterStateReducer.test.ts
- src/store/Store.ts
- src/types/GraphFilterToolbar.ts
This allows for cleaner layouts and faster refresh when the option is off.  It is off by default in this PR.  We could easily change the default based on user feedback.
Option on:
Option off:
> KIALI-1696 Make showing unused nodes optional

- src/config.ts
- src/services/Api.ts
Moved const loginHeaders from `src/services/Api.ts` to `src/config.ts`.
**Issue reference**
https://issues.jboss.org/browse/KIALI-1700
**Backwards compatible?**
Yes
> [KIALI-1700] Move const loginHeaders to config.ts

- src/components/Filters/StatefulFilters.tsx
- src/pages/AppList/AppListComponent.tsx
- src/pages/AppList/ItemDescription.tsx
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/ServiceList/ItemDescription.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/ServiceList/__tests__/ItemDescription.test.tsx
- src/pages/WorkloadList/ItemDescription.tsx
- src/pages/WorkloadList/WorkloadListComponent.tsx
Callback of some async data fetches were trying to update the state of
already umounted components. This was causing some errors to appear in
the browser console.
Currently, errors aren't causing any problems, but by stopping further
processing when component umounts this may prevent future problems.
> KIALI-1597 Don't try to update state on umounted components

- src/actions/GraphActions.ts
- src/components/GraphFilter/GraphFilterToolbar.tsx
- src/reducers/GraphDataState.ts
- Because graph type and node type interact, make sure we reinit cy
when fundamentally changing the graph (as we already do on namespace change)
> KIALI-1706 Initialize Cy on graph type change

- src/components/Metrics/HistogramChart.tsx
- src/components/Metrics/MetricChart.tsx
- src/components/Metrics/Metrics.tsx
- src/components/Metrics/MetricsChartBase.tsx
- src/components/Metrics/__tests__/__snapshots__/Metrics.test.tsx.snap
- src/components/MetricsOptions/MetricsLabels.ts
- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/components/MetricsOptions/MetricsSettings.tsx
- src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
- src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
Enables filtering based on label values. Example: while showing metrics per remote app, we can now hide metrics by app.
JIRA: https://issues.jboss.org/browse/KIALI-1687
Screenshot:
> KIALI-1687 (followup): Metrics page, add dynamic labels filtering

- package.json
Standardize the package.json structure via: - https://www.npmjs.com/package/sort-package-json
This arose out of the need to see both _dependencies_ and _dev-dependencies_ near one another -- as their versions are linked -- most especially with the '@types/*' stuff for typescript definitions.
Obviously, others have already solved this issue.
https://issues.jboss.org/browse/KIALI-1725
yes
> KIALI-1725: Standardize package.json via sort-package-json 

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/services/Api.ts
- src/types/Health.ts
This requires server-side PR: https://github.com/kiali/kiali/pull/551.
@jmazzitelli The DNM label is there only because of the dependency on the server pr merge.
> KIALI-1728 Add Service Health to the Graph and Service Summary

- src/components/About/AboutUIModal.tsx
- src/components/Nav/Navigation.tsx
- src/components/Pf/PfInfoCard.tsx
- src/config.ts
- src/logos.ts
- src/pages/AppDetails/AppInfo/AppDescription.tsx
- src/pages/AppList/AppListClass.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/WorkloadList/ItemDescription.tsx
Application configuration and style/logo configuration are different separations of concerns and deserve different configurations. Also, this makes it easier for UxD to change.
https://issues.jboss.org/browse/KIALI-1726
Yes
> KIALI-1726: Move Logo images into their own config file 'logos.ts'

- src/store/ConfigStore.ts
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>
right now, the persist key is hard-coded as `root` in config. it may conflict with other application which is also using `persist:root` as key in localStorage. Since Kaili supports customize base path (fixed in https://github.com/kiali/kiali-ui/pull/569) so that we should get the WEB_ROOT instead of hardcode.
Yes
> Customize persist key

- src/components/MessageCenter/MessageCenterTrigger.tsx
The system errors make the yellow triangle appear, the blue dot appear
on unread notifications and red dot appears when any unread error appears
systemErrors are errors, they will make the red dot appear, but when read the
dot will dissapear.
Before:
After:
> KIALI-1673 Removes systemError count dependency from the blue/red dot

- src/types/AceValidations.ts
TLS validations weren fully shown as HTTP and TCP ones.
https://issues.jboss.org/browse/KIALI-1739
This PR is adding TLS and TCP subset validations: https://github.com/kiali/kiali/pull/565
> KIALI-1739 Counting last line for drawing validations into ACEditor

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/pages/Graph/SummaryPanelEdge.tsx
- src/utils/TrafficRate.ts
- tslint.json
It is typescript best practices to use `Number()` instead of `parseFloat()` as it is typesafe and won't parse garbage as `parseFloat` does.
For further information on this: https://stackoverflow.com/questions/23437476/in-typescript-how-to-check-if-a-string-is-numeric/23440948#23440948
Yes
Non-UI change
> Remove 'parseFloat' and replace with Typescript 'Number()' for type safety

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/pages/Graph/GraphRouteHandler.tsx
Typescript type assertions don't cast the type of the variables. The
_injectServiceNodes variable was being assigned a string instead of a
boolean. This was causing a test failure in
GraphSettingsContainer.constructor, leading to toggling the "Services
nodes" display option.
This ensures that the rigth value and type is assigned to
_injectServiceNodes.
https://issues.jboss.org/browse/KIALI-1769
> KIALI-1769 Fix wrong type at variable assignment

- src/actions/GrafanaActions.ts
- src/actions/LoginActions.ts
- src/components/About/AboutUIModal.tsx
- src/components/Metrics/Metrics.tsx
- src/components/Metrics/__tests__/Metrics.test.tsx
- src/components/Metrics/__tests__/__snapshots__/Metrics.test.tsx.snap
- src/components/Nav/Navigation.tsx
- src/components/Nav/__tests__/Navigation.test.tsx
- src/containers/NavigationContainer.ts
- src/containers/ServiceMetricsContainer.tsx
- src/reducers/GrafanaState.ts
- src/reducers/index.ts
- src/services/Api.ts
- src/store/ConfigStore.ts
- src/store/Store.ts
- src/types/GrafanaInfo.ts
Now we can see the url services in the status after the merge of https://github.com/kiali/kiali/pull/573 . /api/status provide us of the urls and versions now. So we only need to check one time to get all the urls
When the jaeger url is empty we have not menu item in the navigation
behaviour in Firefox with https popup, now we have not warning message.
[KIALI-1587](
https://issues.jboss.org/browse/KIALI-1587)
> KIALI-1587 Jaeger link tries to open popup

- package.json
- src/components/Details/__tests__/__snapshots__/DetailObject.test.tsx.snap
- src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap
- src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
- src/components/Metrics/__tests__/__snapshots__/Metrics.test.tsx.snap
- src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
- src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
- src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
- src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
- src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoPods.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRoutes.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/pages/ServiceList/__tests__/__snapshots__/RateIntervalToolbarItem.test.tsx.snap
- yarn.lock
- Revert typescript and react-script-ts upgrade (KIALI-1553) due to dependency issue with tests and Jest libs.  See also https://github.com/wmonk/create-react-app-typescript/issues/417
- Update test snapshots
KIALI-1814
Yes
> Kiali-1814 Revert typescript and react-script-ts upgrade 

- src/config.ts
- src/services/Api.ts
Moved API URLs from `src/services/Api.ts` to `src/config.ts`.
**Issue reference**
https://issues.jboss.org/browse/KIALI-1701
**Backwards compatible?**
Yes
> KIALI-1701 Move API URLs to a config file

- src/components/ListPage/ListPageLink.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioRuleInfo.tsx
- src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
- src/services/Api.ts
- src/types/IstioConfigDetails.ts
- src/types/IstioConfigList.ts
- src/types/Permissions.ts
Related backend PR: https://github.com/kiali/kiali/pull/566
Also, we may want to have tasks for istio objects creation & update ready before we merge this one, as "delete" capability alone could sound a little weird?
JIRA: https://issues.jboss.org/browse/KIALI-1651
> KIALI-1651 Add delete action on istio object page

- src/components/NamespaceDropdown.tsx
- src/components/ToolbarDropdown/ToolbarDropdown.tsx
- src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
This restores the refresh of the namespaces list when the dropdown is opened.
https://issues.jboss.org/browse/KIALI-1792
> KIALI-1792 Fix graph dropdown not updating namespace list

- src/pages/Graph/SummaryPanelEdge.tsx
Fix sparkline issue for edge leading from service and including traffic from unknown
- make sure this fix does not break the fix in kiali-1732 for TCP sparkine
for edges leading from a service.
After the fix we have both sparklines correct, The http sparkline combines  traffic from unknown and ingress:
The TCP traffic is shown corrrectly as well:
> KIALI-1830 Fix sparkline issue for edge leading from service

- src/components/SummaryPanel/ResponseTimeChart.tsx
- src/components/SummaryPanel/RpsChart.tsx
Sometimes, the "No traffic logged" statement is false. There may be data, but the available data is not enough to show stats or graphs.
> KIALI-1826 Change side panel "No traffic logged" to "Not enough traffic to generate chart"

- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
Long labels are cut off
[X] Is your pull-request introducing changes in behaviour?
For before see 
Now:
Note: perhaps we should in the longer run not have the labels as part of the table, but rather
as a row that is as wide as the whole table.
> KIALI-1827 Resize columns to allow for longer labels.

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
- src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts
In order to keep compound nodes from being bigger than needed, a pre-process is done on the input to:
1. Remove child nodes and reserve enough size for them.
2. Create synthetic edges to replace edges that go or leave from a compound node.
After the layout is finished, the child nodes are added back and the synthetic edges are removed.
This should work for any discrete layout and any dynamic layout that issues `layoutstop`.
This allows us to keep all the compound nodes as tight as possible, preventing overlap (if the layout prevents that) as the layout positioning only happen on 1st level nodes and we should not have any unwanted surprise when a child node is positioned  (by the layout) on the top left of the screen while the other is positioned on the bottom …
> KIALI-1800 Avoid overlapping of compounds nodes

- src/actions/GraphDataActions.ts
- src/actions/NamespaceAction.ts
- src/actions/__tests__/NamespaceAction.test.ts
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/GraphFilter/GraphFilter.tsx
- src/components/GraphFilter/GraphFilterToolbar.tsx
- src/components/GraphFilter/__tests__/GraphFilterToolbar.test.tsx
- src/components/NamespaceDropdown.tsx
- src/components/Nav/NavUtils.tsx
- src/config.ts
- src/containers/GraphPageContainer.ts
- src/containers/GraphSettingsContainer.tsx
- src/pages/Graph/GraphPage.tsx
- src/pages/Graph/GraphRouteHandler.tsx
- src/pages/Overview/OverviewPage.tsx
- src/reducers/NamespaceState.ts
- src/reducers/__tests__/NamespacesReducer.test.ts
- src/routes.tsx
- src/services/Api.ts
- src/services/__mocks__/Api.ts
- src/services/__tests__/Api.test.tsx
- src/services/__tests__/ApiMethods.test.tsx.ts
- src/store/Selectors.ts
- src/store/Store.ts
- src/types/Graph.ts
- rely on redux state change to update activeNamespace
- avoid pushing URLs to force change
- avoid handler 'drill-down'
- support bookmarkability
- trust URLs as the truth on initial navigation
- trust redux for state change after initial navigation
- keep URL reflecting current state
- separate redux-managed state from session-managed state
*** Requires Server PR https://github.com/kiali/kiali/pull/622 ***
*** The server PR is because this incorporates the fix for 1542 ***
> Kiali 1782 Handle activeNamespace in a more consistent way

- src/components/Filters/NamespaceFilter.ts
- src/components/ListPage/ListPageLink.tsx
- src/pages/Overview/OverviewPage.tsx
- src/pages/Overview/OverviewStatus.tsx
When clicking on a status icon in overview (ex: degraded in namespace X), it will bring you to the Apps list page with namespace=X and health=degraded filters.
JIRA: https://issues.jboss.org/browse/KIALI-1561
> KIALI-1561 Add status-filtered links to overview page

- src/pages/Graph/SummaryLink.tsx
@mwringe pointed me to the correct lock icon  (pficon-private), so there is no longer a re-use of the fa-lock icon and no an inaccessible node and it's links are handled with the same image.
> KIALI-1852 User proper lock icon for inaccessible link in side panel

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/GraphFilter/GraphFilter.tsx
- src/components/GraphFilter/GraphFilterToolbar.tsx
- src/containers/GraphSettingsContainer.tsx
- src/pages/Graph/GraphPage.tsx
- src/pages/Graph/GraphRouteHandler.tsx
- src/types/GraphFilterToolbar.ts
- add connected components as needed
- replace direct store access with property-based access
- Use XxxContainer naming for connected components and access them directly
- Avoid inner code from having to both push a URL and perform redux init,
centralize the logic in GraphRouteHandler; when processing a URL now
ensure that for a new graph we do redux initializiation as needed.
also:
- make a tweak to the focus graph filter toolbar, don't show namespace dropdown
because going forward it will be unable to show multiple namespaces.
> KIALI-1892 avoid direct access to the redux store

- src/pages/WorkloadList/FiltersAndSorts.ts
Disabling non-deployment workload feature. It will allow helm users to properly install kiali.
Base branch is v0.9.0, not v0.9.1. Using 0.9.1 it would be the undo a little bit trickier because there is the deletion feature included.
Had to revert the feature manually, because git-revert would mess the whole codebase.
Backend reference: https://github.com/kiali/kiali/pull/646
It should fix the following issues:
#644
#623
> Rolling back non-deployment workload list

- src/components/GraphFilter/GraphFilter.tsx
- src/components/GraphFilter/GraphFilterToolbar.tsx
- remove access to duration in the redux store
- remove the container, it's no longer currently needed
@israel-hdez This is the follow up PR to your review comment in 1880 about simplifying GraphFilter because it did not need to access "duration" in the store.
> KIALI-1894 Simplify GraphFilter component

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
Adds a real layout for the contents of the compounds nodes, we were using a "vertical" layout and now we are using dagre that works better with https://github.com/kiali/kiali-ui/pull/820
Before:
After:
Before:
After:
> KIALI-1916 Use dagre for the layout of compound nodes

- src/components/GraphFilter/GraphRefresh.tsx
- src/containers/GraphRefreshContainer.tsx
Removal of the old unused `onSelect` methods and while we are in here... separate the Redux properties from react properties for better comprehension of react/redux props.
Yes
No visual changes just code cleanup.
> Trivial: remove old unused methods from GraphRefresh

- src/components/Refresh/Refresh.tsx
- src/containers/OverviewPageContainer.ts
- src/containers/RefreshContainer.tsx
- src/pages/Overview/OverviewToolbar.tsx
- src/pages/Overview/__tests__/OverviewPage.test.tsx
This PR uses redux global state to enable synchronization of the refresh rate with other pages in the application. So refresh rates appear consistent in their state between screen navigation. Adds reduxification of Refresh component.
This is the quick low-risk fix for this issue as this just provides common global state between multiple components. The ultimate solution would be to create a new common `Refresh` component that is shared all over the application. However, we still have design and unanswered questions on this so here is the immediate fix.
https://issues.jboss.org/browse/KIALI-1887
Next steps:
https://issues.jboss.org/browse/KIALI-1929
Yes
> KIALI-1887: Make sure overview page refresh rate is in sync with other pages

- src/actions/LoginActions.ts
- src/app/__tests__/App.test.tsx
This allows the UI to anonymously log in when the server allows for anonymous login (that is, it does not require credentials when submitting requests).
https://issues.jboss.org/browse/KIALI-1958
Yes.
Before, if the server did not have credentials defined thus allowing for anonymous access, the UI console would still show you the login screen (at which time the user would be able to type any username and any password and the login would succeed - that is because the credentials were ignored on the server).
Now, if you go to any URL in the UI console, and the server allows for anonymous access, the UI console will not ask for the user to type in username and password; instead, the UI console will consider itself …
> KIALI-1958 allow for anonymous access without requiring login screen

- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
In destination Rules, within Service Details has a trafficPolicy layout broken in subset column.
https://issues.jboss.org/browse/KIALI-1806
Before:
After:
> KIALI-1806 Fixing broken layout for destination rules in Service Details

- src/app/History.ts
- src/pages/Overview/FiltersAndSorts.ts
- src/pages/Overview/NamespaceInfo.ts
- src/pages/Overview/OverviewPage.tsx
- src/pages/Overview/OverviewStatus.tsx
- src/pages/Overview/OverviewToolbar.tsx
- src/pages/Overview/__tests__/OverviewPage.test.tsx
- src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
- Add switch between app-based health and workload-based health
- In toolbar, some perf enhancements as refresh is not needed in every component change, and prevents unnecessary change checks & state updates (less renders)
- Remove unused function setActiveNamespace
JIRA: https://issues.jboss.org/browse/KIALI-1878
Screenshoft:
> KIALI-1878 Overview: allow to switch to workloads health

- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
- src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
Adding missing icon to DR list within Service Details page.
https://issues.jboss.org/browse/KIALI-1919
Following the pattern from VS, which is:
Here you have the DR one:
> KIALI-1919 Add status for destination rules list into service details page

- src/components/Health/__tests__/HealthDetails.test.tsx
- src/components/Health/__tests__/HealthIndicator.test.tsx
- src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/pages/AppList/AppErrorRate.tsx
- src/pages/AppList/FiltersAndSorts.ts
- src/pages/ServiceList/FiltersAndSorts.ts
- src/pages/ServiceList/ServiceErrorRate.tsx
- src/pages/ServiceList/__tests__/ItemDescription.test.tsx
- src/pages/ServiceList/__tests__/ServiceErrorRate.test.tsx
- src/pages/ServiceList/__tests__/ServiceListComponent.test.ts
- src/pages/WorkloadList/ErrorRate.tsx
- src/pages/WorkloadList/FiltersAndSorts.ts
- src/types/Health.ts
- src/types/__tests__/Health.test.ts
In order to bring a better idea about where to look for issues, provide the detail about if errors are for incoming connections or for outgoing connections (or both). This is shown in health pop-overs.
Since pop-over is shared across all Kiali, all pop-overs got the details except for service health where only inbound health is available.
https://issues.jboss.org/browse/KIALI-1873
**Dependant PR:** https://github.com/kiali/kiali/pull/647
Example screenshot:
> KIALI-1873 Show inbound/outbound error rate for requests health

- src/components/Tour/Tour.tsx
Before, when focusing on a node, the tour would take space (hidden) at the bottom of the page, making a space to appear.
This fixes it
Before
The after is the same image without the empty bottom space :)
> KIALI-1999 Ensure Tour doesn't take any space when hidden.

- src/actions/GraphDataActions.ts
- src/actions/NamespaceAction.ts
- src/actions/__tests__/NamespaceAction.test.ts
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/GraphFilter/GraphFilterToolbar.tsx
- src/components/Nav/NavUtils.tsx
- src/containers/EmptyGraphLayoutContainer.tsx
- src/containers/GraphPageContainer.ts
- src/containers/GraphSettingsContainer.tsx
- src/containers/NamespaceDropdownContainer.tsx
- src/containers/OverviewPageContainer.ts
- src/pages/Graph/GraphPage.tsx
- src/pages/Graph/GraphRouteHandler.tsx
- src/pages/Graph/SummaryLink.tsx
- src/pages/Graph/SummaryPanel.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/Graph/SummaryPanelGroup.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/reducers/NamespaceState.ts
- src/reducers/__tests__/NamespacesReducer.test.ts
- src/services/Api.ts
- src/store/Selectors.ts
- src/store/Store.ts
- src/types/Graph.ts
- src/types/GraphFilterToolbar.ts
- src/types/Namespace.ts
- src/utils/Common.ts
- Handle multiple namespaces in the sidebar
- Add key attribute to some elements
- Uses PromiseRegistry to ignore requests
- Avoids loading an "empty" namespace
- Unselects cy object when the graph is destroyed
This PR adds support for multiple namespaces to the redux store and the graph page, but it doesn't do any change to the Namespace Component (is a subset of #802).
I think this will be easier to review/merge and later we can focus only on the dropdown component and its interaction.
Yes
No UI changes.
> KIALI-2000 Prepares redux and graph page for multiple namespaces

- .gitignore
Remove old unused `kiali-browser-test.png` from `.gitignore`. This is old from when we were saving the browser image snapshots.
Yes.
No new behaviour.
> Trivial: Remove old unused kiali-browser-test.png from .gitignore. 

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
When navigating trough pages, is required to resize the canvas upon mounting the components.
Is backwards compatible
> KIALI-2047 Ensure the cy canvas is resized when mounting

- .travis.yml
- Makefile.jenkins
- RELEASING.adoc
This is disabling releasing through Travis. Now, only "edge snapshots"
will be published by Travis. Released snapshots and released versions
will now be published in a Jenkins Pipeline.
This also adds a Makefile.jenkins to support the automatic
release process.
https://issues.jboss.org/browse/KIALI-1982
> KIALI-1982 Prepare repository to automate releases

- src/actions/GrafanaActions.ts
- src/reducers/GrafanaState.ts
So that grafana link isn't displayed when server is configured with `display_link: false`
> KIALI-2056 Handle Grafana response returning 204

- src/components/MissingSidecar/MissingSidecar.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoWorkloads.test.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
- src/types/ServiceInfo.ts
JIRA: [KIALI-1200](https://issues.jboss.org/browse/KIALI-1200)
The Jira is an old one , now we have not pods in services so after read comments(@lucasponce & @xeviknal ), I did these changes:
- Now we can see in the list of workloads in a service of they have missing Istio Sidecar like @lucasponce proposed. @abonas I set the icon with tooltip (see demo) next to the name of the workload, It's ok in this place under the perspective of UX ?
- Improved component MissingSidecar to let a new attribute "**tooltip**" iff with this we'll have the **text** like a tooltip and not in the right of the icon.
- Added to the types/WorkloadOverview the istioSidecar value.
> KIALI-1200 Istio sidecar indicator should be present on pods and not only as summary on service

- src/actions/GraphDataThunkActions.ts
- src/actions/NamespaceThunkActions.ts
- src/actions/__tests__/NamespaceAction.test.ts
- src/components/GraphFilter/GraphFilter.tsx
- src/components/NamespaceDropdown.tsx
- src/components/Nav/NavUtils.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
- src/reducers/NamespaceState.ts
- src/reducers/__tests__/NamespacesReducer.test.ts
KIALI-1724 Removes the 'all' namespace
Allows to select multiple namespaces instead of only one or all.
This allows a more fine-grained selection of the namespaces that we care in a single view.
This PR only focuses on having the component in the graph page but it could very well be used in other pages. 
> KIALI-1390 Multiple namespace filter on the graph

- package.json
- src/components/Filters/StatefulFilters.tsx
- src/components/Health/HealthIndicator.tsx
- src/components/MessageCenter/NotificationDrawer.tsx
- src/components/Metrics/__tests__/Metrics.test.tsx
- src/components/SessionTimeout/SessionTimeout.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigList/FiltersAndSorts.ts
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
- src/services/__mockData__/getServiceDetail.json
- src/store/Selectors.ts
- src/types/ServiceInfo.ts
- yarn.lock
Update the more _compile-time_ oriented packages:
- prettier                      1.13.4  →    1.15.3
-  tslint-no-circular-imports     0.5.0  →     0.6.1
-  typescript                     3.1.3  →     3.2.1
https://issues.jboss.org/browse/KIALI-2076
Yes
No new behaviour
> KIALI-2076: Upgrade typescript and prettier

- package.json
- yarn.lock
We no longer do code coverage and there are no coverage scripts in package.json anymore.
Yes
No.
> Trivial: Remove 'coveralls' library since we no longer do coverage

- src/components/Metrics/Metrics.tsx
- src/components/Metrics/__tests__/Metrics.test.tsx
- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
- src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/Graph/SummaryPanelCommon.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelGraph.tsx
- src/pages/Graph/SummaryPanelGroup.tsx
- src/pages/Graph/SummaryPanelNode.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/services/__mocks__/Api.ts
- src/services/__tests__/ApiMethods.test.tsx.ts
- src/types/Metrics.ts
- src/types/MetricsOptions.ts
Reporter and Direction now have to be provided in the query, to avoid fetching too many unnecessary metrics
As a consequence, response model doesn't include them anymore
No functional change expected.
JIRA: https://issues.jboss.org/browse/KIALI-2086
backend PR: https://github.com/kiali/kiali/pull/710
> KIALI-2086 More optimized metrics API

- src/pages/Graph/GraphPage.tsx
- it was only refreshing on toggleOn, but we want the info to disappear immediately when disabled
> KIALI-2100 refresh graph immediately on toggle of showUnused and showSecurity

- src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
- src/components/GraphFilter/GraphFilter.tsx
- src/components/NamespaceDropdown.tsx
- src/components/Nav/RenderPage.tsx
- src/components/Nav/SecondaryMasthead.tsx
- src/components/Pf/PfContainerNavVertical.tsx
- src/pages/Graph/GraphPage.tsx
- src/routes.tsx
This is only for the graph page, but it prepares for other pages
to use it.
Moves the namespace selector to a secondary masthead in the GraphPage
Moving the namespace of place, but still works as before
> KIALI-2075 Move namespace selector to a secondary masthead

- src/app/App.tsx
Run in StrictMode to catch any deprecated lifecycle methods. Also note: This does nothing when compiled in production so its safe to leave in code. The lifecycle violations will show up as warnings in the console.
https://reactjs.org/docs/strict-mode.html
Yes
No
> Trivial: Run in StrictMode to catch any deprecated lifecycle methods

- .snyk
- package.json
- yarn.lock
This PR was created as a direct result of https://github.com/kiali/kiali-ui/pull/864 since the library upgrades resulted in Snyk violations that would not allow it to be merged. So splitting the snyk remediation file from the upgrades is what this PR is about. 
**NOTE**: there is now a `snyk` command in `package.json` that can be used by CI (it runs `snyk test`)  if needed to identify vulnerabilities as early as possible. It is probably not necessary in CI but anyway, it can be run without having additional global npm packages installed locally.
_Also_: There is an update to `react-scripts-ts` to get rid of a higher priority vulnerability. That is why the jest snapshots changed.
https://issues.jboss.org/browse/KIALI-2109
** Backwards …
> KIALI-2109 Snyk install for vulnerability remediation

- src/actions/LoginThunkActions.ts
- src/components/GraphFilter/GraphRefresh.tsx
- src/components/Metrics/Metrics.tsx
- src/components/MetricsOptions/MetricsOptionsBar.tsx
- src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
- src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
- src/components/Refresh/Refresh.tsx
- src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
- src/config/config.ts
- src/containers/WorkloadMetricsContainer.tsx
- Move the Grafana Link to the topbar
- Add the grafana Link to Workload Metrics 
- Move displaying metrics last x minutes to the toolbarRight
JIRA: [KIALI-2129](https://issues.jboss.org/browse/KIALI-2129)
> KIALI-2129 UXD: Move the grafana link to the topbar

- src/pages/Graph/SummaryPanelGroup.tsx
- now that app boxes can contain service nodes we can not assume all
app box child nodes have a version.
> KIALI-2132 Only show valid version label for app box children

- package.json
- yarn.lock
Remove the `@types/node` from package.json since we don't do any node.js server-side stuff. So no need for the node typing libs.
> Trivial: Remove the @types/node from package.json 

- package.json
- yarn.lock
Fixes a bug that prevents some nodes from being removed when adding
and removing the unused nodes
> KIALI-2110 Updates to cytoscape 3.3.1

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
from: $app \n $version \n $namespace (if any)
to:   $app \n $namespace (if any) \n $version
Before:
After:
> KIALI-2200 Changes the label order of non-parent nodes

- src/components/NamespaceDropdown.tsx
Fixes an issue where the incorrect id was being used in the page.
Since there was two components with the same id on the page, the tour component wasn't properly selecting the right one.
The tour component was also expecting a component to be named 'namespace-selector' to be available. Since this id didn't exist, the tour component would get confused and cause a failure when trying to access this id.
https://issues.jboss.org/browse/KIALI-2195
> KIALI-2195 Fix issue with the first graph tour element

- src/types/AceValidations.ts
Makes the ACE Editor's validation errors part skip the metadata part when evaluating yaml paths for validation error markers. This is because the marker does not really understand yaml but parses matching words in the strings / lines and the metadata part can include the same matching words as part of the kubernetes annotations.
KIALI-2023
> KIALI-2023 Make aceValidation parseMaker skip the metadata part 

- src/pages/Graph/GraphPage.tsx
- We need to use booleans when doing conditional rendering to avoid
passing the raw values to react.
The zero was appearing because `this.props.graphTimestamp` has the value `0`, that value is given to the renderer.
> KIALI-2221 Remove 0 on graph screen when no namespace is selected

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Save a flag to prevent multiple Prompt invocations on Istio Config editor
https://issues.jboss.org/browse/KIALI-2248
> KIALI-2248 Prevent to show multiple Prompts when abandon the editor page

- src/components/Metrics/MetricsChartBase.tsx
JIRA: https://issues.jboss.org/browse/KIALI-2230
Note: backend PR is also part of the work to split in two columns, but can be merged independently: https://github.com/kiali/kiali/pull/780
> KIALI-2230 Reduce charts height and do not adjust anymore

- package.json
- yarn.lock
- Unused compound nodes were not removed on update
- App box labels were getting father away from the box
[KIALI-2191](https://issues.jboss.org/browse/KIALI-2191)
[KIALI-2210](https://issues.jboss.org/browse/KIALI-2210)
> KIALI-2191 KIALI-2210 Updates cytoscape to 3.3.2 to receive bug fixes

- src/app/App.scss
Only allow the toast width to take up the maximum space of its parent (the ToastNotificationList).
Before this change toasts could be larger than the screen and be rendered behind the left navigation bar.
https://issues.jboss.org/browse/KIALI-1636
Before:
After:
> KIALI-1636 Confine toast width to the toastnotificationlist

- package.json
- yarn.lock
This is an optional tool to visualize the relative package sizes in the project.
First step: `yarn build`
Then: `yarn run analyze`
> Add source-map-explorer to visualize relative package sizes

- src/components/IstioWizards/IstioWizard.tsx
- src/components/IstioWizards/IstioWizardDropdown.tsx
- src/components/IstioWizards/Slider/BootstrapSlider.tsx
- src/components/IstioWizards/Slider/Boundaries.tsx
- src/components/IstioWizards/Slider/DropdownMenu.tsx
- src/components/IstioWizards/Slider/Slider.tsx
- src/config/Config.ts
- src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/services/Api.ts
- src/types/IstioConfigList.ts
- src/types/IstioObjects.ts
- src/types/Permissions.ts
This PR enables two operations at Service detail level:
- Create A/B Traffic Routing.
- Delete ALL Traffic Routing.
Basically to not need to go into individual configs to delete all Istio linked with a particular service.
The Wizard only performs a "Create" operation, and it's enabled when service has not defined any prior configuration (for existing configuration, standard YAML edition is enabled).
The A/B patter is extended in a generic way, meaning that it works for 1..N cases, the wizard will control the weights between the workloads and it will create a basic DestinationRule/VirtualService pair.
> KIALI-2256 Wizard for creating traffic rules 

- src/reducers/LoginState.ts
This requires kiali PR https://github.com/kiali/kiali/pull/811
Once that PR and this PR are built and running, if the Kiali secret is missing, the user will see this message on the login screen:
> KIALI-2303 - provide a user-friendly message indicating that the Kiali secret is missing

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
- src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
- src/components/GraphFilter/GraphFind.tsx
- src/components/GraphFilter/__tests__/GraphFind.test.tsx
- src/pages/Graph/GraphHelpFind.tsx
- src/store/Selectors/GraphData.ts
- Use the same DSL as Graph Find for filtering.
- Also
- fixes issue with finding no traffic
- adds 'trafficsource' operand to node help
- removes unnecessary 'traffic' field from cy node and edge elements
@abonas @mwringe There is also a container for this: https://hub.docker.com/r/jshaughn/kiali tag filter.  I'm not sure if we need a UX design issue for this or if it OK from a design perspective.
> KIALI-1774 Graph Hide

- src/components/MissingSidecar/MissingSidecar.tsx
- src/pages/AppDetails/AppInfo/AppDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap
[KIALI-2057](https://issues.jboss.org/browse/KIALI-2057)
Added missing istio sidecar when worklaods not have istio sidecar deployed with a tooltip.
> KIALI-2057 Istio sidecar indicator should be present on Workloads and not only as summary on Application

- src/components/Health/HealthDetails.tsx
- src/components/Health/HealthIndicator.tsx
- src/components/Health/__tests__/HealthDetails.test.tsx
- src/components/Health/__tests__/HealthIndicator.test.tsx
- src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/pages/AppDetails/AppInfo/AppDescription.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
- src/types/Health.ts
- src/types/__tests__/Health.test.ts
Now tooltip content is displayed right below the big health indicator, not as a tooltip anymore.
It replaces the previous "report" text.
For small indicator (in list views) it's unchanged, still as a tooltip
Moving popover & overlay components from HealthDetails to HealthIndicator
> KIALI-2036 fix inaccurate wording and redesign health report

- src/components/Metrics/Helper.ts
- src/pages/Graph/GraphPage.tsx
- src/pages/Overview/OverviewStatuses.tsx
- src/services/Prometheus.ts
- src/services/__tests__/Prometheus.test.ts
Istio 1.1 has updated the scrape interval for relevant metrics from 5s to
15s, presumably to reduce metric collection intensity.  This affects the
rateInterval/step param calculation we do in the UI, resulting in "single-dot"
sparklines for "Last Minute" durations, and affects other calls as well.
The change increases the minimum step to include 2 data points (making rate()
for short durations basically the same as irate()).  This provides us with at
least a minimal sparkline graph of 3 points.
Additionally, do a little refactoring for this compute method and set things
up for a possible follow-on that adds scrap interval to the server config.
The new 3-dot sparklines for a 1 minute duration:
> KIALI-2352 Update prom rate query param calculation given change in scrape interval

- src/app/History.ts
- src/components/Metrics/CustomMetrics.tsx
- src/components/MetricsOptions/MetricsRawAggregation.tsx
- src/types/MetricsOptions.ts
Add an operator dropdown for custom dashboards to allow different aggregations across pods.
Possible values: min, max, sum, avg, standard deviation, standard variance.
Backend PR: https://github.com/kiali/kiali/pull/829
> KIALI-2362 Allow different operators than "sum" for raw metrics

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigList/FiltersAndSorts.ts
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
- src/types/IstioConfigDetails.ts
- src/types/IstioConfigList.ts
MeshPolicies are now listed and detailed into Istio Config section.
Requires PR: https://github.com/kiali/kiali/pull/831
https://issues.jboss.org/browse/KIALI-2311
** Backwards incompatible? **
yes
** Screenshots **
> KIALI-2311 Add support to display MeshPolicies items

- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/Overview/OverviewStatuses.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
This fixes an issue when user navigates to another workload from Kiali.
The URL updates and the page should fetch the data of the newly
requested workload.
https://issues.jboss.org/browse/KIALI-2357
Before:
After:
> KIALI-2357 Fetch data when a new workload (URL) is requested

- src/assets/img/graph-legend.svg
https://issues.jboss.org/browse/KIALI-2334
Each browser may render SVG differently, because of available fonts. This fixes size issue for Firefox. Chrome will show more white space at the right of the legend.
Before:
After:
> KIALI-2334 Fix legend sizing for Firefox

- src/components/Tour/Tour.tsx
I was using a resize callback to know if the pointed element moved from place, to refresh. 
When opening the popperjs element on the "edge" before the browser pushed the refresh section to the bottom it caused the browser to push and pull the refresh section, triggering resize events (of the dom element) and requesting an update to the popperjs element (which looped this).
Adding debounce to group these events into one and avoiding the re-trigger.
There is still a small flicker when starting, probably something from popperjs or Floater (or maybe even us, not sure), but is way more usable now.
Notice that this only happens if the window width is so that if is slighly less, it will cause the refresh to be pushed down.
> KIALI-2318 Debounce resize detection events to avoid the flickering-loop

- src/components/DebugInformation/DebugInformation.tsx
- Blocks textarea from resize it horizontally.
- Sets min height
Avoids duplicating the error message (the second one was confusing and implied that the text didn't get copied)
Also prevents the textarea from being resized to overflow the modal box
> KIALI-2377 Remove error message as the library takes care of that.

- src/components/CytoscapeGraph/graphs/GraphHighlighter.ts
When hovering highlight the element's neighborhood but when selected
highlight the end-to-end paths involving the element.
For example, a selected edge before:
A selected edge after:
> KIALI-2013 Extend highlighting for selected graph element

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigList/FiltersAndSorts.ts
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
- src/types/IstioConfigDetails.ts
- src/types/IstioConfigList.ts
- src/types/IstioObjects.ts
Adding support to RbacConfig, ServiceRole and ServiceRoleBindings to IstioConfig.
It allows list, view, update and delete.
Backend: https://github.com/kiali/kiali/pull/842
https://issues.jboss.org/browse/KIALI-2381
yes.
> KIALI-2381 Adding support to RbacConfig, ServiceRole and ServiceRoleBindings to IstioConfig

- src/components/GraphFilter/GraphFind.tsx
Instead of always using the redux property, it checks if we already started any typing and uses that value.
> KIALI-2388 Prevent filter and hide fields from reseting on refresh

- src/pages/Graph/SummaryPanelEdge.tsx
When updating `SummaryPanelEdge`, it used values for the other type (HTTP vs TCP) as undefined but on object creation we were using (and considering) an empty array. 
This lead that when switching from TCP to HTTP the used reqAvg state value was "undefined" and crashing the rendering.
Fixed that by always using the empty array as a default value.
> KIALI-2430 Ensure default values are used for SummaryPanelEdge  state

- src/components/Health/__tests__/HealthDetails.test.tsx
- src/components/Health/__tests__/HealthIndicator.test.tsx
- src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/AppList/AppListClass.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/ServiceList/__tests__/ItemDescription.test.tsx
- src/pages/ServiceList/__tests__/ServiceListComponent.test.ts
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/pages/WorkloadList/WorkloadListComponent.tsx
- src/services/Api.ts
- src/services/__tests__/ApiMethods.test.tsx.ts
- src/types/Health.ts
- src/types/__tests__/Health.test.ts
When pods are not istio-sidecared, just omit requests errors in health
(or in case of ServiceHealth where this is the only item checked, just write n/a - no sidecar)
JIRA: https://issues.jboss.org/browse/KIALI-1469
> KIALI-1469 Do not report "no requests" in health on missing sidecar

- src/components/IstioWizards/IstioWizardDropdown.tsx
This PR fixes the frontend, filtering workloads from Wizard without proper labels.
Without app/version, Wizard can't automatically fill a DR, so that step should be done manually via the YAML editor.
https://issues.jboss.org/browse/KIALI-2419
> KIALI-2419 Workloads used in Wizard contains proper labels to build a DestinationRule

- src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/VirtualServiceRoute.tsx
Wrong formatted Virtual Service now doesn't break the console.
This is just a quick patch bc we accorded to strong type the backend (and also rely on Galley) to ensure that all the data from backend have proper formats.
https://issues.jboss.org/browse/KIALI-2150
> KIALI-2150 Fix VirtualService Route graph

- package.json
- src/actions/JaegerThunkActions.ts
- src/actions/LoginActions.ts
- src/actions/LoginThunkActions.ts
- src/actions/NamespaceThunkActions.ts
- src/actions/__tests__/LoginAction.test.ts
- src/components/Nav/UserDropdown.tsx
- src/config/config.ts
- src/containers/LoginPageContainer.ts
- src/containers/NavigationContainer.ts
- src/containers/UserDropdownContainer.ts
- src/pages/Login/LoginPage.tsx
- src/pages/Login/__tests__/LoginPage.test.tsx
- src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
- src/reducers/LoginState.ts
- src/services/Api.ts
- src/services/Login.ts
- src/services/__tests__/ApiMethods.test.tsx.ts
- src/store/Store.ts
- src/types/Auth.ts
- src/types/Common.ts
- src/utils/AuthenticationToken.ts
- src/utils/__tests__/Authentication.test.ts
- yarn.lock
This is a big one, and touch many parts of the system, so it should be reviewed with care.
The main idea here is to enable Openshift users to authorize themselves using the OAuth interface provided, and as doing so, also simplifying the task of adding new behaviours and protocols for the user to authorize from.
Following [Kent Beck's](https://twitter.com/kentbeck/status/250733358307500032) advice, to do something hard, you refactor the code until it becomes easy, then do the easy change.
1. All endpoints for authentication (generating tokens, validating tokens) now return the same interface:
```typescript
export interface Session {
token: string;
expiresOn: string;
username: string;
}
```
The usual expiration time calculation was removed, so now the endpoint returns when the token is …
> KIALI-1185 Implement Openshift OAuth support

- src/actions/GraphDataThunkActions.ts
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
- src/components/GraphFilter/GraphFilter.tsx
- src/components/GraphFilter/GraphSettings.tsx
- src/pages/Graph/GraphHelpTour.ts
- src/reducers/GraphDataState.ts
- src/reducers/__tests__/GraphDataState.test.ts
- src/types/GraphFilter.ts
- also, a little clean up/space optimization
Before:
After:
Note that the 95th percentile info has been moved to the help:
> KIALI-1594 Reflect current edge label mode in dropdown

- src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/VirtualServiceDetail.tsx
- src/types/IstioObjects.ts
Parse gateway hostname to FQDN and then generate a correct link to the YAML, without assuming it is in the same namespace.
KIALI-2402
> KIALI-2402 Fix link to gateway in another namespace

- src/types/IstioObjects.ts
It updates Istio Config object mapping to add "kind" and "apiVersion" into the yaml editor.
https://issues.jboss.org/browse/KIALI-2442
It requires backend PR https://github.com/kiali/kiali/pull/886
> KIALI-2442 Map kind and apiVersion attributes

- src/components/MetricsOptions/MetricsDuration.tsx
- src/components/MetricsOptions/MetricsRawAggregation.tsx
- src/components/MetricsOptions/MetricsReporter.tsx
JIRA: https://issues.jboss.org/browse/KIALI-2492
We should not expect changes to be caught on re-rendering, we can deal with it before (as soon as the change hook is called)
> KIALI-2492 Fix changing duration in metrics page

- src/components/IstioWizards/IstioWizard.tsx
- src/components/IstioWizards/MatchingRouting.tsx
When Matching Wizard is empty and Galley is not working/configured propery. Wizard has "Create" button enabled and it can create an incompleted pair of VS/DR.
With this PR, Matching Wizard only can create VS/DR when matching rules are defined.
https://issues.jboss.org/browse/KIALI-2495
** Some screenshots **
> KIALI-2495 Do not create VS/DR when Matching Wizard is empty

- src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
This change allows a user to not provide a runtime for a given dashboard (ex: an application-specific dashboard) so that it won't appear in runtimes list
JIRA: https://issues.jboss.org/browse/KIALI-2481
> KIALI-2481 filter empty runtimes (minor change)

- src/components/CytoscapeGraph/CytoscapeGraph.tsx
The call to get health information may not return health for every node. There
are valid use cases for no health (like no traffic for the health calc period).
Change to log no health at debug level and only log an error if the call to the
backend fails.
> KIALI-2484 fix console log error for NA health use case

- src/components/GraphFilter/GraphFind.tsx
- give better indication of problematic expression element
- make more generic (apply better to both find AND hide)
- remove full expression from error messages in anticipation of showing
messages co-located to hide/find inputs (not in message center)
> KIALI-2476 Improve error messages for Graph Find/Hide

- src/components/IstioWizards/IstioWizard.tsx
- src/components/IstioWizards/IstioWizardDropdown.tsx
Minor change.
When onCreate is invoked, disable the "Create" button to avoid multiple clicks.
https://issues.jboss.org/browse/KIALI-2463
> KIALI-2463 Block Wizard Create button until it has finished

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
Removes the giant lock icon from the application grouping box.
https://issues.jboss.org/browse/KIALI-2504
Before:
After:
> KIALI-2504 Don't show the lock icon on the grouping box

- src/types/IstioConfigList.ts
IstioConfig list now shows validations for:
- MeshPolicy
- Policy
- ClusterRbacConfig
- ServiceRole
- ServiceRoleBinding
There are only validations for MeshPolicy at the moment. However, KIALI-2392 should add validations for the latest 4 config types.
https://issues.jboss.org/browse/KIALI-2486
yes
> KIALI-2486 Adding Policy and MeshPolicy validations to IstioConfigList

- src/pages/Graph/GraphHelpFind.tsx
Applies the current suggestions from @jstickler and @abonas : 
- Add preface text
- Rename tips
- Rearrange tabs
- Update some of the existing help text
The result for feedback:
> Kiali 2478 Graph Find/Hide help improvements

- src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
- src/components/Metrics/CustomMetrics.tsx
- src/reducers/GrafanaState.ts
- src/reducers/HelpDropdownState.ts
- src/reducers/LoginState.ts
- src/reducers/MessageCenter.ts
- src/utils/Reducer.ts
- tslint.json
Let's replace this old javascript Object.assign() syntax with the current object spread syntax. It's just more descriptive and therefore easier to grok.
This adds the tslint rules to enforce this.
- https://palantir.github.io/tslint/rules/prefer-object-spread/
- https://redux.js.org/recipes/using-object-spread-operator
- https://davidwalsh.name/merge-objects
> Add new tslint rule to eliminate the old Object.assign() syntax with ES6+

- src/components/IstioWizards/IstioWizard.tsx
Matching Routing Wizard introduced some spaces when parsing values.
That created non valid configuration; only when Galley is up un running it can be detected.
https://issues.jboss.org/browse/KIALI-2533
> KIALI-2533 Fix trim space in Matching Routing Wizard

- src/components/JaegerIntegration/JaegerToolbar.tsx
Minor change to indicate users that Min / Max Duration referes to spans, not traces.
> KIALI-2545 Include Span in Min / Max Duration labels

- src/actions/LoginActions.ts
- src/actions/LoginThunkActions.ts
- src/app/App.tsx
- src/components/Nav/UserDropdown.tsx
- src/components/SessionTimeout/SessionTimeout.tsx
- src/config/config.ts
- src/containers/UserDropdownContainer.ts
- src/pages/Login/LoginPage.tsx
- src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
- src/reducers/LoginState.ts
- src/reducers/MessageCenter.ts
- src/services/Api.ts
- src/store/Store.ts
https://issues.jboss.org/browse/KIALI-2273
also: https://issues.jboss.org/browse/KIALI-2518
* SessionTimeout was not appearing because of a time unit mismatch (seconds vs milliseconds)
* Extend session feature was not working. UI cannot extend the session by itself; it needs back-end's help. Now the "extend session" button will make the required request to extend the session successfully. *Note:* If Oauth login is configured, the session cannot be extended.
* "Friendly message" (motivation of KIALI-2273)... Instead of displaying an error in the message center, the user will be redirected to the login page:
**This requires https://github.com/kiali/kiali/pull/903**
> KIALI-2273 Fix SessionTimeout dialog

- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelNode.tsx
It is not valid to specify 'tcp' as the request_protocol when calling for
metrics because request_protocol applies only to request count metrics (I.e. istio_requests_total)
> KIALI-2552 Don't use request_protocol metrics option with TCP

- src/pages/Graph/SummaryPanel.tsx
https://issues.jboss.org/browse/KIALI-2500
This will properly avoid rendering of the hide/show tab of the side panel when there is no side panel rendered.
> KIALI-2500 Fix rendering hide/show tab when no graph

- src/components/ToolbarDropdown/ToolbarDropdown.tsx
Warning message was: 
Warning: [react-bootstrap] Specifying only the `"hover"` trigger limits the visibility of the overlay to just mouse users. Consider also including the `"focus"` trigger so that touch and keyboard only users can see the overlay as well.
> [Minor] Fix warning about accessibility issue

- src/components/Metrics/MetricsChartBase.tsx
This is to prevent some data types (currently bytes and bitrates) to be downscaled as "milli-bytes" / "µbps" which are quite uncommon. At the same time, introducing IEC-based versus SI-based data units.
Now, some unit types are recognized from the dashboards renderer and processed in a specific way.
Other units / non-recognized ones continue to fall under the standard SI scaler
JIRA: https://issues.jboss.org/browse/KIALI-2438
Backend PR: https://github.com/kiali/kiali/pull/925
> KIALI-2438 Metrics dashboards to manage non-SI underscaling like bytes

- src/components/Nav/Navigation.tsx
- src/config/serverConfig.ts
- src/types/ServerConfig.ts
**Describe the change**
Add the new installation tag var to the server config and set that as the tab title on login. Default will be "Kiali Console".
Related server PR - [#926](https://github.com/kiali/kiali/pull/926)
**Issue reference**
[JIRA KIALI-1987](https://issues.jboss.org/browse/KIALI-1987)
**Backwards compatible?**
Yes
> KIALI-1987 Add installation tag to serverConfig

- src/actions/JaegerActions.ts
- src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/types/Health.ts
- Same col span for Health in App/Workload/Service
- Align Ports/Endpoints
https://issues.jboss.org/browse/KIALI-2369
Using same wording and grid/col(3) for Health in all pages:
> KIALI-2369 Fix style on Service Details:

- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
The two first fixes are trivial.
@xeviknal the WithErrorBoundary class doesn't seem to need the component attribute, as it uses the TabPane inside:
```
const TabPaneWithErrorBoundary = withErrorBoundary<TabPane.propTypes>(TabPane);
export default TabPaneWithErrorBoundary;
```
So I think it's safe, but just take a look and let me how it looks there.
> KIALI-2547 JS warnings in App/Workload/Service details

- src/components/IstioWizards/MatchingRouting.tsx
Fix style of matching rule
https://issues.jboss.org/browse/KIALI-2588
https://issues.jboss.org/browse/KIALI-2576
Buttons are disabled in case there is a validation message:
Text of matching rule is changed to address KIALI-2576, minor adjustments in style to support large header names.
> KIALI-2588 Fix headers without name

- src/components/MessageCenter/NotificationDrawer.tsx
- src/components/MessageCenter/__tests__/MessageCenter.test.tsx
- src/reducers/MessageCenter.ts
- src/reducers/__tests__/MessageCenterReducer.test.ts
- src/types/MessageCenter.ts
This keeps repeating error messages from piling up in the message drawer.
It now works like the Openshift messages with a count of how many times the notification message is repeated and for how long the same notification has been going on.
https://issues.jboss.org/browse/KIALI-907
yes
no, just changes the way the messages are presented
**Old**:
**New**:
> Kiali-907: Error messages pile up infinitely.

- src/components/IstioWizards/MatchingRouting.tsx
The "Route to" div could overlap the floating "actions" layer and make the button non clickable.
This is a fix to put the floating layer always on top.
https://issues.jboss.org/browse/KIALI-2612
> KIALI-2612 Fix non-clickable remove button

- src/components/ErrorBoundary/WithErrorBoundary.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
Use TabPaneWithErrorBoundary instead of WithErrorBounday. This last one doesn't show which Component was rendering for real.
https://issues.jboss.org/browse/KIALI-2606
> KIALI-2606 Using TabPaneWithErrorBoundary instead of plain implicit WithErrorBoundary

- src/components/IstioWizards/MatchingRouting.tsx
Matching Wizard doesn't not explicit indicate that an empty Matching will mean "Match any request".
That may lead in some confusion to the user, a first workaround can be to explicit indicate the Matching selected, included the "Any request" when the matching section is empty.
Style can be arranged in a following PR, but at least feature-wise now it will explicit inform user about the matching before he/she can add a new rule.
https://issues.jboss.org/browse/KIALI-2613
> KIALI-2613 Explicit matching selected values

- src/components/IstioWizards/IstioWizard.tsx
- src/components/IstioWizards/IstioWizardDropdown.tsx
- src/components/IstioWizards/SuspendTraffic.tsx
- src/types/IstioObjects.ts
This PR introduces a new use-case Wizard for suspend traffic.
This operation might require different low level Istio configuration, depending if we want to stop traffic for a particular workload or whole service.
I.e. when more than one workload, typically a suspended traffic means to redirect traffic to pending workloads with weights. When all workloads are stopped, then a fault injection is generated.
The UI hides the complexity to the user and try to offer a one-click operation simplifying all steps around it.
https://issues.jboss.org/browse/KIALI-1962
> KIALI-1962 Suspend Traffic Wizard

- src/pages/Overview/NamespaceInfo.ts
- src/pages/Overview/OverviewCardContent.tsx
- src/pages/Overview/OverviewCardContentExpanded.tsx
- src/pages/Overview/OverviewCardLinks.tsx
- src/pages/Overview/OverviewHelper.ts
- src/pages/Overview/OverviewPage.tsx
- src/pages/Overview/OverviewStatusesExpanded.tsx
- src/pages/Overview/OverviewToolbar.tsx
- src/pages/Overview/__tests__/OverviewPage.test.tsx
- src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
See https://github.com/kiali/kiali-design/issues/57
- Fetch metrics in overview when mode is expanded
- Add toggle button to switch expanded/compact
- Horizontal bar chart (for health) and sparkline (for RPS)
JIRA: https://issues.jboss.org/browse/KIALI-2560
> KIALI-2560 Add expanded mode for overview cards

- src/components/IstioWizards/IstioWizard.tsx
- src/components/IstioWizards/MatchingRouting.tsx
- src/components/IstioWizards/MatchingRouting/MatchBuilder.tsx
- src/components/IstioWizards/MatchingRouting/Matches.tsx
- src/components/IstioWizards/MatchingRouting/RuleBuilder.tsx
- src/components/IstioWizards/MatchingRouting/Rules.tsx
Matching Routing Wizard only allowed to select one destination.
That limited some valid use cases like:
I.e. reviews service with v1, v2, v3 versions:
- Rule [1]: if user == lucas then go to reviews/v1
- Rule [2]: if Any request then go to reviews/v2, reviews/v3
This PRs includes multiple selection of workloads to accept these kind of VS/DR combinations
https://issues.jboss.org/browse/KIALI-2615
> Add multiple destinations on Matching Wizard

- src/components/Details/DetailedTrafficList.tsx
- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelNode.tsx
https://issues.jboss.org/browse/KIALI-2556
This prevents creating links for the "unknown" node when it is a destination of traffic.
This fix is for the side panels of the graph and, also for the traffic tabs of the details pages.
> KIALI-2556 Fix links to unknown destination service

- src/actions/LoginThunkActions.ts
- src/pages/Login/LoginPage.tsx
- src/reducers/LoginState.ts
- src/services/Login.ts
Adds in some better error handling when dealing with OpenShift OAuth logins.
If we encounter a problem during login it will be bring the user back to the OAuth login page so that the user can start the login process again. Otherwise they can get stuck on the main username/password login screen.
I was not able to exactly recreate the issue mention in KIALI-2555, but spent some time modifying the code to do things like setup cookies with invalid tokens, expired OpenShift tokens, etc. So I can't verify it this fixes the exact problem reported.
https://issues.jboss.org/browse/KIALI-2555
> KIALI-2555 Return to the OpenShift login page on error

- src/components/IstioActions/IstioActionsButtons.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/reducers/MessageCenter.ts
- Save / Reload / Cancel buttons when user can write
- Reload / Close buttons on readonly scenarios
- Success msg and toast on Save operations
https://issues.jboss.org/browse/KIALI-2335
> KIALI-2335 Improvements in YAML editor

- src/components/ConfigValidation/ConfigIndicator.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
- src/types/ServiceInfo.ts
These modifications check if validations is empty from the backend result and then goes to avoid displaying those items that require validation. All the pages should work, but the validation result is missing or text is displayed indicating that the validations that were expected could not be found.
Related to issue 936 in kiali repository. I could not repeat the issue at all and as such, one will need a modified kiali backend to test this. I have posted a docker image to ``docker.io/burmanm/kiali:kiali-2624`` that returns empty validations.
KIALI-2624 (I hope, JIRA is not working)
> KIALI-2624 Prevent UI crash even if validation is missing

- src/pages/AppDetails/AppInfo.tsx
- src/pages/AppList/ItemDescription.tsx
- src/pages/ServiceList/ItemDescription.tsx
- src/pages/ServiceList/__tests__/ItemDescription.test.tsx
- src/pages/WorkloadDetails/WorkloadInfo.tsx
- src/pages/WorkloadList/ItemDescription.tsx
List items used internally a table for layout.
That created some problems when resizing.
Moved to a grid for auto-adjust on these cases.
Changed on app/workload/service list item to maintain same aspect/ratio.
https://issues.jboss.org/browse/KIALI-2592
> KIALI-2592 Use grid instead of table for list items

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
In the scenario of having mTLS enabled mesh-wide, the open locks on edges should be visible whenever there is traffic not using mTLS (from 0% to 99% of traffic that uses mTLS).
https://issues.jboss.org/browse/KIALI-2666
yes
mTLS not enabled globally. Graph shows locks whenever there is traffic with using mtls (from 1% to 100% of the traffic using mTLS).
mTLS enabled for service mesh. Graph should show open locks whenever there is traffic **not** using mTLS (from 0% to 99% of traffic using mTLS)
> KIALI-2666 Show open lock whenever traffic is under 100%

- src/app/StartupInitializer.tsx
- src/config/AuthenticationConfig.ts
- src/pages/Login/LoginPage.tsx
- src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
- src/reducers/LoginState.ts
- src/types/Auth.ts
https://issues.jboss.org/browse/KIALI-2497
These changes will show the _secret missing_ message to the user without the need to try to login. Taking advantage that a request is made to the /api/auth/info endpoint as initialization to check if secret configuration is pending.
Related backend PR: https://github.com/kiali/kiali/pull/979
> KIALI-2497 Show message to user at first load if secret is missing

- src/components/MetricsOptions/MetricsDuration.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
- src/services/Api.ts
- introduce tail lines limit
- add disabled and tooltip options to MetricsDuration
By default Tail 500 lines to ensure that we don't ask for an overwhelming number of lines based on duration.  In the screenshot below show 10 lines.  Note that the duration is disabled when using a line limit:
When asking for all lines the time limit is enabled:
** Question: Perhaps it would be better to keep the duration dropdown enabled even though it's value is trumped when there is a line limit.  Otherwise the user can not alter the duration for the first fetch after selecting "All Lines".  Thoughts?
*** SERVER PR REQUIRED: https://github.com/kiali/kiali/pull/1009
> KIALI-2712 Share duration with other tabs

- src/components/Details/DetailedTrafficList.tsx
- src/components/Details/__tests__/DetailedTrafficList.test.tsx
- src/components/Metrics/Helper.ts
- src/components/Metrics/IstioMetrics.tsx
- src/components/Metrics/__tests__/TrafficDetails.test.tsx
- src/components/MetricsOptions/MetricsSettings.tsx
- src/pages/Login/LoginPage.tsx
https://issues.jboss.org/browse/KIALI-2423
This will let the user navigate to the detailed metrics. Filters are preset depending on the clicked row.
> KIALI-2423 Add links from traffic tab to metrics

- src/pages/AppList/AppListComponent.tsx
- src/pages/IstioConfigList/IstioConfigListComponent.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/WorkloadList/WorkloadListComponent.tsx
componentDidMount() was calling this.updateListItems() which caused the React to call componentDidUpdate() which called again this.updateListItems() and that caused the backend calls to be duplicated.
Replaced with this.setState({}); in this componentDidMount() which causes only the call to componentDidUpdate() and as such there's only a single call to the backend.
KIALI-2663
> KIALI-2663 Prevent duplicate calls to this.updateListItems()

- src/components/SessionTimeout/SessionTimeout.tsx
This doesn't really do much but maybe it's enough to solve this minor issue.  I'm not 100% sure this countdown mechanism really works as expected.  We may want to consider changing to a more simple approach that just pops up a dialog when the session expires and then gives the user a minute or so to extend before logging out.
> KIALI-2598 protect against negative countdown

- src/app/StartupInitializer.tsx
- src/components/Nav/Masthead/UserDropdown.tsx
- src/types/Auth.ts
If running on OpenShift 4 we will now redirect to the OpenShift logout page so that the user is properly logged out.
https://issues.jboss.org/browse/KIALI-2689
This is backwards compatible with OpenShift 3.
> KIALI-2689 Support OAuth logout in OpenShift 4

- src/components/About/AboutUIModal.tsx
- src/config/Config.ts
The `component="a"` attribute was missing.
I had to add @ts-ignore comments, because typescript complains, but the app works correctly.
Also, swapping icons of Homepage and Repository links, since they look inverted.
> KIALI-2737 Fix links in the About box

- src/components/NamespaceDropdown.tsx
The current namespace dropdown label and checkbox are backed up to one another. This PR gives them a 10px space so as not to look so compacted.
https://issues.jboss.org/browse/KIALI-2744
yes
Before:
After:
> Increase Namespace dropdown label space between dropdown and label

- src/components/Metrics/Helper.ts
When working on links from Traffic tab, needed a way to preselect filters. I succeeded to preselect filters, but also broke the normal behavior and sub-filters are not being checked by default when user selects a filter. This seems to fix the issue.
> Fix metrics settings when filters are first checked

- src/components/Nav/Masthead/UserDropdown.tsx
https://issues.jboss.org/browse/KIALI-2722
This was fixed previously and is a partial regression of https://issues.jboss.org/browse/KIALI-2518.
> KIALI-2722 Fix unit mismatch in timeLeft() method

- package.json
- yarn.lock
KIALI-2754 Fix High severity vulnerability in js-yaml package (3.13.0 -> 3.13.1). Arbitrary code execution: https://snyk.io/vuln/SNYK-JS-JSYAML-174129
_explanation of what it does_
https://issues.jboss.org/browse/KIALI-2754
https://snyk.io/vuln/SNYK-JS-JSYAML-174129
yes
No
> KIALI-2754 Fix High severity vulnerability in js-yaml package

- package.json
- tsconfig.json
- yarn.lock
KIALI-2764 Update typescript to 2.4.5 from 3.3.4000 to get --incremental dev compilation performance increases and other things.
http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html
> For a project the size of Visual Studio Code, TypeScript’s new --incremental flag was able to reduce subsequent build times down to approximately a fifth of the original.
https://issues.jboss.org/browse/KIALI-2764
yes
No
> KIALI-2764 Update typescript to 2.4.5 to get --incremental compile feature

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/types/IstioConfigDetails.ts
- src/types/IstioObjects.ts
Remove old references to RouteRules and DestinationPolicies. Both of them were deprecated 1 year ago (https://istio.io/blog/2018/v1alpha3-routing/).
https://issues.jboss.org/browse/KIALI-2793
yes
> KIALI-2793 Remove RouteRule and DestinationPolicy types - deprecated on istio long time ago

- src/components/IstioActions/IstioActionsDropdown.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
https://issues.jboss.org/browse/KIALI-2138
All types that show up in the "Istio Config" list page seems to have the
"kind" property. Using this property to show the type in the confirm
dialog. Falling back to "Isito object" just in case.
> KIALI-2138 Show type in confirmation when deleting Istio Objects

- src/components/Label/Labels.tsx
- src/components/Label/__tests__/Labels.test.tsx
- src/components/Label/__tests__/__snapshots__/Labels.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadServices.tsx
- src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
Task in the roadmap of supporting Knative.
Knative services has 8 labels per service. They take a lot of space in the service page.
We should use the 'More labels...' link to hide some labels.
Openshift uses this feature when there are more than 3 labels:
https://issues.jboss.org/browse/KIALI-2757
yes
In the Workloads details page:
In Service Details page:
> KIALI-2757 Adding 'More Labels...' links when there are more than 3 labels

- src/pages/Graph/SummaryPanel.tsx
- src/styles/_overrides.scss
- src/types/Graph.ts
https://issues.jboss.org/browse/KIALI-2746
Also: https://issues.jboss.org/browse/KIALI-2765
Reducing sizes as a workaround until we have a new design available.
* Font size of side panel is reduced. This produces a more adequate
size to not distract the user from the graph.
* Width of main navigation menu is reduced to make better use of
available screen space.
Before:
After:
> KIALI-2746 Reduce size of graph sidepanel and main nav menu

- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/services/__mockData__/getServiceDetail.ts
- src/types/ServiceInfo.ts
Knative introduced a new kind of services, the ExternalName services.
I think it would be a good idea to show which is that ExternalName.
Depending on: https://github.com/kiali/kiali/pull/1030
https://issues.jboss.org/browse/KIALI-2676
yes
ExternalName Service doesn't show any IP but shows the actual ExternalName.
ClusterIP doesn't show the externalName since it doesn't make sense for this type of services:
> KIALI-2676 Show ExternalName field for ExternalName Services

- src/components/CytoscapeGraph/graphs/GraphStyles.ts
This isn't the best example of crowding, see the Jira/design issue, but it should be easy enough to see that the stacked label is less wide, and I think cleaner without the comma-separator.
Before:
After:
> KIALI-2389 Reduce edge label congenstion by moving percentErr under rate

- package.json
- src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx
Istio 1.1 added new way to write the gateway string in the VirtualService definition. This one allows correct parsing to happen in the UI if the resource is in another namespace (current parsing only works for the same namespace).
KIALI-2772
Yes
> KIALI-2772 Support new gateway annotation format for VS gateway parsing

- src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts
- src/components/CytoscapeGraph/graphs/GraphStyles.ts
**Describe the change**
Change to the compound node labels based on UX feedback. https://github.com/kiali/kiali-design/issues/121
**Issue reference**
https://issues.jboss.org/browse/KIALI-2768
~~**DO NOT MERGE**~~
~~There is a bug here which has my a bit stumped. When you first load the graph everything works fine, if you switch the layout then the labels are not aligned properly.~~
~~I suspect its in how we are doing things in the GroupCompoundLayout with removing elements and adding things back in, I think it might be taking the size with the temporary elements and not the final size.~~
~~If we explicitly set the label margin in GroupCompoundLayout, then it works when you change the layout, but is broken when you first load the page (and it also doesn't work when you hover over …
> KIALI-2768 UX updates to compound node labels

- src/components/Nav/Navigation.tsx
- src/components/Nav/RenderPage.tsx
- src/components/Nav/SecondaryMasthead.tsx
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.scss
- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
- src/styles/_layout.scss
https://issues.jboss.org/browse/KIALI-2799
Not a great approach, but I don't see other option rather than making
calculations using the size of the controls at the top of the pane.
As a plus, this also fixes:
* Sizing issues with the main content `div`. The issue can be seen
in any of the app/workloads/services list pages. The scroll bar
will run beyond the screen.
* Scroll bar issue in the metrics tab of the service details page.
* Applies the same fix of the logs tab to the YAML editor to fill the available page space.
> KIALI-2799 Adapt logs pane to the height of the browser window

- src/actions/GraphFilterActions.ts
- src/app/History.ts
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/CytoscapeGraphSelector.ts
- src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
- src/components/CytoscapeGraph/FocusAnimation.ts
- src/components/CytoscapeGraph/__tests__/CytoscapeGraphSelector.test.ts
- src/components/GraphFilter/GraphFilter.tsx
- src/components/Nav/NavUtils.tsx
- src/components/Pf/PfInfoCard.tsx
- src/pages/AppDetails/AppInfo/AppDescription.tsx
- src/pages/Graph/GraphPage.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDescription.test.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadInfo.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
- src/pages/WorkloadDetails/WorkloadInfo/__tests__/WorkloadDescription.test.tsx
- src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
- src/reducers/GraphDataState.ts
- src/store/Selectors.ts
- src/utils/SearchParamUtils.ts
- This focus on the desired element, centering it on the resulting graph
It adds a link on the detail page of app/workload/service to "show on graph" the element.
It does that by going to the graph page and focusing (currently only centers the view on the element(s))
Probably a visual cue is needed aside of just centering the graph on the nodes.
//cc: @pilhuhn
> KIALI-2104 Shows link to go from workload/service/app page to graph

- src/components/GraphFilter/GraphFind.tsx
Also:
- add tootips to find/hide clear buttons to help distinguish inputs when both are filled
- add name and autocomplete attributes to find/hide inputs to [maybe] help browsers present previous expressions
> KIALI-2798 Ensure find/hide clear buttons survive navigation

- public/index.html
- src/index.tsx
- allow clean/incognito browsers to properly show badges on first render
This is currently a draft until we figure out whether it's safe to preload from static/media, I have a feeling those filenames will change if there is an update to the font.
> KIALI-2817 preload icon webfonts

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
When opening the overview of a single Istio Config item, the params does an object !== object compare which will not work. Thus the backend is called twice to load the same information even if the information inside the object is equivalent.
Fix the compare to avoid dual loading.
KIALI-2830
> KIALI-2830 Fix the params compare to avoid duplicate loads from backend

- src/pages/Graph/GraphHelpFind.tsx
Updates the examples found in the "Help: Graph find/hide" to be feature neutral. i.e. drop the use of the "find" in the descriptions, as this apply for find/hide
>  KIALI-2846 Update wording in "Help: Graph find/hide" Examples

- src/components/GraphFilter/GraphFind.tsx
- src/components/GraphFilter/__tests__/GraphFind.test.tsx
- src/pages/Graph/GraphHelpFind.tsx
Can now easily find edges with any traffic for any protocol, or negated can
find edges with no traffic for all protocols.
Also, slightly improve unary patterns to now match in a truthy way.
> KIALI-2831 Add unary 'traffic' operator for edges

- src/components/IstioWizards/IstioWizard.tsx
- src/components/IstioWizards/IstioWizardActions.ts
- src/components/IstioWizards/IstioWizardDropdown.tsx
- src/components/IstioWizards/ThreeScaleIntegration.tsx
- src/components/IstioWizards/__tests__/ThreeScaleIntegration.test.ts
- src/config/Config.ts
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/services/Api.ts
- src/types/ThreeScale.ts
This PRs refers to JIRA
https://issues.jboss.org/browse/KIALI-2641
and it needs backend PR https://github.com/kiali/kiali/pull/1050 with the API services.
Summary
----
Maistra will include a new Istio 3Scale adapter [1] that will allow to autenticate Services deployed in Istio with a 3Scale API. 
The configuration of this integration is somehow complex as a user needs to create Istio objects like rules, handlers and template instances.
The goal of this PR is to provide a high level integration from the UI to make this setup easier.
For this first step, we have defined a new Wizard at Service Details level. 
This Wizard only will be visible when the 3scale adapter is present in the cluster, otherwise, this PR will be transparent to the rest of the users.
When the 3scale adapter is …
> KIALI-2641 Add Wizard for 3scale adapter config

- src/components/GraphFilter/GraphFind.tsx
The buttons can be hidden only when the input is clear *and* submitted. Otherwise
editing is in progress.
also: fix some static keys and ids to be consistently formed.
@xeviknal This video shows the clear button staying in place until the edit is submitted.  Is this sufficient or do you believe we should auto-submit if the user edits to an empty value?  I feel like that is a non-standard thing to do but let me know.
> KIALI-2829 Don't hide graph-find clear buttons prematurely

- src/components/IstioWizards/TrafficPolicy.tsx
MUTUAL option is an advanced option that requires more fields and objects correctly configured.
So it does make sense to remove it from the high level Wizard use case.
Also, an "advanced" Wizard is planned to be investigated 
https://issues.jboss.org/browse/KIALI-2855
Which can cover this and other complex options.
> KIALI-2812 Remove TLS MUTUAL option from Wizard

- src/components/Pf/PfInfoCard.tsx
- src/pages/AppDetails/AppInfo/AppDescription.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap
- src/types/Workload.ts
Because Info tab is the default it renders multiple times, first without all
of the item detail, and then again after the detail is available/fetched. By
assuming a missing sidecar the icon is rendered initially.
- Don't assume missing sidecar by default
- Only show icon when explicitly set false for optional prop
- Don't render "Show on Graph" link or MS icon until title is available
- Consistently position "Show on Graph" link on the right (i.e. after MS icon)
> kiali-2827 Improve handling of missing sidecar icon on detail pages

- src/components/IstioWizards/IstioWizardDropdown.tsx
propagate the key inside the elements instead to surround the higher component with a React.Fragment
cc @josejulio as he introduced the regression :-).
The helper render...() function has some missing keys, I fixed that.
The fragment used here broke the events of the menu.
> KIALI-2876 Fix broken Wizard Menu

- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
Adds validation information to ports in ServiceDetails
KIALI-2454, KIALI-2749
Adds validation information:
In case of errors:
Tooltip to show the issue:
> KIALI-2454 KIALI-2749 Add ServiceDetails ports validation information

- src/app/AuthenticationController.tsx
- src/components/Nav/Menu.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
JIRA: [KIALI-2849](https://issues.jboss.org/browse/KIALI-2849)
- Now in authentication process if jaeger is disabled we set the values to false, the problem was in the persist configuration
- Fixed externalIcon , it wasn't working with PF4
- This is fixed in https://github.com/kiali/kiali-ui/pull/1188 where we check if the errTraces is not -1, anyway I added an extra control with the URL.
> KIALI-2849 Tracing options still appear when removed in the backend

- src/components/CytoscapeGraph/FocusAnimation.ts
Adjust focus animation.
It takes 2 seconds and the first circle in takes 1s, the out half a second and the second "in" the other half second.
I could do something different, please comment what you have in mind.
Before:
After:
a)
b)
c) same as (a) but with color PfColors.Blue300
> KIALI-2872 Adjust focus animation

- src/components/Health/__tests__/HealthIndicator.test.tsx
- src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
- src/types/Health.ts
- src/types/__tests__/Health.test.ts
List Pods individually
This UI needs backend PR https://github.com/kiali/kiali/pull/1081.
Pod Status details desired/current/available info.
This will help to give user more information on Pod problems.
Also, another problem we had in our previous design, is that the Group Pods can't be really merged, as in situation like these, you want to see what are the failed Pods. So, now Pod table shows all individual Pods (as it happens with OpenShift Console).
Note that for an investigation fields like Phase or CreatedAt can be completely different, so we can't merge it.
> KIALI-2728 Introduce Desired/Current/Available Pod Status details

- src/pages/AppDetails/AppDetailsPage.tsx
- src/pages/ServiceDetails/ServiceDetailsPage.tsx
- src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
JIRA: [KIALi-2893](https://issues.jboss.org/browse/KIALI-2893)
Continue of https://github.com/kiali/kiali-ui/pull/1171
- Rename info tab to Overview like design https://github.com/kiali/kiali-design/issues/116
- Clean code, remove empty ```<div></div>```
cc @abonas @skondkar
> KIALI-2840 Rename Info tab to Overview

- package.json
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/GraphFilter/GraphFilter.tsx
- src/components/Nav/Menu.tsx
- src/components/Nav/NavUtils.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
- yarn.lock
Upgrading from 4.3.1 to 5.0.0.
According to https://reacttraining.com/blog/react-router-v5/, version 5.0.0 was meant to be published as 4.4, so versioni 5.0 is fully backwards compatible with 4.x.
Upgrading to major version 5.0 is safe, since API is compatible.
> KIALI-2899 Upgrade react-router-dom

- src/pages/Graph/GraphPage.tsx
https://issues.jboss.org/browse/KIALI-1606
Changing the main title of the graph page when visualizing a drilled
down graph. Hopefully, this helps the user to identify that the graph is
not showing the entire namespace.
> KIALI-1606 Reflect in graph title the drilled down state

- src/pages/Graph/SummaryPanelEdge.tsx
- src/pages/Graph/SummaryPanelGroup.tsx
- src/pages/Graph/SummaryPanelNode.tsx
https://issues.jboss.org/browse/KIALI-2894
This ensures that the side panel scroll is at the top position when changing a selection in the graph.
The issue only happens when changing selection of same cytoscape "type" (i.e select and edge while another edge is currently selected). It does not happen if screen resolution leads to no scrollbars in side panel when changing context.
> KIALI-2894 Scroll to top of side panel when graph selection changes

- src/pages/Overview/OverviewCardLinks.tsx
- Make tooltip text better indicate that these are links
> KIALI-2895 Use PF tooltips for Overview card icons

- src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
- src/utils/IstioConfigUtils.ts
- src/utils/__tests__/IstioConfigUtils.test.ts
This fix adds key: null into the mergeJsonPatch used by Kiali to update an Istio config resource.
Those null in the patch values are necessary when an attribute is removed from the yaml view and transformed into an non key. The Merge Patch needs a key with a null value to perform the delete.
> KIALI-2901 Fix missing nulls in MergeJsonPatch

- package.json
- src/app/App.tsx
- src/components/CytoscapeGraph/CytoscapeGraph.scss
- src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
- yarn.lock
This PoC uses tippy.js to add a right-click context menu to the graph for extended functionality
https://issues.jboss.org/browse/KIALI-2271
https://github.com/kiali/kiali-design/issues/104
Yes
For a node:
https://atomiks.github.io/tippyjs/
> Add tippy.js for cytoscape context menu on Nodes/Edges

- src/components/Nav/Masthead/UserDropdown.tsx
There may be a better fix than this but this adds a simple guard.  It seems that during logout the session in redux gets set undefined, which can cause a re-render of the UserDropdown (due to the state change) before that element is unmounted, which then crashes because it assumes a session.
> KIALI-2903 protect against missing session on logout

- src/app/InitializingScreen.tsx
- src/app/StartupInitializer.tsx
https://issues.jboss.org/browse/KIALI-2930
At first load of Kiali, a request is done to retrieve some settings. If this request fails, an error message is shown. Sometimes, this error message is not enough to troubleshoot the issue and the developer console is needed to see what the back-end is returning.
To improve this experience, adding a "Show details" pane to display the raw response sent by the back-end if first-load initialization fails.
> KIALI-2930 Show details of error in initialization screen

- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/components/CytoscapeGraph/ContextMenuComponent/ContextMenuNodeComponent.tsx
- src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
- src/pages/Graph/GraphPage.tsx
The react components take the node/edge data as their props,
the tippyInstance (contextMenu) and the node/edge element from cy
Warning: UI didn't change, the gif is only a basic example of what can be done given the following components:
```typescript
class CEdge extends React.Component<ContextMenuEdgeProps> {
render() {
return (
<div>
Hello Edge from: {this.props.source} to: {this.props.target}{' '}
</div>
);
}
}
const CNode = () => {
return <div> Hello Node</div>;
};
class CGroup extends React.PureComponent<ContextMenuNodeProps> {
render() {
return <div>Hello Group with id {this.props.id}</div>;
}
}
```
> KIALI-2919 Allows context menu to use react components.

- src/pages/Login/LoginPage.tsx
https://issues.jboss.org/browse/KIALI-2949
This will avoid the need to use the mouse to select the username field and/or use extra keypresses to somehow focus on the username field.
> KIALI-2949 Focus login's username field on load

- src/pages/ServiceDetails/ServiceInfo.tsx
- src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
- src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
- src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
- src/types/ServiceInfo.ts
Adding the selector labels of a service into the Service Details page.
Needs: https://github.com/kiali/kiali/pull/1100
https://issues.jboss.org/browse/KIALI-2570
yes
> KIALI-2570 Add Selector labels to Service Details page

- src/actions/KialiAppAction.ts
- src/actions/MeshTlsActions.ts
- src/app/AuthenticationController.tsx
- src/components/MTls/MeshMTLSStatus.tsx
- src/config/Config.ts
- src/reducers/MeshTlsState.ts
- src/reducers/index.ts
- src/services/Api.ts
- src/store/ConfigStore.ts
- src/store/Selectors.ts
- src/store/Store.ts
Automatically refresh the mesh-wide TLS status.
- The lock appears and disappears in the masthead. 
- In the graph, it switches the logic between using open locks and full locks. 
- In the Overview page, locks next to namespaces, changes accordingly.
Needs: https://github.com/kiali/kiali/pull/1102
https://issues.jboss.org/browse/KIALI-2795
yes
> KIALI-2795 Automaticaly refresh the mesh-wide TLS lock in the masthead

- src/actions/GraphDataActions.ts
- src/actions/GraphDataThunkActions.ts
- src/reducers/GraphDataState.ts
Clean errors when requesting graph data without namespaces
The issue happens because the graph data without namespaces just returns and doesn't clean previous errors (if any)
The error will stop appearing when Kiali notices that we don't have that namespace anymore (e.g. when opening the namespace selector) 
> KIALI-2832 Clean errors if there is no namespace selected

- src/store/Selectors.ts
This is extracted from #1154, using the `unknown` type added on
Typescript 3.0 (we're using 3.4.5). It fixes a compilation problem that happens
after the change from `react-scripts-ts` to `react-scripts` and breaks
the build there.
There should not be any breakage, as the generated code is the same. The
only thing this is doing is helping the compiler to understand what
types are being returned.
> KIALI-2529 Fix type erasure on selectors

- src/actions/MessageCenterActions.ts
Const enums are deprecated[1] and breaks the build after the update from
`react-scripts-ts` to `react-scripts`.
This PR has no breaking changes.
[1]: https://github.com/Microsoft/TypeScript/issues/21391
Refers to #1154.
> KIALI-2529 Remove const enums

- src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
- src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
- src/components/CytoscapeGraph/CytoscapeGraph.tsx
- src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
- src/pages/Graph/GraphPage.tsx
- Moved some redux properties to redux-connect syntax
- In versioned graph, the versioned node (v1, v2) will be considered as workloads
- Droped the version from the title because it won't be valid to show a workload name with a version
- NodeType=unknown and isInaccessible won't show any menu
> KIALI-2918 Enable group nodes to have a context menu

- src/components/Nav/Masthead/UserDropdown.tsx
Logs the user out of Kiali before logging the user out of OpenShift 4
https://issues.jboss.org/browse/KIALI-2942
> KIALI-2942 Properly logout when using OAuth on OpenShift4

- src/components/Metrics/MetricsChartBase.tsx
The expand link text overlaps the chart and looks off.
https://issues.jboss.org/browse/KIALI-2948
Yes
No
**Before**
**After**
**:
> KIALI-2948 Chart expand link overlaps chart

- src/app/App.tsx
- src/app/AuthenticationController.tsx
- src/app/InitializingScreen.tsx
- src/pages/Login/LoginPage.tsx
- src/pages/Login/__tests__/LoginPage.test.tsx
- src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
https://issues.jboss.org/browse/KIALI-2950
After logging in, the "initializing" screen is no longer shown. Instead, the "Log in" button text is disabled and the text is changed to "Logging in...".
Openshift authentication is not affected.
Also, if user is already logged in, Kiali's first load is also unaffected.
**A succeeded login**
**A failed login**
> KIALI-2950 Improve login - avoid unnecessary screen switching

- src/pages/Overview/OverviewCardContentExpanded.tsx
This should not compile before, and it does not after the update to `react-scripts`, and to be honest I have no idea if that has even worked at all. Either way, this PR fixes it.
> KIALI-2529 Fix compilation error

- src/components/Nav/Masthead/UserDropdown.tsx
- src/pages/ServiceList/ServiceListComponent.tsx
- src/pages/ServiceList/__tests__/ItemDescription.test.tsx
- tsconfig.json
Moving to `react-scripts` from `react-scripts-ts` moves our
transpilation layer to use babel instead of tsc, which forbids absolute
imports.
> KIALI-2529 Remove absolute imports

- src/components/Metrics/IstioMetrics.tsx
- src/reducers/JaegerState.ts
- src/types/Namespace.ts
The exports on this PR are failing compilation after the change to
`react-scripts`:
* `export { x }` does not work anymore.
* You can not overwrite an imported type and then export it anymore.
> KIALI-2529 Fix export problems

- package.json
- yarn.lock
Patch for high severity CVE with Axios library.
https://issues.jboss.org/browse/KIALI-2980
Yes
No
https://nvd.nist.gov/vuln/detail/CVE-2019-10742
> KIALI-2980 Patch Axios DDoS CVE.

- src/components/Metrics/IstioMetrics.tsx
- src/components/Metrics/__tests__/IstioMetrics.test.tsx
- src/reducers/GrafanaState.ts
- src/store/Store.ts
As explained in https://issues.jboss.org/browse/KIALI-2966 , some grafana configuration is not expected to change hence can be hardcoded for simplicity.
Backend PR: https://github.com/kiali/kiali/pull/1111
> KIALI-2963 / KIALI-2966 simplify grafana model

- src/pages/Overview/Sorts.ts
Now, by default, the most unhealthy namespace cards should appear first.  Note that the URL will trump the default, so when testing ensure the URL 'sort' or 'direction' params are not overriding the default.
@jotak Any reason this sort field is called 'status' and not 'health' ?
> KIALI-1717 Overview default sort from namespace name to health (aka status)
